### ISSUE TITLE
./nodebb setup fails due to depency 'eslint'

### ISSUE THREAD

**Issue by God-status** [NodeBB/NodeBB#10001]
- I'm attempting to install NodeBB version 1.18.6
- My NodeBB git hash is: 5d3c814d57a4dc28fdc0c799c8d1f7b9325ea8e8
- I'm using Node.JS version 16.13.0
- I have not installed any plugins, because I have been so far unable to install NodeBB itself
- Database type: redis
- Database version: 6.2.6

The error occurred when the command `./nodebb setup` was run. 

I was attempting to run the initial setup steps for NodeBB, but got the following error:

```
$ NodeBB % ./nodebb setup
Dependencies outdated or not yet installed.
Installing them now...

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nodebb@1.10.2
npm ERR! Found: eslint@5.6.1
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"5.6.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^4.9.0" from eslint-config-airbnb-base@12.1.0
npm ERR! node_modules/eslint-config-airbnb-base
npm ERR!   dev eslint-config-airbnb-base@"12.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/familymaupin1/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/familymaupin1/.npm/_logs/2021-11-13T20_41_06_524Z-debug.log
Error installing dependencies!
message: Command failed: npm install --production
stdout: null
stderr: null
/Users/familymaupin1/NodeBB/src/cli/package-install.js:54
		throw e;
		^

Error: Command failed: npm install --production
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.installAll (/Users/familymaupin1/NodeBB/src/cli/package-install.js:45:9)
    at Object.<anonymous> (/Users/familymaupin1/NodeBB/src/cli/index.js:58:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 94550,
  stdout: null,
  stderr: null
}
```

Help would be greatly appreciated, thx in advance!

**Comment by julianlam** [comment]
Are you sure that is that git hash you are using? The one you linked is several years old.

**Comment by julianlam** [comment]
I would `git reset --hard v1.18.6` and try again

**Comment by God-status** [comment]
> I would `git reset --hard v1.18.6` and try again

I ran that command and my git hash is now 22e74dc0b

**Comment by God-status** [comment]
I solved this issue by adding the `--force` prefix.
