### ISSUE TITLE
[BUG] - Default plugin nodebb-plugin-emoji fails to load

### ISSUE THREAD

**Issue by NazimHAli** [NodeBB/NodeBB#10044]
This is running everything with default settings - didn't enable/disable plugins or modify configs.

- **NodeBB version:** 
- NodeBB v1.18.6
- **NodeBB git hash:**
- 7b99dc46eb25d65c1922f5b1adc5f00ac515e89f 
- **NodeJS version:**
- v14.18.1

- **Installed NodeBB Plugins:** 
- Active plugins:
	* nodebb-plugin-composer-default@7.0.14 (installed, enabled)
	* nodebb-plugin-dbsearch@5.1.0 (installed, disabled)
	* nodebb-plugin-emoji@3.5.3 (installed, enabled)
	* nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
	* nodebb-plugin-markdown@8.14.4 (installed, enabled)
	* nodebb-plugin-mentions@3.0.3 (installed, enabled)
	* nodebb-plugin-spam-be-gone@0.7.11 (installed, disabled)
	* nodebb-rewards-essentials@0.2.0 (installed, enabled)
	* nodebb-theme-lavender@5.3.1 (installed, disabled)
	* nodebb-theme-persona@11.3.1 (installed, enabled)
	* nodebb-theme-slick@1.4.16 (installed, disabled)
	* nodebb-theme-vanilla@12.1.10 (installed, disabled)
	* nodebb-widget-essentials@5.0.4 (installed, enabled)

- **Database type:** mongo
- **Database version:** 

- **Exact steps to cause this issue:**

1. Cloned repo
2. `./nodebb setup`
3. `./nodebb -d start`

- **What you expected:**

- **What happened instead:**
```bash
2021-12-01T00:51:32.555Z [4567/29344] - verbose: [plugins/fireHook] filter:settings.get
2021-12-01T00:51:32.556Z [4567/29344] - error: [plugins] Error executing 'static:app.load' in plugin 'nodebb-plugin-emoji'
Error: Route.put() requires a callback function but got a [object Undefined]
    at Route.<computed> [as put] (/home/nazim/source/NodeBB/node_modules/express/lib/router/route.js:202:15)
    at Function.proto.<computed> [as put] (/home/nazim/source/NodeBB/node_modules/express/lib/router/index.js:510:19)
    at helpers.setupApiRoute (/home/nazim/source/NodeBB/src/routes/helpers.js:50:14)
    at Object.controllers [as default] (/home/nazim/source/NodeBB/node_modules/nodebb-plugin-emoji/build/lib/controllers.js:55:5)
    at init (/home/nazim/source/NodeBB/node_modules/nodebb-plugin-emoji/build/lib/index.js:36:26)
    at Object.fireStaticHook [as static] (/home/nazim/source/NodeBB/src/plugins/hooks.js:209:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Hooks.fire (/home/nazim/source/NodeBB/src/plugins/hooks.js:105:17)
    at async Plugins.reloadRoutes (/home/nazim/source/NodeBB/src/plugins/index.js:140:2)
    at async module.exports (/home/nazim/source/NodeBB/src/routes/index.js:143:2)

```

**Comment by barisusakli** [comment]
You seem to be using latest nodebb instead of nodebb 1.18.6, try checking out the v1.18.x branch.

Latest master has breaking changes for 1.19.0

**Comment by barisusakli** [comment]
If you want to use latest master apply these changes to emoji https://github.com/NodeBB/nodebb-plugin-emoji/commit/da8e6e1cca62a56af3d041bb8b1463746d9769e8

**Comment by NazimHAli** [comment]
@barisusakli you're right, checking out `master` is a force of habit :sweat_smile: . We use it to reflect production.

**Comment by NazimHAli** [comment]
Not reproducible on v1.18.x
