### ISSUE TITLE
Error installing NodeBB dependencies

### ISSUE THREAD

**Issue by okaeiz** [NodeBB/NodeBB#10507]
After installing NodeBB prerequisites e.g. MongoDB & nodejs ,when I was trying to install NodeBB using its script which is available in the Github repo that I cloned, I encountered the following error (screenshot included).

![errorlog](https://user-images.githubusercontent.com/100111649/164224004-df10acfb-76c2-44f5-8cb3-79dc348e0be9.PNG)

**Comment by okaeiz** [comment]
> What command did you run when you got this error? Please don't provide images of text, copy the text into a coffee block instead.

I was simply following the official installation document; which provided an executable script.
I ran the following command:

>>> ./nodebb setup

then it seemed like it was fetching some dependencies.
After a while it output this error:

>>> Error: Command failed: npm install --production
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.installAll (/home/hossein/nodebb/src/cli/package-install.js:73:9)
    at Object.<anonymous> (/home/hossein/nodebb/src/cli/index.js:62:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)

**Comment by pitaj** [comment]
I fixed your comment with actual code blocks. It's still unclear what the actual error is, can you please provide the entire terminal text including where you entered the command all the way to the end.

**Comment by barisusakli** [comment]
What is your nodejs version? Make sure it's one of 12/14/16

**Comment by okaeiz** [comment]
I'm using Node v16.14.2.
this is what I get when I try to configure MongoDB using mongo command:

MongoDB shell version v5.0.7
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:372:17
@(connect):2:6
exception: connect failed
exiting with code 1

**Comment by nodebb-misty** [comment]
Issue closed due to inactivity.

----

*This is an automated message. If you feel this action was in error, please comment on this issue so it can be looked at again*
