### ISSUE TITLE
nodemailer breaks on node18

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#10511]
https://github.com/nodemailer/smtp-server/pull/176

```
  1) emailer
       should send via SMTP:
     Uncaught TypeError: Cannot set property closed of #<Writable> which has only a getter
      at new SMTPStream (node_modules/smtp-server/lib/smtp-stream.js:34:21)
      at new SMTPConnection (node_modules/smtp-server/lib/smtp-connection.js:55:24)
      at SMTPServer.connect (node_modules/smtp-server/lib/smtp-server.js:93:26)
      at /home/runner/work/NodeBB/NodeBB/node_modules/smtp-server/lib/smtp-server.js:84:26
      at Immediate.<anonymous> (node_modules/smtp-server/lib/smtp-server.js:345:39)
      at process.processImmediate (node:internal/timers:471:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/10540
