### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] when upgrading

### ISSUE THREAD

**Issue by mzch** [NodeBB/NodeBB#10537]
- **NodeBB version:** `1.19.7`
- **NodeBB git hash:** `0c4850e2872b50716c1feb10a9363aa0935d7b57`
- **NodeJS version:** `v16.14.2`

- **Installed NodeBB Plugins:** 
```
	* nodebb-plugin-2factor@3.0.7 (installed, enabled)
	* nodebb-plugin-api-encrypt@1.0.1 (installed, enabled)
	* nodebb-plugin-audio-embed@1.2.1 (installed, enabled)
	* nodebb-plugin-calendar@1.1.3 (installed, enabled)
	* nodebb-plugin-cards@0.3.1 (installed, enabled)
	* nodebb-plugin-cards-fullname@0.0.4 (installed, enabled)
	* nodebb-plugin-code-button@0.0.7 (installed, enabled)
	* nodebb-plugin-composer-default@7.0.22 (installed, enabled)
	* nodebb-plugin-dbsearch@5.1.3 (installed, disabled)
	* nodebb-plugin-desktop-notifications-v2mm@0.2.6 (installed, enabled)
	* nodebb-plugin-dplayer@0.0.2 (installed, enabled)
	* nodebb-plugin-email-blacklist@1.1.1 (installed, enabled)
	* nodebb-plugin-emoji@3.5.17 (installed, enabled)
	* nodebb-plugin-emoji-android@2.0.5 (installed, enabled)
	* nodebb-plugin-extended-markdown@1.5.1 (installed, enabled)
	* nodebb-plugin-feed@2.0.3 (installed, enabled)
	* nodebb-plugin-gdpr@1.1.1 (installed, enabled)
	* nodebb-plugin-github-embed@0.7.9 (installed, enabled)
	* nodebb-plugin-gravatar@2.3.0 (installed, enabled)
	* nodebb-plugin-hashtag@0.1.20 (installed, enabled)
	* nodebb-plugin-hashtags@2.1.5 (installed, enabled)
	* nodebb-plugin-html5videoplayer@0.2.5 (installed, disabled)
	* nodebb-plugin-imgur@2.0.5 (installed, enabled)
	* nodebb-plugin-imgur-preview@2.0.1 (installed, enabled)
	* nodebb-plugin-lightbox@0.0.3 (installed, enabled)
	* nodebb-plugin-markdown@9.0.10 (installed, enabled)
	* nodebb-plugin-mentions@3.0.8 (installed, enabled)
	* nodebb-plugin-night-mode@1.0.7 (installed, enabled)
	* nodebb-plugin-poll@2.0.3 (installed, enabled)
	* nodebb-plugin-private-forum@1.3.0 (installed, enabled)
	* nodebb-plugin-soundpack-default@2.0.1 (installed, enabled)
	* nodebb-plugin-spam-be-gone@0.8.1 (installed, enabled)
	* nodebb-plugin-sso-github@2.3.2 (installed, enabled)
	* nodebb-plugin-threaded-replies@0.1.0 (installed, enabled)
	* nodebb-plugin-user-invitations@0.6.0 (installed, enabled)
	* nodebb-plugin-ws-markdown@8.17.8 (installed, enabled)
	* nodebb-rewards-essentials@0.2.1 (installed, enabled)
	* nodebb-theme-lavender@5.3.2 (installed, disabled)
	* nodebb-theme-oxide@6.0.6 (installed, disabled)
	* nodebb-theme-persona@11.4.4 (installed, enabled)
	* nodebb-theme-slick@1.4.23 (installed, disabled)
	* nodebb-theme-vanilla@12.1.17 (installed, disabled)
	* nodebb-theme-ws-persona@11.3.12 (installed, disabled)
	* nodebb-widget-essentials@5.0.11 (installed, enabled)
```

- **Database type:** mongo
- **Database version:** 5.2

- **Exact steps to cause this issue:**

1. ./nodebb upgrade
- **What you expected:**

done upgrading successfully.
- **What happened instead:**

the following error occurred. Nodebb shows upgraded version `1.19.7` on the admin panel and it seems to run normally... May I as well ignore this errors?
- Log
```
nodebb@n08:~/NodeBB$ ./nodebb upgrade

Updating NodeBB...

1. Updating package.json file with defaults...  OK

2. Bringing base dependencies up to date...  started

up to date, audited 923 packages in 11s

72 packages are looking for funding
  run `npm fund` for details

11 vulnerabilities (5 moderate, 6 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

3. Checking installed plugins for updates...Checking installed plugins and themes for updates...   OK
All packages up-to-date!

4. Updating NodeBB data store schema...2022-04-28T13:55:47.917Z [4567/2268703] - verbose: [minifier] utilizing a maximum of 1 additional threads

Parsing upgrade scripts...
OK | 0 script(s) found, 122 skipped
Schema update complete!


5. Rebuilding assets...2022-04-28T13:55:48.091Z [4567/2268703] - verbose: [build] Querying CPU core count for build strategy
2022-04-28T13:55:48.092Z [4567/2268703] - verbose: [build] System returned 2 cores, opting for series build strategy
2022-04-28T13:55:48.093Z [4567/2268703] - verbose: [build] building the following targets: plugin static dirs, requirejs modules, client js bundle, admin js bundle, client side styles, admin control panel styles, templates, languages
  started
2022-04-28T13:55:48.137Z [4567/2268703] - verbose: [plugins] loading the following fields from plugin data: staticDirs, modules, clientScripts, acpScripts, cssFiles, lessFiles, acpLessFiles, languageData
2022-04-28T13:55:48.146Z [4567/2268703] - warn: [plugins] "nodebb-plugin-html5videoplayer" is active but not installed.
2022-04-28T13:55:48.176Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-composer-default
2022-04-28T13:55:48.178Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-markdown
2022-04-28T13:55:48.179Z [4567/2268703] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-widget-essentials
2022-04-28T13:55:48.181Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-emoji
2022-04-28T13:55:48.181Z [4567/2268703] - verbose: [plugins] Found 1 acpLess file(s) for plugin nodebb-plugin-emoji
2022-04-28T13:55:48.182Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-spam-be-gone
2022-04-28T13:55:48.183Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-2factor
2022-04-28T13:55:48.184Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-audio-embed
2022-04-28T13:55:48.185Z [4567/2268703] - verbose: [plugins] Found 2 less file(s) for plugin nodebb-plugin-calendar
2022-04-28T13:55:48.186Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-cards-fullname
2022-04-28T13:55:48.187Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-desktop-notifications-v2mm
2022-04-28T13:55:48.187Z [4567/2268703] - verbose: [plugins] Found 2 css file(s) for plugin nodebb-plugin-dplayer
2022-04-28T13:55:48.188Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-extended-markdown
2022-04-28T13:55:48.189Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-hashtag
2022-04-28T13:55:48.191Z [4567/2268703] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-plugin-lightbox
2022-04-28T13:55:48.191Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-night-mode
2022-04-28T13:55:48.192Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-cards
2022-04-28T13:55:48.192Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-github-embed
2022-04-28T13:55:48.193Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-user-invitations
2022-04-28T13:55:48.194Z [4567/2268703] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-plugin-poll
2022-04-28T13:55:48.194Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-poll
2022-04-28T13:55:48.195Z [4567/2268703] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-ws-markdown
2022-04-28T13:55:48.207Z [4567/2268703] - verbose: [plugins] Found 11 AMD-style module(s) for plugin nodebb-plugin-composer-default
2022-04-28T13:55:48.208Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-composer-default
2022-04-28T13:55:48.208Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-theme-persona
2022-04-28T13:55:48.210Z [4567/2268703] - verbose: [plugins] Found 3 AMD-style module(s) for plugin nodebb-plugin-markdown
2022-04-28T13:55:48.210Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-markdown
2022-04-28T13:55:48.212Z [4567/2268703] - verbose: [plugins] Found 1 AMD-style module(s) for plugin nodebb-plugin-mentions
2022-04-28T13:55:48.212Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-mentions
2022-04-28T13:55:48.216Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-rewards-essentials
2022-04-28T13:55:48.217Z [4567/2268703] - verbose: [plugins] Found 3 AMD-style module(s) for plugin nodebb-plugin-emoji
2022-04-28T13:55:48.217Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-emoji
2022-04-28T13:55:48.218Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-emoji
2022-04-28T13:55:48.219Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-2factor
2022-04-28T13:55:48.220Z [4567/2268703] - verbose: [plugins] Found 1 AMD-style module(s) for plugin nodebb-plugin-audio-embed
2022-04-28T13:55:48.221Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-audio-embed
2022-04-28T13:55:48.221Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-calendar
2022-04-28T13:55:48.222Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-calendar
2022-04-28T13:55:48.223Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-cards-fullname
2022-04-28T13:55:48.224Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-code-button
2022-04-28T13:55:48.225Z [4567/2268703] - verbose: [plugins] Found 1 AMD-style module(s) for plugin nodebb-plugin-dplayer
2022-04-28T13:55:48.225Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-dplayer
2022-04-28T13:55:48.226Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-extended-markdown
2022-04-28T13:55:48.226Z [4567/2268703] - verbose: [plugins] Found 1 AMD-style module(s) for plugin nodebb-plugin-feed
2022-04-28T13:55:48.227Z [4567/2268703] - verbose: [plugins] Found 1 AMD-style module(s) for plugin nodebb-plugin-gdpr
2022-04-28T13:55:48.227Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-gdpr
2022-04-28T13:55:48.228Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-gravatar
2022-04-28T13:55:48.228Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-hashtag
2022-04-28T13:55:48.229Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-hashtags
2022-04-28T13:55:48.230Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-imgur-preview
2022-04-28T13:55:48.230Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-lightbox
2022-04-28T13:55:48.230Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-night-mode
2022-04-28T13:55:48.231Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-cards
2022-04-28T13:55:48.231Z [4567/2268703] - verbose: [plugins] Found 1 AMD-style module(s) for plugin nodebb-plugin-github-embed
2022-04-28T13:55:48.232Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-user-invitations
2022-04-28T13:55:48.232Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-user-invitations
2022-04-28T13:55:48.233Z [4567/2268703] - verbose: [plugins] Found 4 AMD-style module(s) for plugin nodebb-plugin-poll
2022-04-28T13:55:48.234Z [4567/2268703] - warn: [plugins] File not found: /srv/nodebb/NodeBB/node_modules/highlight.js/styles (Ignoring)
2022-04-28T13:55:48.237Z [4567/2268703] - error: [build] Encountered error preparing for build
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.stat (node:internal/fs/promises:658:10)
    at processDir (/srv/nodebb/NodeBB/src/plugins/data.js:102:36)
    at async Promise.all (index 0)
    at async Data.getStaticDirectories (/srv/nodebb/NodeBB/src/plugins/data.js:120:2)
2022-04-28T13:55:48.237Z [4567/2268703] - error: [build] Encountered error during build step
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.stat (node:internal/fs/promises:658:10)
    at processDir (/srv/nodebb/NodeBB/src/plugins/data.js:102:36)
    at async Promise.all (index 0)
    at async Data.getStaticDirectories (/srv/nodebb/NodeBB/src/plugins/data.js:120:2)
Error occurred during upgrade: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.stat (node:internal/fs/promises:658:10)
    at processDir (/srv/nodebb/NodeBB/src/plugins/data.js:102:36)
    at async Promise.all (index 0)
    at async Data.getStaticDirectories (/srv/nodebb/NodeBB/src/plugins/data.js:120:2)
2022-04-28T13:55:48.243Z [4567/2268703] - error: uncaughtException: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.stat (node:internal/fs/promises:658:10)
    at processDir (/srv/nodebb/NodeBB/src/plugins/data.js:102:36)
    at async Promise.all (index 0)
    at async Data.getStaticDirectories (/srv/nodebb/NodeBB/src/plugins/data.js:120:2) {"date":"Thu Apr 28 2022 06:55:48 GMT-0700 (Pacific Daylight Time)","error":{"code":"ERR_INVALID_ARG_TYPE"},"exception":true,"os":{"loadavg":[0.31,0.16,0.16],"uptime":2827950.25},"process":{"argv":["/usr/bin/node","/srv/nodebb/NodeBB/nodebb","upgrade"],"cwd":"/srv/nodebb/NodeBB","execPath":"/usr/bin/node","gid":1005,"memoryUsage":{"arrayBuffers":18415720,"external":21260661,"heapTotal":98910208,"heapUsed":66268520,"rss":157835264},"pid":2268703,"uid":1005,"version":"v16.14.2"},"stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string or an instance of Buffer or URL. Received undefined\n    at Object.stat (node:internal/fs/promises:658:10)\n    at processDir (/srv/nodebb/NodeBB/src/plugins/data.js:102:36)\n    at async Promise.all (index 0)\n    at async Data.getStaticDirectories (/srv/nodebb/NodeBB/src/plugins/data.js:120:2)","trace":[{"column":10,"file":"node:internal/fs/promises","function":"Object.stat","line":658,"method":"stat","native":false},{"column":36,"file":"/srv/nodebb/NodeBB/src/plugins/data.js","function":"processDir","line":102,"method":null,"native":false},{"column":null,"file":null,"function":"async Promise.all","line":null,"method":"all","native":false},{"column":2,"file":"/srv/nodebb/NodeBB/src/plugins/data.js","function":"async Data.getStaticDirectories","line":120,"method":"getStaticDirectories","native":false}]}
2022-04-28T13:55:48.245Z [4567/2268703] - verbose: [plugins] Found 2 AMD-style module(s) for plugin nodebb-plugin-ws-markdown
2022-04-28T13:55:48.245Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-ws-markdown
2022-04-28T13:55:48.245Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-ws-markdown
2022-04-28T13:55:48.246Z [4567/2268703] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-soundpack-default
2022-04-28T13:55:48.247Z [4567/2268703] - verbose: [plugins] Found 1 AMD-style module(s) for plugin nodebb-plugin-sso-github
2022-04-28T13:55:48.249Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-plugin-markdown
2022-04-28T13:55:48.252Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-rewards-essentials
2022-04-28T13:55:48.252Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-plugin-emoji
2022-04-28T13:55:48.253Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-plugin-spam-be-gone
2022-04-28T13:55:48.253Z [4567/2268703] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-spam-be-gone
2022-04-28T13:55:48.253Z [4567/2268703] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-spam-be-gone
2022-04-28T13:55:48.254Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-plugin-2factor
2022-04-28T13:55:48.255Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-plugin-audio-embed
2022-04-28T13:55:48.255Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-plugin-calendar
2022-04-28T13:55:48.256Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-plugin-cards-fullname
2022-04-28T13:55:48.256Z [4567/2268703] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-desktop-notifications-v2mm
2022-04-28T13:55:48.257Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-plugin-hashtag
2022-04-28T13:55:48.257Z [4567/2268703] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-hashtag
2022-04-28T13:55:48.258Z [4567/2268703] - verbose: [plugins] found 2 static directories for nodebb-plugin-imgur-preview
2022-04-28T13:55:48.258Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-plugin-lightbox
2022-04-28T13:55:48.259Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-plugin-night-mode
2022-04-28T13:55:48.259Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-plugin-cards
2022-04-28T13:55:48.259Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-plugin-user-invitations
2022-04-28T13:55:48.260Z [4567/2268703] - verbose: [plugins] found 2 static directories for nodebb-plugin-poll
2022-04-28T13:55:48.262Z [4567/2268703] - verbose: [plugins] found 1 static directories for nodebb-plugin-soundpack-default
2022-04-28T13:55:48.263Z [4567/2268703] - verbose: [plugins] Found 1 AMD-style module(s) for plugin nodebb-theme-persona
2022-04-28T13:55:48.270Z [4567/2268703] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-composer-default
2022-04-28T13:55:48.271Z [4567/2268703] - verbose: [plugins] Found 4 js file(s) for plugin nodebb-theme-persona
2022-04-28T13:55:48.283Z [4567/2268703] - verbose: [plugins] Found 5 js file(s) for plugin nodebb-plugin-poll
2022-04-28T13:55:48.284Z [4567/2268703] - verbose: [plugins] Found 4 js file(s) for plugin nodebb-plugin-2factor
```

**Comment by barisusakli** [comment]
Seems to be happening because of this `2022-04-28T13:55:48.234Z [4567/2268703] - warn: [plugins] File not found: /srv/nodebb/NodeBB/node_modules/highlight.js/styles (Ignoring)`

Does that folder exist in highlight.js?

**Comment by mzch** [comment]
No, it doesn't exist. Could you tell me how to delete this warning?

**Comment by barisusakli** [comment]
Post a topic on https://community.nodebb.org/category/16/technical-support if you are still having this issue.
