### ISSUE TITLE
NodeBB 2.0.0: WebInstaller crashing due to missing fs-extra

### ISSUE THREAD

**Issue by nilsramsperger** [NodeBB/NodeBB#10580]
Hi ppl.

Setting up NodeBB 2.0.0 via the WebInstaller currently fails. After submitting the first form, It just gets emptied.
In that form, I selected Redis as database.

The console log shows that the npm package fs-extra ist missing.
Doing a `npm install fs-extra` right after `npm install --production` solves the issue.

Sadly I can only procede to the end of the setup process. Trying to start NodeBB crashes due to the same problem. But I couldn't figure out why by now. Could be a problem with my container as well. :)

Greets
Nils

```
2022-05-05T07:29:52.204Z [undefined/12] - info: NodeBB v2.0.0 Copyright (C) 2013-2022 NodeBB Inc.
2022-05-05T07:29:52.204Z [undefined/12] - info: This program comes with ABSOLUTELY NO WARRANTY.
2022-05-05T07:29:52.204Z [undefined/12] - info: This is free software, and you are welcome to redistribute it under certain conditions.
2022-05-05T07:29:52.204Z [undefined/12] - info: 
2022-05-05T07:29:52.335Z [12] - info: Launching web installer on port 4567
2022-05-05T07:29:55.485Z [12] - info: Web installer listening on http://0.0.0.0:4567
2022-05-05T07:30:28.776Z [12] - info: Starting setup process
2022-05-05T07:30:29.206Z [28] - info: NodeBB Setup Triggered via Command Line

Welcome to NodeBB v2.0.0!

This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
Press enter to accept the default setting (shown in brackets).
2022-05-05T07:30:29.209Z [28] - info: [install/checkSetupFlagEnv] checking env vars for setup info...
2022-05-05T07:30:29.282Z [28] - info: 
Now configuring redis database:
2022-05-05T07:30:29.831Z [28] - verbose: [minifier] utilizing a maximum of 3 additional threads
Configuration Saved OK
Populating database with default configs, if not already set...
2022-05-05T07:30:29.850Z [28] - warn: [cache-buster] could not read cache buster ENOENT: no such file or directory, open '/opt/nodebb/build/cache-buster' {"code":"ENOENT","errno":-2,"path":"/opt/nodebb/build/cache-buster","stack":"Error: ENOENT: no such file or directory, open '/opt/nodebb/build/cache-buster'","syscall":"open"}
Enabling default theme: nodebb-theme-persona
No categories found, populating instance with default categories
2022-05-05T07:30:29.953Z [28] - warn: No administrators have been detected, running initial user setup

2022-05-05T07:30:30.314Z [28] - verbose: [UserReset.cleanByUid] No tokens found for uid (1).
Creating welcome post!
Enabling default plugins
2022-05-05T07:30:30.354Z [28] - info: [install/defaultPlugins] customDefaults []
2022-05-05T07:30:30.355Z [28] - info: [install/enableDefaultPlugins] activating default plugins {"0":"nodebb-plugin-composer-default","1":"nodebb-plugin-markdown","2":"nodebb-plugin-mentions","3":"nodebb-widget-essentials","4":"nodebb-rewards-essentials","5":"nodebb-plugin-emoji","6":"nodebb-plugin-emoji-android"}

Parsing upgrade scripts... 
OK | 118 script(s) found
  → [2015/12/15] Upgrading chats... skipped
  → [2015/12/23] Chat room hashes... skipped
  → [2015/12/23] Adding theme to active plugins sorted set... skipped
  → [2016/1/14] Creating user best post sorted sets... skipped
  → [2016/1/20] Creating users:notvalidated... skipped
  → [2016/1/23] Creating Global moderators group... skipped
  → [2016/2/25] Social: Post Sharing... skipped
  → [2016/4/14] Group title from settings to user profile... skipped
  → [2016/4/19] Users post count per tid... skipped
  → [2016/4/29] Dismiss flags from deleted topics... skipped
  → [2016/5/28] Giving topics:read privs to any group/user that was previously allowed to Find & Access Category... skipped
  → [2016/6/13] Store upvotes/downvotes separately... skipped
  → [2016/7/12] Giving upload privileges... skipped
  → [2016/8/5] Removing best posts with negative scores... skipped
  → [2016/8/7] Granting edit/delete/delete topic on existing categories... skipped
  → [2016/9/22] Category recent tids... skipped
  → [2016/10/8] Favourites to Bookmarks... skipped
  → [2016/10/14] Sorted sets for post replies... skipped
  → [2016/11/22] Update global and user language keys... skipped
  → [2016/11/25] Sorted set for pinned topics... skipped
  → [2017/2/25] Update global and user sound settings... skipped
  → [2017/2/28] Upgrading config urls to use assets route... skipped
  → [2017/4/16] Delete accidentally long-lived sessions... skipped
  → [2016/12/7] Migrating flags to new schema... skipped
  → [2017/2/27] New sorted set posts:votes... skipped
  → [2017/3/22] Update moderation notes to zset... skipped
  → [2017/4/14] Set default allowed file extensions... skipped
  → [2017/4/26] Remove relative_path from uploaded profile cover urls... skipped
  → [2017/5/26] rename user mod privileges group... skipped
  → [2017/6/16] Give tag privilege to registered-users on all categories... skipped
  → [2017/7/5] Wipe all existing RSS tokens... skipped
  → [2017/7/10] Fix incorrect robots.txt schema... skipped
  → [2017/7/17] Generate email logo for use in email header... skipped
  → [2017/9/6] Clearing stale digest templates that were accidentally saved as custom... skipped
  → [2017/9/7] Changing ip blacklist storage to object... skipped
  → [2017/10/30] New sorted set cid:<cid>:tids:lastposttime... skipped
  → [2017/10/12] Generate customHTML block from old customJS setting... skipped
  → [2017/11/15] Convert old notification digest settings... skipped
  → [2017/12/8] Add votes to topics... skipped
  → [2017/12/18] Change the schema of simple keys so they don't use value field (mongodb only)... skipped
  → [2017/12/18] Give chat privilege to registered-users... skipped
  → [2018/1/3] Give upload privilege to registered-users globally if it is given on a category... skipped
  → [2018/1/8] Fix sort by votes for moved topics... skipped
  → [2018/1/9] Give vote privilege to registered-users on all categories... skipped
  → [2018/1/12] Rename privileges:downvote and privileges:flag to min:rep:downvote, min:rep:flag respectively... skipped
  → [2018/1/22] Fix topics in categories per user if they were moved... skipped
  → [2018/2/14] Add default settings for notification delivery types... skipped
  → [2018/2/17] Flatten navigation data... skipped
  → [2018/2/21] Revising minimum password strength to 1 (from 0)... skipped
  → [2018/1/31] Give category access privileges to spiders system group... skipped
  → [2018/2/28] Give registered users signature privilege... skipped
  → [2018/3/15] Reformatting post diffs to be stored in lists and hash instead of single zset... skipped
  → [2018/4/16] Refresh post-upload associations... skipped
  → [2018/5/28] Give global search privileges... skipped
  → [2018/6/7] Give post history viewing privilege to registered-users on all categories... skipped
  → [2018/6/8] Give deleted post viewing privilege to moderators on all categories... skipped
  → [2018/6/22] Hash all IP addresses stored in Recent IPs zset... skipped
  → [2018/8/28] Record first entry in username/email history... skipped
  → [2018/9/24] Upgrade bans to hashes... skipped
  → [2018/9/28] Give global local login privileges... skipped
  → [2018/10/1] Optimize PostgreSQL sessions... skipped
  → [2018/10/4] add filters to events... skipped
  → [2018/10/10] Fix category post zsets... skipped
  → [2018/10/11] Fix category topic zsets... skipped
  → [2018/10/24] Rename maximumImageWidth to resizeImageWidth... skipped
  → [2018/11/10] Navigation item visibility groups... skipped
  → [2018/11/10] Widget visibility groups... skipped
  → [2018/12/11] Remove uid:<uid>:ignored:cids... skipped
  → [2018/12/13] Update category watch data... skipped
  → [2019/1/4] Group create global privilege... skipped
  → [2019/1/5] Global view privileges... skipped
  → [2019/3/16] Calculate image sizes of all uploaded images... skipped
  → [2019/3/25] Delete username email history for deleted users... skipped
  → [2019/4/5] Update moderation notes to hashes... skipped
  → [2019/5/21] Disable plugin metrics for existing installs... skipped
  → [2019/5/28] Give mods explicit privileges... skipped
  → [2019/6/4] Update registration type... skipped
  → [2019/6/23] Create zsets for user posts per category... skipped
  → [2019/10/8] give mod info privilege... skipped
  → [2019/9/24] Clean flag byCid zsets... skipped
  → [2019/10/7] Clean up post hash data... skipped
  → [2019/10/7] Clean up old notifications and hash data... skipped
  → [2020/5/2] Fix user sorted sets... skipped
  → [2020/5/21] Removing file upload privilege if file uploads were disabled (`allowFileUploads`)... skipped
  → [2020/6/9] Remove duplicate image field for categories... skipped
  → [2020/6/26] Unescape navigation titles... skipped
  → [2018/10/11] Re-add deleted topics to topics:recent... skipped
  → [2020/7/15] New sorted set for tracking flags by target... skipped
  → [2020/7/16] Consolidate multiple flags reports, going forward... skipped
  → [2020/7/31] Remove flag reporters sorted set... skipped
  → [2020/8/22] Add target uid to flag objects... skipped
  → [2020/9/6] Disable nodebb-plugin-soundpack-default... skipped
  → [2020/9/6] Remove allow from uri setting... skipped
  → [2020/9/11] Create fullname search set... skipped
  → [2020/10/11] Fix category colors that are 3 digit hex colors... skipped
  → [2020/10/13] Create verified/unverified user groups... skipped
  → [2020/10/24] Store poster count in topic hash... skipped
  → [2020/11/26] Clear purged replies and toPid... skipped
  → [2020/11/23] Create category tags sorted sets... skipped
  → [2020/12/11] Migrate existing topic thumbnails to new format... skipped
  → [2020/12/13] Move banned users to banned-users group... skipped
  → [2021/1/27] Create category name sorted set... skipped
  → [2021/1/31] Create subCategoriesPerPage property for categories... skipped
  → [2021/2/7] Store number of thumbs a topic has in the topic object... skipped
  → [2021/3/9] Store default favicon if it does not exist... skipped
  → [2021/3/11] Add "schedule" to default privileges of admins and gmods for existing categories... skipped
  → [2021/6/18] Enable setting to include unverified emails for all mailings... skipped
  → [2021/9/9] Store tags in topic hash... skipped
  → [2021/9/28] Category topics sorted sets by views... skipped
  → [2021/11/23] Re-enable username login... skipped
  → [2021/12/13] Upgrade navigation items to hashes... skipped
  → [2022/2/4] Store downvoted posts in user votes sorted set... skipped
  → [2022/2/7] Clean up leftover topic thumb sorted sets and files for since-purged topics... skipped
  → [2022/2/10] Fix paths in user uploads sorted sets... skipped
  → [2022/2/10] Rename object and sorted sets used in post uploads... skipped
  → [2022/1/31] Reset Markdown Theme (if selected theme is not available)... skipped
  → [2022/2/17] Update Markdown Theme to point to unminified file... skipped
  → [2021/11/2] Delete mentions:sent:<pid> sorted sets... skipped
Schema update complete!

2022-05-05T07:30:30.449Z [28] - verbose: [build] Querying CPU core count for build strategy
2022-05-05T07:30:30.449Z [28] - verbose: [build] System returned 4 cores, opting for parallel build strategy
2022-05-05T07:30:30.450Z [28] - verbose: [build] building the following targets: plugin static dirs, requirejs modules, client js bundle, admin js bundle, client side styles, admin control panel styles, templates, languages
  started
2022-05-05T07:30:30.455Z [28] - verbose: [plugins] loading the following fields from plugin data: staticDirs, modules, clientScripts, acpScripts, cssFiles, lessFiles, acpLessFiles, languageData
2022-05-05T07:30:30.458Z [28] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-composer-default
2022-05-05T07:30:30.459Z [28] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-markdown
2022-05-05T07:30:30.460Z [28] - verbose: [plugins] Found 1 css file(s) for plugin nodebb-widget-essentials
2022-05-05T07:30:30.460Z [28] - verbose: [plugins] Found 1 less file(s) for plugin nodebb-plugin-emoji
2022-05-05T07:30:30.460Z [28] - verbose: [plugins] Found 1 acpLess file(s) for plugin nodebb-plugin-emoji
2022-05-05T07:30:30.461Z [28] - verbose: [plugins] Found 12 AMD-style module(s) for plugin nodebb-plugin-composer-default
2022-05-05T07:30:30.461Z [28] - verbose: [plugins] Found 3 AMD-style module(s) for plugin nodebb-theme-persona
2022-05-05T07:30:30.462Z [28] - verbose: [plugins] Found 1 AMD-style module(s) for plugin nodebb-plugin-markdown
2022-05-05T07:30:30.462Z [28] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-markdown
2022-05-05T07:30:30.462Z [28] - verbose: [plugins] Found 1 AMD-style module(s) for plugin nodebb-plugin-mentions
2022-05-05T07:30:30.462Z [28] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-mentions
2022-05-05T07:30:30.462Z [28] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-rewards-essentials
2022-05-05T07:30:30.463Z [28] - verbose: [plugins] Found 5 AMD-style module(s) for plugin nodebb-plugin-emoji
2022-05-05T07:30:30.463Z [28] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-emoji
2022-05-05T07:30:30.463Z [28] - verbose: [plugins] Found 1 js file(s) for plugin nodebb-plugin-emoji
2022-05-05T07:30:30.463Z [28] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-theme-persona
2022-05-05T07:30:30.464Z [28] - verbose: [plugins] found 1 static directories for nodebb-rewards-essentials
2022-05-05T07:30:30.464Z [28] - verbose: [plugins] found 1 static directories for nodebb-plugin-emoji
2022-05-05T07:30:30.466Z [28] - verbose: [plugins] Found 2 js file(s) for plugin nodebb-plugin-composer-default
2022-05-05T07:30:30.466Z [28] - verbose: [plugins] found 1 static directories for nodebb-plugin-markdown
2022-05-05T07:30:30.468Z [28] - info: [build] Building in parallel mode
2022-05-05T07:30:30.469Z [28] - info: [build]         plugin static dirs  build started
2022-05-05T07:30:30.470Z [28] - info: [build]          requirejs modules  build started
2022-05-05T07:30:30.471Z [28] - info: [build]           client js bundle  build started
2022-05-05T07:30:30.471Z [28] - info: [build]            admin js bundle  build started
2022-05-05T07:30:30.471Z [28] - info: [build]         client side styles  build started
2022-05-05T07:30:30.471Z [28] - info: [build] admin control panel styles  build started
2022-05-05T07:30:30.471Z [28] - info: [build]                  templates  build started
2022-05-05T07:30:30.472Z [28] - info: [build]                  languages  build started
2022-05-05T07:30:30.481Z [28] - error: [build]          requirejs modules  build failed
2022-05-05T07:30:30.481Z [28] - error: [build] Encountered error during build step
Error: Cannot find module 'fs-extra'
Require stack:
- /opt/nodebb/src/meta/js.js
- /opt/nodebb/src/meta/index.js
- /opt/nodebb/src/install.js
- /opt/nodebb/src/cli/setup.js
- /opt/nodebb/require-main.js
- /opt/nodebb/app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at JS.buildModules (/opt/nodebb/src/meta/js.js:77:14)
    at async Object.requirejs modules (/opt/nodebb/src/meta/build.js:21:3)
    at async step (/opt/nodebb/src/meta/build.js:101:3)
    at async Promise.all (index 1)
    at async buildTargets (/opt/nodebb/src/meta/build.js:84:3)
    at async exports.build (/opt/nodebb/src/meta/build.js:178:3)
2022-05-05T07:30:30.485Z [28] - error: uncaughtException: Cannot find module 'fs-extra'
Require stack:
- /opt/nodebb/src/meta/js.js
- /opt/nodebb/src/meta/index.js
- /opt/nodebb/src/install.js
- /opt/nodebb/src/cli/setup.js
- /opt/nodebb/require-main.js
- /opt/nodebb/app.js
Error: Cannot find module 'fs-extra'
Require stack:
- /opt/nodebb/src/meta/js.js
- /opt/nodebb/src/meta/index.js
- /opt/nodebb/src/install.js
- /opt/nodebb/src/cli/setup.js
- /opt/nodebb/require-main.js
- /opt/nodebb/app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at JS.buildModules (/opt/nodebb/src/meta/js.js:77:14)
    at async Object.requirejs modules (/opt/nodebb/src/meta/build.js:21:3)
    at async step (/opt/nodebb/src/meta/build.js:101:3)
    at async Promise.all (index 1)
    at async buildTargets (/opt/nodebb/src/meta/build.js:84:3)
    at async exports.build (/opt/nodebb/src/meta/build.js:178:3) {"date":"Thu May 05 2022 07:30:30 GMT+0000 (Coordinated Universal Time)","error":{"code":"MODULE_NOT_FOUND","requireStack":["/opt/nodebb/src/meta/js.js","/opt/nodebb/src/meta/index.js","/opt/nodebb/src/install.js","/opt/nodebb/src/cli/setup.js","/opt/nodebb/require-main.js","/opt/nodebb/app.js"]},"exception":true,"os":{"loadavg":[0.41,0.26,0.1],"uptime":297.8},"process":{"argv":["/usr/local/bin/node","/opt/nodebb/app","--setup"],"cwd":"/opt/nodebb","execPath":"/usr/local/bin/node","gid":0,"memoryUsage":{"arrayBuffers":206894,"external":2822475,"heapTotal":80920576,"heapUsed":65852624,"rss":128372736},"pid":28,"uid":0,"version":"v16.14.0"},"stack":"Error: Cannot find module 'fs-extra'\nRequire stack:\n- /opt/nodebb/src/meta/js.js\n- /opt/nodebb/src/meta/index.js\n- /opt/nodebb/src/install.js\n- /opt/nodebb/src/cli/setup.js\n- /opt/nodebb/require-main.js\n- /opt/nodebb/app.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\n    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at JS.buildModules (/opt/nodebb/src/meta/js.js:77:14)\n    at async Object.requirejs modules (/opt/nodebb/src/meta/build.js:21:3)\n    at async step (/opt/nodebb/src/meta/build.js:101:3)\n    at async Promise.all (index 1)\n    at async buildTargets (/opt/nodebb/src/meta/build.js:84:3)\n    at async exports.build (/opt/nodebb/src/meta/build.js:178:3)","trace":[{"column":15,"file":"node:internal/modules/cjs/loader","function":"Module._resolveFilename","line":933,"method":"_resolveFilename","native":false},{"column":27,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":778,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1005,"method":"require","native":false},{"column":18,"file":"node:internal/modules/cjs/helpers","function":"require","line":102,"method":null,"native":false},{"column":14,"file":"/opt/nodebb/src/meta/js.js","function":"JS.buildModules","line":77,"method":"buildModules","native":false},{"column":3,"file":"/opt/nodebb/src/meta/build.js","function":"async Object.requirejs modules","line":21,"method":"requirejs modules","native":false},{"column":3,"file":"/opt/nodebb/src/meta/build.js","function":"async step","line":101,"method":null,"native":false},{"column":null,"file":null,"function":"async Promise.all","line":null,"method":"all","native":false},{"column":3,"file":"/opt/nodebb/src/meta/build.js","function":"async buildTargets","line":84,"method":null,"native":false},{"column":3,"file":"/opt/nodebb/src/meta/build.js","function":"async exports.build","line":178,"method":"build","native":false}]}
2022-05-05T07:30:30.630Z [28] - info: [build]         plugin static dirs  build completed in 0.161sec
2022-05-05T07:30:31.234Z [28] - info: [build]            admin js bundle  build completed in 0.763sec
2022-05-05T07:30:31.243Z [28] - info: [build]           client js bundle  build completed in 0.772sec
node:events:498
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (node:internal/child_process:866:20)
    at process.target.send (node:internal/child_process:739:19)
    at process.<anonymous> (/opt/nodebb/src/meta/minifier.js:118:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on process instance at:
    at node:internal/child_process:870:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by julianlam** [comment]
That's really odd that this wasn't caught before... we _all_ already have `fs-extra` installed? Very weird.

**Comment by julianlam** [comment]
Commit [e707739](https://github.com/NodeBB/NodeBB/commit/e7077393263436668768d72f52c0e53d7ba3dd16) has been backported to the `v2.0.x` branch, and the `v2.0.0` tag has been updated.

**Comment by barisusakli** [comment]
@nilsramsperger let us know if it works now.

**Comment by nilsramsperger** [comment]
It works. Now I can install and start the forum. Thanks for the fix.
