### ISSUE TITLE
Failed to upgrade to 2.4.0

### ISSUE THREAD

**Issue by mzch** [NodeBB/NodeBB#10817]
### NodeBB version

v2.4.0

### NodeBB git hash

55254422794f9d221a996d306c5ab44c33989057

### NodeJS version

v16.16.0

### Installed NodeBB plugins

```
nodebb@n08:~/NodeBB$ ./nodebb plugins
2022-08-11T02:27:00.503Z [4567/608251] - verbose: [minifier] utilizing a maximum of 1 additional threads
Active plugins:
	* nodebb-plugin-2factor@5.0.2 (installed, enabled)
	* nodebb-plugin-api-encrypt (not installed, enabled)
	* nodebb-plugin-audio-embed (not installed, enabled)
	* nodebb-plugin-calendar (not installed, enabled)
	* nodebb-plugin-cards (not installed, enabled)
	* nodebb-plugin-cards-fullname (not installed, enabled)
	* nodebb-plugin-code-button (not installed, enabled)
	* nodebb-plugin-composer-default@8.0.0 (installed, enabled)
	* nodebb-plugin-dbsearch@5.1.5 (installed, disabled)
	* nodebb-plugin-desktop-notifications-v2mm (not installed, enabled)
	* nodebb-plugin-dplayer (not installed, enabled)
	* nodebb-plugin-email-blacklist (not installed, enabled)
	* nodebb-plugin-emoji@4.0.4 (installed, enabled)
	* nodebb-plugin-emoji-android@3.0.0 (installed, enabled)
	* nodebb-plugin-extended-markdown (not installed, enabled)
	* nodebb-plugin-feed (not installed, enabled)
	* nodebb-plugin-gdpr (not installed, enabled)
	* nodebb-plugin-github-embed (not installed, enabled)
	* nodebb-plugin-gravatar (not installed, enabled)
	* nodebb-plugin-hashtag (not installed, enabled)
	* nodebb-plugin-hashtags (not installed, enabled)
	* nodebb-plugin-imgur (not installed, enabled)
	* nodebb-plugin-imgur-preview (not installed, enabled)
	* nodebb-plugin-lightbox (not installed, enabled)
	* nodebb-plugin-markdown@10.1.0 (installed, enabled)
	* nodebb-plugin-mentions@3.0.11 (installed, enabled)
	* nodebb-plugin-night-mode (not installed, enabled)
	* nodebb-plugin-poll (not installed, enabled)
	* nodebb-plugin-private-forum (not installed, enabled)
	* nodebb-plugin-soundpack-default (not installed, enabled)
	* nodebb-plugin-spam-be-gone@1.0.0 (installed, enabled)
	* nodebb-plugin-sso-github (not installed, enabled)
	* nodebb-plugin-threaded-replies (not installed, enabled)
	* nodebb-plugin-user-invitations (not installed, enabled)
	* nodebb-plugin-ws-markdown (not installed, enabled)
	* nodebb-rewards-essentials@0.2.1 (installed, enabled)
	* nodebb-theme-lavender@6.0.0 (installed, disabled)
	* nodebb-theme-persona@12.1.0 (installed, enabled)
	* nodebb-theme-slick@2.0.2 (installed, disabled)
	* nodebb-theme-vanilla@12.1.18 (installed, disabled)
	* nodebb-widget-essentials@6.0.0 (installed, enabled)
```

### Database type

MongoDB

### Database version

v6.0

### Exact steps to cause this issue

1. git pull
2. git chekcout tags/v2.4.0
3. ./nodebb upgrade

### What you expected

Finish upgrading successfully.

### What happened instead

An error occurred.
```
nodebb@n08:~/NodeBB$ ./nodebb upgrade
Dependencies outdated or not yet installed.
Installing them now...

npm WARN config production Use `--omit=dev` instead.

added 31 packages, removed 3 packages, changed 15 packages, and audited 950 packages in 16s

88 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (2 moderate, 7 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm notice
npm notice New minor version of npm available! 8.11.0 -> 8.17.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.17.0
npm notice Run npm install -g npm@8.17.0 to update!
npm notice
OK


Updating NodeBB...

1. Updating package.json file with defaults...  OK

2. Bringing base dependencies up to date...  started
npm WARN config production Use `--omit=dev` instead.

up to date, audited 950 packages in 5s

88 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (2 moderate, 7 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

3. Checking installed plugins for updates...Checking installed plugins and themes for updates...   OK
All packages up-to-date!

4. Updating NodeBB data store schema...2022-08-11T02:22:33.765Z [4567/607973] - verbose: [minifier] utilizing a maximum of 1 additional threads
Error occurred during upgrade: TypeError: maxAge must be a number
    at LRUCache.set (/srv/nodebb/NodeBB/node_modules/lru-cache/index.js:157:13)
    at Object.cache.set (/srv/nodebb/NodeBB/src/cache/lru.js:65:12)
    at /srv/nodebb/NodeBB/src/database/mongo/hash.js:138:10
    at Array.forEach (<anonymous>)
    at module.getObjectsFields (/srv/nodebb/NodeBB/src/database/mongo/hash.js:136:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.getObjects (/srv/nodebb/NodeBB/src/database/mongo/hash.js:92:10)
    at async module.getObject (/srv/nodebb/NodeBB/src/database/mongo/hash.js:87:16)
    at async Configs.getFields (/srv/nodebb/NodeBB/src/meta/configs.js:111:12)
    at async Configs.list (/srv/nodebb/NodeBB/src/meta/configs.js:98:9)
2022-08-11T02:22:33.890Z [4567/607973] - error: uncaughtException: maxAge must be a number
TypeError: maxAge must be a number
    at LRUCache.set (/srv/nodebb/NodeBB/node_modules/lru-cache/index.js:157:13)
    at Object.cache.set (/srv/nodebb/NodeBB/src/cache/lru.js:65:12)
    at /srv/nodebb/NodeBB/src/database/mongo/hash.js:138:10
    at Array.forEach (<anonymous>)
    at module.getObjectsFields (/srv/nodebb/NodeBB/src/database/mongo/hash.js:136:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.getObjects (/srv/nodebb/NodeBB/src/database/mongo/hash.js:92:10)
    at async module.getObject (/srv/nodebb/NodeBB/src/database/mongo/hash.js:87:16)
    at async Configs.getFields (/srv/nodebb/NodeBB/src/meta/configs.js:111:12)
    at async Configs.list (/srv/nodebb/NodeBB/src/meta/configs.js:98:9) {"date":"Wed Aug 10 2022 19:22:33 GMT-0700 (Pacific Daylight Time)","error":{},"exception":true,"os":{"loadavg":[0.71,0.22,0.07],"uptime":761809.34},"process":{"argv":["/usr/bin/node","/srv/nodebb/NodeBB/nodebb","upgrade"],"cwd":"/srv/nodebb/NodeBB","execPath":"/usr/bin/node","gid":1005,"memoryUsage":{"arrayBuffers":18581682,"external":24707144,"heapTotal":96948224,"heapUsed":62339512,"rss":154234880},"pid":607973,"uid":1005,"version":"v16.16.0"},"stack":"TypeError: maxAge must be a number\n    at LRUCache.set (/srv/nodebb/NodeBB/node_modules/lru-cache/index.js:157:13)\n    at Object.cache.set (/srv/nodebb/NodeBB/src/cache/lru.js:65:12)\n    at /srv/nodebb/NodeBB/src/database/mongo/hash.js:138:10\n    at Array.forEach (<anonymous>)\n    at module.getObjectsFields (/srv/nodebb/NodeBB/src/database/mongo/hash.js:136:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async module.getObjects (/srv/nodebb/NodeBB/src/database/mongo/hash.js:92:10)\n    at async module.getObject (/srv/nodebb/NodeBB/src/database/mongo/hash.js:87:16)\n    at async Configs.getFields (/srv/nodebb/NodeBB/src/meta/configs.js:111:12)\n    at async Configs.list (/srv/nodebb/NodeBB/src/meta/configs.js:98:9)","trace":[{"column":13,"file":"/srv/nodebb/NodeBB/node_modules/lru-cache/index.js","function":"LRUCache.set","line":157,"method":"set","native":false},{"column":12,"file":"/srv/nodebb/NodeBB/src/cache/lru.js","function":"Object.cache.set","line":65,"method":"set","native":false},{"column":10,"file":"/srv/nodebb/NodeBB/src/database/mongo/hash.js","function":null,"line":138,"method":null,"native":false},{"column":null,"file":null,"function":"Array.forEach","line":null,"method":"forEach","native":false},{"column":16,"file":"/srv/nodebb/NodeBB/src/database/mongo/hash.js","function":"module.getObjectsFields","line":136,"method":"getObjectsFields","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false},{"column":10,"file":"/srv/nodebb/NodeBB/src/database/mongo/hash.js","function":"async module.getObjects","line":92,"method":"getObjects","native":false},{"column":16,"file":"/srv/nodebb/NodeBB/src/database/mongo/hash.js","function":"async module.getObject","line":87,"method":"getObject","native":false},{"column":12,"file":"/srv/nodebb/NodeBB/src/meta/configs.js","function":"async Configs.getFields","line":111,"method":"getFields","native":false},{"column":9,"file":"/srv/nodebb/NodeBB/src/meta/configs.js","function":"async Configs.list","line":98,"method":"list","native":false}]}
```

**Comment by julianlam** [comment]
Can you run `npm show lru-cache`? It seems like you are not running the latest version. Maybe try running `./nodebb upgrade -mi` again.

**Comment by mzch** [comment]
When I tried install using PostgreSQL, I finished installation successfully.

**Comment by mzch** [comment]
Oh, `./nodebb upgrade -mi` finished successfully. Thanks!

```
nodebb@n08:~/NodeBB$ npm show lru-cache

lru-cache@7.13.2 | ISC | deps: none | versions: 100
A cache object that deletes the least-recently-used items.
https://github.com/isaacs/node-lru-cache#readme

keywords: mru, lru, cache

dist
.tarball: https://registry.npmjs.org/lru-cache/-/lru-cache-7.13.2.tgz
.shasum: bb5d3f1deea3f3a7a35c1c44345566a612e09cd0
.integrity: sha512-VJL3nIpA79TodY/ctmZEfhASgqekbT574/c4j3jn4bKXbSCnTTCH/KltZyvL2GlV+tGSMtsWyem8DCX7qKTMBA==
.unpackedSize: 73.8 kB

maintainers:
- isaacs <i@izs.me>

dist-tags:
latest: 7.13.2        v7.0-backport: 7.0.4  v7.2-backport: 7.2.3  v7.4-backport: 7.4.5  v7.6-backport: 7.6.1
legacy: 4.1.5         v7.1-backport: 7.1.3  v7.3-backport: 7.3.3  v7.5-backport: 7.5.2  v7.7-backport: 7.7.4

published a week ago by isaacs <i@izs.me>
```

**Comment by battosai30** [comment]
Hi,
I had the same issue, `./nodebb upgrade -mi && ./nodebb upgrade` solved it ;)
