### ISSUE TITLE
error upgrading to v2.5.2 from v2.5.1

### ISSUE THREAD

**Issue by sweetppro** [NodeBB/NodeBB#10876]
### NodeBB version

v2.5.2

### NodeJS version

Node.js v18.8.0

### Installed NodeBB plugins

Active plugins:
	* nodebb-plugin-2factor@5.0.2 (installed, disabled)
	* nodebb-plugin-composer-default@9.1.0 (installed, disabled)
	* nodebb-plugin-dbsearch@5.1.5 (installed, disabled)
	* nodebb-plugin-emoji@4.0.4 (installed, disabled)
	* nodebb-plugin-emoji-android@3.0.0 (installed, disabled)
	* nodebb-plugin-imgur@2.0.5 (installed, disabled)
	* nodebb-plugin-markdown@10.1.0 (installed, disabled)
	* nodebb-plugin-mentions@3.0.11 (installed, disabled)
	* nodebb-plugin-soundpack-default@2.0.1 (installed, disabled)
	* nodebb-plugin-spam-be-gone@1.0.0 (installed, disabled)
	* nodebb-rewards-essentials@0.2.1 (installed, disabled)
	* nodebb-theme-lavender@6.0.0 (installed, disabled)
	* nodebb-theme-persona@12.1.1 (installed, disabled)
	* nodebb-theme-slick@2.0.2 (installed, disabled)
	* nodebb-theme-sweetp@1.0.0 (installed, disabled)
	* nodebb-theme-vanilla@12.1.18 (installed, disabled)
	* nodebb-widget-essentials@6.0.0 (installed, disabled)

### Database type

PostgreSQL

### Exact steps to cause this issue

I ran `./nodebb/upgrade`

### What you expected

the install to complete

### What happened instead

received the following report:
```
Warning: An unexpected error occured when attempting to verify plugin upgradability
Error occurred during upgrade: StatusCodeError: 504 - "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
    at new StatusCodeError (NodeBB/node_modules/request-promise-core/lib/errors.js:32:15)
    at plumbing.callback (NodeBB/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (NodeBB/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (NodeBB/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (NodeBB/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (NodeBB/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
2022-09-04T20:09:01.799Z [4567/3115800] - error: uncaughtException: 504 - "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
StatusCodeError: 504 - "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
    at new StatusCodeError (NodeBB/node_modules/request-promise-core/lib/errors.js:32:15)
    at plumbing.callback (NodeBB/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (NodeBB/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (NodeBB/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (NodeBB/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (NodeBB/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35) {"date":"Sun Sep 04 2022 22:09:01 GMT+0200 (Central European Summer Time)","error":{"error":"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n","message":"504 - \"<html>\\r\\n<head><title>504 Gateway Time-out</title></head>\\r\\n<body>\\r\\n<center><h1>504 Gateway Time-out</h1></center>\\r\\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\"","name":"StatusCodeError","options":{"json":true,"method":"GET","resolveWithFullResponse":false,"simple":true,"transform2xxOnly":false,"url":"https://packages.nodebb.org/api/v1/suggest?version=2.5.2&package[]=nodebb-plugin-imgur&package[]=nodebb-plugin-soundpack-default&package[]=nodebb-theme-sweetp"},"response":{"body":"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n","headers":{"alt-svc":"h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400","cf-cache-status":"DYNAMIC","cf-ray":"74595ad13ffb9205-FRA","connection":"close","content-type":"text/html","date":"Sun, 04 Sep 2022 20:09:01 GMT","nel":"{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}","report-to":"{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=kfCJuK%2Fo%2FnT%2BQLECD0N5wTkhpHFaujS6Ss2tO1hEVUyt8EO4%2Fi0vJpzVT739eATym9GStAxEt9a7GIllHzj%2FO%2FURARgha2N5v0dXhOW5SStOTLwDFAkUrugL4DFlofiN%2FY%2FUbuUpVbsoYHUFGNOXSgW6\"}],\"group\":\"cf-nel\",\"max_age\":604800}","server":"cloudflare","transfer-encoding":"chunked"},"request":{"headers":{"accept":"application/json"},"method":"GET","uri":{"auth":null,"hash":null,"host":"packages.nodebb.org","hostname":"packages.nodebb.org","href":"https://packages.nodebb.org/api/v1/suggest?version=2.5.2&package[]=nodebb-plugin-imgur&package[]=nodebb-plugin-soundpack-default&package[]=nodebb-theme-sweetp","path":"/api/v1/suggest?version=2.5.2&package[]=nodebb-plugin-imgur&package[]=nodebb-plugin-soundpack-default&package[]=nodebb-theme-sweetp","pathname":"/api/v1/suggest","port":443,"protocol":"https:","query":"version=2.5.2&package[]=nodebb-plugin-imgur&package[]=nodebb-plugin-soundpack-default&package[]=nodebb-theme-sweetp","search":"?version=2.5.2&package[]=nodebb-plugin-imgur&package[]=nodebb-plugin-soundpack-default&package[]=nodebb-theme-sweetp","slashes":true}},"statusCode":504},"statusCode":504},"exception":true,"os":{"loadavg":[0.05,0.18,0.25],"uptime":7265985.15},"process":{"argv":["/usr/bin/node","NodeBB/nodebb","upgrade"],"cwd":"NodeBB","execPath":"/usr/bin/node","gid":1003,"memoryUsage":{"arrayBuffers":55123,"external":957398,"heapTotal":23031808,"heapUsed":19983088,"rss":71692288},"pid":3115800,"uid":10009,"version":"v18.8.0"},"stack":"StatusCodeError: 504 - \"<html>\\r\\n<head><title>504 Gateway Time-out</title></head>\\r\\n<body>\\r\\n<center><h1>504 Gateway Time-out</h1></center>\\r\\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\"\n    at new StatusCodeError (NodeBB/node_modules/request-promise-core/lib/errors.js:32:15)\n    at plumbing.callback (NodeBB/node_modules/request-promise-core/lib/plumbing.js:104:33)\n    at Request.RP$callback [as _callback] (NodeBB/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (NodeBB/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:513:28)\n    at Request.<anonymous> (NodeBB/node_modules/request/request.js:1154:10)\n    at Request.emit (node:events:513:28)\n    at IncomingMessage.<anonymous> (NodeBB/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (node:events:627:28)\n    at IncomingMessage.emit (node:events:525:35)","trace":[{"column":15,"file":"NodeBB/node_modules/request-promise-core/lib/errors.js","function":"new StatusCodeError","line":32,"method":null,"native":false},{"column":33,"file":"NodeBB/node_modules/request-promise-core/lib/plumbing.js","function":"plumbing.callback","line":104,"method":"callback","native":false},{"column":31,"file":"NodeBB/node_modules/request-promise-core/lib/plumbing.js","function":"Request.RP$callback [as _callback]","line":46,"method":"RP$callback [as _callback]","native":false},{"column":22,"file":"NodeBB/node_modules/request/request.js","function":"self.callback","line":185,"method":"callback","native":false},{"column":28,"file":"node:events","function":"Request.emit","line":513,"method":"emit","native":false},{"column":10,"file":"NodeBB/node_modules/request/request.js","function":null,"line":1154,"method":null,"native":false},{"column":28,"file":"node:events","function":"Request.emit","line":513,"method":"emit","native":false},{"column":12,"file":"NodeBB/node_modules/request/request.js","function":null,"line":1076,"method":null,"native":false},{"column":28,"file":"node:events","function":"Object.onceWrapper","line":627,"method":"onceWrapper","native":false},{"column":35,"file":"node:events","function":"IncomingMessage.emit","line":525,"method":"emit","native":false}]}
```

**Comment by sweetppro** [comment]
hmm,
I disabled all plugins and reran the upgrade, and it seems to have worked

**Comment by sweetppro** [comment]
Although now I can't load the `Appearance/Skins` tab in the admin panel

**Comment by barisusakli** [comment]
There was an issue with packages.nodebb.org, you can enable the plugins and rerun the upgrade.

**Comment by sweetppro** [comment]
yup that worked
thx
