### ISSUE TITLE
npm run test fails

### ISSUE THREAD

**Issue by bhavya3024** [NodeBB/NodeBB#11050]
### Database type

MongoDB, Redis, PostgreSQL

### Exact steps to cause this issue

I ran npm run test but came with a follwing error.

```
> nodebb@3.0.0-alpha.1 test /Users/bhavya.dhiman/Documents/NodeBB
> nyc --reporter=html --reporter=text-summary mocha

info: configJSON
info: {
  "url": "http://localhost:4567",
  "secret": "9edfb62a-6018-4101-815e-d59617ab840e",
  "database": "mongo",
  "mongo": {
    "host": "127.0.0.1",
    "port": "27017",
    "username": "",
    "password": "",
    "database": "nodebb",
    "uri": ""
  },
  "test_database": {
    "host": "127.0.0.1",
    "port": "6379",
    "password": "",
    "database": "1"
  },
  "port": "4567"
}

info: database config mongo {"database":"1","host":"127.0.0.1","password":"","port":"6379"}
info: environment production

/Users/bhavya.dhiman/Documents/NodeBB/node_modules/jsdom/lib/jsdom/browser/parser/html.js:170
    after._pushedOnStackOfOpenElements?.();
                                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module.replacementCompile (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/jsdom/lib/jsdom/browser/parser/index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.replacementCompile (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:12:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.replacementCompile (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/jsdom/lib/jsdom/living/generated/Element.js:1718:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.replacementCompile (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/jsdom/lib/jsdom/living/interfaces.js:22:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.replacementCompile (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/jsdom/lib/jsdom/browser/Window.js:6:31)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.replacementCompile (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/jsdom/lib/api.js:13:26)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.replacementCompile (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/test/utils.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.replacementCompile (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.<anonymous> (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:195:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async formattedImport (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/mocha/lib/nodejs/esm-utils.js:38:28)
    at async Object.exports.loadFilesAsync (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/mocha/lib/nodejs/esm-utils.js:91:20)
    at async singleRun (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/bhavya.dhiman/Documents/NodeBB/node_modules/mocha/lib/cli/run.js:370:5)

=============================== Coverage summary ===============================
Statements   : 18.93% ( 3506/18517 )
Branches     : 0.63% ( 61/9563 )
Functions    : 3.91% ( 141/3599 )
Lines        : 19.83% ( 3503/17657 )
================================================================================
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodebb@3.0.0-alpha.1 test: `nyc --reporter=html --reporter=text-summary mocha`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodebb@3.0.0-alpha.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bhavya.dhiman/.npm/_logs/2022-11-18T18_50_48_581Z-debug.log
```
I suspect nodejs doesn't support optional chaining operator yet. That's why error is coming on npm run test.
Which nodejs version support this. Let me try with 19 and see if it works or not. If not, what should I do ?

### What you expected

execute test cases successfully.

**Comment by julianlam** [comment]
Hi @bhavya3024 !

[Our test runner checks 14, 16, and 18](https://github.com/NodeBB/NodeBB/blob/master/.github/workflows/test.yaml#L32)

**Comment by bhavya3024** [comment]
Worked, now it is giving this error:
```
info: Giving default global privileges...

info: Enabling default plugins

info: [install/enableDefaultPlugins] activating default plugins {"0":"nodebb-plugin-dbsearch","1":"nodebb-widget-essentials","2":"nodebb-plugin-composer-default"}
warn: You have no mongo username/password setup!
info: [socket.io] Restricting access to origin: *:*

warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-dbsearch
  * nodebb-widget-essentials
  * nodebb-plugin-composer-default
  * nodebb-theme-persona

info: [api] Adding 0 route(s) to `api/v3/plugins`
info: [router] Routes added
info: 🎉 NodeBB Ready
info: 🤝 Enabling 'trust proxy'
info: 📡 NodeBB is now listening on: 0.0.0.0:4567
info: 🔗 Canonical URL: http://localhost:4567

  ........url http://localhost:4567
2022-11-18T20:22:25.855Z [4567/92363] - warn: You have no mongo username/password setup!
2022-11-18T20:22:25.855Z [4567/92362] - warn: You have no mongo username/password setup!
2022-11-18T20:22:25.856Z [4567/92364] - warn: You have no mongo username/password setup!
2022-11-18T20:22:26.781Z [4567/92362] - warn: You have no mongo username/password setup!
!




  8 passing (10s)
  1 failing

  1) should not error out when called:
     Error: connect ECONNREFUSED ::1:4567
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)




=============================== Coverage summary ===============================
Statements   : 35.82% ( 8789/24536 )
Branches     : 16.36% ( 2006/12260 )
Functions    : 23.09% ( 1030/4460 )
Lines        : 36.55% ( 8613/23563 )
================================================================================
```

**Comment by julianlam** [comment]
Assuming you got the test runner working? Let me know if not.
