### ISSUE TITLE
redis authentication fail error

### ISSUE THREAD

**Issue by StopGuardianDev** [NodeBB/NodeBB#11347]
### NodeBB version

v2.8.8

### NodeBB git hash

fb4f1e1315bed7b425756ad25a396c42b2ba3891

### Installed NodeBB plugins

11/3 00:47 [124456] - error: Error: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
    at JavascriptReplyParser._parseResult (/home/stopguardianofficialproxy.website/public_html/nodebb/node_modules/redis/lib/parsers/javascript.js:43:16)
    at JavascriptReplyParser.try_parsing (/home/stopguardianofficialproxy.website/public_html/nodebb/node_modules/redis/lib/parsers/javascript.js:114:21)
    at JavascriptReplyParser.run (/home/stopguardianofficialproxy.website/public_html/nodebb/node_modules/redis/lib/parsers/javascript.js:126:22)
    at JavascriptReplyParser.execute (/home/stopguardianofficialproxy.website/public_html/nodebb/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/home/stopguardianofficialproxy.website/public_html/nodebb/node_modules/redis/index.js:131:27)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

### Database type

Redis

### Database version

v7.0.5

### Exact steps to cause this issue

1. I followed all the steps at https://community.cyberpanel.net/t/how-to-install-nodebb-on-cyberpanel/30643
2. I got to ./nodebb setup and after getting to database password it gave me this error 

11/3 00:49 [124502] - error: Error: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
    at JavascriptReplyParser._parseResult (/home/stopguardianofficialproxy.website/public_html/nodebb/node_modules/redis/lib/parsers/javascript.js:43:16)
    at JavascriptReplyParser.try_parsing (/home/stopguardianofficialproxy.website/public_html/nodebb/node_modules/redis/lib/parsers/javascript.js:114:21)
    at JavascriptReplyParser.run (/home/stopguardianofficialproxy.website/public_html/nodebb/node_modules/redis/lib/parsers/javascript.js:126:22)
    at JavascriptReplyParser.execute (/home/stopguardianofficialproxy.website/public_html/nodebb/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/home/stopguardianofficialproxy.website/public_html/nodebb/node_modules/redis/index.js:131:27)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

### What you expected

For it to work without a password

### What happened instead

It didn't work

**Comment by julianlam** [comment]
Hi @StopGuardianDev — we don't maintain that guide, so we can't offer any support regarding that. It sounds like you're setting up NodeBB with a password in the `redis` block, but the actual redis server you're trying to connect to doesn't have a password set up.

You'll want to contact the Cyberpanel team for assistance on this one.
