### ISSUE TITLE
thumbs Post Can not upload a thumbnail, only multiple uploads

### ISSUE THREAD

**Issue by Veronikya** [NodeBB/NodeBB#11482]
### NodeBB version

v3.0.0-rc.2

### NodeBB git hash

S-1-5-21-813565011-3974154250-3479964205-500

### NodeJS version

v18.15.0

### Exact steps to cause this issue

```
var request = require('request');
var fs = require('fs');
var options = {
  'method': 'POST',
  'url': 'https://test.nodebb.com/api/v3/topics/158/thumbs?_uid=1',
  'headers': {
    'Authorization': 'Bearer ********',
    'Cookie': 'express.sid=********'
  },
  formData: {
    'files': [{
      'value': fs.createReadStream('F:/Data/Pictures/3.jpg'),
      'options': {
        'filename': 'F:/Data/Pictures/3.jpg',
        'contentType': null
      }
    }]
  }
};



request(options, function (error, response) {
  if (error) throw new Error(error);
  console.log(response.body);
});
```
```
response.body:
{
    "status": {
        "code": "bad-request",
        "message": "invalid-files"
    },
    "response": {},
    "stack": "Error: invalid-files\n    at validateFiles (F:\\Data\\Desktop\\xxxxx\\NodeBB-3.0.0-rc.1\\src\\middleware\\index.js:119:15)\n    at Layer.handle [as handle_request] (F:\\Data\\Desktop\\xxxx\\NodeBB-3.0.0-rc.1\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (F:\\Data\\Desktop\\xxxxx\\NodeBB-3.0.0-rc.1\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Form.<anonymous> (F:\\Data\\Desktop\\xxxx\\NodeBB-3.0.0-rc.1\\node_modules\\connect-multiparty\\index.js:114:7)\n    at Form.emit (node:events:525:35)\n    at Form.emit (node:domain:489:12)\n    at F:\\Data\\Desktop\\xxxxx\\NodeBB-3.0.0-rc.1\\node_modules\\multiparty\\index.js:612:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)"
}

```

```
var request = require('request');
var fs = require('fs');
var options = {
  'method': 'POST',
  'url': 'https://test.nodebb.com/api/v3/topics/158/thumbs?_uid=1',
  'headers': {
    'Authorization': 'Bearer ********',
    'Cookie': 'express.sid=********'
  },
  formData: {
    'files': [{
      'value': fs.createReadStream('F:/Data/Pictures/3.jpg'),
      'options': {
        'filename': 'F:/Data/Pictures/3.jpg',
        'contentType': null
      }
    }, {
      'value': fs.createReadStream('F:/Data/Pictures/3.jpg'),
      'options': {
        'filename': 'F:/Data/Pictures/3.jpg',
        'contentType': null
      }
    }]
  }
};



request(options, function (error, response) {
  if (error) throw new Error(error);
  console.log(response.body);
});
```

```
response.body:
{
    "status": {
        "code": "ok",
        "message": "OK"
    },
    "response": {
            {
                "path": "F:\\Data\\Desktop\\*****\\NodeBB-3.0.0-rc.1\\public\\uploads\\files\\1681445963722-3.jpg",
                "name": "3.jpg"
            },
            {
                "url": "/assets/uploads/files/1681445963749-3.jpg",
                "path": "F:\\Data\\Desktop\\*******\\NodeBB-3.0.0-rc.1\\public\\uploads\\files\\1681445963749-3.jpg",
                "name": "3.jpg"
            }
        ]
    }
}
```
I found that this issue is documented, but not resolved
https://github.com/request/request/issues/2445
It seems to be a problem left over from historical requests

In the first code snippet, only one file is being uploaded, but the server is expecting an array of files. This results in the server returning an error message indicating that the files are invalid.

In the second code snippet, two files are being uploaded as an array, and the server returns a success response with the paths and URLs of the uploaded files.

https://github.com/NodeBB/NodeBB/blob/654abb48cd6c998adbbc0a86213e27bf9579904c/src/middleware/index.js#L106

I guess it is middleware.validateFiles This method judges whether it is an error caused by an array, because when the array is one, some requested files may be converted into objects

I tried a lot of tools fetch, postman can not upload a file, only multiple uploads

nodebb log:
This is uploading only one file:
```
🚀 ---------------------------------------------------------------🚀
🚀 ~ file: index.js:109 ~ validateFiles ~ req.files: {
  files: {
    fieldName: 'files',
    originalFilename: '3.jpg',
    path: 'C:\\Users\\xxxxxx\\AppData\\Local\\Temp\\BwuUvChu750zEjyfBWlS_oiR.jpg',
    headers: {
      'content-disposition': 'form-data; name="files"; filename="3.jpg"',
      'content-type': 'image/jpeg'
    },
    size: 212751,
    name: '3.jpg',
    type: 'image/jpeg'
  }
}
🚀 ---------------------------------------------------------------🚀
🚀 ---------------------------------------------------------------------------🚀
🚀 ~ file: index.js:109 ~ validateFiles ~ req.files.files: {
  fieldName: 'files',
  originalFilename: '3.jpg',
  path: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\BwuUvChu750zEjyfBWlS_oiR.jpg',
  headers: {
    'content-disposition': 'form-data; name="files"; filename="3.jpg"',
    'content-type': 'image/jpeg'
  },
  size: 212751,
  name: '3.jpg',
  type: 'image/jpeg'
}
🚀 ---------------------------------------------------------------------------🚀
```

-----------------------------------------------------------------------------------------------------------------
This is uploading multiple files
```
🚀 ~ file: index.js:109 ~ validateFiles ~ req.files.files: [
  {
    fieldName: 'files',
    originalFilename: '3.jpg',
    path: 'C:\\Users\\xxxxxx\\AppData\\Local\\Temp\\CT067jHii8hIBUtjH3yxp9jt.jpg',
    headers: {
      'content-disposition': 'form-data; name="files"; filename="3.jpg"',
      'content-type': 'image/jpeg'
    },
    size: 212751,
    name: '3.jpg',
    type: 'image/jpeg'
  },
  {
    fieldName: 'files',
    originalFilename: '3.jpg',
    path: 'C:\\Users\\xxxxxx\\AppData\\Local\\Temp\\OVnCnHcPz5MvF8NhfdnChZTG.jpg',
    headers: {
      'content-disposition': 'form-data; name="files"; filename="3.jpg"',
      'content-type': 'image/jpeg'
    },
    size: 212751,
    name: '3.jpg',
    type: 'image/jpeg'
  }
]
🚀 ---------------------------------------------------------------------------🚀
```

**Comment by Veronikya** [comment]
I solved it like this
```
middleware.validateFiles = function validateFiles(req, res, next) {
	if (!req.files.files) {
		return next(new Error(['[[error:invalid-files]]']));
	}

	if (Array.isArray(req.files.files) && req.files.files.length) {
		return next();
	}

	if (typeof req.files.files === 'object') {
		req.files.files = [req.files.files];
		return next();
	}

	return next(new Error(['[[error:invalid-files]]']));
};
```

**Comment by barisusakli** [comment]
@Veronikya see here https://github.com/NodeBB/NodeBB/blob/master/src/controllers/uploads.js#L26-L32, maybe we don't need those checks anymore with your propsed change, can you open a PR?
