### ISSUE TITLE
on windows editing the main post deletes the topic thumbs from disk

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#11725]
they are still in `topic:<tid>:thumbs` zset

```
file delete D:\github\NodeBB\public\uploads\files\1687022214592-1687013363139-screenshot-2023-06-17-в-17.47.28.png Error: a
    at file.delete (D:\github\NodeBB\src\file.js:104:35)
    at wrapperCallback (D:\github\NodeBB\src\promisify.js:46:11)
    at Array.map (<anonymous>)
    at Posts.uploads.deleteFromDisk (D:\github\NodeBB\src\posts\uploads.js:216:31)
    at async Posts.uploads.dissociate (D:\github\NodeBB\src\posts\uploads.js:199:4)
    at async Promise.all (index 1)
    at async Posts.uploads.sync (D:\github\NodeBB\src\posts\uploads.js:77:3)
    at async Posts.edit (D:\github\NodeBB\src\posts\edit.js:72:3)
    at async postsAPI.edit (D:\github\NodeBB\src\api\posts.js:108:21)
    at async Posts.edit (D:\github\NodeBB\src\controllers\write\posts.js:78:21)
   ```

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/11727
