### ISSUE TITLE
Please update the plugin for FusionAUTH so it will be compatible with latest version of NodeBB

### ISSUE THREAD

**Issue by ursuad** [NodeBB/NodeBB#11840]
### Description

Hi,
Someone from FusionAuth wrote a guide and a plugin for integrating NodeBB and and using FusionAuth for authentication. 
[Plugin Github repo](https://github.com/FusionAuth/nodebb-plugin-fusionauth-oidc)
[The blog post guide](https://fusionauth.io/blog/2020/05/13/setting-up-single-sign-on-for-nodebb)

I think the plugin might be a bit outdated. When I tried to install it on `v3.2.3` of NodeBB, I got the following errors:
```
2023-07-25T06:43:02.012Z [4567/695] - info: Initializing NodeBB v3.2.3 MY_FORUM_LINK
2023-07-25T06:43:02.664Z [4567/695] - info: [socket.io] Restricting access to origin: https://MY_FORUM_LINK:*
2023-07-25T06:43:02.689Z [4567/695] - warn: [plugins] "nodebb-plugin-gravatar" is active but not installed.
2023-07-25T06:43:02.747Z [4567/695] - warn:    [plugins/nodebb-plugin-fusionauth-oidc] The plugin.json field "library" is deprecated. Please use the package.json field "main" instead.
2023-07-25T06:43:02.747Z [4567/695] - warn: [plugins] Unable to load library for: nodebb-plugin-fusionauth-oidc
2023-07-25T06:43:02.748Z [4567/695] - error: Error: Cannot find module './src/passport-fusionauth-oidc'
Require stack:
- /usr/src/app/node_modules/nodebb-plugin-fusionauth-oidc/library.js
- /usr/src/app/src/plugins/index.js
- /usr/src/app/src/groups/index.js
- /usr/src/app/src/user/index.js
- /usr/src/app/src/events.js
- /usr/src/app/src/meta/themes.js
- /usr/src/app/src/meta/index.js
- /usr/src/app/src/start.js
- /usr/src/app/require-main.js
- /usr/src/app/app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at /usr/src/app/node_modules/nodebb-plugin-fusionauth-oidc/library.js:11:27
    at Object.<anonymous> (/usr/src/app/node_modules/nodebb-plugin-fusionauth-oidc/library.js:251:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)

2023-07-25T06:43:02.748Z [4567/695] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-rewards-essentials
  * nodebb-plugin-fusionauth-oidc
```
Would it be possible for someone that is familiar with NodeBB Plugins to bring it up to date? 

### Community forum reference

https://community.nodebb.org/topic/14746/setting-up-single-sign-on-for-nodebb

**Comment by julianlam** [comment]
You'll want to contact @mooreds directly about bringing this plugin up to date (although that stack trace doesn't look like a compatibility issue 🤔)

**Comment by barisusakli** [comment]
this PR needs merging for 2.x+
https://github.com/FusionAuth/nodebb-plugin-fusionauth-oidc/pull/17

**Comment by mooreds** [comment]
hi folks. We're aware that the nodebb OIDC plugin needs to be updated to work with the latest version of nodebb. There's some patches and forks available on the repo. Sorry about this, it just keeps getting pushed off due to higher priority stuff.
