### ISSUE TITLE
Error upgrade script chat_room_refactor.js UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Sebastian-Roth** [NodeBB/NodeBB#11947]
### NodeBB version

v3.3.6

### NodeBB git hash

7fb387926e5e7ef8e001fcdae19a6e2c7d2f953e

### NodeJS version

v6.14.18

### Installed NodeBB plugins

* nodebb-plugin-2factor@7.2.1 (installed, disabled)
* nodebb-plugin-adsense@3.0.0 (installed, enabled)
* nodebb-plugin-code-button (not installed, enabled)
* nodebb-plugin-composer-default@10.2.13 (installed, enabled)
* nodebb-plugin-dbsearch@6.2.0 (installed, enabled)
* nodebb-plugin-emailer-sendgrid@3.1.5 (installed, disabled)
* nodebb-plugin-emoji@5.1.5 (installed, enabled)
* nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
* nodebb-plugin-markdown@12.1.7 (installed, enabled)
* nodebb-plugin-mentions@4.3.4 (installed, enabled)
* nodebb-plugin-ntfy@1.4.0 (installed, disabled)
* nodebb-plugin-question-and-answer@1.1.0 (installed, enabled)
* nodebb-plugin-spam-be-gone@2.1.1 (installed, enabled)
* nodebb-rewards-essentials@0.2.3 (installed, enabled)
* nodebb-theme-harmony@1.1.41 (installed, disabled)
* nodebb-theme-lavender@7.1.3 (installed, disabled)
* nodebb-theme-peace@2.1.12 (installed, disabled)
* nodebb-theme-persona@13.2.19 (installed, enabled)
* nodebb-theme-vanilla@12.1.19 (installed, disabled)
* nodebb-widget-essentials@7.0.13 (installed, enabled)

### Database type

MongoDB

### Database version

v4.2.24

### Exact steps to cause this issue

Tried to update from from 3.2.x to 3.3.4 at first and then from 3.3.4 to 3.3.6 and ran into the same issue again.

Steps:
```
git fetch
git reset --hard origin/v3.x
./nodebb upgrade
...
### error see below
```

### What you expected

Upgrade scripts should run all the way to the end.

### What happened instead

Error message (does not quit but hangs there with the error, have left it there for 30 minutes with a change):
```
...
4. Updating NodeBB data store schema...
Parsing upgrade scripts... 
OK | 1 script(s) found, 130 skipped
  → [2023/7/2] Update chat messages to add roomId field...
    [####         ] (1600/4159) 38% Error occurred
Error occurred during upgrade: Error: [[error:invalid-score, undefined]]
    at sortedSetAddBulk (/opt/NodeBB/src/database/mongo/sorted/add.js:39:11)
    at module.sortedSetAdd (/opt/NodeBB/src/database/mongo/sorted/add.js:12:17)
    at Object.wrapperCallback [as sortedSetAdd] (/opt/NodeBB/src/promisify.js:46:11)
    at batch.processSortedSet.batch (/opt/NodeBB/src/upgrades/3.3.0/chat_room_refactor.js:62:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.processSortedSet (/opt/NodeBB/src/database/mongo/sorted.js:591:5)
    at async exports.processSortedSet (/opt/NodeBB/src/batch.js:30:10)
    at async batch.processArray.batch (/opt/NodeBB/src/upgrades/3.3.0/chat_room_refactor.js:43:7)
    at async exports.processArray (/opt/NodeBB/src/batch.js:85:3)
(node:16873) UnhandledPromiseRejectionWarning: Error: [[error:invalid-score, undefined]]
    at sortedSetAddBulk (/opt/NodeBB/src/database/mongo/sorted/add.js:39:11)
    at module.sortedSetAdd (/opt/NodeBB/src/database/mongo/sorted/add.js:12:17)
    at Object.wrapperCallback [as sortedSetAdd] (/opt/NodeBB/src/promisify.js:46:11)
    at batch.processSortedSet.batch (/opt/NodeBB/src/upgrades/3.3.0/chat_room_refactor.js:62:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.processSortedSet (/opt/NodeBB/src/database/mongo/sorted.js:591:5)
    at async exports.processSortedSet (/opt/NodeBB/src/batch.js:30:10)
    at async batch.processArray.batch (/opt/NodeBB/src/upgrades/3.3.0/chat_room_refactor.js:43:7)
    at async exports.processArray (/opt/NodeBB/src/batch.js:85:3)
(node:16873) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:16873) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Anything else?

This is a long running install which we updated many times over the years. Can't say which version we started with.

To work around the issue and be able to get the forum back up again I did the following:
```
mv src/upgrades/3.3.0/chat_room_refactor.js .
./nodebb upgrade
```

**Comment by barisusakli** [comment]
@Sebastian-Roth thanks for reporting. 

This would happen if a chat message is somehow missing the `timestamp` field. I will make a modification to the upgrade script so it handles this.

**Comment by Sebastian-Roth** [comment]
@barisusakli Thanks heaps for the super quick answer and fixing the issue straight away as well as releasing a new version!

I just updated to v3.3.8 and the script ran through all the way just fine.
