### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by Michaelwucoc** [NodeBB/NodeBB#11967]
### NodeBB version

3.2.3

### What you expected

Start Normally

### What happened instead

2023-08-13T08:58:31.104Z [4567/191848] - info: Initializing NodeBB v3.2.3 http://shsxslt.icu
2023-08-13T08:59:03.904Z [4567/191848] - error: MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Timeout._onTimeout (/home/NodeBB/node_modules/mongodb/lib/sdam/topology.js:278:38)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[cluster] Child Process (191848) has exited (code: 0, signal: null)

**Comment by Michaelwucoc** [comment]
I mean how to solve the problem. I tried to reset NodeBB

**Comment by Michaelwucoc** [comment]
I am now using npm to reinstall mongodb

**Comment by Michaelwucoc** [comment]
A advice that to create a script that can 1-click install. Including mongodb radis and so on. Or post a video of full install process.
The manual is so difficult for newbie to install!

**Comment by julianlam** [comment]
We can expound more on why a one click script is not used for NodeBB, but let's leave this issue tracker for bugs.
