### ISSUE TITLE
NodeBB Get Plugins list ERROR

### ISSUE THREAD

**Issue by MSCMDD** [NodeBB/NodeBB#12315]
### NodeBB version

v3.6.4

### NodeBB git hash

6e6c3974e4d8685977eb7cc607a8412bd125cc07

### NodeJS version

v20.11.0

### Installed NodeBB plugins

Active plugins:
        * nodebb-plugin-2factor@7.4.0 (installed, disabled)
        * nodebb-plugin-composer-default@10.2.31 (installed, enabled)
        * nodebb-plugin-dbsearch@6.2.3 (installed, disabled)
        * nodebb-plugin-dingtalk-auth@0.1.1 (installed, enabled)
        * nodebb-plugin-emoji@5.1.13 (installed, enabled)
        * nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
        * nodebb-plugin-markdown@12.2.5 (installed, enabled)
        * nodebb-plugin-meilisearch@0.7.1 (installed, enabled)
        * nodebb-plugin-mentions@4.3.7 (installed, enabled)
        * nodebb-plugin-ntfy@1.7.3 (installed, disabled)
        * nodebb-plugin-rss@4.0.0 (installed, enabled)
        * nodebb-plugin-session-sharing@7.1.2 (installed, enabled)
        * nodebb-plugin-soundpack-default@3.0.0 (installed, enabled)
        * nodebb-plugin-spam-be-gone@2.2.0 (installed, disabled)
        * nodebb-plugin-sso-github@3.1.0 (installed, enabled)
        * nodebb-rewards-essentials@1.0.0 (installed, enabled)
        * nodebb-theme-harmony@1.1.108 (installed, enabled)
        * nodebb-theme-lavender@7.1.7 (installed, disabled)
        * nodebb-theme-peace@2.1.26 (installed, disabled)
        * nodebb-theme-persona@13.2.50 (installed, disabled)
        * nodebb-widget-essentials@7.0.14 (installed, enabled)

### Database type

MongoDB

### Database version

v5.0.9

### Exact steps to cause this issue

1、Enter https://example.dom/admin/extend/plugins
2、fetch failed
Although there is a "fetch failed" prompt, the server is able to successfully retrieve the JSON.
Log:
```
2024-01-30T06:12:45.023Z [4567/162713] - error: Error loading https://packages.nodebb.org/api/v1/plugins?version=3.6.4 fetch failed {"cause":{"code":"ETIMEDOUT"},"stack":"TypeError: fetch failed\n    at node:internal/deps/undici/undici:12344:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async call (/www/NodeBB/src/request.js:36:19)\n    at async Plugins.list (/www/NodeBB/src/plugins/index.js:172:30)\n    at async getPlugins (/www/NodeBB/src/controllers/admin/plugins.js:63:23)\n    at async getCompatiblePlugins (/www/NodeBB/src/controllers/admin/plugins.js:54:9)\n    at async Promise.all (index 0)\n    at async pluginsController.get (/www/NodeBB/src/controllers/admin/plugins.js:11:38)\n    at async /www/NodeBB/src/routes/helpers.js:78:5"}
2024-01-30T06:12:45.095Z [4567/162713] - error: Error loading https://packages.nodebb.org/api/v1/plugins fetch failed {"cause":{"code":"ETIMEDOUT"},"stack":"TypeError: fetch failed\n    at node:internal/deps/undici/undici:12344:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:540:9)\n    at process.processTimers (node:internal/timers:514:7)\n    at async call (/www/NodeBB/src/request.js:36:19)\n    at async Plugins.list (/www/NodeBB/src/plugins/index.js:172:30)\n    at async getPlugins (/www/NodeBB/src/controllers/admin/plugins.js:63:23)\n    at async getAllPlugins (/www/NodeBB/src/controllers/admin/plugins.js:58:9)\n    at async Promise.all (index 1)"}
2024-01-30T06:12:45.101Z [4567/162713] - error: GET /api/admin/extend/plugins?_=1706594678987
TypeError: fetch failed
    at node:internal/deps/undici/undici:12344:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processTimers (node:internal/timers:511:9)
    at async call (/www/NodeBB/src/request.js:36:19)
    at async Plugins.listTrending (/www/NodeBB/src/plugins/index.js:185:29)
    at async Promise.all (index 2)
    at async pluginsController.get (/www/NodeBB/src/controllers/admin/plugins.js:11:38)
    at async /www/NodeBB/src/routes/helpers.js:78:5
```

### What you expected

I can retrieve the list of plugins.

**Comment by barisusakli** [comment]
I can't reproduce this, could be something with your network.

**Comment by MSCMDD** [comment]
QAQ

But...
```
root@AwA:/www/NodeBB# ping nodebb.org
PING nodebb.org (192.0.78.247): 56 data bytes
64 bytes from 192.0.78.247: icmp_seq=0 ttl=51 time=209.905 ms
64 bytes from 192.0.78.247: icmp_seq=1 ttl=51 time=209.508 ms
^C--- nodebb.org ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 209.508/209.707/209.905/0.199 ms
root@AwA:/www/NodeBB# ping packages.nodebb.org
PING packages.nodebb.org (172.67.159.182): 56 data bytes
64 bytes from 172.67.159.182: icmp_seq=1 ttl=51 time=301.725 ms
64 bytes from 172.67.159.182: icmp_seq=2 ttl=51 time=301.390 ms
64 bytes from 172.67.159.182: icmp_seq=3 ttl=51 time=301.792 ms
64 bytes from 172.67.159.182: icmp_seq=4 ttl=51 time=301.596 ms
64 bytes from 172.67.159.182: icmp_seq=5 ttl=51 time=301.801 ms
```

**Comment by MSCMDD** [comment]
Emmmmm...
```
--- packages.nodebb.org ping statistics ---
7 packets transmitted, 5 packets received, 28% packet loss
round-trip min/avg/max/stddev = 301.390/301.661/301.801/0.154 ms
```
28% packet loss

**Comment by MSCMDD** [comment]
But...
```
root@AwA:/www/NodeBB# curl https://packages.nodebb.org/api/v1/plugins?version=3.6.4

[{"latest":"1.0.1","updated":"1697843215053","description":"NodeBB plugin that al...
```
This can return JSON.

**Comment by MSCMDD** [comment]
I have tried changing the network and refreshing DNS, but still reported an error
How should I solve it? Thank you!
