### ISSUE TITLE
Error: kill EPERM -- cannot start nodebb

### ISSUE THREAD

**Issue by CLCK0622** [NodeBB/NodeBB#12539]
### NodeBB version

v3.7.4

### NodeBB git hash

c26c904ae7a3cbc5529424bbbba943393bd6d0ea

### NodeJS version

v18.17.1

### Installed NodeBB plugins

Active plugins:
        * @veronikya/nodebb-plugin-meilisearch@1.0.0 (installed, enabled)
        * nodebb-plugin-2factor@7.4.0 (installed, disabled)
        * nodebb-plugin-composer-default@10.2.33 (installed, enabled)
        * nodebb-plugin-dbsearch@6.2.3 (installed, disabled)
        * nodebb-plugin-emoji@5.1.13 (installed, enabled)
        * nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
        * nodebb-plugin-markdown@12.2.6 (installed, enabled)
        * nodebb-plugin-mentions@4.4.0 (installed, enabled)
        * nodebb-plugin-ntfy@1.7.4 (installed, disabled)
        * nodebb-plugin-spam-be-gone@2.2.1 (installed, disabled)
        * nodebb-rewards-essentials@1.0.0 (installed, disabled)
        * nodebb-theme-harmony@1.2.49 (installed, enabled)
        * nodebb-theme-lavender@7.1.8 (installed, disabled)
        * nodebb-theme-peace@2.2.4 (installed, disabled)
        * nodebb-theme-persona@13.3.14 (installed, disabled)
        * nodebb-theme-slick@2.0.2 (installed, disabled)
        * nodebb-theme-vanilla@12.1.19 (installed, disabled)
        * nodebb-widget-essentials@7.0.15 (installed, enabled)

### Database type

MongoDB

### Database version

v7.0.0

### Exact steps to cause this issue

I first discovered that logging in to my site would fail. The log appeared like:
```bash
2024-04-28T02:19:44.237Z [4566/73501] - error: POST /login?error=csrf-invalid
invalid csrf token
```
Later I found that the server had stopped. When I tried to start the server, there would be a error stopping me from doing this.
```bash
ubuntu@VM-0-14-ubuntu:~/nodebb$ ./nodebb start

Starting NodeBB
  "./nodebb stop" to stop the NodeBB server
  "./nodebb log" to view server output
  "./nodebb help" for more commands

Error: kill EPERM
    at process.kill (node:internal/process/per_thread:233:13)
    at /home/ubuntu/nodebb/loader.js:200:14
    at /home/ubuntu/nodebb/node_modules/graceful-fs/graceful-fs.js:362:16
    at FSReqCallback.oncomplete (node:fs:200:23)
/home/ubuntu/nodebb/loader.js:213
                                        throw err;
                                        ^

Error: kill EPERM
    at process.kill (node:internal/process/per_thread:233:13)
    at /home/ubuntu/nodebb/loader.js:200:14
    at /home/ubuntu/nodebb/node_modules/graceful-fs/graceful-fs.js:362:16
    at FSReqCallback.oncomplete (node:fs:200:23) {
  errno: -1,
  code: 'EPERM',
  syscall: 'kill'
}

Node.js v18.17.1
```

### What you expected

The server should be starting normally.

### Anything else?

When I tried to start a dev server, the log was like:
```bash
2024-04-28T02:39:38.348Z [4566/2420703] - info: 🎉 NodeBB Ready
2024-04-28T02:39:38.359Z [4566/2420703] - info: 🤝 Enabling 'trust proxy'
2024-04-28T02:39:38.374Z [4566/2420703] - error: NodeBB address in use, exiting...
Error: listen EADDRINUSE: address already in use 0.0.0.0:4566
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at doListen (node:net:1948:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-04-28T02:39:38.385Z [4570/2420707] - info: [router] Routes added
2024-04-28T02:39:38.388Z [4566/2420703] - error: uncaughtException: listen EADDRINUSE: address already in use 0.0.0.0:4566
Error: listen EADDRINUSE: address already in use 0.0.0.0:4566
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at doListen (node:net:1948:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {"date":"Sun Apr 28 2024 10:39:38 GMT+0800 (China Standard Time)","error":{"address":"0.0.0.0","code":"EADDRINUSE","errno":-98,"port":4566,"syscall":"listen"},"exception":true,"os":{"loadavg":[0.78,0.31,0.23],"uptime":18743609.77},"process":{"argv":["/usr/bin/node","/home/ubuntu/nodebb/app.js"],"cwd":"/home/ubuntu/nodebb","execPath":"/usr/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":19397697,"external":21639377,"heapTotal":105459712,"heapUsed":78972968,"rss":185786368},"pid":2420703,"uid":1000,"version":"v18.17.1"},"stack":"Error: listen EADDRINUSE: address already in use 0.0.0.0:4566\n    at Server.setupListenHandle [as _listen2] (node:net:1751:16)\n    at listenInCluster (node:net:1799:12)\n    at doListen (node:net:1948:7)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)","trace":[{"column":16,"file":"node:net","function":"Server.setupListenHandle [as _listen2]","line":1751,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"node:net","function":"listenInCluster","line":1799,"method":null,"native":false},{"column":7,"file":"node:net","function":"doListen","line":1948,"method":null,"native":false},{"column":21,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":83,"method":"processTicksAndRejections","native":false}]}
2024-04-28T02:39:38.389Z [4566/2420703] - error: Error: listen EADDRINUSE: address already in use 0.0.0.0:4566
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at doListen (node:net:1948:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-04-28T02:39:38.390Z [4566/2420703] - info: [app] Shutdown (SIGTERM/SIGINT/SIGQUIT) Initialised.
2024-04-28T02:39:38.384Z [4568/2420705] - info: [api] Adding 3 route(s) to `api/v3/plugins`
2024-04-28T02:39:38.390Z [4570/2420707] - verbose: [meta/blacklist] Loading 0 blacklist rule(s)
2024-04-28T02:39:38.384Z [4567/2420704] - info: [router] Routes added
2024-04-28T02:39:38.393Z [4566/2420703] - error: Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at new NodeError (node:internal/errors:405:5)
    at Server.close (node:net:2095:12)
    at Object.onceWrapper (node:events:628:28)
    at Server.emit (node:events:526:35)
    at emitCloseNT (node:net:2148:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
2024-04-28T02:39:38.397Z [4567/2420704] - verbose: [meta/blacklist] Loading 0 blacklist rule(s)
2024-04-28T02:39:38.409Z [4570/2420707] - info: 🎉 NodeBB Ready
2024-04-28T02:39:38.414Z [4570/2420707] - info: 🤝 Enabling 'trust proxy'
2024-04-28T02:39:38.416Z [4567/2420704] - info: 🎉 NodeBB Ready
2024-04-28T02:39:38.423Z [4570/2420707] - error: NodeBB address in use, exiting...
Error: listen EADDRINUSE: address already in use 0.0.0.0:4570
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at doListen (node:net:1948:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-04-28T02:39:38.428Z [4567/2420704] - info: 🤝 Enabling 'trust proxy'
2024-04-28T02:39:38.431Z [4567/2420704] - error: NodeBB address in use, exiting...
Error: listen EADDRINUSE: address already in use 0.0.0.0:4567
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at doListen (node:net:1948:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-04-28T02:39:38.433Z [4570/2420707] - error: uncaughtException: listen EADDRINUSE: address already in use 0.0.0.0:4570
Error: listen EADDRINUSE: address already in use 0.0.0.0:4570
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at doListen (node:net:1948:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {"date":"Sun Apr 28 2024 10:39:38 GMT+0800 (China Standard Time)","error":{"address":"0.0.0.0","code":"EADDRINUSE","errno":-98,"port":4570,"syscall":"listen"},"exception":true,"os":{"loadavg":[0.78,0.31,0.23],"uptime":18743609.81},"process":{"argv":["/usr/bin/node","/home/ubuntu/nodebb/app.js"],"cwd":"/home/ubuntu/nodebb","execPath":"/usr/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":19384094,"external":21625774,"heapTotal":103985152,"heapUsed":77007840,"rss":187031552},"pid":2420707,"uid":1000,"version":"v18.17.1"},"stack":"Error: listen EADDRINUSE: address already in use 0.0.0.0:4570\n    at Server.setupListenHandle [as _listen2] (node:net:1751:16)\n    at listenInCluster (node:net:1799:12)\n    at doListen (node:net:1948:7)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)","trace":[{"column":16,"file":"node:net","function":"Server.setupListenHandle [as _listen2]","line":1751,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"node:net","function":"listenInCluster","line":1799,"method":null,"native":false},{"column":7,"file":"node:net","function":"doListen","line":1948,"method":null,"native":false},{"column":21,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":83,"method":"processTicksAndRejections","native":false}]}
2024-04-28T02:39:38.433Z [4570/2420707] - error: Error: listen EADDRINUSE: address already in use 0.0.0.0:4570
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at doListen (node:net:1948:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-04-28T02:39:38.434Z [4570/2420707] - info: [app] Shutdown (SIGTERM/SIGINT/SIGQUIT) Initialised.
2024-04-28T02:39:38.435Z [4570/2420707] - error: Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at new NodeError (node:internal/errors:405:5)
    at Server.close (node:net:2095:12)
    at Object.onceWrapper (node:events:628:28)
    at Server.emit (node:events:526:35)
    at emitCloseNT (node:net:2148:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
2024-04-28T02:39:38.442Z [4567/2420704] - error: uncaughtException: listen EADDRINUSE: address already in use 0.0.0.0:4567
Error: listen EADDRINUSE: address already in use 0.0.0.0:4567
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at doListen (node:net:1948:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {"date":"Sun Apr 28 2024 10:39:38 GMT+0800 (China Standard Time)","error":{"address":"0.0.0.0","code":"EADDRINUSE","errno":-98,"port":4567,"syscall":"listen"},"exception":true,"os":{"loadavg":[0.78,0.31,0.23],"uptime":18743609.83},"process":{"argv":["/usr/bin/node","/home/ubuntu/nodebb/app.js"],"cwd":"/home/ubuntu/nodebb","execPath":"/usr/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":19384062,"external":21625742,"heapTotal":103985152,"heapUsed":76990120,"rss":186322944},"pid":2420704,"uid":1000,"version":"v18.17.1"},"stack":"Error: listen EADDRINUSE: address already in use 0.0.0.0:4567\n    at Server.setupListenHandle [as _listen2] (node:net:1751:16)\n    at listenInCluster (node:net:1799:12)\n    at doListen (node:net:1948:7)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)","trace":[{"column":16,"file":"node:net","function":"Server.setupListenHandle [as _listen2]","line":1751,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"node:net","function":"listenInCluster","line":1799,"method":null,"native":false},{"column":7,"file":"node:net","function":"doListen","line":1948,"method":null,"native":false},{"column":21,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":83,"method":"processTicksAndRejections","native":false}]}
2024-04-28T02:39:38.443Z [4567/2420704] - error: Error: listen EADDRINUSE: address already in use 0.0.0.0:4567
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at doListen (node:net:1948:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-04-28T02:39:38.443Z [4567/2420704] - info: [app] Shutdown (SIGTERM/SIGINT/SIGQUIT) Initialised.
2024-04-28T02:39:38.451Z [4567/2420704] - error: Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at new NodeError (node:internal/errors:405:5)
    at Server.close (node:net:2095:12)
    at Object.onceWrapper (node:events:628:28)
    at Server.emit (node:events:526:35)
    at emitCloseNT (node:net:2148:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
[cluster] Child Process (2420703) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2024-04-28T02:39:38.480Z [4568/2420705] - info: [router] Routes added
2024-04-28T02:39:38.495Z [4568/2420705] - verbose: [meta/blacklist] Loading 0 blacklist rule(s)
[cluster] Child Process (2420707) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2024-04-28T02:39:38.507Z [4568/2420705] - info: 🎉 NodeBB Ready
2024-04-28T02:39:38.510Z [4568/2420705] - info: 🤝 Enabling 'trust proxy'
[cluster] Child Process (2420704) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2024-04-28T02:39:38.517Z [4568/2420705] - error: NodeBB address in use, exiting...
```

**Comment by julianlam** [comment]
You can't start NodeBB in dev mode because it's already started and listening on that port.

Kill it first then start it again.

Use `ps aux | grep node` to find pid.

**Comment by julianlam** [comment]
Continue debugging discussion in NodeBB community. Thank you.
