### ISSUE TITLE
crash in activitypub/mocks.js

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#12613]
```
2024-06-04T12:34:23.551Z [4568/3480205] - ^[[31merror^[[39m: TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:676:13)
    at /home/saas/nodebb/src/activitypub/mocks.js:44:24
    at Array.map (<anonymous>)
    at Mocks.profile (/home/saas/nodebb/src/activitypub/mocks.js:32:45)
    at Actors.assert (/home/saas/nodebb/src/activitypub/actors.js:122:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async middleware.validate (/home/saas/nodebb/src/middleware/activitypub.js:84:2)
2024-06-04T12:34:23.553Z [4568/3480205] - ^[[32minfo^[[39m: [app] Shutdown (SIGTERM/SIGINT/SIGQUIT) Initialise
```

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/6f37825b1a7829d23310f2bb6e3472d24fd45e8b
