### ISSUE TITLE
show which plugin has invalid semver version

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#12979]
```
2024-12-16T14:00:19.820Z [4567/126778] - error: Error loading https://packages.nodebb.org/api/v1/plugins Invalid Version: 1.0.00 {"stack":"TypeError: Invalid Version: 1.0.00\n    at new SemVer (/opt/nodebb/node_modules/semver/classes/semver.js:38:13)\n    at compare (/opt/nodebb/node_modules/semver/functions/compare.js:3:3)\n    at Object.gt (/opt/nodebb/node_modules/semver/functions/gt.js:2:29)\n    at /opt/nodebb/src/plugins/index.js:238:42\n    at Array.forEach (<anonymous>)\n    at Plugins.normalise (/opt/nodebb/src/plugins/index.js:210:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Plugins.list (/opt/nodebb/src/plugins/index.js:178:10)\n    at async getPlugins (/opt/nodebb/src/controllers/admin/plugins.js:63:23)\n    at async getAllPlugins (/opt/nodebb/src/controllers/admin/plugins.js:58:9)"}
2024-12-16T14:00:19.851Z [4567/126778] - error: TypeError: Invalid Version: 1.0.00
at new SemVer (/opt/nodebb/node_modules/semver/classes/semver.js:38:13)
at compare (/opt/nodebb/node_modules/semver/functions/compare.js:3:3)
at Object.gt (/opt/nodebb/node_modules/semver/functions/gt.js:2:29)
at /opt/nodebb/src/plugins/index.js:238:42
at Array.forEach (<anonymous>)
at Plugins.normalise (/opt/nodebb/src/plugins/index.js:210:19)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async Plugins.list (/opt/nodebb/src/plugins/index.js:181:10)
at async getPlugins (/opt/nodebb/src/controllers/admin/plugins.js:63:23)
at async getAllPlugins (/opt/nodebb/src/controllers/admin/plugins.js:58:9)
```

**Comment by girls-whocode** [comment]
./nodebb plugins
Active plugins:
* @nodebb/nodebb-plugin-reactions@2.2.4 (installed, disabled)
* @nodebb/nodebb-widget-board-stats@2.0.8 (installed, disabled)
* nodebb-plugin-2factor@7.5.7 (installed, disabled)
* nodebb-plugin-cards@0.4.0 (installed, disabled)
* nodebb-plugin-composer-default@10.2.43 (installed, disabled)
* nodebb-plugin-dbsearch@6.2.5 (installed, disabled)
* nodebb-plugin-emoji@5.1.15 (installed, disabled)
* nodebb-plugin-emoji-android@4.0.0 (installed, disabled)
* nodebb-plugin-google-analytics@1.1.0 (installed, disabled)
* nodebb-plugin-imgur@4.1.0 (installed, disabled)
* nodebb-plugin-markdown@12.2.8 (installed, disabled)
* nodebb-plugin-mentions@4.4.3 (installed, disabled)
* nodebb-plugin-ntfy@1.7.7 (installed, disabled)
* nodebb-plugin-openai@1.2.0 (installed, disabled)
* nodebb-plugin-question-and-answer@1.2.7 (installed, disabled)
* nodebb-plugin-recent-cards@3.3.2 (installed, disabled)
* nodebb-plugin-spam-be-gone@2.3.0 (installed, disabled)
* nodebb-rewards-essentials@1.0.0 (installed, disabled)
* nodebb-theme-harmony@1.2.88 (installed, disabled)
* nodebb-theme-lavender@7.1.16 (installed, disabled)
* nodebb-theme-peace@2.2.22 (installed, disabled)
* nodebb-theme-persona@13.3.54 (installed, disabled)
* nodebb-widget-essentials@7.0.31 (installed, disabled)

**Comment by barisusakli** [comment]
@girls-whocode try with above commit to see which plugin is causing you an issue.

**Comment by barisusakli** [comment]
@girls-whocode that explains the issue, you will have to change your version to be valid semver so, `1.0.1, 1.0.2 ... 1.0.111` and so on.

**Comment by girls-whocode** [comment]
I agree, I would have, although it has been deleted. I believe the reset removed the nodebb_theme_codename folder

**Comment by girls-whocode** [comment]
Ok, so I fetch the latest commit, rebuild and start with same in the output.log:

NodeBB v3.11.1 Copyright (C) 2013-2024 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

No arguments passed in, so nothing was reset.

Use ./nodebb reset {-t|-p|-w|-s|-a}
-t  themes
-p  plugins
-w  widgets
-s  settings
-a  all of the above

Plugin and theme reset flags (-p & -t) can take a single argument
e.g. ./nodebb reset -p nodebb-plugin-mentions, ./nodebb reset -t nodebb-theme-harmony
Prefix is optional, e.g. ./nodebb reset -p markdown, ./nodebb reset -t harmony
[cluster] Child Process (9110) has exited (code: 0, signal: null)

**Comment by girls-whocode** [comment]
Verified:

git log -1
commit abcb200fda1e757dd74ebaac0428ed208eb8d96c (HEAD, origin/develop)
Author: Barış Soner Uşaklı <barisusakli@gmail.com>
Date:   Mon Dec 16 10:52:57 2024 -0500

**Comment by barisusakli** [comment]
Are you getting `No arguments passed in, so nothing was reset.` this error message when you run `./nodebb start` ? Or are you running `./nodebb reset`?

**Comment by girls-whocode** [comment]
That is the output.log when I run `./nodebb start`

**Comment by girls-whocode** [comment]
Here is the output with `./node reset -a`

```node
./nodebb reset -a
2024-12-16T16:28:11.065Z [4567/9212] - info: [reset] All Widgets moved to Draft Zone
2024-12-16T16:28:11.078Z [4567/9212] - info: [reset] Theme reset to nodebb-theme-harmony and default skin
2024-12-16T16:28:11.079Z [4567/9212] - warn: [reset] Plugin `undefined` was not active on this forum
2024-12-16T16:28:11.080Z [4567/9212] - info: [reset] No action taken.
2024-12-16T16:28:11.086Z [4567/9212] - info: [reset] registered-users given login privilege
2024-12-16T16:28:11.086Z [4567/9212] - info: [reset] Settings reset to default
2024-12-16T16:28:11.086Z [4567/9212] - info: [reset] Reset complete. Please run `./nodebb build` to rebuild assets.
```

**Comment by barisusakli** [comment]
That's expected since all your plugins are disabled right now, you can enable a theme and the composer-default plugin. Then try build again.

I am not sure about the error message you are getting when you run `./nodebb start`. I don't get `No arguments passed in, so nothing was reset.` when I run `./nodebb start`

**Comment by girls-whocode** [comment]
It is really weird... it's like something is stuck. I'll dig through the node cli script to see if something is calling it when I get home

**Comment by duyanhstar** [comment]
Today, i get same problem:
@barisusakli 

`2025-02-14T23:46:18.540Z [9567/217306] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-theme-harmony

2025-02-14T23:46:18.856Z [9568/217307] - info: [api] Adding 0 route(s) to `api/v3/plugins`
2025-02-14T23:46:18.865Z [9568/217307] - info: [router] Routes added
2025-02-14T23:46:18.866Z [9569/217308] - info: [api] Adding 0 route(s) to `api/v3/plugins`
2025-02-14T23:46:18.869Z [9568/217307] - info: 🎉 NodeBB Ready
2025-02-14T23:46:18.871Z [9568/217307] - info: 🤝 Enabling 'trust proxy'`
