### ISSUE TITLE
mongodb crash FieldPath field names may not start with '$'.

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#13007]
Happens with this call `db.getObjectField('someObject', '$somefield')`

```
2024-12-24T00:23:14.794Z [4567/2375379] - ^[[31merror^[[39m: MongoServerError: FieldPath field names may not start with '$'.
    at Connection.sendCommand (/home/saas/nodebb/node_modules/mongodb/lib/cmap/connection.js:296:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.command (/home/saas/nodebb/node_modules/mongodb/lib/cmap/connection.js:323:26)
    at async Server.command (/home/saas/nodebb/node_modules/mongodb/lib/sdam/server.js:170:29)
    at async FindOperation.execute (/home/saas/nodebb/node_modules/mongodb/lib/operations/find.js:36:16)
    at async tryOperation (/home/saas/nodebb/node_modules/mongodb/lib/operations/execute_operation.js:203:20)
    at async executeOperation (/home/saas/nodebb/node_modules/mongodb/lib/operations/execute_operation.js:73:16)
    at async FindCursor._initialize (/home/saas/nodebb/node_modules/mongodb/lib/cursor/find_cursor.js:60:26)
    at async FindCursor.cursorInit (/home/saas/nodebb/node_modules/mongodb/lib/cursor/abstract_cursor.js:607:27)
    at async FindCursor.fetchBatch (/home/saas/nodebb/node_modules/mongodb/lib/cursor/abstract_cursor.js:641:13)

```

**Comment by barisusakli** [comment]
another one that doesn't cause a crash
```
2024-12-24T01:00:06.517Z [4567/2377342] - error: MongoServerError: An empty update path is not valid.
    at UpdateOneOperation.execute (/home/saas/nodebb/node_modules/mongodb/lib/operations/update.js:75:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async tryOperation (/home/saas/nodebb/node_modules/mongodb/lib/operations/execute_operation.js:203:20)
    at async executeOperation (/home/saas/nodebb/node_modules/mongodb/lib/operations/execute_operation.js:73:16)
    at async Collection.updateOne (/home/saas/nodebb/node_modules/mongodb/lib/collection.js:207:16)
    at async module.deleteObjectFields (/home/saas/nodebb/src/database/mongo/hash.js:210:4)
    at async module.deleteObjectField (/home/saas/nodebb/src/database/mongo/hash.js:190:3)
    at async Promise.all (index 3)
    at async Actors.remove (/home/saas/nodebb/src/activitypub/actors.js:269:2)
    at async Promise.all (index 14)
```
