### ISSUE TITLE
Error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#2316]
```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:331:11)
    at ServerResponse.header (/var/www/nodebb/node_modules/express/lib/response.js:662:10)
    at ServerResponse.send (/var/www/nodebb/node_modules/express/lib/response.js:146:12)
    at defaultFn (/var/www/nodebb/src/middleware/middleware.js:406:10)
    at /var/www/nodebb/src/middleware/middleware.js:441:7
    at checkComplete (/var/www/nodebb/public/src/translator.js:138:5)
    at Object.translator.translate (/var/www/nodebb/public/src/translator.js:134:3)
    at /var/www/nodebb/src/middleware/middleware.js:440:17
    at View.express [as engine] (/var/www/nodebb/node_modules/templates.js/lib/templates.js:76:11)
    at View.render (/var/www/nodebb/node_modules/express/lib/view.js:76:8)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:331:11)
    at ServerResponse.header (/var/www/nodebb/node_modules/express/lib/response.js:662:10)
    at ServerResponse.res.location (/var/www/nodebb/node_modules/express/lib/response.js:776:8)
    at ServerResponse.redirect (/var/www/nodebb/node_modules/express/lib/response.js:815:8)
    at handleErrors (/var/www/nodebb/src/routes/index.js:185:6)
    at Layer.handle_error (/var/www/nodebb/node_modules/express/lib/router/layer.js:58:5)
    at trim_prefix (/var/www/nodebb/node_modules/express/lib/router/index.js:268:13)
    at /var/www/nodebb/node_modules/express/lib/router/index.js:237:9
    at Function.proto.process_params (/var/www/nodebb/node_modules/express/lib/router/index.js:312:12)
    at /var/www/nodebb/node_modules/express/lib/router/index.js:228:12
```

**Comment by Vinlow** [comment]
After upgrading, this issue appeared on my board.
It only appears when i try to access the "edit user page".

18/5 10:53 [1720] - error: Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:691:11)
    at ServerResponse.header (/var/www/****/node_modules/express/lib/response.js:695:10)
    at ServerResponse.send (/var/www/****/node_modules/express/lib/response.js:146:12)
    at ServerResponse.json (/var/www/****/node_modules/express/lib/response.js:235:15)
    at ServerResponse.res.render (/var/www/****/src/middleware/middleware.js:389:15)
    at /var/www/****/src/controllers/accounts.js:339:7
    at /var/www/****/src/database/redis/hash.js:31:4
    at /var/www/****/src/database/redis/hash.js:37:4
    at /var/www/****/src/database/redis/hash.js:66:4
    at /var/www/****/node_modules/redis/index.js:1138:13

Any ideas how i can fix this?
