### ISSUE TITLE
Invalid csrf token error on login and register

### ISSUE THREAD

**Issue by pejuaxel** [NodeBB/NodeBB#2571]
After upgrading to 0.6.0, I'm getting an invalid csrf token error when trying to log in or register:

```
error: /login
 Error: invalid csrf token
    at verifytoken (/Users/axel/Sites/NodeBB/node_modules/csurf/index.js:237:11)
    at csrf (/Users/axel/Sites/NodeBB/node_modules/csurf/index.js:100:7)
    at Layer.handle [as handle_request] (/Users/axel/Sites/NodeBB/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/axel/Sites/NodeBB/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/Users/axel/Sites/NodeBB/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/Users/axel/Sites/NodeBB/node_modules/express/lib/router/layer.js:82:5)
    at /Users/axel/Sites/NodeBB/node_modules/express/lib/router/index.js:235:24
    at Function.proto.process_params (/Users/axel/Sites/NodeBB/node_modules/express/lib/router/index.js:313:12)
    at /Users/axel/Sites/NodeBB/node_modules/express/lib/router/index.js:229:12
    at Function.match_layer (/Users/axel/Sites/NodeBB/node_modules/express/lib/router/index.js:296:3)
```

Here are the versions of the themes:
── nodebb-theme-lavender@0.2.7 
── nodebb-theme-vanilla@0.2.6

**Comment by jacobbridges** [comment]
I am running v0.5.1 of NodeBB, and when I attempt to log in to the forum on two different computers, I get that error. A hard refresh and another log in attempt usually fixes this.

**Comment by julianlam** [comment]
Can anyone reliably reproduce this? A clean install works fine for me.

**Comment by pejuaxel** [comment]
A clean install works fine as well. However this issue occurs when using the redis database that version 0.5.7 used.

**Comment by pejuaxel** [comment]
I managed to find out what caused the bug to show up. You can reliably reproduce this issue by using a ' character in the site title. For instance, using "McDonald's" will cause the issue to show up, while using "McDonald" won't.
