### ISSUE TITLE
Error installing or uninstalling plugins on latest master

### ISSUE THREAD

**Issue by pichalite** [NodeBB/NodeBB#2615]
```
nodebb-plugin-rss@0.2.10 node_modules/nodebb-plugin-rss
├── string@1.7.0
└── to-markdown@0.0.2 (he@0.5.0)
15/1 10:42 [51856] - error: ReferenceError: plugins is not defined
```

**Comment by julianlam** [comment]
Paste full stack trace please

**Comment by pichalite** [comment]
```
nodebb-plugin-rss@0.2.10 node_modules/nodebb-plugin-rss
├── string@1.7.0
└── to-markdown@0.0.2 (he@0.5.0)
15/1 10:42 [51856] - error: ReferenceError: plugins is not defined
    at /path-to-nodebb/src/plugins/install.js:91:5
    at save (/path-to-nodebb/node_modules/npm/lib/install.js:372:12)
    at /path-to-nodebb/node_modules/npm/lib/install.js:115:7
    at /path-to-nodebb/node_modules/npm/lib/install.js:225:5
    at /path-to-nodebb/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
    at /path-to-nodebb/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
    at cb (/path-to-nodebb/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /path-to-nodebb/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
    at cb (/path-to-nodebb/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /path-to-nodebb/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
ReferenceError: plugins is not defined
    at /path-to-nodebb/src/plugins/install.js:91:5
    at save (/path-to-nodebb/node_modules/npm/lib/install.js:372:12)
    at /path-to-nodebb/node_modules/npm/lib/install.js:115:7
    at /path-to-nodebb/node_modules/npm/lib/install.js:225:5
    at /path-to-nodebb/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
    at /path-to-nodebb/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
    at cb (/path-to-nodebb/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /path-to-nodebb/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
    at cb (/path-to-nodebb/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /path-to-nodebb/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
```
