### ISSUE TITLE
Problem with Login on IOS/safari

### ISSUE THREAD

**Issue by razoraxis** [NodeBB/NodeBB#2642]
I seem to be having an issue with ios/safari where a user can view the forum but when they login they get a black screen saying forbidden. Seems to be global for the most part.

On monday when we did an upgarde to .6.1-dev and then back down to 6.0 due to issues. Just incase its related not sure if the issue has been going on that long.

Log:

warn: Route requested but not found: /csrf.js
error: /login
Error: invalid csrf token
at verifytoken (/var/node/NodeBB/node_modules/csurf/index.js:237:11)
at csrf (/var/node/NodeBB/node_modules/csurf/index.js:100:7)
at Layer.handle [as handle_request] (/var/node/NodeBB/node_modules/express/lib/router/layer.js:82:5)
at next (/var/node/NodeBB/node_modules/express/lib/router/route.js:110:13)
at Route.dispatch (/var/node/NodeBB/node_modules/express/lib/router/route.js:91:3)
at Layer.handle [as handle_request] (/var/node/NodeBB/node_modules/express/lib/router/layer.js:82:5)
at /var/node/NodeBB/node_modules/express/lib/router/index.js:267:22
at Function.proto.process_params (/var/node/NodeBB/node_modules/express/lib/router/index.js:321:12)
at next (/var/node/NodeBB/node_modules/express/lib/router/index.js:261:10)
at Function.proto.handle (/var/node/NodeBB/node_modules/express/lib/router/index.js:166:3)

/var/node/NodeBB$ find ./ -name "csrf"
./node_modules/csurf
./node_modules/csurf/node_modules/csrf
./public/src/modules/csrf.js

**Comment by MegaGM** [comment]
oh, freaking ` /apple-touch-icon `

0.7.0-dev
![](http://i.imgur.com/cp9Qr7q.png)

**Comment by psychobunny** [comment]
We've released 0.7.0, do you still have this problem after upgrading?
