### ISSUE TITLE
0.6.1dev Groups unable to acces to group page

### ISSUE THREAD

**Issue by esiao** [NodeBB/NodeBB#2648]
`/groups` is working and listing all groups.
`/groups/groupname` isn't working an error is returned
```
Erreur interne.
Oops ! Il semblerait que quelque chose se soit mal passé !
/api/groups/VIP
Ce groupe n'existe pas
```

And in logs
```
24/1 12:53 [1406] - error: /groups/VIP
 Error: [[error:no-group]]
    at /home/esiao/forum/src/groups.js:242:21
    at /home/esiao/forum/src/database/redis/hash.js:31:4
    at /home/esiao/forum/src/database/redis/hash.js:37:4
    at /home/esiao/forum/src/database/redis/hash.js:66:4
    at /home/esiao/forum/node_modules/redis/index.js:1138:13
    at try_callback (/home/esiao/forum/node_modules/redis/index.js:573:9)
    at RedisClient.return_reply (/home/esiao/forum/node_modules/redis/index.js:661:13)
    at ReplyParser.<anonymous> (/home/esiao/forum/node_modules/redis/index.js:309:14)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_reply (/home/esiao/forum/node_modules/redis/lib/parser/javascript.js:300:10)

```

**Comment by barisusakli** [comment]
We started using group slugs in urls so if you have custom theme you need to change the group urls to this

`<a href="{config.relative_path}/groups/{groups.slug}">{groups.name}</a>`

**Comment by esiao** [comment]
It's working thanks.
