### ISSUE TITLE
Pagination is broken. 

### ISSUE THREAD

**Issue by a5mith** [NodeBB/NodeBB#2671]
Running master, git rev-parse HEAD is eb5746b2b. Pagination gives error
```
ERR value is not an integer or out of range
```

**Comment by barisusakli** [comment]
Make sure you are update on vanilla and lavender, also if you have a custom theme there has been some changes to the paginator. 
Namely a new paginator partial. https://github.com/NodeBB/nodebb-theme-vanilla/commit/2fb032603140ab546935a291efcd4943960200be

**Comment by a5mith** [comment]
Themes are up to date, logs state

```
 Error: ERR value is not an integer or out of range
    at ReplyParser.<anonymous> (/home/a_5mith/35hz/node_modules/redis/index.js:305:31)
    at ReplyParser.emit (events.js:95:17)
    at ReplyParser.send_error (/home/a_5mith/35hz/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/home/a_5mith/35hz/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/home/a_5mith/35hz/node_modules/redis/index.js:534:27)
    at Socket.<anonymous> (/home/a_5mith/35hz/node_modules/redis/index.js:91:14)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
```

**Comment by barisusakli** [comment]
What version is templates.js? Tryin updating to latest.

**Comment by a5mith** [comment]
0.1.10. Updated to 0.1.15 and pagination vanishes completely. Installing using npm sets the version at 0.1.10.

**Comment by barisusakli** [comment]
Hmm seems to work for me. Latest master, t.js@0.1.15, vanilla@0.2.29, lavender@0.2.13.

Is it broken on all themes?

**Comment by a5mith** [comment]
I'm using Lavender. No modifications outside of CSS changes. Will have a play again with 0.1.15 and try using Vanilla and let you know.

**Comment by a5mith** [comment]
Yeah, 0.1.15 fixed it. I cloned it off github the first time, ran it through npm the 2nd time and did a full stop/start. Resolved. :)
