### ISSUE TITLE
Cluster Mode + Forever = Crash

### ISSUE THREAD

**Issue by jchamb2010** [NodeBB/NodeBB#2697]
I was playing around with cluster mode in NodeBB and came across a bug.

If you put additional ports and then try to start NodeBB using 
`node ./app.js`

You will get the following error:

    5/2 10:42 [1940] - info: NodeBB v0.6.0 Copyright (C) 2013-2014 NodeBB Inc.
    5/2 10:42 [1940] - info: This program comes with ABSOLUTELY NO WARRANTY.
    5/2 10:42 [1940] - info: This is free software, and you are welcome to redistribute it under certain conditions.
    5/2 10:42 [1940] - info: 
    5/2 10:42 [1940] - info: Time: Thu Feb 05 2015 10:42:08 GMT-0500 (EST)
    5/2 10:42 [1940] - info: Initializing NodeBB v0.6.0
    5/2 10:42 [1940] - info: Enabling 'trust proxy'
    5/2 10:42 [1940] - warn: [meta/templates] Partial not loaded: partials/breadcrumbs.tpl
    5/2 10:42 [1940] - warn: [meta/templates] Partial not loaded: partials/paginator.tpl
    5/2 10:42 [1940] - error: TypeError: path must be a string
        at Object.fs.exists (fs.js:166:11)
        at [FilePath]/nodebb/src/webserver.js:143:8
        at [FilePath]/nodebb/node_modules/async/lib/async.js:610:21
        at [FilePath]/nodebb/node_modules/async/lib/async.js:249:17
        at iterate ([FilePath]/nodebb/node_modules/async/lib/async.js:149:13)
        at async.eachSeries ([FilePath]/nodebb/node_modules/async/lib/async.js:165:9)
        at _asyncMap ([FilePath]/nodebb/node_modules/async/lib/async.js:248:13)
        at Object.mapSeries ([FilePath]/nodebb/node_modules/async/lib/async.js:231:23)
        at Object.async.series ([FilePath]/nodebb/node_modules/async/lib/async.js:608:19)
        at Object.module.exports.testSocket ([FilePath]/nodebb/src/webserver.js:141:9)
    TypeError: path must be a string
        at Object.fs.exists (fs.js:166:11)
        at [FilePath]/nodebb/src/webserver.js:143:8
        at [FilePath]/nodebb/node_modules/async/lib/async.js:610:21
        at [FilePath]/nodebb/node_modules/async/lib/async.js:249:17
        at iterate ([FilePath]/nodebb/node_modules/async/lib/async.js:149:13)
        at async.eachSeries ([FilePath]/nodebb/node_modules/async/lib/async.js:165:9)
        at _asyncMap ([FilePath]/nodebb/node_modules/async/lib/async.js:248:13)
        at Object.mapSeries ([FilePath]/nodebb/node_modules/async/lib/async.js:231:23)
        at Object.async.series ([FilePath]/nodebb/node_modules/async/lib/async.js:608:19)
        at Object.module.exports.testSocket ([FilePath]/nodebb/src/webserver.js:141:9)
    5/2 10:42 [1940] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
    5/2 10:42 [1940] - info: [app] Database connection closed.

    net.js:1233
        throw new Error('Not running');
              ^
    Error: Not running
        at Server.close (net.js:1233:11)
        at shutdown ([FilePath]/nodebb/app.js:374:36)
        at process.<anonymous> ([FilePath]/nodebb/app.js:211:7)
        at process.EventEmitter.emit (events.js:95:17)
        at process._fatalException (node.js:272:26)

You therefore cannot run NodeBB using a Forever monitor with cluster mode enabled.

If I remove all but one of the ports or start NodeBB using `./nodebb start` it starts without error.

I'm not highly concerned with this issue because I don't need clustering, but it was there so I was playing with it :P

-John

**Comment by julianlam** [comment]
The NodeBB loader removes the need to use the forever daemon, actually, as any crashes will cause the service to come right back up again.

**Comment by jchamb2010** [comment]
Ahh, ok. Guess this is a non-issue then. 

Thanks for the quick reply.
