### ISSUE TITLE
Forbidden Error On Login and Register

### ISSUE THREAD

**Issue by Stormtrooper595** [NodeBB/NodeBB#2728]
For some reason I was able to login, but after that, others are not capable of registering/logging in.
./nodebb log Spits this out:
15/2 22:21 [19420] - error: /register

Error: invalid csrf token
    at verifytoken (/home/nodebb/nodebb/node_modules/csurf/index.js:237:11)
    at csrf (/home/nodebb/nodebb/node_modules/csurf/index.js:100:7)
    at Layer.handle [as handle_request] (/home/nodebb/nodebb/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/nodebb/nodebb/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/home/nodebb/nodebb/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/home/nodebb/nodebb/node_modules/express/lib/router/layer.js:82:5)
    at /home/nodebb/nodebb/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/home/nodebb/nodebb/node_modules/express/lib/router/index.js:321:12)
    at next (/home/nodebb/nodebb/node_modules/express/lib/router/index.js:261:10)
    at Function.proto.handle (/home/nodebb/nodebb/node_modules/express/lib/router/index.js:166:3)

Just to mention, I am not running this process via root, It is being ran on CentOS 7 with a user named nodebb.

**Comment by Stormtrooper595** [comment]
I am using the Classic Theme, I Just read that someone else has the same issue with it, must be outdated, sorry for wasting space on the bug reports section.

**Comment by julianlam** [comment]
Okay, glad to hear it works with regular themes :smile:

**Comment by greasan** [comment]
How did you solve the issue? I have the same. But cannot read the log. Nothing found ...

**Comment by julianlam** [comment]
Depends on your version... you must have the appropriate vanilla/lavender version for your NodeBB version.
