### ISSUE TITLE
invalid csrf token in branch 0.6.x

### ISSUE THREAD

**Issue by laudney** [NodeBB/NodeBB#2760]
After upgrading from 0.5.7 to 0.6.x, we keep getting invalid csrf error on login and logout. We have installed nodebb-theme-lavender at version 0.2.13 and nodebb-theme-vanilla at version 0.2.35.

23/2 15:15 [2525] - error: /login
 ForbiddenError: invalid csrf token
    at verifytoken (/home/reddcoin/reddcointalk.org/node_modules/csurf/index.js:263:11)
    at csrf (/home/reddcoin/reddcointalk.org/node_modules/csurf/index.js:93:7)
    at Layer.handle [as handle_request] (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/layer.js:82:5)
    at /home/reddcoin/reddcointalk.org/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/index.js:321:12)
    at next (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/index.js:261:10)
    at Function.proto.handle (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/index.js:166:3)
23/2 15:15 [2525] - error: /logout
 ForbiddenError: invalid csrf token
    at verifytoken (/home/reddcoin/reddcointalk.org/node_modules/csurf/index.js:263:11)
    at csrf (/home/reddcoin/reddcointalk.org/node_modules/csurf/index.js:93:7)
    at Layer.handle [as handle_request] (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/layer.js:82:5)
    at /home/reddcoin/reddcointalk.org/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/index.js:321:12)
    at next (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/index.js:261:10)
    at Function.proto.handle (/home/reddcoin/reddcointalk.org/node_modules/express/lib/router/index.js:166:3)

**Comment by julianlam** [comment]
Just a thought... what happens if you clear all of the cookies related to reddcointalk.org? Does the login start working then?

**Comment by laudney** [comment]
Clearing cookies in browsers doesn't solve the problem.

**Comment by laudney** [comment]
Is it somehow affected by the IP address of the server?

**Comment by julianlam** [comment]
Is this on a separate build? The production site seems to be working fine to me.

**Comment by laudney** [comment]
The production site has been reverted back to 0.5.7

**Comment by julianlam** [comment]
Any error messages in server logs or on client side? Sounds like the csrf token isn't generated or saved properly.

When logging in, inspect the login POST call -- does it have the `x-csrf-token` header?

**Comment by reddink** [comment]
Hi Julian, I am taking this up from laudney.
So I have set up a test VM to help sort this out. (i have run a few setups already for plugin dev)

Steps so far are
I just did a fresh clone of 0.6.x into a clean directory
used the provided DB from laudney
after nodebb start up attempted to log in
same csrf issue persists as reported

to answer your previous question the x-csrf-token exists in the header

as a sanity check,
i imported one of my DB backups,
after performing upgrade, running up and logging in. the error did not occur

from this i would have to assume that the issue is local to the DB and probably there is a field in the reddcointalk forum DB that it is not happy about.

**Comment by reddink** [comment]
Julian
I have done some further testing,
While i was originally testing on a http site, and i was able to make it work

reddcointalk is https

When i check the headers in this case, there is no x-csrf-token in the POST header

**Comment by niklas-heer** [comment]
Do you use nginx? Because I ran into this problem while I moved the forum between domains. To fix it i deleted the cache of nginx and restartet it.

On CentOS 6 I did (as root):
```sh
service nginx stop
rm -rf /var/cache/nginx/
mkdir /var/cache/nginx/
service nginx start
```

**Comment by FLYBYME** [comment]
Im getting this error too.
Version: 0.6.1
npm ls nodebb-theme-vanilla nodebb-theme-lavender
├── nodebb-theme-lavender@0.2.13 
└── nodebb-theme-vanilla@0.2.36 
I my first install and I cant login. Anyone know of a fix?
