### ISSUE TITLE
filter:post.parse deprecated?

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#2869]
https://github.com/NodeBB/NodeBB/wiki/Writing-Plugins-for-NodeBB

**Comment by atomoc** [comment]
I use NodeBB **v0.7.0dev**
**plugin.json:**
```js
{
    "id": "nodebb-plugin-test",
    "name": "Plugin name",
    "url": "url to github",
    "library": "./index.js",
    "hooks": [
        {
            "hook": "filter:post.parse"
            , "method": "parse"
            , "callbacked": true
        }
    ]
}
```
**index.js**:
```javascript
(function(Preparsed) {
'use strict'

var async = module.parent.require('async'),
	db = module.parent.require('./database');

Preparsed.parse = function(postContent, callback) {
    postContent = postContent.replace(/123/g, "check")
    callback(null, postContent)
}

}(module.exports))
```
**package.json:**
```js
{
  "name": "nodebb-plugin-test",
  "version": "1.0.0",
  "description": "Description plugin",
  "main": "index.js",
  "author": "I'm <me@mail.com>",
  "license": "MIT",
  "dependencies": {
    "express": "^4.12.0",
    "passport-http-bearer": "^1.0.1"
  },
  "nbbpm": {
    "compatibility": "^0.6.0"
  }
}
```
I create topic. Topic name: 123123123, Content: 123 123 123
123 should be replaced by check, but nothing happens.

**Comment by julianlam** [comment]
Please direct all plugin implementation questions to the forum, as this
issue tracker is for bugs with NodeBB itself.

That said, the plugin documentation does need updating.

**Comment by atomoc** [comment]
Ok!

**Comment by psychobunny** [comment]
https://community.nodebb.org/topic/3039/filter-post-parse-and-filter-post-parsesignature-changes

Will close after updating docs

**Comment by atomoc** [comment]
Thanks!

**Comment by psychobunny** [comment]
np :)

**Comment by atomoc** [comment]
:) Works for me! but it took me to remove: `db = module.parent.require('./database')`
Output:
```
16/3 17:15 [6679] - error: Error: Not running
    at Server.close (net.js:1236:11)
    at process.shutdown (/home/me/nodebb/app.js:364:36)
    at process.emit (events.js:92:17)
    at Signal.wrap.onsignal (node.js:761:46)
Error: Not running
    at Server.close (net.js:1236:11)
    at process.shutdown (/home/me/nodebb/app.js:364:36)
    at process.emit (events.js:92:17)
    at Signal.wrap.onsignal (node.js:761:46)
16/3 17:15 [6679] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
16/3 17:15 [6679] - info: [app] Database connection closed.

net.js:1236
    throw new Error('Not running');
          ^
Error: Not running
    at Server.close (net.js:1236:11)
    at shutdown (/home/me/nodebb/app.js:364:36)
    at process.<anonymous> (/home/me/nodebb/app.js:206:7)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
```

**Comment by psychobunny** [comment]
It's a pretty old wiki page actually, once we spend some time expanding our official docs page: https://docs.nodebb.org/en/latest/plugins/create.html

we will remove this page and redirect

**Comment by atomoc** [comment]
It will be great!
