### ISSUE TITLE
Latest master branch is broken

### ISSUE THREAD

**Issue by astr0skillz** [NodeBB/NodeBB#2914]
Hi,

Upgrading from the latest stable 0.6.x version, I cannot seem to get the master branch working. I'm getting the following error upon executing ./nodebb upgrade:

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/webserver/web/blockify.us/public_html/forums/node_modules/mmmagic/build/Release/magic.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/webserver/web/blockify.us/public_html/forums/node_modules/mmmagic/index.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I've also tried to perform a clean installation, with the same output. Any other branches work fine. If it makes any difference:
- Node version: 0.12.1
- NPM version: 2.5.1

Please let me know if you need additional details.

Thanks.

**Comment by barisusakli** [comment]
https://community.nodebb.org/topic/4108/nodebb-0-7-0-dev-fails-to-install
