### ISSUE TITLE
Logs show frequent crashes

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#3079]
Is this something I should be concerned about?
```log
22/4 10:25 [14390] - [31merror[39m: /topic/1174/make-it-deutsch+++++++++++++++++++++++++++++Result:+%e8%f1%ef%ee%eb%fc%e7%ee%e2%e0%ed+%ed%e8%ea%ed%e5%e9%ec+"Williamnisk";+%e7%e0%f0%e5%e3%e8%f1%f2%f0%e8%f0%ee%e2%e0%eb%e8%f1%fc;+%e2%ee%f8%eb%e8;+%ed%e5+%ed%e0%f8%eb%ee%f1%fc+%f4%ee%f0%ec%fb+%e4%eb%ff+%ee%f2%ef%f0%e0%e2%ea%e8;+%e2%ee%e7%ec%ee%e6%ed%ee,+%f0%e5%e3%e8%f1%f2%f0%e0%f6%e8%ff+%ed%e5+%f3%e4%e0%eb%e0%f1%fc+(%e2%fb%f1%eb%e0%ed+%ea%ee%e4+%e0%ea%f2%e8%e2%e0%f6%e8%e8+/+%e8%f1%ef%ee%eb%fc%e7%f3%e5%f2%f1%ff+%e4%ee%ef%ee%eb%ed%e8%f2%e5%eb%fc%ed%e0%ff+%e7%e0%f9%e8%f2%e0+/+%f1%e1%ee%e9+%e2+%f0%e0%e1%ee%f2%e5+%f4%ee%f0%f3%ec%e0+/+...);
 Error: Bad Request
    at SendStream.error (/opt/nodebb/node_modules/express/node_modules/send/index.js:239:16)
    at SendStream.pipe (/opt/nodebb/node_modules/express/node_modules/send/index.js:411:32)
    at serveStatic (/opt/nodebb/node_modules/express/node_modules/serve-static/index.js:107:12)
    at Layer.handle [as handle_request] (/opt/nodebb/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/opt/nodebb/node_modules/express/lib/router/index.js:271:13)
    at /opt/nodebb/node_modules/express/lib/router/index.js:238:9
    at Function.proto.process_params (/opt/nodebb/node_modules/express/lib/router/index.js:313:12)
    at /opt/nodebb/node_modules/express/lib/router/index.js:229:12
    at Function.match_layer (/opt/nodebb/node_modules/express/lib/router/index.js:296:3)
    at next (/opt/nodebb/node_modules/express/lib/router/index.js:190:10)
22/4 10:25 [14390] - [31merror[39m: Invalid url fragment : topic/1174/make-it-deutsch+++++++++++++++++++++++++++++Result:+%e8%f1%ef%ee%eb%fc%e7%ee%e2%e0%ed+%ed%e8%ea%ed%e5%e9%ec+"Williamnisk";+%e7%e0%f0%e5%e3%e8%f1%f2%f0%e8%f0%ee%e2%e0%eb%e8%f1%fc;+%e2%ee%f8%eb%e8;+%ed%e5+%ed%e0%f8%eb%ee%f1%fc+%f4%ee%f0%ec%fb+%e4%eb%ff+%ee%f2%ef%f0%e0%e2%ea%e8;+%e2%ee%e7%ec%ee%e6%ed%ee,+%f0%e5%e3%e8%f1%f2%f0%e0%f6%e8%ff+%ed%e5+%f3%e4%e0%eb%e0%f1%fc+(%e2%fb%f1%eb%e0%ed+%ea%ee%e4+%e0%ea%f2%e8%e2%e0%f6%e8%e8+/+%e8%f1%ef%ee%eb%fc%e7%f3%e5%f2%f1%ff+%e4%ee%ef%ee%eb%ed%e8%f2%e5%eb%fc%ed%e0%ff+%e7%e0%f9%e8%f2%e0+/+%f1%e1%ee%e9+%e2+%f0%e0%e1%ee%f2%e5+%f4%ee%f0%f3%ec%e0+/+...); URIError: URI malformed
    at decodeURIComponent (native)
    at Object.Meta.title.build (/opt/nodebb/src/meta/title.js:22:10)
    at Object.async.parallel.title (/opt/nodebb/src/middleware/middleware.js:234:16)
    at /opt/nodebb/node_modules/async/lib/async.js:583:25
    at /opt/nodebb/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/opt/nodebb/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/opt/nodebb/node_modules/async/lib/async.js:124:9)
    at _parallel (/opt/nodebb/node_modules/async/lib/async.js:582:20)
    at Object.async.parallel (/opt/nodebb/node_modules/async/lib/async.js:598:9)
22/4 10:25 [14390] - [31merror[39m: /register
 invalid csrf token
22/4 10:25 [14390] - [31merror[39m: /login
 invalid csrf token
22/4 10:25 [14390] - [31merror[39m: /topic/1174/make-it-deutsch+++++++++++++++++++++++++++++Result:+%e8%f1%ef%ee%eb%fc%e7%ee%e2%e0%ed+%ed%e8%ea%ed%e5%e9%ec+"Williamnisk";+%e7%e0%f0%e5%e3%e8%f1%f2%f0%e8%f0%ee%e2%e0%eb%e8%f1%fc;+%e2%ee%f8%eb%e8;+%ed%e5+%ed%e0%f8%eb%ee%f1%fc+%f4%ee%f0%ec%fb+%e4%eb%ff+%ee%f2%ef%f0%e0%e2%ea%e8;+%e2%ee%e7%ec%ee%e6%ed%ee,+%f0%e5%e3%e8%f1%f2%f0%e0%f6%e8%ff+%ed%e5+%f3%e4%e0%eb%e0%f1%fc+(%e2%fb%f1%eb%e0%ed+%ea%ee%e4+%e0%ea%f2%e8%e2%e0%f6%e8%e8+/+%e8%f1%ef%ee%eb%fc%e7%f3%e5%f2%f1%ff+%e4%ee%ef%ee%eb%ed%e8%f2%e5%eb%fc%ed%e0%ff+%e7%e0%f9%e8%f2%e0+/+%f1%e1%ee%e9+%e2+%f0%e0%e1%ee%f2%e5+%f4%ee%f0%f3%ec%e0+/+...);
 Error: Bad Request
    at SendStream.error (/opt/nodebb/node_modules/express/node_modules/send/index.js:239:16)
    at SendStream.pipe (/opt/nodebb/node_modules/express/node_modules/send/index.js:411:32)
    at serveStatic (/opt/nodebb/node_modules/express/node_modules/serve-static/index.js:107:12)
    at Layer.handle [as handle_request] (/opt/nodebb/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/opt/nodebb/node_modules/express/lib/router/index.js:271:13)
    at /opt/nodebb/node_modules/express/lib/router/index.js:238:9
    at Function.proto.process_params (/opt/nodebb/node_modules/express/lib/router/index.js:313:12)
    at /opt/nodebb/node_modules/express/lib/router/index.js:229:12
    at Function.match_layer (/opt/nodebb/node_modules/express/lib/router/index.js:296:3)
    at next (/opt/nodebb/node_modules/express/lib/router/index.js:190:10)
22/4 10:25 [14390] - [31merror[39m: Invalid url fragment : topic/1174/make-it-deutsch+++++++++++++++++++++++++++++Result:+%e8%f1%ef%ee%eb%fc%e7%ee%e2%e0%ed+%ed%e8%ea%ed%e5%e9%ec+"Williamnisk";+%e7%e0%f0%e5%e3%e8%f1%f2%f0%e8%f0%ee%e2%e0%eb%e8%f1%fc;+%e2%ee%f8%eb%e8;+%ed%e5+%ed%e0%f8%eb%ee%f1%fc+%f4%ee%f0%ec%fb+%e4%eb%ff+%ee%f2%ef%f0%e0%e2%ea%e8;+%e2%ee%e7%ec%ee%e6%ed%ee,+%f0%e5%e3%e8%f1%f2%f0%e0%f6%e8%ff+%ed%e5+%f3%e4%e0%eb%e0%f1%fc+(%e2%fb%f1%eb%e0%ed+%ea%ee%e4+%e0%ea%f2%e8%e2%e0%f6%e8%e8+/+%e8%f1%ef%ee%eb%fc%e7%f3%e5%f2%f1%ff+%e4%ee%ef%ee%eb%ed%e8%f2%e5%eb%fc%ed%e0%ff+%e7%e0%f9%e8%f2%e0+/+%f1%e1%ee%e9+%e2+%f0%e0%e1%ee%f2%e5+%f4%ee%f0%f3%ec%e0+/+...); URIError: URI malformed
    at decodeURIComponent (native)
    at Object.Meta.title.build (/opt/nodebb/src/meta/title.js:22:10)
    at Object.async.parallel.title (/opt/nodebb/src/middleware/middleware.js:234:16)
    at /opt/nodebb/node_modules/async/lib/async.js:583:25
    at /opt/nodebb/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/opt/nodebb/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/opt/nodebb/node_modules/async/lib/async.js:124:9)
    at _parallel (/opt/nodebb/node_modules/async/lib/async.js:582:20)
    at Object.async.parallel (/opt/nodebb/node_modules/async/lib/async.js:598:9)
22/4 11:20 [14390] - [32minfo[39m: [emailer.mailgun] Sent `notif_post` email to uid 678
22/4 11:38 [14390] - [31merror[39m: TypeError: Cannot call method 'apply' of undefined
    at Object.postObj (/opt/nodebb/node_modules/async/lib/async.js:656:23)
    at /opt/nodebb/node_modules/async/lib/async.js:583:25
    at /opt/nodebb/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/opt/nodebb/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/opt/nodebb/node_modules/async/lib/async.js:124:9)
    at _parallel (/opt/nodebb/node_modules/async/lib/async.js:582:20)
    at Object.async.parallel (/opt/nodebb/node_modules/async/lib/async.js:598:9)
    at /opt/nodebb/src/socket.io/posts.js:234:9
    at /opt/nodebb/src/posts.js:118:5
[cluster] Child Process (14390) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
22/4 11:38 [14512] - [32minfo[39m: Time: Wed Apr 22 2015 11:38:22 GMT-0500 (CDT)
22/4 11:38 [14512] - [32minfo[39m: Initializing NodeBB v0.7.0-dev
22/4 11:38 [14512] - [32minfo[39m: Enabling 'trust proxy'
```

**Comment by barisusakli** [comment]
Only `22/4 11:38 [14390] - �[31merror�[39m: TypeError: Cannot call method 'apply' of undefined` is a crash, the others are just errors that don't crash nodebb. 

It is fixed on latest master.

**Comment by lots0logs** [comment]
Thanks!
