### ISSUE TITLE
Logs show `ERR value is not an integer or out of range` every now and then

### ISSUE THREAD

**Issue by FokkeZB** [NodeBB/NodeBB#3089]
A few times per day, the logs show the following error which I have no idea how to fix:

```
22/4 15:57 [526] - error: /category/5/mobile-apps-q-a
 Error: ERR value is not an integer or out of range
    at ReplyParser.<anonymous> (/data/nettle-server/5535c16113a34aafa5fda93e/55072a856fc28a5f07748acd_qanda_1429586742172/0.6.14/node_modules/redis/index.js:305:31)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_error (/data/nettle-server/5535c16113a34aafa5fda93e/55072a856fc28a5f07748acd_qanda_1429586742172/0.6.14/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/data/nettle-server/5535c16113a34aafa5fda93e/55072a856fc28a5f07748acd_qanda_1429586742172/0.6.14/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/data/nettle-server/5535c16113a34aafa5fda93e/55072a856fc28a5f07748acd_qanda_1429586742172/0.6.14/node_modules/redis/index.js:534:27)
    at Socket.<anonymous> (/data/nettle-server/5535c16113a34aafa5fda93e/55072a856fc28a5f07748acd_qanda_1429586742172/0.6.14/node_modules/redis/index.js:91:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
```

**Comment by julianlam** [comment]
Could it possibly be related to pagination? Try scrolling down and invoking the infinite loader -- do you see the error in the log?

**Comment by barisusakli** [comment]
Repro

https://community.nodebb.org/category/2/general-discussion?page=test
