### ISSUE TITLE
Crash when requesting any RSS endpoint

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#3093]
This is happening on the latest master every time the RSS endpoints are requested:

```log
25/4 19:12 [20603] - [31merror[39m: TypeError: Cannot read property 'content' of null
    at /opt/nodebb/src/routes/feeds.js:244:35
    at /opt/nodebb/src/topics.js:285:4
    at Object.Topics.addPostData (/opt/nodebb/src/topics/posts.js:60:11)
    at /opt/nodebb/src/topics.js:325:11
    at /opt/nodebb/src/posts.js:67:5
    at fn (/opt/nodebb/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/opt/nodebb/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
TypeError: Cannot read property 'content' of null
    at /opt/nodebb/src/routes/feeds.js:244:35
    at /opt/nodebb/src/topics.js:285:4
    at Object.Topics.addPostData (/opt/nodebb/src/topics/posts.js:60:11)
    at /opt/nodebb/src/topics.js:325:11
    at /opt/nodebb/src/posts.js:67:5
    at fn (/opt/nodebb/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/opt/nodebb/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
25/4 19:12 [20603] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
25/4 19:12 [20603] - [32minfo[39m: [app] Database connection closed.
25/4 19:12 [20603] - [32minfo[39m: [app] Web server closed to connections.
25/4 19:12 [20603] - [32minfo[39m: [app] Shutdown complete.
25/4 19:12 [20615] - [32minfo[39m: Time: Sat Apr 25 2015 19:12:26 GMT-0500 (CDT)
```

**Comment by barisusakli** [comment]
Let me know if it works with above commit.

**Comment by lots0logs** [comment]
Seems to have resolved the issue. Thanks!!
