### ISSUE TITLE
"TypeError: Cannot set property 'email' of undefined" when supplying URL to non-existent uid (API)

### ISSUE THREAD

**Issue by sotarules** [NodeBB/NodeBB#3109]
On NodeBB 0.7.0, I was experimenting with the built-in read-only API, and I accidentally specified a non-existent uid.  Example:

```
http://support.pract.us/api/user/uid/28
```
I noticed that instead of a "soft error" (some feedback indicating record not found), I was getting "Bad Gateway" from NGINX.

So I checked my Forever log for NodeBB.  Here is what I found:

```
2/5 19:30 [15930] error: TypeError: Cannot set property 'email' of undefined
    at /home/bitnami/nodebb/src/controllers/accounts.js:118:26
    at /home/bitnami/nodebb/node_modules/async/lib/async.js:592:17
    at done (/home/bitnami/nodebb/node_modules/async/lib/async.js:135:19)
    at /home/bitnami/nodebb/node_modules/async/lib/async.js:32:16
    at /home/bitnami/nodebb/node_modules/async/lib/async.js:589:21
    at /home/bitnami/nodebb/src/user.js:84:4
    at fireFilterHook (/home/bitnami/nodebb/src/plugins/hooks.js:78:11)
    at Object.Plugins.fireHook (/home/bitnami/nodebb/src/plugins/hooks.js:62:5)
    at modifyUserData (/home/bitnami/nodebb/src/user.js:136:11)
    at /home/bitnami/nodebb/src/user.js:102:4
TypeError: Cannot set property 'email' of undefined
    at /home/bitnami/nodebb/src/controllers/accounts.js:118:26
    at /home/bitnami/nodebb/node_modules/async/lib/async.js:592:17
    at done (/home/bitnami/nodebb/node_modules/async/lib/async.js:135:19)
    at /home/bitnami/nodebb/node_modules/async/lib/async.js:32:16
    at /home/bitnami/nodebb/node_modules/async/lib/async.js:589:21
    at /home/bitnami/nodebb/src/user.js:84:4
    at fireFilterHook (/home/bitnami/nodebb/src/plugins/hooks.js:78:11)
    at Object.Plugins.fireHook (/home/bitnami/nodebb/src/plugins/hooks.js:62:5)
    at modifyUserData (/home/bitnami/nodebb/src/user.js:136:11)
    at /home/bitnami/nodebb/src/user.js:102:4
```

**Comment by barisusakli** [comment]
Thanks for reporting.
