### ISSUE TITLE
crash in markdown

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#3121]
Haven't found the content that causes it.

```
7/5 19:02 [29796] - [31merror[39m: TypeError: undefined is not a function
    at Array.inline (/home/nodebb/community.nodebb.org/node_modules/nodebb-plugin-markdown/node_modules/markdown-it/lib/rules_core/normalize.js:15:19)
    at Core.process (/home/nodebb/community.nodebb.org/node_modules/nodebb-plugin-markdown/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/home/nodebb/community.nodebb.org/node_modules/nodebb-plugin-markdown/node_modules/markdown-it/lib/index.js:490:13)
    at MarkdownIt.render (/home/nodebb/community.nodebb.org/node_modules/nodebb-plugin-markdown/node_modules/markdown-it/lib/index.js:510:36)
    at Object.Markdown.parsePost [as method] (/home/nodebb/community.nodebb.org/node_modules/nodebb-plugin-markdown/index.js:92:37)
    at /home/nodebb/community.nodebb.org/src/plugins/hooks.js:89:12
    at /home/nodebb/community.nodebb.org/node_modules/async/lib/async.js:272:13
    at iterate (/home/nodebb/community.nodebb.org/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/home/nodebb/community.nodebb.org/node_modules/async/lib/async.js:165:9)
    at Object.async.reduce (/home/nodebb/community.nodebb.org/node_modules/async/lib/async.js:271:15)
```

**Comment by barisusakli** [comment]
The first 30 chars of the post that causes the crash  is `Thanks to [@Mr_Waffle](https:/`
