### ISSUE TITLE
Cannot find module 'colors'

### ISSUE THREAD

**Issue by tedr56** [NodeBB/NodeBB#3190]
I tried to update today from 20983c4 to f168566
and I got this error. 

The next capture is from ```./nodebb upgrade```
After ```npm install``` , all went well. 

```
src/views/admin/manage/groups.tpl      |  57 +-
 .../partials/categories/privileges.tpl | 123 +-
 src/views/emails/digest.tpl            |   2 +-
 src/views/emails/digest_plaintext.tpl  |   2 +-
 src/views/emails/notif_chat.tpl        |   2 +-
 .../emails/notif_chat_plaintext.tpl    |   2 +-
 tests/groups.js                        |   4 +-
 225 files changed, 2663 insertions(+), 2957 deletions(-)
 delete mode 100644 public/less/admin/manage/groups.less
 create mode 100644 src/groups/create.js
 create mode 100644 src/groups/delete.js
 create mode 100644 src/groups/membership.js
 create mode 100644 src/groups/ownership.js
 create mode 100644 src/groups/search.js
 create mode 100644 src/groups/update.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/tchernobob/NodeBB/nodebb:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

module.js:340
    throw err;
          ^
Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/tchernobob/NodeBB/nodebb:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)```

**Comment by julianlam** [comment]
Odd, what hash are you on? In my `package.json`, the `colors` module is specified as a dependency, so it should have been installed when you ran `npm install`.

**Comment by tedr56** [comment]
I'm now on f168566
```./nodebb upgrade``` usually works but I got this error and had to enter ```npm install``` to bypass it.

**Comment by julianlam** [comment]
Oh I see. Then yes, this is alright. I started using the `colors` module, but *only in the NodeBB executable*, which jumpstarts `npm install`, but it can't do that if the script itself relies on the `colors` module :laughing:

**Comment by tedr56** [comment]
Hmm, you're the expert :wink:
