### ISSUE TITLE
Server crash entering Acp 

### ISSUE THREAD

**Issue by tedr56** [NodeBB/NodeBB#3191]
Sorry for the title, I have not better title except this

```
28/5 17:31 [9304] - warn: [plugins.reload] Library not found for plugin: nodebb-theme-persona
28/5 17:32 [9304] - info: NodeBB Ready
28/5 17:32 [9304] - info: Enabling 'trust proxy'
28/5 17:32 [9304] - info: NodeBB is now listening on: 0.0.0.0:4567
y28/5 17:32 [9304] - error: TypeError: undefined is not a function
    at Command.callback (/home/tchernobob/NodeBB/src/groups.js:86:12)
    at RedisClient.return_error (/home/tchernobob/NodeBB/node_modules/redis/index.js:558:25)
    at HiredisReplyParser.<anonymous> (/home/tchernobob/NodeBB/node_modules/redis/index.js:303:18)
    at HiredisReplyParser.emit (events.js:95:17)
    at HiredisReplyParser.execute (/home/tchernobob/NodeBB/node_modules/redis/lib/parser/hiredis.js:41:18)
    at RedisClient.on_data (/home/tchernobob/NodeBB/node_modules/redis/index.js:534:27)
    at Socket.<anonymous> (/home/tchernobob/NodeBB/node_modules/redis/index.js:91:14)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
[cluster] Child Process (9304) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
```

I can't see if it's plugin related.

**Comment by julianlam** [comment]
Hm, it definitely is. Can you please check if mentions plugin is >= 0.11.3?

**Comment by tedr56** [comment]
mentions is on 0.11.2 and I can upgrade to 0.11.4

**Comment by julianlam** [comment]
That'd do it :smile: I'll update the required version in this `package.json`.

**Comment by julianlam** [comment]
eddabe5a37fe55745621a60b0a13728937b1f4d8

**Comment by tedr56** [comment]
Nice catch
