### ISSUE TITLE
Unable to start on v0.7.x

### ISSUE THREAD

**Issue by darrenxyli** [NodeBB/NodeBB#3208]
2/6 00:38 [8779] - info: Time: Tue Jun 02 2015 00:38:32 GMT+0000 (UTC)
2/6 00:38 [8779] - info: Initializing NodeBB v0.7.0
2/6 00:38 [8779] - error: TypeError: object is not a function
    at /root/NodeBB/src/meta/configs.js:24:4
    at /root/NodeBB/src/meta/configs.js:32:4
    at try_callback (/root/NodeBB/node_modules/redis/index.js:573:9)
    at RedisClient.return_reply (/root/NodeBB/node_modules/redis/index.js:661:13)
    at ReplyParser.<anonymous> (/root/NodeBB/node_modules/redis/index.js:309:14)
    at ReplyParser.emit (events.js:95:17)
    at ReplyParser.send_reply (/root/NodeBB/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/root/NodeBB/node_modules/redis/lib/parser/javascript.js:211:22)
    at RedisClient.on_data (/root/NodeBB/node_modules/redis/index.js:534:27)
    at Socket.<anonymous> (/root/NodeBB/node_modules/redis/index.js:91:14)
[cluster] Child Process (8779) has exited (code: 1, signal: null)
[cluster] Spinning up another process...

Redis server v=3.0.1
Mongodb version v3.0.3

And I am using secondary database to store. So could you help? Seems it's redis issue?

**Comment by darrenxyli** [comment]
PS: If I run it with only one database, redis. Everything is good. =] So seems it's not issue with redis, but something else. Thank you

**Comment by barisusakli** [comment]
Can you post your config.json? Are you using the `secondary_database` block in config.json?

**Comment by barisusakli** [comment]
Keep in mind secondary databases is not tested and shouldn't be used on production.
