### ISSUE TITLE
Notification not working on master

### ISSUE THREAD

**Issue by phoenixlzx** [NodeBB/NodeBB#3298]
I got the error in console output.

```
Missing error handler on `socket`.
TypeError: undefined is not a function
    at SocketPlugins.mentions.listGroups (~/NodeBB/node_modules/nodebb-plugin-mentions/library.js:202:9)
    at callMethod (~/NodeBB/src/socket.io/index.js:204:2)
    at onMessage (~/NodeBB/src/socket.io/index.js:149:3)
    at Socket.<anonymous> (~/NodeBB/src/socket.io/index.js:61:3)
    at Socket.emit (events.js:107:17)
    at Socket.onevent (~/NodeBB/node_modules/socketio-wildcard/index.js:17:17)
    at Socket.onpacket (~/NodeBB/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (~/NodeBB/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (~/NodeBB/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (~/NodeBB/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
```

Notifications didn't work, but seems not the error above. Notifications just hang up and no errors displayed in console.

I'm using the master branch.

**Comment by phoenixlzx** [comment]
OK I got the error - on opening admin page.

**Comment by phoenixlzx** [comment]
It seems to be the upgrade not clean. I made a clean install and recover from a backup and now it works.

Closing #3298
