### ISSUE TITLE
Can't install with mongodb.

### ISSUE THREAD

**Issue by Juxtapo** [NodeBB/NodeBB#3304]
Hey, I installed NodeBB no problem with redis, but I'd like to use MongoDB for easier integration with a webapp I'm creating with the MEAN stack, but I'm not having much luck. (Ubuntu 14.04 vps)

I install the latest versions of nodejs, mongodb, build-essential, and imagemagick, then setup databases following [this explanation](https://community.nodebb.org/topic/1450/mongodb-install/2), and then ./nodebb setup or npm start, enter all of the info, but get this error:

```
mongodb@2.0.35 node_modules/mongodb
├── readable-stream@1.0.31 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── mongodb-core@1.2.2 (bson@0.4.7, kerberos@0.0.12)
7/7 01:48 [6255] - info: [database] Checking database indices.
Populating database with default configs, if not already set...
/opt/nodebb/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
Error: Cannot find module './build/Release/magic'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/nodebb/node_modules/mmmagic/index.js:3:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

I assume it has something to do with imagemagick, but installation went flawlessly when I was using redis so I really have no idea.

I've tried old versions of mongo/nodejs but nothing has worked so any help would be appreciated!

Thanks

**Comment by julianlam** [comment]
What happens when you try `npm install mmmagic`?

**Comment by Juxtapo** [comment]
Now I get:

```

Error: Cannot find module '../build/Release/lwip_image'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /opt/nodebb/node_modules/lwip/lib/Image.js:3:22
    at Object.<anonymous> (/opt/nodebb/node_modules/lwip/lib/Image.js:15:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

I've gotten this error before as well

Thanks

**Comment by julianlam** [comment]
Sounds like lwip did not compile correctly. `npm rebuild`

**Comment by Juxtapo** [comment]
I actually just did npm install lwip and it seems to be working! Thanks
