### ISSUE TITLE
Anchor links broken.

### ISSUE THREAD

**Issue by yariplus** [NodeBB/NodeBB#3338]
https://github.com/NodeBB/NodeBB/commit/d712dcdce1a64e7f97e3fa15bbfb2429643b14f6

This seems to break anchor links for me all over. Specifically, bs tabs and carousels. e.g. any link like

`<a href="#about">About</a>`

will reload the page rather then opening my About tab.

**Comment by julianlam** [comment]
Thanks, this is a blocker for 0.7.1

**Comment by julianlam** [comment]
@yariplus I cannot reproduce this. I placed the following html into an widget in the global header widget area (in Lavender, you might have to try the sidebar on Persona), and the tabs work correctly:

``` html
<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">...</div>
    <div role="tabpanel" class="tab-pane" id="profile">...</div>
    <div role="tabpanel" class="tab-pane" id="messages">...</div>
    <div role="tabpanel" class="tab-pane" id="settings">...</div>
  </div>

</div>
```

**Comment by yariplus** [comment]
:confused:

Hmm, did a fresh install, tabs still reloading the page.

Also, puts weird link in location bar, e.g.:
`http://52.5.56.117:4567/#profile#profile`

**Comment by julianlam** [comment]
Thanks @yariplus  -- `git rev-parse HEAD`?

**Comment by yariplus** [comment]
1c973b7bf36ef2448bfbf4756500b1a7e1a2cf54

**Comment by julianlam** [comment]
Ooh, interesting... it breaks only on Persona...

**Comment by yariplus** [comment]
Breaks on vanilla for me too, could it have something to do with this:

```
20/7 16:02 [9902] - warn: NodeBB Setup Aborted.
 Error: [[error:not-enough-tags, undefined]]
    at checkTagsLength (/home/ubuntu/nodebb07x/src/topics/create.js:298:20)
    at async.waterfall.data (/home/ubuntu/nodebb07x/src/topics/create.js:100:5)
    at fn (/home/ubuntu/nodebb07x/node_modules/async/lib/async.js:638:34)
    at Object._onImmediate (/home/ubuntu/nodebb07x/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

:smile:

**Comment by barisusakli** [comment]
@yariplus https://github.com/NodeBB/NodeBB/commit/e171ba59ac2d7c89c66cc692fefa35d8648f9486 should fix that error.

**Comment by yariplus** [comment]
Dang, didn't help.

Exact steps:
```
git clone https://github.com/NodeBB/NodeBB.git nodebb07x
cd nodebb07x
npm i
./nodebb setup // Using all defaults
./nodebb start

Log into admin page and add html widget.
Browse to home page and click tab link.

Reloads page
```

**Comment by julianlam** [comment]
Let's hope this is the last time I have to modify `ajaxify.js` :smile:

**Comment by yariplus** [comment]
:+1:
