### ISSUE TITLE
Frequent Crashes, logs show error from node_redis

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#3425]
I havent been able to determine exactly what action triggers the crash. Let me know if you have any ideas!
```log
7/8 21:54 [5715] - info: NodeBB is now listening on: 0.0.0.0:4567
node_redis: no callback to send error: ERR value is not an integer or out of range
7/8 21:54 [5715] - error: Error: ERR value is not an integer or out of range
    at ReplyParser.<anonymous> (/opt/nodebb/node_modules/redis/index.js:305:31)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_error (/opt/nodebb/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/opt/nodebb/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/opt/nodebb/node_modules/redis/index.js:534:27)
    at Socket.<anonymous> (/opt/nodebb/node_modules/redis/index.js:91:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
7/8 21:54 [5727] - info: Time: Fri Aug 07 2015 21:54:30 GMT-0500 (CDT)
7/8 21:54 [5727] - info: Initializing NodeBB v0.7.3-dev

7/8 21:54 [5727] - warn: [plugins/nodebb-theme-lavender] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
7/8 21:54 [5727] - warn: [plugins/nodebb-theme-lavender] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset -p nodebb-theme-lavender.


7/8 21:54 [5727] - warn: [plugins/nodebb-theme-antergos] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
7/8 21:54 [5727] - warn: [plugins/nodebb-theme-antergos] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset -p nodebb-theme-antergos.

7/8 21:54 [5727] - info: [plugins/spam-be-gone] Settings loaded
7/8 21:54 [5727] - info: NodeBB Ready
7/8 21:54 [5727] - info: Enabling 'trust proxy'
7/8 21:54 [5727] - info: NodeBB is now listening on: 0.0.0.0:4567
node_redis: no callback to send error: ERR value is not an integer or out of range
7/8 21:54 [5727] - error: Error: ERR value is not an integer or out of range
    at ReplyParser.<anonymous> (/opt/nodebb/node_modules/redis/index.js:305:31)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_error (/opt/nodebb/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/opt/nodebb/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/opt/nodebb/node_modules/redis/index.js:534:27)
    at Socket.<anonymous> (/opt/nodebb/node_modules/redis/index.js:91:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
7/8 21:54 [5739] - info: Time: Fri Aug 07 2015 21:54:39 GMT-0500 (CDT)
7/8 21:54 [5739] - info: Initializing NodeBB v0.7.3-dev

7/8 21:54 [5739] - warn: [plugins/nodebb-theme-lavender] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
7/8 21:54 [5739] - warn: [plugins/nodebb-theme-lavender] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset -p nodebb-theme-lavender.


7/8 21:54 [5739] - warn: [plugins/nodebb-theme-antergos] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
7/8 21:54 [5739] - warn: [plugins/nodebb-theme-antergos] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset -p nodebb-theme-antergos.

7/8 21:54 [5739] - info: [plugins/spam-be-gone] Settings loaded
7/8 21:54 [5739] - info: NodeBB Ready
7/8 21:54 [5739] - info: Enabling 'trust proxy'
7/8 21:54 [5739] - info: NodeBB is now listening on: 0.0.0.0:4567
node_redis: no callback to send error: ERR value is not an integer or out of range
7/8 21:55 [5739] - error: Error: ERR value is not an integer or out of range
    at ReplyParser.<anonymous> (/opt/nodebb/node_modules/redis/index.js:305:31)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_error (/opt/nodebb/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/opt/nodebb/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/opt/nodebb/node_modules/redis/index.js:534:27)
    at Socket.<anonymous> (/opt/nodebb/node_modules/redis/index.js:91:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
7/8 21:55 [5754] - info: Time: Fri Aug 07 2015 21:55:12 GMT-0500 (CDT)
7/8 21:55 [5754] - info: Initializing NodeBB v0.7.3-dev

7/8 21:55 [5754] - warn: [plugins/nodebb-theme-lavender] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
7/8 21:55 [5754] - warn: [plugins/nodebb-theme-lavender] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset -p nodebb-theme-lavender.


7/8 21:55 [5754] - warn: [plugins/nodebb-theme-antergos] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
7/8 21:55 [5754] - warn: [plugins/nodebb-theme-antergos] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset -p nodebb-theme-antergos.

7/8 21:55 [5754] - info: [plugins/spam-be-gone] Settings loaded
7/8 21:55 [5754] - info: NodeBB Ready
7/8 21:55 [5754] - info: Enabling 'trust proxy'
7/8 21:55 [5754] - info: NodeBB is now listening on: 0.0.0.0:4567
node_redis: no callback to send error: ERR value is not an integer or out of range
7/8 21:57 [5754] - error: Error: ERR value is not an integer or out of range
    at ReplyParser.<anonymous> (/opt/nodebb/node_modules/redis/index.js:305:31)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_error (/opt/nodebb/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/opt/nodebb/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/opt/nodebb/node_modules/redis/index.js:534:27)
    at Socket.<anonymous> (/opt/nodebb/node_modules/redis/index.js:91:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
7/8 21:57 [5766] - info: Time: Fri Aug 07 2015 21:57:29 GMT-0500 (CDT)
7/8 21:57 [5766] - info: Initializing NodeBB v0.7.3-dev

7/8 21:57 [5766] - warn: [plugins/nodebb-theme-lavender] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
7/8 21:57 [5766] - warn: [plugins/nodebb-theme-lavender] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset -p nodebb-theme-lavender.


7/8 21:57 [5766] - warn: [plugins/nodebb-theme-antergos] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
7/8 21:57 [5766] - warn: [plugins/nodebb-theme-antergos] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset -p nodebb-theme-antergos.

7/8 21:57 [5766] - info: [plugins/spam-be-gone] Settings loaded
7/8 21:57 [5766] - info: NodeBB Ready
7/8 21:57 [5766] - info: Enabling 'trust proxy'
7/8 21:57 [5766] - info: NodeBB is now listening on: 0.0.0.0:4567
```

**Comment by barisusakli** [comment]
Usually happens when an invalid value is passed to redis. Unfortunately it's difficult to find where since the stack trace is pretty much useless.

**Comment by lots0logs** [comment]
@barisusakli Hmmm.. Can you guys reproduce this issue on the latest master or is it something in my fork of lavender causing it? :worried:

**Comment by barisusakli** [comment]
I can't reproduce it on my dev environment on latest master. 
You can try disabling all plugins and test again to rule out any plugins.

**Comment by barisusakli** [comment]
If you can get it to crash on every cold load, you can add some console.logs to determine which socket call or api call is causing it.

**Comment by lots0logs** [comment]
@barisusakli I took your advice about the plugins and I think I found the culprit (as its no longer crashing): /julianlam/nodebb-plugin-mentions

**Comment by barisusakli** [comment]
Do you remember which version of the plugin was installed and causing the crash?

**Comment by barisusakli** [comment]
Nevermind 0.11.8 crashes on latest master 0.11.9 works fine.
