### ISSUE TITLE
topic thumbnail upload error 

### ISSUE THREAD

**Issue by KanwalPrakashSingh** [NodeBB/NodeBB#3426]
Error: Unknown arguments configuration,100,100
    at Error (<anonymous>)
    at Object.cover (/root/NodeBB-0.7.1/node_modules/lwip/node_modules/decree/dist/cjs/decree.js:80:27)
    at Batch.cover (/root/NodeBB-0.7.1/node_modules/lwip/lib/BatchPrototypeInit.js:99:16)
    at /root/NodeBB-0.7.1/src/image.js:22:6
    at /root/NodeBB-0.7.1/node_modules/lwip/lib/obtain.js:32:25
Error: Unknown arguments configuration,100,100
    at Error (<anonymous>)
    at Object.cover (/root/NodeBB-0.7.1/node_modules/lwip/node_modules/decree/dist/cjs/decree.js:80:27)
    at Batch.cover (/root/NodeBB-0.7.1/node_modules/lwip/lib/BatchPrototypeInit.js:99:16)
    at /root/NodeBB-0.7.1/src/image.js:22:6
    at /root/NodeBB-0.7.1/node_modules/lwip/lib/obtain.js:32:25

I dont understand why configuration is unknown , is it because you guys have changed the name of this variable ?

**Comment by barisusakli** [comment]
Posting OS info, nodejs and nodebb version might help.
