### ISSUE TITLE
events.js error

### ISSUE THREAD

**Issue by APXEOLOG** [NodeBB/NodeBB#3443]
My log is full of such errors:
```
Missing error handler on `socket`.
Error: Callback was already called.
    at /root/nodebb/node_modules/async/lib/async.js:30:31
    at /root/nodebb/node_modules/async/lib/async.js:248:21
    at Socket.<anonymous> (/root/nodebb/src/socket.io/rooms.js:54:4)
    at Socket.onack (/root/nodebb/node_modules/socket.io/lib/socket.js:368:9)
    at Socket.onpacket (/root/nodebb/node_modules/socket.io/lib/socket.js:298:12)
    at Client.ondecoded (/root/nodebb/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/root/nodebb/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/root/nodebb/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/root/nodebb/node_modules/socket.io/lib/client.js:175:18)
    at Socket.EventEmitter.emit (events.js:95:17)
```

I think this is because of async.parallel usage. I'm not an expert in node.js / async but i think solutions is to change async.parallel to async.waterfall at `function addUserData() (line 75)`

**Comment by barisusakli** [comment]
What git hash are you on?

**Comment by APXEOLOG** [comment]
0.7.2 release (https://github.com/NodeBB/NodeBB/releases/tag/v0.7.2)

**Comment by barisusakli** [comment]
Looks like some fixes were never ported back to 0.7.2
https://github.com/NodeBB/NodeBB/commit/eac92b00c66ba7e86528d8ba82b7d9de5cbb1f5e#diff-9be9fc822d6d8a51bf817b082d3df0ca

@julianlam

**Comment by APXEOLOG** [comment]
So it will be fixed in next release? Nice!

**Comment by julianlam** [comment]
Yeah, we'll launch tomorrow and get these fixes in. (Although I said that last week, but this time, for real.)

**Comment by barisusakli** [comment]
Give it a shot on 0.7.3
