### ISSUE TITLE
socket is undefined on rooms.broadcast()

### ISSUE THREAD

**Issue by TheBronx** [NodeBB/NodeBB#3471]
Missing error handler on `socket`.
    TypeError: Cannot call method 'emit' of undefined
    at /home/vagrant/NodeBB/src/socket.io/rooms.js:52:35
    at /home/vagrant/NodeBB/node_modules/async/lib/async.js:246:17
    at /home/vagrant/NodeBB/node_modules/async/lib/async.js:122:13
    at _each (/home/vagrant/NodeBB/node_modules/async/lib/async.js:46:13)
    at async.each (/home/vagrant/NodeBB/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/home/vagrant/NodeBB/node_modules/async/lib/async.js:245:13)
    at Object.map (/home/vagrant/NodeBB/node_modules/async/lib/async.js:216:23)
    at Object.rooms.broadcast (/home/vagrant/NodeBB/src/socket.io/rooms.js:42:8)
    at SocketModules.chats.sync (/home/vagrant/NodeBB/src/socket.io/modules.js:105:8)
    at callMethod (/home/vagrant/NodeBB/src/socket.io/index.js:204:2)

**v0.7.2**

## Steps to reproduce:
 - Start two instances of NodeBB (`"port": ["4567", "4568"]`).
 - Open in browser: `127.0.0.1:4567`
 - Open in another tab: `127.0.0.1:4568`
 - See error in console :(

This error causes lots of troubles. The user on instance `4568` just can't use the forum correctly. The editor doesn't show up (thus they can't reply, quote, start new thread, etc), notifications do not load, chats do not load, and so on.

Any ideas about what's going wrong?
Thanks :D

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/eac92b00c66ba7e86528d8ba82b7d9de5cbb1f5e#diff-9be9fc822d6d8a51bf817b082d3df0ca this needs to be backported to 0.7.2 @julianlam 

Or you can upgrade to 0.7.3.

**Comment by julianlam** [comment]
Can only backport to a separate branch, and both v0.7.2 and v0.7.3 are on the same branch.

@TheBronx upgrade to v0.7.3 as suggested by @barisusakli, or possibly run `git cherry-pick eac92b00c66ba7e86528d8ba82b7d9de5cbb1f5e` to pull the fix to your code only.
