### ISSUE TITLE
SSO plugins are no longer working in 0.8.0

### ISSUE THREAD

**Issue by milipili** [NodeBB/NodeBB#3523]
If you lost your session, you can no longer login :

```
30/8 06:16 [3895] - error: /community/auth/google/callback
 InternalOAuthError: failed to fetch user profile (status: 403 data: {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration.",
    "extendedHelp": "https://console.developers.google.com"
   }
  ],
  "code": 403,
  "message": "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration."
 }
}
)
```

Or via github:
```
30/8 06:57 [3895] - error: /community/auth/github/callback
 TypeError: Cannot set property 'user' of undefined
    at ***/nodebb/node_modules/nodebb-plugin-sso-github/node_modules/passport-github/node_modules/passport-oauth/node_modules/passport/lib/passport/http/request.js:45:35
    at pass (***/nodebb/node_modules/passport/lib/authenticator.js:267:43)
    at serialized (***/nodebb/node_modules/passport/lib/authenticator.js:276:7)
    at passport.deserializeUser.done.uid (***/nodebb/src/routes/authentication.js:77:3)
    at pass (***/nodebb/node_modules/passport/lib/authenticator.js:284:9)
    at Authenticator.serializeUser (***/nodebb/node_modules/passport/lib/authenticator.js:289:5)
    at IncomingMessage.req.login.req.logIn (***/nodebb/node_modules/nodebb-plugin-sso-github/node_modules/passport-github/node_modules/passport-oauth/node_modules/passport/lib/passport/http/request.js:43:29)
    at Strategy.strategy.success (***/nodebb/node_modules/passport/lib/middleware/authenticate.js:228:13)
    at verified (***/nodebb/node_modules/nodebb-plugin-sso-github/node_modules/passport-github/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:133:18)
    at ***/nodebb/node_modules/nodebb-plugin-sso-github/library.js:33:7
```

**Comment by julianlam** [comment]
The latest Google login plugin should be fine. I wasn't aware GitHub was broken, so I'll have to take a look at that today.

**Comment by julianlam** [comment]
GitHub plugin is fixed now, thanks.
