### ISSUE TITLE
NodeBB errors (502-504)

### ISSUE THREAD

**Issue by atomoc** [NodeBB/NodeBB#3548]
```
 invalid csrf token
3/9 08:31 [21501] - error: /forum/apple-touch-icon
 Error: ENOENT, stat '/home/nodebb/public/forum/uploads/system/site-logo.png'
Error: misconfigured csrf
    at getsecret (/home/nodebb/node_modules/csurf/index.js:195:11)
    at Object.csrf [as applyCSRF] (/home/nodebb/node_modules/csurf/index.js:60:18)
    at Object.middleware.buildHeader (/home/nodebb/src/middleware/middleware.js:175:13)
    at /home/nodebb/src/routes/index.js:222:15
    at Layer.handle_error (/home/nodebb/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/nodebb/node_modules/express/lib/router/index.js:310:13)
    at /home/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/home/nodebb/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/home/nodebb/node_modules/express/lib/router/layer.js:67:12)
3/9 09:32 [21501] - error: /forum/apple-touch-icon
 Error: ENOENT, stat '/home/nodebb/public/forum/uploads/system/site-logo.png'
Error: misconfigured csrf
    at getsecret (/home/nodebb/node_modules/csurf/index.js:195:11)
    at Object.csrf [as applyCSRF] (/home/nodebb/node_modules/csurf/index.js:60:18)
    at Object.middleware.buildHeader (/home/nodebb/src/middleware/middleware.js:175:13)
    at /home/nodebb/src/routes/index.js:222:15
    at Layer.handle_error (/home/nodebb/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/nodebb/node_modules/express/lib/router/index.js:310:13)
    at /home/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/home/nodebb/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/home/nodebb/node_modules/express/lib/router/layer.js:67:12)
3/9 10:13 [21501] - error: /forum/apple-touch-icon
 Error: ENOENT, stat '/home/nodebb/public/forum/uploads/system/site-logo.png'
Error: misconfigured csrf
    at getsecret (/home/nodebb/node_modules/csurf/index.js:195:11)
    at Object.csrf [as applyCSRF] (/home/nodebb/node_modules/csurf/index.js:60:18)
    at Object.middleware.buildHeader (/home/nodebb/src/middleware/middleware.js:175:13)
    at /home/nodebb/src/routes/index.js:222:15
    at Layer.handle_error (/home/nodebb/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/nodebb/node_modules/express/lib/router/index.js:310:13)
    at /home/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/home/nodebb/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/home/nodebb/node_modules/express/lib/router/layer.js:67:12)
3/9 10:29 [21501] - error: /forum/apple-touch-icon
 Error: ENOENT, stat '/home/nodebb/public/forum/uploads/system/site-logo.png'
Error: misconfigured csrf
    at getsecret (/home/nodebb/node_modules/csurf/index.js:195:11)
    at Object.csrf [as applyCSRF] (/home/nodebb/node_modules/csurf/index.js:60:18)
    at Object.middleware.buildHeader (/home/nodebb/src/middleware/middleware.js:175:13)
    at /home/nodebb/src/routes/index.js:222:15
    at Layer.handle_error (/home/nodebb/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/nodebb/node_modules/express/lib/router/index.js:310:13)
    at /home/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/home/nodebb/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/home/nodebb/node_modules/express/lib/router/layer.js:67:12)
```
NodeBB unavailable!

**Comment by atomoc** [comment]
Every day NodeBB falls. With what it can be connected?!

**Comment by atomoc** [comment]
Please give at least advice

**Comment by atomoc** [comment]
I ran ./nodebb setup, but this is unlikely to help

**Comment by atomoc** [comment]
Fall began after the transition from version 7 to 8

**Comment by julianlam** [comment]
Not sure why this would fail, as we haven't changed CSRF handling for many versions.

Paste your `config.json` here please.

**Comment by atomoc** [comment]
```
{
    "url": "http://мойсайт.рф/forum",
    "secret": "ec1236d8-066a-433c-22cf-11026291e491",
    "database": "redis",
    "redis": {
        "host": "127.0.0.1",
        "port": "6379",
        "password": "parampurum",
        "database": "0"
    }
}
```

**Comment by julianlam** [comment]
Googling reveals this error may occur if your session store is down. Ensure redis is running with no errors.

**Comment by atomoc** [comment]
No errors, only:
```
...
31123:C 12 Sep 17:20:03.492 * DB saved on disk
31123:C 12 Sep 17:20:03.493 * RDB: 0 MB of memory used by copy-on-write
2655:M 12 Sep 17:20:03.591 * Background saving terminated with success
2655:M 12 Sep 17:51:46.581 * 1 changes in 900 seconds. Saving...
2655:M 12 Sep 17:51:46.582 * Background saving started by pid 31190
31190:C 12 Sep 17:51:46.976 * DB saved on disk
31190:C 12 Sep 17:51:46.977 * RDB: 0 MB of memory used by copy-on-write
2655:M 12 Sep 17:51:46.982 * Background saving terminated with success
2655:M 12 Sep 18:00:47.316 * 10 changes in 300 seconds. Saving...
2655:M 12 Sep 18:00:47.317 * Background saving started by pid 31215
...
```
