### ISSUE TITLE
Stops working threadtools

### ISSUE THREAD

**Issue by XenTerSeO** [NodeBB/NodeBB#3630]
Does not work the closing, deleting, pinned.

Error:

Missing error handler on `socket`.
TypeError: Cannot read property 'lock' of undefined
    at Object.SocketTopics.doTopicAction (/var/www/src/socket.io/topics.js:241:25)
    at SocketTopics.lock (/var/www/src/socket.io/topics.js:216:15)
    at callMethod (/var/www/src/socket.io/index.js:204:2)
    at onMessage (/var/www/src/socket.io/index.js:149:3)
    at Socket.<anonymous> (/var/www/src/socket.io/index.js:61:3)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.onevent (/var/www/node_modules/socketio-wildcard/index.js:17:17)
    at Socket.onpacket (/var/www/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/var/www/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/var/www/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)

**Comment by barisusakli** [comment]
Works for me in latest what is your commit hash?

**Comment by XenTerSeO** [comment]
8403b010a55929abf72d8458eda762dbd27e971d

**Comment by XenTerSeO** [comment]
@barisusakli 
+ I decided to download a clean nodeb.
+ on the new database.
= error:

No categories found, populating instance with default categories
17/9 18:48 [13007] - warn: NodeBB Setup Aborted.
 Error: [[error:invalid-data]]
    at Object.Groups.join (/var/www/NodeBB/src/groups/membership.js:48:20)
    at /var/www/NodeBB/src/privileges/categories.js:305:11
    at /var/www/NodeBB/node_modules/async/lib/async.js:187:20
    at /var/www/NodeBB/node_modules/async/lib/async.js:239:13
    at _arrayEach (/var/www/NodeBB/node_modules/async/lib/async.js:91:13)
    at _each (/var/www/NodeBB/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/var/www/NodeBB/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/var/www/NodeBB/node_modules/async/lib/async.js:215:22)
    at privileges.categories.give (/var/www/NodeBB/src/privileges/categories.js:304:9)
    at /var/www/NodeBB/node_modules/async/lib/async.js:731:23

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/31ddb8a0e03e1af79b72e0089bce8c6d819da827

**Comment by barisusakli** [comment]
Let me know if its resolved

**Comment by XenTerSeO** [comment]
This problem is solved, but there was another:

17/9 19:08 [13274] - warn: NodeBB Setup Aborted.
 Error: [[error:no-category]]
    at async.waterfall.data (/var/www/NodeBB/src/topics/create.js:111:18)
    at fn (/var/www/NodeBB/node_modules/async/lib/async.js:717:34)
    at /var/www/NodeBB/node_modules/async/lib/async.js:1170:16
    at /var/www/NodeBB/node_modules/async/lib/async.js:172:37
    at /var/www/NodeBB/node_modules/async/lib/async.js:677:43
    at /var/www/NodeBB/node_modules/async/lib/async.js:173:37
    at /var/www/NodeBB/node_modules/async/lib/async.js:1166:30
    at /var/www/NodeBB/src/database/redis/sorted.js:193:4
    at try_callback (/var/www/NodeBB/node_modules/redis/index.js:573:9)
    at RedisClient.return_reply (/var/www/NodeBB/node_modules/redis/index.js:661:13)

**Comment by XenTerSeO** [comment]
@barisusakli I installed a new database.
With the installation of the problems no longer exist.

But problems remain Topic Tools.
