### ISSUE TITLE
nodebb upgrade

### ISSUE THREAD

**Issue by denis631** [NodeBB/NodeBB#3641]
I have a problem by upgrading the nodebb. I've decided to upgrade, cause I can not install it on my mac... 
When I try ``` npm install ``` I get the following message:
```
$ npm install
-
> heapdump@0.3.7 install /path/to/heapdump
> node-gyp rebuild

module.js:338
    throw err;
    ^

Error: Cannot find module '../package'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:78:17)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.0
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/path/to/log/npm-debug.log
```

When I upgrade it, I get the following message:
```
$ ./nodebb upgrade
1. Bringing base dependencies up to date... 
Error: Command failed: /usr/bin/env npm i --production
module.js:338
    throw err;
    ^

Error: Cannot find module '../package'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:78:17)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--production"
npm ERR! node v4.1.0
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/****/npm-debug.log
```

**Comment by HorusGoul** [comment]
The problem is the node version, v4.1.0 isn't compatible with nodebb yet. There is an issue about that https://github.com/NodeBB/NodeBB/issues/3582
