### ISSUE TITLE
NodeBB 0.8.2 + plugin-sso-github: error on post-authorization redirect

### ISSUE THREAD

**Issue by yyx990803** [NodeBB/NodeBB#3645]
Error:

```
TypeError: Cannot read property '0' of undefined
    at Strategy._verify (/home/evan/nodebb/node_modules/nodebb-plugin-sso-github/library.js:29:63)
    at /home/evan/nodebb/node_modules/nodebb-plugin-sso-github/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:195:22
    at /home/evan/nodebb/node_modules/nodebb-plugin-sso-github/node_modules/passport-github/lib/strategy.js:109:5
    at passBackControl (/home/evan/nodebb/node_modules/nodebb-plugin-sso-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:125:9)
    at IncomingMessage.<anonymous> (/home/evan/nodebb/node_modules/nodebb-plugin-sso-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:142:7)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickDomainCallback (node.js:459:13)
```

The line in question: https://github.com/julianlam/nodebb-plugin-sso-github/blob/master/library.js#L29

Looks like the `profile` object doesn't have the `emails` property.

**Comment by julianlam** [comment]
Do you have a publicly viewable email in GitHub? Not sure if that's
related.

**Comment by yyx990803** [comment]
Yeah, the account I tested with has no public email. Adding a public email fixes the issue - although the plugin should probably handle this edge case?

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-sso-github/pull/2
