### ISSUE TITLE
NodeBB 0.8.2 socket.io problem

### ISSUE THREAD

**Issue by henrikekblad** [NodeBB/NodeBB#3648]
Getting this after cleaning out and reinstalling npm packages.

socket.io-redis@0.1.4 node_modules/socket.io-redis
├── uid2@0.0.3
├── debug@0.7.4
├── redis@0.10.1
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
└── msgpack-js@0.3.0 (bops@0.0.7)
mysensors@stage:~/mysensors-forum/NodeBB$ 

```
22/9 09:40 [3136] - info: NodeBB is now listening on: 0.0.0.0:4567
22/9 09:40 [3136] - error: TypeError: Object socket.io#YFiYNp has no method 'split'
    at Redis.onmessage (/usr/mysensors/mysensors-forum/NodeBB/node_modules/socket.io-redis/index.js:92:26)
    at RedisClient.emit (events.js:106:17)
    at RedisClient.return_reply (/usr/mysensors/mysensors-forum/NodeBB/node_modules/redis/index.js:624:22)
    at RedisClient.<anonymous> (/usr/mysensors/mysensors-forum/NodeBB/node_modules/redis/index.js:284:18)
    at process._tickDomainCallback (node.js:486:13)
TypeError: Object socket.io#YFiYNp has no method 'split'
    at Redis.onmessage (/usr/mysensors/mysensors-forum/NodeBB/node_modules/socket.io-redis/index.js:92:26)
    at RedisClient.emit (events.js:106:17)
    at RedisClient.return_reply (/usr/mysensors/mysensors-forum/NodeBB/node_modules/redis/index.js:624:22)
    at RedisClient.<anonymous> (/usr/mysensors/mysensors-forum/NodeBB/node_modules/redis/index.js:284:18)
    at process._tickDomainCallback (node.js:486:13)
22/9 09:40 [3136] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
```

**Comment by barisusakli** [comment]
Last comment might be related.
https://github.com/socketio/socket.io-redis/issues/17#issuecomment-142347688

What is your `redis` version? npm ls redis

Also post the other module versions.

`socket.io`
`socket.io-redis`
nodebb git hash

**Comment by henrikekblad** [comment]
Maybe related.. But unfortunately I cannot get the version because I just deleted node_modules and did

npm install
node app —setup
./nodebb upgrade

And now it starts fine again.

It is a bit unfortunate that npm seems to keep caches and other things under the hood which makes upgrades a bit un-deterministic.

**Comment by stephengardner** [comment]
I'm having the same issue. I've re-npm-installed to no avail.

Redis `v2.0.1`
Socket.io `v1.3.6`
Socket.io-redis `v0.1.4`

**Comment by stephengardner** [comment]
Can confirm that dropping back to Redis `v1.0.0` solved my problem.  Though this is not ideal.  Hopefully the new version gets a patch for this.
