### ISSUE TITLE
MongoDB: new installation

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#3667]
Hi guys,

I have decided to reinstall NodeBB, and experience weird error, have tried both: web installer and `./nodebb setup` in both, I'm receiving error:

```
mongodb@2.0.43 node_modules/mongodb
├── es6-promise@2.1.1
├── readable-stream@1.0.31 (isarray@0.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── mongodb-core@1.2.12 (bson@0.4.12, kerberos@0.0.14)
/Users/nicolas/Documents/Works/JavaScript/NodeBB/node_modules/mongodb/lib/mongo_client.js:435
              throw err
                    ^
TypeError: undefined is not a function
    at new MongoStore (/Users/nicolas/Documents/Works/JavaScript/NodeBB/node_modules/connect-mongo/lib/connect-mongo.js:114:19)
    at /Users/nicolas/Documents/Works/JavaScript/NodeBB/src/database/mongo.js:111:27
    at /Users/nicolas/Documents/Works/JavaScript/NodeBB/node_modules/mongodb/lib/mongo_client.js:432:15
    at process._tickCallback (node.js:355:11)
```

In mongo logs, there is successful authentication.

**Comment by barisusakli** [comment]
Are you node 4.0 +

**Comment by NicolasSiver** [comment]
```
$ node -v
v0.12.7
```

**Comment by barisusakli** [comment]
What happens when you just run `npm i mongodb@~2.0.0`

**Comment by NicolasSiver** [comment]
Successful installation.

cropped logs
```
$ npm i mongodb@~2.0.0

> kerberos@0.0.14 install /Users/nicolas/Documents/Works/JavaScript/NodeBB/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
./Release/.deps/Release/obj.target/kerberos/lib/kerberos.o.d.raw { dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 7351682,
  size: 1313,
  blocks: 8,
  atime: Thu Sep 24 2015 22:04:13 GMT-0400 (EDT),
  mtime: Thu Sep 24 2015 22:04:13 GMT-0400 (EDT),
  ctime: Thu Sep 24 2015 22:04:13 GMT-0400 (EDT),
  birthtime: Thu Sep 24 2015 22:04:13 GMT-0400 (EDT) }
  CXX(target) Release/obj.target/kerberos/lib/worker.o

bson@0.4.12 node_modules/mongodb/node_modules/mongodb-core/node_modules/bson -> node_modules/bson
core-util-is@1.0.1 node_modules/mongodb/node_modules/readable-stream/node_modules/core-util-is -> node_modules/core-util-is
es6-promise@2.1.1 node_modules/mongodb/node_modules/es6-promise -> node_modules/es6-promise
isarray@0.0.1 node_modules/mongodb/node_modules/readable-stream/node_modules/isarray -> node_modules/isarray
nan@2.0.9 node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/node_modules/nan -> node_modules/nan
kerberos@0.0.14 node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos -> node_modules/kerberos
mongodb-core@1.2.12 node_modules/mongodb/node_modules/mongodb-core -> node_modules/mongodb-core
string_decoder@0.10.31 node_modules/mongodb/node_modules/readable-stream/node_modules/string_decoder -> node_modules/string_decoder
readable-stream@1.0.31 node_modules/mongodb/node_modules/readable-stream -> node_modules/readable-stream
nodebb@0.8.2 /Users/nicolas/Documents/Works/JavaScript/NodeBB
├─┬ grunt@0.4.5
│ ├── async@0.1.22
│ ├── colors@0.6.2
│ ├─┬ grunt-legacy-log@0.1.2
│ │ ├── colors@0.6.2
│ │ └─┬ grunt-legacy-log-utils@0.1.1
│ │   └── colors@0.6.2
│ ├─┬ grunt-legacy-util@0.2.0
│ │ └── async@0.1.22
│ ├─┬ js-yaml@2.0.5
│ │ └─┬ argparse@0.1.16
│ │   └── underscore@1.7.0
│ └── rimraf@2.2.8
├─┬ grunt-contrib-watch@0.6.1
│ └── async@0.2.10
├─┬ mocha@1.13.0
│ ├─┬ jade@0.26.3
│ │ └── mkdirp@0.3.0
│ └── mkdirp@0.3.5
├── mongodb@2.0.43
├─┬ nodebb-plugin-dbsearch@0.2.16
│ ├── async@0.2.10
│ └─┬ winston@0.8.3
│   └── colors@0.6.2
├─┬ nodebb-plugin-spam-be-gone@0.4.2
│ └── simple-recaptcha@1.0.0  (git://github.com/wzrdtales/simple-recaptcha.git#f408725106872df696436ff6a988923539ab80a6)
├─┬ prompt@0.2.14
│ ├─┬ utile@0.2.1
│ │ └── async@0.2.10
│ └─┬ winston@0.8.3
│   ├── async@0.2.10
│   └── colors@0.6.2
└─┬ uglify-js@2.4.24
  └── async@0.2.10
```

**Comment by barisusakli** [comment]
What about `npm i connect-mongo`

**Comment by NicolasSiver** [comment]
Also success.

```
$ npm i connect-mongo
depd@1.1.0 node_modules/connect-mongo/node_modules/depd -> node_modules/depd
nodebb@0.8.2 /Users/nicolas/Documents/Works/JavaScript/NodeBB
└── connect-mongo@0.8.2  extraneous
```

**Comment by barisusakli** [comment]
That's weird, not sure it would crash during setup. `./nodebb setup` calls npm i as well.

**Comment by barisusakli** [comment]
Post the entire ./nodebb setup as well

**Comment by NicolasSiver** [comment]
```
$ ./nodebb setup
24/9 22:17 [1392] - info: NodeBB Setup Triggered via Command Line

Welcome to NodeBB!

This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
Press enter to accept the default setting (shown in brackets).
URL used to access this NodeBB (http://localhost:4567)
Please enter a NodeBB secret (af3b332c-d418-402a-9cdd-9ff18289a84e)
Which database to use (mongo)

24/9 22:17 [1392] - info: Now configuring mongo database:
Host IP or address of your MongoDB instance (127.0.0.1)
Host port of your MongoDB instance (27017)
MongoDB username (someuser)
Password of your MongoDB database
Which database to use (somedb)
Configuration Saved OK
connect-mongo@0.8.2 node_modules/connect-mongo

mongodb@2.0.43 node_modules/mongodb
/Users/nicolas/Documents/Works/JavaScript/NodeBB/node_modules/mongodb/lib/mongo_client.js:435
              throw err
                    ^
TypeError: undefined is not a function
    at new MongoStore (/Users/nicolas/Documents/Works/JavaScript/NodeBB/node_modules/connect-mongo/lib/connect-mongo.js:114:19)
    at /Users/nicolas/Documents/Works/JavaScript/NodeBB/src/database/mongo.js:111:27
    at /Users/nicolas/Documents/Works/JavaScript/NodeBB/node_modules/mongodb/lib/mongo_client.js:432:15
    at process._tickCallback (node.js:355:11)
```

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/blob/master/src/install.js#L16

try adding a @0.8.1 after connect-mongo and see if ./nodebb setup works you can go back a few more versions to test.

**Comment by NicolasSiver** [comment]
Doesn't help.
Does it support Mongo 3? (`3.0.5`)

Created db and new user just for test, same error:

```
$ mongo
MongoDB shell version: 3.0.5
connecting to: test
Server has startup warnings:
2015-09-24T21:39:09.155-0400 I CONTROL  [initandlisten]
2015-09-24T21:39:09.155-0400 I CONTROL  [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
> use ninstall
switched to db ninstall
> db.createUser({user:'master', pwd: 'test', roles:['dbAdmin', 'readWrite']})
Successfully added user: { "user" : "master", "roles" : [ "dbAdmin", "readWrite" ] }
```

**Comment by NicolasSiver** [comment]
What about this?

https://github.com/NodeBB/NodeBB/blob/master/src/database/mongo.js#L109-L113

**Comment by barisusakli** [comment]
You can remove the db.openCalled =true; I think thats fixed in later versions of connect-mongo.

And yes I used mongodb 3.0 but connect-mongo doesn't work on node4. So I used connect-redis instead.

**Comment by NicolasSiver** [comment]
- reinstalled mongodb.
- created new database
- so many things...

Actually I have found problem, but by fixing it, I have encountered `node gyp`...

**Are you curious to find what was the problem? ;)**

It looks like, on this stage of changes, everyone should move really fast... I mean update stuff for latest releases.

**Comment by barisusakli** [comment]
Yes please share your fix so others can benefit as well

**Comment by NicolasSiver** [comment]
Just recommendation, don't update npm to 3-rd version. Main problem was in npm.
But after downgrade of npm, I have lost it, so I had to reinstall node, and solve problem with node gyp just like this `npm i -g node-gyp`

npm `2.14` does not produce any installation issues.
