### ISSUE TITLE
NodeBB hangs when uploading a group cover image

### ISSUE THREAD

**Issue by manolino** [NodeBB/NodeBB#3669]
When you drag an image into the group cover image and save it, NodeBB stops and restarts.
Here the error:
```
24/9 12:18 [20262] - error: TypeError: Cannot read property 'replace' of undefined
    at Mime.lookup (/home/agora/NodeBB/node_modules/nodebb-plugin-s3-uploads/node_modules/mime/mime.js:72:17)
    at uploadToS3 (/home/agora/NodeBB/node_modules/nodebb-plugin-s3-uploads/index.js:268:25)
    at /home/agora/NodeBB/node_modules/nodebb-plugin-s3-uploads/index.js:196:9
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```
Modified line **196** of **nodebb-plugin-s3-uploads/index.js** file with these:

```javascript
		  // PIC added: seems image has no name property when comes from a drag-into
		 if (!image.name) {  // PIC added
			winston.warn("uploadImage: no image name");  // PIC added
			uploadToS3(image.path, err, buffer, callback);  // PIC added
		 } else {  // PIC added
			winston.warn("uploadImage: image name provided");  // PIC added
			uploadToS3(image.name, err, buffer, callback); 
		 }  // PIC added
```

The **data.image** object argument in ```plugin.uploadImage = function (data, callback) { ... ``` has no **name** property.

I think that the problem is not in the **nodebb-plugin-s3-uploads** but in *groups* where calling **uploadimage** plugin function.
The above mentioned functions works well in composer.

**Comment by julianlam** [comment]
Let me know if this resolves the issue.

**Comment by manolino** [comment]
It works. Thanks Julian.
