### ISSUE TITLE
error: [plugins] filter:search.query,  Unable to execute query: error processing 

### ISSUE THREAD

**Issue by ogerly** [NodeBB/NodeBB#3684]
#### if I want to search for something breaks .. NodeBB from

28/9 12:22 [5129] - error: [plugins] filter:search.query,  Unable to execute query: error processing query: ns=1.searchpost limit=50 skip=0
Tree: TEXT : query=welt, language=, tag=NULL
Sort: {}
Proj: {}
 planner returned error: need exactly one text index for $text query
28/9 12:22 [5129] - error: /api/search/welt
 MongoError: Unable to execute query: error processing query: ns=1.searchpost limit=50 skip=0
Tree: TEXT : query=welt, language=, tag=NULL
Sort: {}
Proj: {}
 planner returned error: need exactly one text index for $text query
    at Function.MongoError.create (/var/www/clients/10/30/web/nodebb_senderfm/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/var/www/clients/10/30/web/nodebb_senderfm/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:267:34)
    at Callbacks.emit (/var/www/clients/10/30/web/nodebb_senderfm/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/var/www/clients/10/30/web/nodebb_senderfm/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/var/www/clients/10/30/web/nodebb_senderfm/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
28/9 12:22 [5129] - error: [plugins] filter:search.query,  Unable to execute query: error processing query: ns=1.searchtopic limit=50 skip=0
Tree: TEXT : query=welt, language=, tag=NULL
Sort: {}
Proj: {}
 planner returned error: need exactly one text index for $text query
28/9 12:22 [5129] - error: TypeError: Cannot read property 'link' of null
    at /var/www/clients/10/30/web/nodebb_senderfm/src/controllers/search.js:78:20
    at Array.filter (native)
    at /var/www/clients/10/30/web/nodebb_senderfm/src/controllers/search.js:77:27
    at /var/www/clients/10/30/web/nodebb_senderfm/node_modules/async/lib/async.js:52:16
    at /var/www/clients/10/30/web/nodebb_senderfm/node_modules/async/lib/async.js:1166:30
    at /var/www/clients/10/30/web/nodebb_senderfm/src/categories.js:167:4
    at /var/www/clients/10/30/web/nodebb_senderfm/node_modules/async/lib/async.js:697:13
    at /var/www/clients/10/30/web/nodebb_senderfm/node_modules/async/lib/async.js:52:16
    at done (/var/www/clients/10/30/web/nodebb_senderfm/node_modules/async/lib/async.js:248:21)
    at /var/www/clients/10/30/web/nodebb_senderfm/node_modules/async/lib/async.js:44:16
TypeError: Cannot read property 'link' of null
    at /var/www/clients/10/30/web/nodebb_senderfm/src/controllers/search.js:78:20
    at Array.filter (native)
    at /var/www/clients/10/30/web/nodebb_senderfm/src/controllers/search.js:77:27
    at /var/www/clients/10/30/web/nodebb_senderfm/node_modules/async/lib/async.js:52:16
    at /var/www/clients/10/30/web/nodebb_senderfm/node_modules/async/lib/async.js:1166:30
    at /var/www/clients/10/30/web/nodebb_senderfm/src/categories.js:167:4
    at /var/www/clients/10/30/web/nodebb_senderfm/node_modules/async/lib/async.js:697:13
    at /var/www/clients/10/30/web/nodebb_senderfm/node_modules/async/lib/async.js:52:16
    at done (/var/www/clients/10/30/web/nodebb_senderfm/node_modules/async/lib/async.js:248:21)
    at /var/www/clients/10/30/web/nodebb_senderfm/node_modules/async/lib/async.js:44:16
28/9 12:22 [5129] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
28/9 12:22 [5129] - info: [app] Database connection closed.
28/9 12:22 [5129] - info: [app] Web server closed to connections.
28/9 12:22 [5129] - info: [app] Shutdown complete.

**Comment by barisusakli** [comment]
Duplicated of https://github.com/NodeBB/NodeBB/issues/3651#issuecomment-143759909
