### ISSUE TITLE
Got error while implementing facebook login

### ISSUE THREAD

**Issue by sameer-yadav01011990** [NodeBB/NodeBB#3778]
I've installed `nodebb-plugin-sso-facebook` plugin to enable Facebook sing-up/ login.

I've updated app and secret key correctly in admin panel, also added website url in `config.json` file.

Also restarted app after this.

I'm getting following error while trying to singup from `facebook singup` button.

```
error: /auth/facebook/callback
 FacebookTokenError: Error validating verification code. Please make sure your redirect_uri  is identical to the one you used in the OAuth dialog request
    at Strategy.parseErrorResponse (/node_modules/nodebb-plugin-sso-facebook/node_modules/passport-facebook/lib/strategy.js:198:12)
    at Strategy.OAuth2Strategy._createOAuthError (/node_modules/nodebb-plugin-sso-facebook/node_modules/passport-facebook/node_modules/passport-     oauth2/lib/strategy.js:345:16)
    at /node_modules/nodebb-plugin-sso-facebook/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:171:43
    at /node_modules/nodebb-plugin-sso-facebook/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18
    at passBackControl (/node_modules/nodebb-plugin-sso-facebook/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/ oauth2.js:123:9)
    at IncomingMessage.<anonymous> (/node_modules/nodebb-plugin-sso-facebook/node_modules/passport-facebook/node_modules/passport-oauth2/            node_modules/oauth/lib/oauth2.js:143:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

```
I'm running app on following setup.
`AWS - ec2`
`nginx` running on port 80
`NodeBB master branch version` running on port `4567` 

I think this error is cause of `nginx` 

Please provide some help to solve this.

**Comment by sameer-yadav01011990** [comment]
My bad, this error was caused by extra `/` in `config.json`
