### ISSUE TITLE
Installation script fails

### ISSUE THREAD

**Issue by Marc-Boisvert-Dupras** [NodeBB/NodeBB#3805]
Using the latest master as of this writing (git hash: fa643e0c25c8aed6d90d269493b91ef97d6665ca)

The installer fails to create Administrator users when running ```npm start``` or ```./nodebb setup```
Console log:
```/home/marc/Documents/nodebb/node_modules/async/lib/async.js:52
            fn.apply(this, arguments);
               ^

TypeError: fn.apply is not a function
    at /home/marc/Documents/nodebb/node_modules/async/lib/async.js:52:16
    at Immediate._onImmediate (/home/marc/Documents/nodebb/node_modules/async/lib/async.js:1163:34)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

**Comment by barisusakli** [comment]
What version of async?
