### ISSUE TITLE
Cannot upload cover picture

### ISSUE THREAD

**Issue by Marc-Boisvert-Dupras** [NodeBB/NodeBB#3808]
On the latest master of this writing, there is an error when trying to upload a cover picture. I made sure all settings were enabled in the admin panel.

Hash: ```2fef7acf4b006544bd9c6227f889d197fd4c2ff1```

Log:
```31/10 12:01 [14123] - error: /api/user/uploadcover
 Error: [[error:uploads-are-disabled]]
    at uploadImage (/home/marc/Documents/nodebb/src/controllers/uploads.js:111:12)
    at Object.uploadsController.uploadUserCover (/home/marc/Documents/nodebb/src/controllers/uploads.js:100:2)
    at /home/marc/Documents/nodebb/src/user/picture.js:167:23
    at /home/marc/Documents/nodebb/node_modules/async/lib/async.js:689:13
    at iterate (/home/marc/Documents/nodebb/node_modules/async/lib/async.js:265:13)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
31/10 12:01 [14123] - error: /api/user/uploadcover
 Error: [[error:uploads-are-disabled]]
    at uploadImage (/home/marc/Documents/nodebb/src/controllers/uploads.js:111:12)
    at Object.uploadsController.uploadUserCover (/home/marc/Documents/nodebb/src/controllers/uploads.js:100:2)
    at /home/marc/Documents/nodebb/src/user/picture.js:167:23
    at /home/marc/Documents/nodebb/node_modules/async/lib/async.js:689:13
    at iterate (/home/marc/Documents/nodebb/node_modules/async/lib/async.js:265:13)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)```

**Comment by barisusakli** [comment]
Works for me on latest with `Allow users to upload regular files` enabled in ACP.

**Comment by Marc-Boisvert-Dupras** [comment]
@barisusakli I have that enabled. I will try with the very latest master again and report back.
