### ISSUE TITLE
Nested Categories not working in Lavendar Theme

### ISSUE THREAD

**Issue by atonb117** [NodeBB/NodeBB#3823]
I was testing the Lavender Theme on a local install after creating a Category called North America with a Sub Category of Georgia which has a sub category of Fulton.

From the home page, one could not enter the North American Category unless ALL it's sub categories where deactivated.

After switching back to default theme, nested categories work fine.

Here is output of error:

home:~/../../NodeBB$ ./nodebb log

Type Ctrl-C to exit

Clustering enabled: Spinning up 1 process(es).

1/11 17:30 [4813] - info: Time: Sun Nov 01 2015 17:30:57 GMT-0500 (EST)
1/11 17:30 [4813] - info: Initializing NodeBB v0.8.2

1/11 17:31 [4813] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-theme-lavender

1/11 17:31 [4813] - info: NodeBB Ready
1/11 17:31 [4813] - info: NodeBB is now listening on: 0.0.0.0:4567
[cluster] Restarting...
Clustering enabled: Spinning up 1 process(es).
1/11 17:33 [4813] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.

1/11 17:33 [4813] - info: [app] Database connection closed.
1/11 17:33 [4813] - info: [app] Web server closed to connections.
1/11 17:33 [4813] - info: [app] Shutdown complete.
[cluster] Child Process (4813) has exited (code: 0, signal: null)
1/11 17:33 [4847] - info: Time: Sun Nov 01 2015 17:33:20 GMT-0500 (EST)
1/11 17:33 [4847] - info: Initializing NodeBB v0.8.2

1/11 17:33 [4847] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-theme-lavender

1/11 17:33 [4847] - info: NodeBB Ready
1/11 17:33 [4847] - info: NodeBB is now listening on: 0.0.0.0:4567
2/11 18:09 [4847] - error: RangeError: Maximum call stack size exceeded
    at String.match (native)
    at checkConditional (/home/NodeBB/node_modules/templates.js/lib/templates.js:221:26)
    at checkConditionals (/home/NodeBB/node_modules/templates.js/lib/templates.js:217:27)
    at parseValue (/home/NodeBB/node_modules/templates.js/lib/templates.js:383:14)
    at parse (/home/NodeBB/node_modules/templates.js/lib/templates.js:402:17)
    at cleanup (/home/NodeBB//node_modules/templates.js/lib/templates.js:473:27)
    at parse (/home/NodeBB/node_modules/templates.js/lib/templates.js:419:15)
    at cleanup (/home/NodeBB/node_modules/templates.js/lib/templates.js:473:27)
    at parse (/home/NodeBB/node_modules/templates.js/lib/templates.js:419:15)
    at cleanup (/home/NodeBB/node_modules/templates.js/lib/templates.js:473:27)
RangeError: Maximum call stack size exceeded
    at String.match (native)
    at checkConditional (/home/NodeBB/node_modules/templates.js/lib/templates.js:221:26)
    at checkConditionals (/home/NodeBB/node_modules/templates.js/lib/templates.js:217:27)
    at parseValue (/home/NodeBB/node_modules/templates.js/lib/templates.js:383:14)
    at parse (/home/NodeBB/node_modules/templates.js/lib/templates.js:402:17)
    at cleanup (/home/NodeBB/node_modules/templates.js/lib/templates.js:473:27)
    at parse (/home/NodeBB/node_modules/templates.js/lib/templates.js:419:15)
    at cleanup (/home/NodeBB/node_modules/templates.js/lib/templates.js:473:27)
    at parse (/home/NodeBB/node_modules/templates.js/lib/templates.js:419:15)
    at cleanup(/home/NodeBB/node_modules/templates.js/lib/templates.js:473:27)
2/11 18:09 [4847] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2/11 18:09 [4847] - info: [app] Database connection closed.
2/11 18:09 [4847] - info: [app] Web server closed to connections.
2/11 18:09 [4847] - info: [app] Shutdown complete.
[cluster] Child Process (4847) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2/11 18:09 [12562] - info: Time: Mon Nov 02 2015 18:09:43 GMT-0500 (EST)
2/11 18:09 [12562] - info: Initializing NodeBB v0.8.2

**Comment by barisusakli** [comment]
What version of lavender and templates.js?

**Comment by atonb117** [comment]
Not quite sure how to find that info quickly.
