### ISSUE TITLE
0.9.0 Upgrade Script Error at Gravatar Update Again

### ISSUE THREAD

**Issue by scottalanmiller** [NodeBB/NodeBB#3856]
Had this a few days ago then an update fixed it.  Upgrading a different community and a similar error has come up again.  This is fully updated as of a few minutes ago, so not an older version of the tree.

8/11 19:55 [6759] - info: [2015/07/03] Enabling default composer plugin skipped
8/11 19:55 [6759] - info: [2015/08/18] Creating children category sorted sets skipped
8/11 19:55 [6759] - info: [2015/09/30] Converting default Gravatar image to default User Avatar
8/11 19:55 [6759] - info: [2015/09/30] Converting default Gravatar image to default User Avatar skipped
8/11 19:55 [6759] - info: [2015/11/06] Removing gravatar

/opt/ntge-9.0/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
Error: Callback was already called.
    at /opt/ntge-9.0/node_modules/async/lib/async.js:43:36
    at /opt/ntge-9.0/node_modules/async/lib/async.js:694:17
    at /opt/ntge-9.0/node_modules/async/lib/async.js:173:37
    at /opt/ntge-9.0/src/database/mongo/hash.js:15:4
    at handleCallback (/opt/ntge-9.0/node_modules/mongodb/lib/utils.js:95:12)
    at /opt/ntge-9.0/node_modules/mongodb/lib/collection.js:782:5
    at /opt/ntge-9.0/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:806:13
    at Callbacks.emit (/opt/ntge-9.0/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/opt/ntge-9.0/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:246:23)
    at Socket.<anonymous> (/opt/ntge-9.0/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:                            22)

Error: undefined

**Comment by scottalanmiller** [comment]
I ran the full git fetch; git pull; npm i; ./nodebb upgrade again (from command history, so none of this was missed before) and it worked fine.  So my guess is that this is a transient issue.
