### ISSUE TITLE
0.9.0 Database Upgrade Error

### ISSUE THREAD

**Issue by scottalanmiller** [NodeBB/NodeBB#3857]
0.8.2 to 0.9.0

root@iad-lnx-mangodb:/opt/kae-9.0# ./nodebb upgrade
1. Bringing base dependencies up to date... OK
2. Updating NodeBB data store schema.
8/11 21:17 [13630] - info: [database] Checking database indices.

/opt/kae-9.0/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
Error: Cannot find module 'isarray'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/kae-9.0/node_modules/socket.io/node_modules/socket.io-adapter/node_modules/socket.io-parser/index.js:8:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Error: undefined

**Comment by julianlam** [comment]
Still experiencing this issue?
