### ISSUE TITLE
restarting nodebb multiple time

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#3978]
nodebb will be restart after some hours, with this on `log`:

	20/12 17:57 [678] - error: TypeError: Cannot read property 'length' of undefined
		at Object.Plugins.normalise (/path/to/nodebb/src/plugins.js:225:27)
		at Request._callback (/path/to/nodebb/src/plugins.js:217:12)
		at self.callback (/path/to/nodebb/node_modules/request/request.js:198:22)
		at Request.emit (events.js:107:17)
		at Request.onRequestError (/path/to/nodebb/node_modules/request/request.js:820:8)
		at ClientRequest.emit (events.js:107:17)
		at TLSSocket.socketErrorListener (_http_client.js:271:9)
		at TLSSocket.emit (events.js:129:20)
		at net.js:952:16
		at process._tickDomainCallback (node.js:381:11)
	TypeError: Cannot read property 'length' of undefined
		at Object.Plugins.normalise (/path/to/nodebb/src/plugins.js:225:27)
		at Request._callback (/path/to/nodebb/src/plugins.js:217:12)
		at self.callback (/path/to/nodebb/node_modules/request/request.js:198:22)
		at Request.emit (events.js:107:17)
		at Request.onRequestError (/path/to/nodebb/node_modules/request/request.js:820:8)
		at ClientRequest.emit (events.js:107:17)
		at TLSSocket.socketErrorListener (_http_client.js:271:9)
		at TLSSocket.emit (events.js:129:20)
		at net.js:952:16
		at process._tickDomainCallback (node.js:381:11)

	 
or this error:

	20/12 18:04 [2947] - error: MongoError: server 127.0.0.1:27017 sockets closed
		at Server.destroy (/path/to/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:676:47)
		at Server.close (/path/to/nodebb/node_modules/mongodb/lib/server.js:367:17)
		at Db.close (/path/to/nodebb/node_modules/mongodb/lib/db.js:333:19)
		at Object.module.close (/path/to/nodebb/src/database/mongo.js:228:6)
		at shutdown (/path/to/nodebb/app.js:305:28)
		at process.<anonymous> (/path/to/nodebb/app.js:176:3)
		at process.emit (events.js:107:17)
		at process._fatalException (node.js:236:26)

**Comment by sohrabafard** [comment]
this will be happen on chat!

**Comment by barisusakli** [comment]
Looks like a issue in [plugins.list](https://github.com/NodeBB/NodeBB/blob/master/src/plugins.js#L210-L217). If there is an error getting the list from the package manager it sets the plugins to an empty array but still goes on to call `Plugins.normalise` which would just crash since body is undefined.
