### ISSUE TITLE
Restart with error

### ISSUE THREAD

**Issue by tailot** [NodeBB/NodeBB#3979]
Click in a discussion:

20/12 16:10 [25732] - error: TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.json (/var/openbadges/node_modules/express/lib/response.js:242:19)
    at ServerResponse.res.render (/var/openbadges/src/middleware/render.js:42:16)
    at /var/openbadges/src/controllers/topics.js:287:8
    at fireFilterHook (/var/openbadges/src/plugins/hooks.js:86:11)
    at Object.Plugins.fireHook (/var/openbadges/src/plugins/hooks.js:70:5)
    at /var/openbadges/src/controllers/topics.js:283:11
    at /var/openbadges/node_modules/async/lib/async.js:52:16
    at Object._onImmediate (/var/openbadges/node_modules/async/lib/async.js:1201:34)
    at processImmediate [as _immediateCallback] (timers.js:363:15)
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.json (/var/openbadges/node_modules/express/lib/response.js:242:19)
    at ServerResponse.res.render (/var/openbadges/src/middleware/render.js:42:16)
    at /var/openbadges/src/controllers/topics.js:287:8
    at fireFilterHook (/var/openbadges/src/plugins/hooks.js:86:11)
    at Object.Plugins.fireHook (/var/openbadges/src/plugins/hooks.js:70:5)
    at /var/openbadges/src/controllers/topics.js:283:11
    at /var/openbadges/node_modules/async/lib/async.js:52:16
    at Object._onImmediate (/var/openbadges/node_modules/async/lib/async.js:1201:34)

**Comment by barisusakli** [comment]
What version we fixed this  yesterday https://github.com/NodeBB/NodeBB/commit/f0217ee19825e9e9205419018992d0373df3c644

**Comment by tailot** [comment]
Thanks!

**Comment by layernull** [comment]
For some reason a fresh checkout of

    git clone https://github.com/NodeBB/NodeBB.git
    cd NodeBB
    git checkout v0.9.3

results in a commit hash da78e4f02b080388d7efe75f84f9621f8cd053cb one revision before this fix.

I had to git hard reset to commit hash 6486197623f8f32ab354503ca40ab6e8e3e4551e to get the same stable hash I have on my developer machine I got by first checking out v0.9.2 and then upgrading to v0.9.3
