### ISSUE TITLE
TypeError: Converting circular structure to JSON 

### ISSUE THREAD

**Issue by 329379172** [NodeBB/NodeBB#3992]
when i run NodeBB v0.9.3 found this error;

then i add this code on render.js,it's fine;
```
options && options.related && options.related.related && delete options.related.related;
var ajaxifyData = JSON.stringify(options);
ajaxifyData = ajaxifyData.replace(/<\//g, '<\\/');
```

**Comment by lots0logs** [comment]
I can confirm this:
```
22/12 23:06 [6586] - error: TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.res.render (/opt/nodebb/src/middleware/render.js:49:27)
    at /opt/nodebb/src/controllers/topics.js:287:8
    at fireFilterHook (/opt/nodebb/src/plugins/hooks.js:86:11)
    at Object.Plugins.fireHook (/opt/nodebb/src/plugins/hooks.js:70:5)
    at /opt/nodebb/src/controllers/topics.js:283:11
    at /opt/nodebb/node_modules/async/lib/async.js:52:16
    at Object._onImmediate (/opt/nodebb/node_modules/async/lib/async.js:1201:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.res.render (/opt/nodebb/src/middleware/render.js:49:27)
    at /opt/nodebb/src/controllers/topics.js:287:8
    at fireFilterHook (/opt/nodebb/src/plugins/hooks.js:86:11)
    at Object.Plugins.fireHook (/opt/nodebb/src/plugins/hooks.js:70:5)
    at /opt/nodebb/src/controllers/topics.js:283:11
    at /opt/nodebb/node_modules/async/lib/async.js:52:16
    at Object._onImmediate (/opt/nodebb/node_modules/async/lib/async.js:1201:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by julianlam** [comment]
This may have already been resolved by @barisusakli

Can you check that it works fine on master? If so, we'll need to backport the fix to `v0.9.x`

**Comment by lots0logs** [comment]
All good on master :thumbsup:

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/f0217ee19825e9e9205419018992d0373df3c644 is the fix for this

**Comment by 329379172** [comment]
@barisusakli  now it works well:thumbsup:
