### ISSUE TITLE
error: TypeError: Cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#3999]
24/12 00:09 [6630] - error: TypeError: Cannot read property 'render' of undefined
		at Object.Markdown.parsePost [as method] (/path/to/nodebb/node_modules/nodebb-plugin-markdown/index.js:104:36)
		at /path/to/nodebb/src/plugins/hooks.js:97:12
		at /path/to/nodebb/node_modules/async/lib/async.js:375:13
		at Immediate.iterate [as _onImmediate] (/path/to/nodebb/node_modules/async/lib/async.js:262:13)
		at processImmediate [as _immediateCallback] (timers.js:367:17)
	TypeError: Cannot read property 'render' of undefined
		at Object.Markdown.parsePost [as method] (/path/to/nodebb/node_modules/nodebb-plugin-markdown/index.js:104:36)
		at /path/to/nodebb/src/plugins/hooks.js:97:12
		at /path/to/nodebb/node_modules/async/lib/async.js:375:13
		at Immediate.iterate [as _onImmediate] (/path/to/nodebb/node_modules/async/lib/async.js:262:13)
		at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-markdown/pull/57 @julianlam
