### ISSUE TITLE
URIError: Failed to decode param 

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#4003]
24/12 19:24 [27536] - error: /category/84/1%CC'6%CC-'F3'F%CC
	 URIError: Failed to decode param '1%CC'6%CC-'F3'F%CC'
		at decodeURIComponent (native)
		at decode_param (/path/to/nodebb/node_modules/express/lib/router/layer.js:167:12)
		at Layer.match (/path/to/nodebb/node_modules/express/lib/router/layer.js:143:15)
		at matchLayer (/path/to/nodebb/node_modules/express/lib/router/index.js:557:18)
		at next (/path/to/nodebb/node_modules/express/lib/router/index.js:216:15)
		at Function.handle (/path/to/nodebb/node_modules/express/lib/router/index.js:176:3)
		at router (/path/to/nodebb/node_modules/express/lib/router/index.js:46:12)
		at Layer.handle [as handle_request] (/path/to/nodebb/node_modules/express/lib/router/layer.js:95:5)
		at trim_prefix (/path/to/nodebb/node_modules/express/lib/router/index.js:312:13)
		at /path/to/nodebb/node_modules/express/lib/router/index.js:280:7

**Comment by julianlam** [comment]
Looks to be improperly translated/escaped data in the slug.

Please clear the slug in mongo: `db.objects.update({ _key: "category:48" }, { $set: { "slug": "48/" } }, { "upsert": true, "w": 1 })`

**Comment by sohrabafard** [comment]
query result:

````
WriteResult({
        "nMatched" : 0,
        "nUpserted" : 1,
        "nModified" : 0,
        "_id" : ObjectId("567d67cce3ab879bab922ba5")
})
````
`"nModified" : 0` so I think exists another problem!
