### ISSUE TITLE
cannot logout from the website

### ISSUE THREAD

**Issue by pikshub** [NodeBB/NodeBB#4009]
cannot exist from the website both desktop and mobile version. when trying to quit the website is crushing.

*HEAD is now at 29e87ac... fix initial room creation*

**Comment by julianlam** [comment]
Hello there, please report any server side or client side errors..

**Comment by pikshub** [comment]
at /home/user/nodebb/src/user/auth.js:124:95
    at Command.callback (/home/user/nodebb/node_modules/connect-redis/lib/connect-redis.js:120:14)
    at RedisClient.return_reply (/home/user/nodebb/node_modules/redis/index.js:664:25)
    at JavascriptReplyParser.reply_parser.send_reply (/home/user/nodebb/node_modules/redis/index.js:332:14)
    at JavascriptReplyParser.run (/home/user/nodebb/node_modules/redis/lib/parsers/javascript.js:132:18)
    at JavascriptReplyParser.execute (/home/user/nodebb/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/home/user/nodebb/node_modules/redis/index.js:131:27)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
TypeError: Cannot read property 'uuid' of undefined
    at /home/user/nodebb/src/user/auth.js:124:95
    at Command.callback (/home/user/nodebb/node_modules/connect-redis/lib/connect-redis.js:120:14)
    at RedisClient.return_reply (/home/user/nodebb/node_modules/redis/index.js:664:25)
    at JavascriptReplyParser.reply_parser.send_reply (/home/user/nodebb/node_modules/redis/index.js:332:14)
    at JavascriptReplyParser.run (/home/user/nodebb/node_modules/redis/lib/parsers/javascript.js:132:18)
    at JavascriptReplyParser.execute (/home/user/nodebb/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/home/user/nodebb/node_modules/redis/index.js:131:27)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
27/12 10:01 [15698] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
27/12 10:01 [15698] - [32minfo[39m: [app] Database connection closed.
27/12 10:01 [15698] - [32minfo[39m: [app] Web server closed to connections.
27/12 10:01 [15698] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (15698) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
27/12 10:01 [15700] - [31merror[39m: TypeError: Cannot read property 'uuid' of undefined
    at /home/user/nodebb/src/user/auth.js:124:95
    at Command.callback (/home/user/nodebb/node_modules/connect-redis/lib/connect-redis.js:120:14)
    at RedisClient.return_reply (/home/user/nodebb/node_modules/redis/index.js:664:25)
    at JavascriptReplyParser.reply_parser.send_reply (/home/user/nodebb/node_modules/redis/index.js:332:14)
    at JavascriptReplyParser.run (/home/user/nodebb/node_modules/redis/lib/parsers/javascript.js:132:18)
    at JavascriptReplyParser.execute (/home/user/nodebb/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/home/user/nodebb/node_modules/redis/index.js:131:27)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
TypeError: Cannot read property 'uuid' of undefined
    at /home/user/nodebb/src/user/auth.js:124:95
    at Command.callback (/home/user/nodebb/node_modules/connect-redis/lib/connect-redis.js:120:14)
    at RedisClient.return_reply (/home/user/nodebb/node_modules/redis/index.js:664:25)
    at JavascriptReplyParser.reply_parser.send_reply (/home/user/nodebb/node_modules/redis/index.js:332:14)
    at JavascriptReplyParser.run (/home/user/nodebb/node_modules/redis/lib/parsers/javascript.js:132:18)
    at JavascriptReplyParser.execute (/home/user/nodebb/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/home/user/nodebb/node_modules/redis/index.js:131:27)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
27/12 10:01 [15700] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
27/12 10:01 [15700] - [32minfo[39m: [app] Database connection closed.
27/12 10:01 [15700] - [32minfo[39m: [app] Web server closed to connections.
27/12 10:01 [15700] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (15700) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
27/12 10:01 [15730] - [32minfo[39m: Time: Sun Dec 27 2015 10:01:45 GMT-0500 (EST)
27/12 10:01 [15730] - [32minfo[39m: Initializing NodeBB v0.9.3
