### ISSUE TITLE
 error: NodeBB could not connect to your Mongo database.Mongo returned the following error: auth failed.

### ISSUE THREAD

**Issue by toweave** [NodeBB/NodeBB#4018]
Please. Help me.  When I install nodebb that I was failed too many times.

 [initandlisten] MongoDB starting : pid=20058 port=27017 dbpath=/data/db 64-bit host=XXX
 [initandlisten] db version v2.6.11
 [initandlisten] git version: d00c1735675c457f75a12d530bee85421f0c5548

2/1 21:18 [19898] - error: NodeBB could not connect to your Mongo database. Mongo returned the following error: auth failed
2/1 21:18 [19898] - warn: NodeBB Setup Aborted.
 MongoError: auth failed
    at Function.MongoError.create (/home/wwwroot/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at /home/wwwroot/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:778:66
    at Callbacks.emit (/home/wwwroot/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/home/wwwroot/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/home/wwwroot/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:265:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

**Comment by julianlam** [comment]
If auth failed, then it means the credentials you've supplied are not correct. What values are you putting in?

**Comment by toweave** [comment]
but I try too many times. use my password.name
 When I run mongo
MongoDB shell version: 2.6.11
connecting to: nodebb

db.createUser( { user: "nodebb", pwd: "Liz123", roles: [ "readWrite" ] } )
2016-01-02T21:33:39.436+0800 Error: couldn't add user: not authorized on nodebb to execute command { createUser: "nodebb", pwd: "xxx", roles: [ "readWrite" ], digestPassword: false, writeConcern: { w: "majority", wtimeout: 30000.0 } } at src/mongo/shell/db.js:1086
> auth=true
true

**Comment by toweave** [comment]
I search on Google.but can't catch a correct answer.

**Comment by julianlam** [comment]
It seems your MongoDB is not configured properly for user auth. Please post on our community forum for better service as this is for bugs against the software only.

**Comment by toweave** [comment]
Thanks you.
This question really makes very anxious, but I have no solution.
My server can't run redis. can I use Other versions mongo ?
