### ISSUE TITLE
Deleting user from admin panel causes crash

### ISSUE THREAD

**Issue by Whiplash88** [NodeBB/NodeBB#4023]
Hey guys,

I'd thought I'd report what I got.

Version 0.9.3

Issue: Selecting and then deleting a user from the Manage->Users section of the admin panel causes a crash. The user in question was a "email-not-validated" member.

A little modal follows saying "error 0.0.0.0:27017 sockets closed"

4/1 11:20 [773] - info: NodeBB is now listening on: 0.0.0.0:4567
[11:22:07 am] TypeError: callback is not a function
    at /var/www/nodebb.praxusgroup.com/src/database/mongo/sorted.js:143:5
    at handleCallback (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/lib/utils.js:96:12)
    at /var/www/nodebb.praxusgroup.com/node_modules/mongodb/lib/cursor.js:841:16
    at handleCallback (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
    at setCursorNotified (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:563:3)
    at /var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:673:16
    at queryCallback (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:322:5)
    at Callbacks.emit (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket. (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:300:20)
[11:22:07 am] 4/1 11:21 [773] - error: TypeError: callback is not a function
    at /var/www/nodebb.praxusgroup.com/src/database/mongo/sorted.js:143:5
    at handleCallback (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/lib/utils.js:96:12)
    at /var/www/nodebb.praxusgroup.com/node_modules/mongodb/lib/cursor.js:841:16
    at handleCallback (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
    at setCursorNotified (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:563:3)
    at /var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:673:16
    at queryCallback (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:322:5)
    at Callbacks.emit (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket. (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:300:20)
[11:22:07 am] TypeError: callback is not a function
    at /var/www/nodebb.praxusgroup.com/src/database/mongo/sorted.js:143:5
    at handleCallback (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/lib/utils.js:96:12)
    at /var/www/nodebb.praxusgroup.com/node_modules/mongodb/lib/cursor.js:841:16
    at handleCallback (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
    at setCursorNotified (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:563:3)
    at /var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:673:16
    at queryCallback (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:322:5)
    at Callbacks.emit (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket. (/var/www/nodebb.praxusgroup.com/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:300:20)

**Comment by barisusakli** [comment]
can you post your git revision `git rev-parse HEAD`

**Comment by Whiplash88** [comment]
34a725c9da4a2d53428699f0302abe6d24b12326

**Comment by barisusakli** [comment]
I couldn't reproduce it on that hash, is it happening on a brand new user?

**Comment by Whiplash88** [comment]
Its happening with every user.

Thanks for looking into it regardless. If I learn of more details I will comment.

**Comment by Whiplash88** [comment]
Update: we needed to configure our NGINX to allow upstream websockets connections from the server
Problem solved
