### ISSUE TITLE
nodebb 0.9.3 bug report - Nodebb Crash causes restarting

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#4072]
any user when opens setting page it causes nodebb crash!

Nodebb error in `dev mod` :
````
18/1 18:08 [13188] - error: TypeError: Cannot read property 'meta' of undefined
    at /path/to/nodebb/src/user/auth.js:80:16
    at Array.map (native)
    at /path/to/nodebb/src/user/auth.js:79:25
    at fn (/path/to/nodebb/node_modules/async/lib/async.js:741:34)
    at /path/to/nodebb/node_modules/async/lib/async.js:1208:16
    at /path/to/nodebb/node_modules/async/lib/async.js:166:37
    at /path/to/nodebb/node_modules/async/lib/async.js:701:43
    at /path/to/nodebb/node_modules/async/lib/async.js:167:37
    at /path/to/nodebb/node_modules/async/lib/async.js:1204:30
    at /path/to/nodebb/node_modules/async/lib/async.js:52:16
TypeError: Cannot read property 'meta' of undefined
    at /path/to/nodebb/src/user/auth.js:80:16
    at Array.map (native)
    at /path/to/nodebb/src/user/auth.js:79:25
    at fn (/path/to/nodebb/node_modules/async/lib/async.js:741:34)
    at /path/to/nodebb/node_modules/async/lib/async.js:1208:16
    at /path/to/nodebb/node_modules/async/lib/async.js:166:37
    at /path/to/nodebb/node_modules/async/lib/async.js:701:43
    at /path/to/nodebb/node_modules/async/lib/async.js:167:37
    at /path/to/nodebb/node_modules/async/lib/async.js:1204:30
    at /path/to/nodebb/node_modules/async/lib/async.js:52:16
18/1 18:08 [13188] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
18/1 18:08 [13188] - error: /user/mr-shahrokhi/settings
 MongoError: server 127.0.0.1:27017 sockets closed
    at Server.destroy (/path/to/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:679:47)
    at Server.close (/path/to/nodebb/node_modules/mongodb/lib/server.js:368:17)
    at Db.close (/path/to/nodebb/node_modules/mongodb/lib/db.js:332:19)
    at Object.module.close (/path/to/nodebb/src/database/mongo.js:228:6)
    at shutdown (/path/to/nodebb/app.js:311:28)
    at process.<anonymous> (/path/to/nodebb/app.js:182:3)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)
````

**Comment by sohrabafard** [comment]
original topic:
https://community.nodebb.org/topic/7491/nodebb-0-9-3-bug-report-nodebb-crash-causes-restarting

**Comment by barisusakli** [comment]
Already fixed on master
