### ISSUE TITLE
Posts cache hit on non-number

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#4077]
``` plaintext
TypeError: LRU: key must be a string or number. Almost certainly a bug! object
    at typeCheckKey (/home/saas/nodebb/node_modules/lru-cache/lib/lru-cache.js:20:19)
    at LRUCache.get (/home/saas/nodebb/node_modules/lru-cache/lib/lru-cache.js:230:3)
    at Object.Posts.parsePost (/home/saas/nodebb/src/posts/parse.js:12:29)
    at /home/saas/nodebb/src/topics/teaser.js:65:12
```

Or so the stack trace/error suggests...

**Comment by barisusakli** [comment]
I believe you fixed this here https://github.com/NodeBB/NodeBB/commit/bbc42a937ef4b793ff77db45a0f06a6b91c1a6bd

**Comment by julianlam** [comment]
Thanks @barisusakli :smiley:
