### ISSUE TITLE
 Error: Failed to lookup view "account/best" in views directory

### ISSUE THREAD

**Issue by lots0logs** [NodeBB/NodeBB#4148]
@barisusakli I'm seeing this in the log constantly. Any idea? 
```debug
29/1 21:21 [4864] - [31merror[39m: /user/mim86/best
 Error: Failed to lookup view "account/best" in views directory "/opt/nodebb/public/templates"
    at EventEmitter.render (/opt/nodebb/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/opt/nodebb/node_modules/express/lib/response.js:961:7)
    at ServerResponse.res.render (/opt/nodebb/src/middleware/render.js:52:11)
    at /opt/nodebb/src/controllers/accounts/posts.js:148:8
    at /opt/nodebb/node_modules/async/lib/async.js:721:13
    at /opt/nodebb/node_modules/async/lib/async.js:52:16
    at done (/opt/nodebb/node_modules/async/lib/async.js:246:17)
    at /opt/nodebb/node_modules/async/lib/async.js:44:16
    at /opt/nodebb/node_modules/async/lib/async.js:718:17
    at /opt/nodebb/node_modules/async/lib/async.js:167:37
29/1 21:23 [4864] - [31merror[39m: /user/maxime/best
 Error: Failed to lookup view "account/best" in views directory "/opt/nodebb/public/templates"
    at EventEmitter.render (/opt/nodebb/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/opt/nodebb/node_modules/express/lib/response.js:961:7)
    at ServerResponse.res.render (/opt/nodebb/src/middleware/render.js:52:11)
    at /opt/nodebb/src/controllers/accounts/posts.js:148:8
    at /opt/nodebb/node_modules/async/lib/async.js:721:13
    at /opt/nodebb/node_modules/async/lib/async.js:52:16
    at done (/opt/nodebb/node_modules/async/lib/async.js:246:17)
    at /opt/nodebb/node_modules/async/lib/async.js:44:16
    at /opt/nodebb/node_modules/async/lib/async.js:718:17
    at /opt/nodebb/node_modules/async/lib/async.js:167:37
29/1 21:25 [4864] - [31merror[39m: /user/defcon/best
 Error: Failed to lookup view "account/best" in views directory "/opt/nodebb/public/templates"
    at EventEmitter.render (/opt/nodebb/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/opt/nodebb/node_modules/express/lib/response.js:961:7)
    at ServerResponse.res.render (/opt/nodebb/src/middleware/render.js:52:11)
    at /opt/nodebb/src/controllers/accounts/posts.js:148:8
    at /opt/nodebb/node_modules/async/lib/async.js:721:13
    at /opt/nodebb/node_modules/async/lib/async.js:52:16
    at done (/opt/nodebb/node_modules/async/lib/async.js:246:17)
    at /opt/nodebb/node_modules/async/lib/async.js:44:16
    at /opt/nodebb/node_modules/async/lib/async.js:718:17
    at /opt/nodebb/node_modules/async/lib/async.js:167:37
29/1 21:30 [4864] - [31merror[39m: /user/cgrif/best
 Error: Failed to lookup view "account/best" in views directory "/opt/nodebb/public/templates"
    at EventEmitter.render (/opt/nodebb/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/opt/nodebb/node_modules/express/lib/response.js:961:7)
    at ServerResponse.res.render (/opt/nodebb/src/middleware/render.js:52:11)
    at /opt/nodebb/src/controllers/accounts/posts.js:148:8
    at /opt/nodebb/node_modules/async/lib/async.js:721:13
    at /opt/nodebb/node_modules/async/lib/async.js:52:16
    at done (/opt/nodebb/node_modules/async/lib/async.js:246:17)
    at /opt/nodebb/node_modules/async/lib/async.js:44:16
    at /opt/nodebb/node_modules/async/lib/async.js:718:17
    at /opt/nodebb/node_modules/async/lib/async.js:167:37
29/1 21:32 [4864] - [31merror[39m: /user/slevin/best
 Error: Failed to lookup view "account/best" in views directory "/opt/nodebb/public/templates"
    at EventEmitter.render (/opt/nodebb/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/opt/nodebb/node_modules/express/lib/response.js:961:7)
    at ServerResponse.res.render (/opt/nodebb/src/middleware/render.js:52:11)
    at /opt/nodebb/src/controllers/accounts/posts.js:148:8
    at /opt/nodebb/node_modules/async/lib/async.js:721:13
    at /opt/nodebb/node_modules/async/lib/async.js:52:16
    at done (/opt/nodebb/node_modules/async/lib/async.js:246:17)
    at /opt/nodebb/node_modules/async/lib/async.js:44:16
    at /opt/nodebb/node_modules/async/lib/async.js:718:17
    at /opt/nodebb/node_modules/async/lib/async.js:167:37
29/1 21:34 [4864] - [31merror[39m: /user/ajslye/best
 Error: Failed to lookup view "account/best" in views directory "/opt/nodebb/public/templates"
    at EventEmitter.render (/opt/nodebb/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/opt/nodebb/node_modules/express/lib/response.js:961:7)
    at ServerResponse.res.render (/opt/nodebb/src/middleware/render.js:52:11)
    at /opt/nodebb/src/controllers/accounts/posts.js:148:8
    at /opt/nodebb/node_modules/async/lib/async.js:721:13
    at /opt/nodebb/node_modules/async/lib/async.js:52:16
    at done (/opt/nodebb/node_modules/async/lib/async.js:246:17)
    at /opt/nodebb/node_modules/async/lib/async.js:44:16
    at /opt/nodebb/node_modules/async/lib/async.js:718:17
    at /opt/nodebb/node_modules/async/lib/async.js:167:37
```

**Comment by barisusakli** [comment]
Make sure your theme has the account/best template, take a look at persona for reference

**Comment by lots0logs** [comment]
Okay thanks..has this been backported to lavender and I just missed it? :grimacing:

**Comment by barisusakli** [comment]
Lavender should use the template from vanilla.

**Comment by lots0logs** [comment]
Then so should my theme :confused:

**Comment by pichalite** [comment]
looks like the template is in the wrong location in vanilla. it's at templates/best.tpl instead of templates/account/best.tpl

**Comment by lots0logs** [comment]
Ah, that explains it. Thanks @pichalite :+1:
