### ISSUE TITLE
TypeError: Cannot read property 'cache' of undefined

### ISSUE THREAD

**Issue by ishitatsuyuki** [NodeBB/NodeBB#4171]
Version: master @ g3a6ad52
Happening from a few weeks ago.

Seems a flaw on null checking?
```
error: /bbs/nodebb.min.js
 TypeError: Cannot read property 'cache' of undefined
    at sendMinifiedJS (/home/ishitatsuyuki/NodeBB/src/routes/meta.js:8:66)
    at Layer.handle [as handle_request] (/home/ishitatsuyuki/NodeBB/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ishitatsuyuki/NodeBB/node_modules/express/lib/router/route.js:131:13)
    at middleware.addExpiresHeaders (/home/ishitatsuyuki/NodeBB/src/middleware/middleware.js:197:2)
    at Layer.handle [as handle_request] (/home/ishitatsuyuki/NodeBB/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ishitatsuyuki/NodeBB/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/ishitatsuyuki/NodeBB/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ishitatsuyuki/NodeBB/node_modules/express/lib/router/layer.js:95:5)
    at /home/ishitatsuyuki/NodeBB/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/ishitatsuyuki/NodeBB/node_modules/express/lib/router/index.js:330:12)
```

**Comment by ishitatsuyuki** [comment]
Wait. If there is no cache, this won't serve required content. Please reopen this.

**Comment by barisusakli** [comment]
The cache is populated during startup once its set it should not be empty anymore

**Comment by ishitatsuyuki** [comment]
Still experiencing infinite loading even a few minutes after startup. Something is wrong with this. Also, this occured even a long period after startup

**Comment by barisusakli** [comment]
There might be another error while minification then check logs etc

**Comment by ishitatsuyuki** [comment]
No log available after this commit. It showed this error before commit

**Comment by ishitatsuyuki** [comment]
@barisusakli Do you rather having another issue opened or reopen this? It's a serious problem. Now it returns empty js without error, so the site is malfunctioning. It also happen after a long while after startup.

**Comment by barisusakli** [comment]
If /nodebb.min.js route is returning an empty string that means there is a problem with the minification process. I can't reproduce it on my environment but it can happen due to faulty javascript from a plugin. After you restart nodebb post your entire logs/output.log.

**Comment by ishitatsuyuki** [comment]
If you really don't believe...
```
12/2 15:36 [20068] - info: [app] Shutdown complete.
12/2 15:36 [19664] - info: Time: Fri Feb 12 2016 15:36:15 GMT+0900 (JST)
12/2 15:36 [19664] - info: Initializing NodeBB v0.9.3
12/2 15:36 [19664] - warn: [plugins/nodebb-plugin-sso-google] Hook `filter:user.delete` is deprecated, please use `static:user.delete` instead.
12/2 15:36 [19673] - warn: [plugins/nodebb-plugin-sso-google] Hook `filter:user.delete` is deprecated, please use `static:user.delete` instead.

12/2 15:36 [19664] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-composer-default
  * nodebb-plugin-markdown
  * nodebb-plugin-emoji-extended
  * nodebb-plugin-sso-qq-new

12/2 15:36 [19673] - info: [plugins/spam-be-gone] Settings loaded
12/2 15:36 [19673] - info: NodeBB Ready
12/2 15:36 [19673] - info: Enabling 'trust proxy'
12/2 15:36 [19673] - info: NodeBB is now listening on: localhost:6472
12/2 15:36 [19664] - info: NodeBB Ready
12/2 15:36 [19664] - info: Enabling 'trust proxy'
12/2 15:36 [19664] - info: NodeBB is now listening on: localhost:6471
12/2 15:36 [19664] - info: [plugins/spam-be-gone] Settings loaded
```

**Comment by barisusakli** [comment]
What are you using to run nodebb?

**Comment by ishitatsuyuki** [comment]
git master, pulled everyday

**Comment by barisusakli** [comment]
I meant how are you starting the nodebb app. Ie `node app.js`, `./nodebb start` or `grunt` etc.

For example if you run nodebb in dev mode with `./nodebb dev` you should see more logs.

**Comment by ishitatsuyuki** [comment]
This looks the reason of excessive prepare time to me: `info: [user/jobs] Digest (day) scheduling completed.`
After this message, the server started working again.
Sorry, but remaining logs were vanished since for some reason I have a terminal without history saving.
