### ISSUE TITLE
has no method 'getOnlineAnonCount'

### ISSUE THREAD

**Issue by pikshub** [NodeBB/NodeBB#4356]
12/3 16:09 [13599] - error: TypeError: Object #<Object> has no method 'getOnlineAnonCount'
    at /home/yasin/nodebb/node_modules/nodebb-widget-essentials/library.js:188:46
    at /home/yasin/nodebb/node_modules/async/lib/async.js:726:13
    at /home/yasin/nodebb/node_modules/async/lib/async.js:52:16
    at done (/home/yasin/nodebb/node_modules/async/lib/async.js:246:17)
    at /home/yasin/nodebb/node_modules/async/lib/async.js:44:16
    at Command.<anonymous> (/home/yasin/nodebb/node_modules/async/lib/async.js:723:17)
    at Command.callback (/home/yasin/nodebb/node_modules/async/lib/async.js:167:37)
    at RedisClient.return_reply (/home/yasin/nodebb/node_modules/redis/index.js:664:25)
    at JavascriptReplyParser.reply_parser.send_reply (/home/yasin/nodebb/node_modules/redis/index.js:332:14)
    at JavascriptReplyParser.run (/home/yasin/nodebb/node_modules/redis/lib/parsers/javascript.js:132:18)
TypeError: Object #<Object> has no method 'getOnlineAnonCount'
    at /home/yasin/nodebb/node_modules/nodebb-widget-essentials/library.js:188:46
    at /home/yasin/nodebb/node_modules/async/lib/async.js:726:13
    at /home/yasin/nodebb/node_modules/async/lib/async.js:52:16
    at done (/home/yasin/nodebb/node_modules/async/lib/async.js:246:17)
    at /home/yasin/nodebb/node_modules/async/lib/async.js:44:16
    at Command.<anonymous> (/home/yasin/nodebb/node_modules/async/lib/async.js:723:17)
    at Command.callback (/home/yasin/nodebb/node_modules/async/lib/async.js:167:37)
    at RedisClient.return_reply (/home/yasin/nodebb/node_modules/redis/index.js:664:25)
    at JavascriptReplyParser.reply_parser.send_reply (/home/yasin/nodebb/node_modules/redis/index.js:332:14)
    at JavascriptReplyParser.run (/home/yasin/nodebb/node_modules/redis/lib/parsers/javascript.js:132:18)
12/3 16:09 [13599] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
12/3 16:09 [13599] - info: [app] Database connection closed.
12/3 16:09 [13599] - info: [app] Web server closed to connections.
12/3 16:09 [13599] - info: [app] Shutdown complete.

**Comment by pikshub** [comment]
Switched to branch 'v1.x.x'

**Comment by ReyKoxha** [comment]
Confirming this.
