### ISSUE TITLE
Crash log: Cannot assign to read only property 'id'

### ISSUE THREAD

**Issue by frankdiox** [NodeBB/NodeBB#4370]
NodeBB 0.9.3

```
TypeError: Cannot assign to read only property 'id' of <
    at Object.Plugins.normalise (/data/nodebb/src/plugins.js:226:20)
    at Request._callback (/data/nodebb/src/plugins.js:217:12)
    at Request.self.callback (/data/nodebb/node_modules/request/request.js:198:22)
    at emitTwo (events.js:88:13)
    at Request.emit (events.js:173:7)
    at Request.<anonymous> (/data/nodebb/node_modules/request/request.js:1035:10)
    at emitOne (events.js:83:20)
    at Request.emit (events.js:170:7)
    at IncomingMessage.<anonymous> (/data/nodebb/node_modules/request/request.js:962:12)
    at emitNone (events.js:73:20)
```

This happened several times in a row and the forum went down for a minute or so.

Edit:

I just realized this happens when I try to see `/admin/extend/plugins` in the admin page. I haven't installed any plugin recently if I don't remember wrong. I cannot even see the list of plugins.

**Comment by julianlam** [comment]
Fixed via nodebb/nodebb-package-manager@c96f1ee59b04349485807ace3fcb75db16897839
