### ISSUE TITLE
submit log

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#4539]
15/4 13:41 [23042] - [31merror[39m: /topic/1697/%D8%A7%D8%B1%D8%AF%D9%DB-%D8%B7%D9%D8%A7%DB%DB-%D9%81%D8%B1%D8%A7%D8%AA-%D8%A8%D8%AD%D8%AB-%D9-%DA%AF%D9%81%D8%AA%DA%AF%D9-%D9%BE%DB%D8%B1%D8%A7%D9%D9%D9-%D8%A7%D8%B1%D8%AF%D9/21
 URIError: Failed to decode param '%D8%A7%D8%B1%D8%AF%D9%DB-%D8%B7%D9%D8%A7%DB%DB-%D9%81%D8%B1%D8%A7%D8%AA-%D8%A8%D8%AD%D8%AB-%D9-%DA%AF%D9%81%D8%AA%DA%AF%D9-%D9%BE%DB%D8%B1%D8%A7%D9%D9%D9-%D8%A7%D8%B1%D8%AF%D9'
    at decodeURIComponent (native)
    at decode_param (/home/nodeBB/forum/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/home/nodeBB/forum/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/home/nodeBB/forum/node_modules/express/lib/router/index.js:557:18)
    at next (/home/nodeBB/forum/node_modules/express/lib/router/index.js:216:15)
    at Function.handle (/home/nodeBB/forum/node_modules/express/lib/router/index.js:176:3)
    at router (/home/nodeBB/forum/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/home/nodeBB/forum/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/nodeBB/forum/node_modules/express/lib/router/index.js:312:13)
    at /home/nodeBB/forum/node_modules/express/lib/router/index.js:280:7

**Comment by sohrabafard** [comment]
15/4 13:41 [23042] - [31merror[39m: /category/92/%D8%AE%D8%AF%D9%D8%A7%D8%AA-%D8%AA%DA%A9%D9%DB%D9%DB
 URIError: Failed to decode param '%D8%AE%D8%AF%D9%D8%A7%D8%AA-%D8%AA%DA%A9%D9%DB%D9%DB'
    at decodeURIComponent (native)
    at decode_param (/home/nodeBB/forum/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/home/nodeBB/forum/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/home/nodeBB/forum/node_modules/express/lib/router/index.js:557:18)
    at next (/home/nodeBB/forum/node_modules/express/lib/router/index.js:216:15)
    at Function.handle (/home/nodeBB/forum/node_modules/express/lib/router/index.js:176:3)
    at router (/home/nodeBB/forum/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/home/nodeBB/forum/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/nodeBB/forum/node_modules/express/lib/router/index.js:312:13)
    at /home/nodeBB/forum/node_modules/express/lib/router/index.js:280:7

**Comment by sohrabafard** [comment]
19/4 01:10 [22823] - [31merror[39m: Error parsing plugins : connect ETIMEDOUT

**Comment by sohrabafard** [comment]
19/4 01:28 [22823] - [31merror[39m: Error parsing plugins : getaddrinfo ENOTFOUND packages.nodebb.org

**Comment by sohrabafard** [comment]
19/4 01:26 [22823] - [31merror[39m: Error parsing plugins : read ECONNRESET

**Comment by julianlam** [comment]
Do not submit logs to the bug tracker unless you have a specific issue. 

The decode error is due to express not allowing characters outside of UTF-8. It is not something we can fix.
