### ISSUE TITLE
No error thrown during ./nodebb setup if database information is incorrect

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/NodeBB#4542]
At least for redis, it just stops after this line:

`Populating database with default configs, if not already set...`

To somebody new, it might seem like the setup was completed

**Comment by barisusakli** [comment]
This is what I get with a wrong port

```
4/5 09:32 [24219] - info: Now configuring redis database:
Host IP or address of your Redis instance (127.0.0.1)
Host port of your Redis instance (6390)
Password of your Redis database
Which database to use (0..n) (1)
Configuration Saved OK
Populating database with default configs, if not already set...
4/5 09:32 [24219] - error: Error: Redis connection to 127.0.0.1:6390 failed - connect ECONNREFUSED 127.0.0.1:6390
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

**Comment by nodebb-misty** [comment]
Issue closed due to inactivity.

----

*This is an automated message. If you feel this action was in error, please comment on this issue so it can be looked at again*

**Comment by nodebb-misty** [comment]
Issue closed due to inactivity.

----

*This is an automated message. If you feel this action was in error, please comment on this issue so it can be looked at again*

**Comment by psychobunny** [comment]
Try wrong IP, the econrefused message is thrown by redis server which exists at that IP

**Comment by barisusakli** [comment]
```
Host IP or address of your Redis instance (9.9.9.9)
Host port of your Redis instance (8000)
Password of your Redis database
Which database to use (0..n) (1)
Configuration Saved OK

Populating database with default configs, if not already set...
11/5 13:43 [27796] - error: Error: Redis connection to 9.9.9.9:8000 failed - connect ENETUNREACH 9.9.9.9:8000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

:laughing:

**Comment by julianlam** [comment]
:laughing: See you in two weeks, @nodebb-misty

**Comment by psychobunny** [comment]
Lmao. Probably a windows only bug. Need a new label for that
