### ISSUE TITLE
Custom home page cannot be ajaxified into if "custom"

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#4551]
I set it to `/home`, which was a route introduced by [custom-pages](https://github.com/psychobunny/nodebb-plugin-custom-pages), and ajaxifying to it does not work.

**Comment by julianlam** [comment]
Turns out the custom route doesn't need a `/` in front of it. Removed on parse :+1:

**Comment by rbeer** [comment]
Firing up the debugger to investigate further, but I think you broke something. :hushed: 

```
20/4 21:43 [10146] - error: /api/
 TypeError: Cannot read property 'replace' of undefined
    at Controllers.home (/var/wwn/NodeBB/dev/src/controllers/index.js:33:69)
    at Layer.handle [as handle_request] (/var/wwn/NodeBB/dev/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/wwn/NodeBB/dev/node_modules/express/lib/router/route.js:131:13)
    at /var/wwn/NodeBB/dev/src/middleware/middleware.js:101:3
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/var/wwn/NodeBB/dev/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/var/wwn/NodeBB/dev/node_modules/async/lib/async.js:209:22)
    at middleware.pluginHooks (/var/wwn/NodeBB/dev/src/middleware/middleware.js:97:8)
    at Layer.handle [as handle_request] (/var/wwn/NodeBB/dev/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/wwn/NodeBB/dev/node_modules/express/lib/router/route.js:131:13)
20/4 21:43 [10146] - error: /
 TypeError: Cannot read property 'replace' of undefined
    at Controllers.home (/var/wwn/NodeBB/dev/src/controllers/index.js:33:69)
    at Layer.handle [as handle_request] (/var/wwn/NodeBB/dev/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/wwn/NodeBB/dev/node_modules/express/lib/router/route.js:131:13)
    at /var/wwn/NodeBB/dev/src/middleware/middleware.js:101:3
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/var/wwn/NodeBB/dev/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/var/wwn/NodeBB/dev/node_modules/async/lib/async.js:209:22)
    at middleware.pluginHooks (/var/wwn/NodeBB/dev/src/middleware/middleware.js:97:8)
    at Layer.handle [as handle_request] (/var/wwn/NodeBB/dev/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/wwn/NodeBB/dev/node_modules/express/lib/router/route.js:131:13)
```

**Comment by rbeer** [comment]
Yup; if you never set the custom route, `meta.config.homePageCustom` would be `undefined`, resulting in above error. Setting it once creates the entry in the storage, so even *deleting* (i.e. setting config:homePageCustom to '') the value solves it. Maybe creating the empty field in the DB is better than changing to `(meta.config.homePageCustom && meta.config.homePageCustom.replace(/^\/+/, ''))` (which solves the problem).

**Comment by julianlam** [comment]
:frowning:

**Comment by julianlam** [comment]
> Maybe creating the empty field in the DB is better than changing...

Right, that would be fine except it would break existing installs, but will do.

**Comment by julianlam** [comment]
66dd790

**Comment by rbeer** [comment]
LGTM :+1:

**Comment by julianlam** [comment]
:100: Thanks @rbeer
