### ISSUE TITLE
/home route dying / latest change to teasers

### ISSUE THREAD

**Issue by rbeer** [NodeBB/NodeBB#4578]
@julianlam  strikes again :stuck_out_tongue_winking_eye: 
```
error: TypeError: callback is not a function
    at Topics.getTeasers (/var/wwn/NodeBB/dev/src/topics/teaser.js:18:11)
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:760:23
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:166:37
    at fn (/var/wwn/NodeBB/dev/node_modules/async/lib/async.js:746:34)
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:1213:16
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:166:37
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:706:43
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:167:37
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:1209:30
    at Multi.callback (/var/wwn/NodeBB/dev/src/database/redis/hash.js:66:4)
```
`arguments` of Topics.getTeasers
```
{ '0': undefined,
  '1': 
   [ { tid: '30',
       mainPid: '104',
       slug: '30/smoothshorts-one-click-style-d',
       title: 'SmoothShorts - one click style! :D',
       teaserPid: null,
       cid: '2',
       postcount: '1' },
     { tid: '31',
       mainPid: '105',
       slug: '31/testing-smoothshorts-refactor',
       title: 'testing smoothshorts refactor',
       teaserPid: null,
       cid: '4',
       postcount: '1' } ],
  '2': [Function] }
```
, coming from *categories/recentreplies.js*.getTopics:108
`async.apply(topics.getTeasers, topicData),`

Didn't step it through and stopped digging at *redis/hash.js*.getObjectsFields, but I think there's a possible `err` as first argument. :)

---
NodeBB/NodeBB@8eaff14
GNU/Linux Debian, NodeJS v5.10.1, Chrome 50.0.2661.86

**Comment by julianlam** [comment]
Thanks :smile:

**Comment by julianlam** [comment]
My bad, let me know if that does it.

**Comment by rbeer** [comment]
```
error: TypeError: Cannot read property '2' of undefined
    at /var/wwn/NodeBB/dev/src/categories/recentreplies.js:112:29
    at Array.forEach (native)
    at /var/wwn/NodeBB/dev/src/categories/recentreplies.js:110:13
    at fn (/var/wwn/NodeBB/dev/node_modules/async/lib/async.js:746:34)
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:1213:16
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:166:37
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:706:43
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:167:37
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:1209:30
    at /var/wwn/NodeBB/dev/node_modules/async/lib/async.js:52:16
```
:crying_cat_face: :

**Comment by julianlam** [comment]
There :smile:

**Comment by rbeer** [comment]
Haha :clap: 

Just got the same figured, just as `tdata`. I was off with the `err` suspicion. `var topicData` :wink: 

Works fine now, thanks!
