### ISSUE TITLE
Installation setup: Admin password length

### ISSUE THREAD

**Issue by TheFurrow** [NodeBB/NodeBB#4623]
While installation setup, I noticed that there is no indicator to show is password long enough to complete installation. Now it does complete installation with error in back-end: 

1. 11/5 09:40 [9472] - info: Now configuring mongo database:
1. Configuration Saved OK
1. 11/5 09:40 [9472] - warn: You have no mongo password setup!
1. 11/5 09:40 [9472] - info: [database] Checking database indices.
1. Populating database with default configs, if not already set...
1. Enabling default theme: nodebb-theme-persona
1. No categories found, populating instance with default categories
1. 11/5 09:40 [9472] - warn: No administrators have been detected, running initial user setup

1. 11/5 09:40 [9472] - warn: NodeBB Setup Aborted.
1.  Error: [[user:change_password_error_length]]
 1.     at Object.User.isPasswordValid (F:\git\Private\NodeBB\src\user\create.js:193:20)
   1.      at async.parallel.passwordValid (F:\git\Private\NodeBB\src\user\create.js:165:11)
   1.      at F:\git\Private\NodeBB\node_modules\async\lib\async.js:718:13
   1.      at async.forEachOf.async.eachOf (F:\git\Private\NodeBB\node_modules\async\lib\async.js:233:13)
    1.     at _parallel (F:\git\Private\NodeBB\node_modules\async\lib\async.js:717:9)
    1.     at Object.async.parallel (F:\git\Private\NodeBB\node_modules\async\lib\async.js:731:9)
   1.      at Object.User.isDataValid (F:\git\Private\NodeBB\src\user\create.js:152:9)
    1.     at Object.User.create (F:\git\Private\NodeBB\src\user\create.js:22:8)
   1.      at async.waterfall.adminUid (F:\git\Private\NodeBB\src\install.js:275:11)
   1.      at fn (F:\git\Private\NodeBB\node_modules\async\lib\async.js:746:34)
   1.      at F:\git\Private\NodeBB\node_modules\async\lib\async.js:1213:16
   1.      at F:\git\Private\NodeBB\node_modules\async\lib\async.js:166:37
   1.      at F:\git\Private\NodeBB\node_modules\async\lib\async.js:706:43
   1.      at F:\git\Private\NodeBB\node_modules\async\lib\async.js:167:37
    1.     at Object.async.waterfall (F:\git\Private\NodeBB\node_modules\async\lib\async.js:710:44)
    1.     at success (F:\git\Private\NodeBB\src\install.js:273:10)

And the result of installation is: completed installation, unable to log in as admin but capable to register as new user.

Pulled from master 05/11/2016 GMT+2 9:40 AM

**Comment by barisusakli** [comment]
Hmm if there is an error during admin user creation due to a short password the admin user shouldn't be created. Did you check if the admin user was created after that error?

**Comment by pichalite** [comment]
I think what he means to say is that you will be able to start the forum normally even though the admin user creation fails. admin user does not get created but everything else runs fine when you do `./nodebb start`

**Comment by nodebb-misty** [comment]
Issue closed due to inactivity.

----

*This is an automated message. If you feel this action was in error, please comment on this issue so it can be looked at again*
