### ISSUE TITLE
Crashed when after startup!

### ISSUE THREAD

**Issue by Xuchenhao** [NodeBB/NodeBB#4705]
```
29/5 19:09 [27529] - info: Time: Sun May 29 2016 19:09:57 GMT+0800 (CST)
29/5 19:09 [27529] - info: Initializing NodeBB v1.0.3
29/5 19:10 [27529] - info: [plugins/emoji-one] Initial startup detected. Downloading emojione assets...

29/5 19:10 [27529] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-theme-lavender

29/5 19:10 [27529] - info: NodeBB Ready
29/5 19:10 [27529] - info: Enabling 'trust proxy'
29/5 19:10 [27529] - info: NodeBB is now listening on: 0.0.0.0:4567
29/5 19:38 [27529] - error: /register
 invalid csrf token
29/5 20:01 [27529] - error: /register
 invalid csrf token
29/5 20:01 [27529] - error: /login
 invalid csrf token
29/5 20:08 [27529] - error: /register
 invalid csrf token
29/5 20:08 [27529] - error: /login
 invalid csrf token
29/5 20:12 [27529] - error: /register
 invalid csrf token
29/5 22:01 [27529] - error: /user/%C3%83%C2%A6%C3%86%E2%80%99%C3%A2%E2%82%AC%C2%A6%C3%83%C2%A6%C3%82%C2%AD%C3%85%E2%80%99%C3%83%C2%A5%C3%A2%E2%82%AC%C2%9D%C3%82%C2%B1%C3%83%C2%A6%C3%A2%E2%80%9E%C2%A2%C3%85%C2%A1
 TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at ServerResponse.header (/home/nodebb/node_modules/express/lib/response.js:718:10)
    at ServerResponse.location (/home/nodebb/node_modules/express/lib/response.js:835:8)
    at ServerResponse.redirect (/home/nodebb/node_modules/express/lib/response.js:874:8)
    at profileController.get (/home/nodebb/src/controllers/accounts/profile.js:24:15)
    at Layer.handle [as handle_request] (/home/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nodebb/node_modules/express/lib/router/route.js:131:13)
    at /home/nodebb/src/middleware/middleware.js:101:3
    at /home/nodebb/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/home/nodebb/node_modules/async/lib/async.js:236:30)
29/5 22:02 [27529] - error: /register
 invalid csrf token
29/5 22:17 [27529] - error: /register
 invalid csrf token
29/5 22:17 [27529] - error: /login
 invalid csrf token
29/5 22:49 [27529] - error: /register
 invalid csrf token
29/5 22:53 [27529] - error: /login
 invalid csrf token
29/5 22:53 [27529] - error: Error: spawn ENOMEM
    at exports._errnoException (util.js:953:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:372:9)
    at exports.fork (child_process.js:54:10)
    at forkChild (/home/nodebb/src/password.js:15:15)
    at Object.module.compare (/home/nodebb/src/password.js:11:3)
    at /home/nodebb/src/controllers/authentication.js:288:13
    at fn (/home/nodebb/node_modules/async/lib/async.js:746:34)
    at /home/nodebb/node_modules/async/lib/async.js:1213:16
    at /home/nodebb/node_modules/async/lib/async.js:166:37
Error: spawn ENOMEM
    at exports._errnoException (util.js:953:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:372:9)
    at exports.fork (child_process.js:54:10)
    at forkChild (/home/nodebb/src/password.js:15:15)
    at Object.module.compare (/home/nodebb/src/password.js:11:3)
    at /home/nodebb/src/controllers/authentication.js:288:13
    at fn (/home/nodebb/node_modules/async/lib/async.js:746:34)
    at /home/nodebb/node_modules/async/lib/async.js:1213:16
    at /home/nodebb/node_modules/async/lib/async.js:166:37
29/5 22:53 [27529] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
29/5 22:53 [27529] - info: [app] Database connection closed.
29/5 22:53 [27529] - info: [app] Web server closed to connections.
29/5 22:53 [27529] - info: [app] Shutdown complete.
[cluster] Child Process (27529) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
29/5 22:53 [1754] - info: Time: Sun May 29 2016 22:53:23 GMT+0800 (CST)
29/5 22:53 [1754] - info: Initializing NodeBB v1.0.3
29/5 22:53 [1754] - info: [plugins/emoji-one] Initial startup detected. Downloading emojione assets...

29/5 22:53 [1754] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-theme-lavender

29/5 22:54 [1754] - info: NodeBB Ready
29/5 22:54 [1754] - info: Enabling 'trust proxy'
29/5 22:54 [1754] - info: NodeBB is now listening on: 0.0.0.0:4567
[cluster] Child Process (1754) has exited (code: null, signal: SIGKILL)
[cluster] Spinning up another process...
29/5 22:54 [1924] - info: Time: Sun May 29 2016 22:54:56 GMT+0800 (CST)
29/5 22:54 [1924] - info: Initializing NodeBB v1.0.3
29/5 22:55 [1924] - info: [plugins/emoji-one] Initial startup detected. Downloading emojione assets...

29/5 22:55 [1924] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-theme-lavender

```

**Comment by julianlam** [comment]
Your server ran out of memory.
