### ISSUE TITLE
Crashing on Malformed URI

### ISSUE THREAD

**Issue by boomzillawtf** [NodeBB/NodeBB#4717]
Our server crashed on this today:

```
2/6 09:08 [51] - error: URIError: URI malformed
    at decodeURIComponent (native)
    at Url.parse (url.js:195:19)
    at Object.urlParse [as parse] (url.js:84:5)
    at Object.Posts.relativeToAbsolute (/usr/src/app/src/posts/parse.js:55:18)
    at /usr/src/app/src/posts/parse.js:33:34
    at /usr/src/app/src/plugins/hooks.js:141:4
    at /usr/src/app/node_modules/async/lib/async.js:380:13
    at /usr/src/app/node_modules/async/lib/async.js:52:16
    at /usr/src/app/node_modules/async/lib/async.js:269:32
    at /usr/src/app/node_modules/async/lib/async.js:44:16
    at /usr/src/app/node_modules/async/lib/async.js:377:17
    at /usr/src/app/node_modules/nodebb-plugin-iframely/library.js:84:11
    at /usr/src/app/node_modules/nodebb-plugin-iframely/library.js:262:4
    at /usr/src/app/node_modules/async/lib/async.js:52:16
    at Immediate._onImmediate (/usr/src/app/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
URIError: URI malformed
    at decodeURIComponent (native)
    at Url.parse (url.js:195:19)
    at Object.urlParse [as parse] (url.js:84:5)
    at Object.Posts.relativeToAbsolute (/usr/src/app/src/posts/parse.js:55:18)
    at /usr/src/app/src/posts/parse.js:33:34
    at /usr/src/app/src/plugins/hooks.js:141:4
    at /usr/src/app/node_modules/async/lib/async.js:380:13
    at /usr/src/app/node_modules/async/lib/async.js:52:16
    at /usr/src/app/node_modules/async/lib/async.js:269:32
    at /usr/src/app/node_modules/async/lib/async.js:44:16
    at /usr/src/app/node_modules/async/lib/async.js:377:17
    at /usr/src/app/node_modules/nodebb-plugin-iframely/library.js:84:11
    at /usr/src/app/node_modules/nodebb-plugin-iframely/library.js:262:4
    at /usr/src/app/node_modules/async/lib/async.js:52:16
    at Immediate._onImmediate (/usr/src/app/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
2/6 09:08 [51] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2/6 09:08 [51] - error: [plugins] filter:parse.post,  server wtdwtf-mongo:27017 sockets closed
2/6 09:08 [51] - error: /topic/5338/multiple-wtf/1
```

The problem is a mailto link:

`<a href="mailto:anoy%*@(*&amp;#...&lt;NO">anoy%*@(*&amp;#...&lt;NO</a>`

**Comment by julianlam** [comment]
Hey @boomzillawtf -- is this happening without IFramely?

**Comment by boomzillawtf** [comment]
Yes. iFramely just happened to be in the chain. I can reproduce this without it being enabled.

**Comment by julianlam** [comment]
Thanks for confirming

**Comment by barisusakli** [comment]
@boomzillawtf what was the raw post content?

I was only able to crash that method by explicitly calling `url.parse('mailto:anoy%*@(*&amp;#...&lt;NO');` which I fixed in the above commit.

**Comment by boomzillawtf** [comment]
@barisusakli I just did this again. The post I had was simply:

```
@boomzilla
<a href="mailto:anoy%*@(*&amp;#...&lt;NO">anoy%*@(*&amp;#...&lt;NO</a>
```

It was crashing after passing through my youtube-lite plugin, so I disabled that.
Then it was crashing after the mentions plugin, so I disabled that.
Then it was crashing after the emoji plugin...
```
3/6 05:24 [20731] - error: URIError: URI malformed
    at decodeURIComponent (native)
    at Url.parse (url.js:195:19)
    at Object.urlParse [as parse] (url.js:84:5)
    at Object.Posts.relativeToAbsolute (/home/boomzilla/nodebb/src/posts/parse.js:58:18)
    at /home/boomzilla/nodebb/src/posts/parse.js:33:34
    at /home/boomzilla/nodebb/src/plugins/hooks.js:143:4
    at /home/boomzilla/nodebb/node_modules/async/lib/async.js:380:13
    at /home/boomzilla/nodebb/node_modules/async/lib/async.js:52:16
    at /home/boomzilla/nodebb/node_modules/async/lib/async.js:269:32
    at /home/boomzilla/nodebb/node_modules/async/lib/async.js:44:16
    at /home/boomzilla/nodebb/node_modules/async/lib/async.js:377:17
    at Object.parsePost [as method] (/home/boomzilla/nodebb/node_modules/nodebb-plugin-emoji-extended/lib/controller.js:46:3)
    at /home/boomzilla/nodebb/src/plugins/hooks.js:136:12
    at /home/boomzilla/nodebb/node_modules/async/lib/async.js:375:13
    at Immediate.iterate [as _onImmediate] (/home/boomzilla/nodebb/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

The value of `current`, BTW, in `relativeToAbsolute` right before the call to `url.parse(current[1])` is:
```
[ 'href="mailto:anoy%*@(*&amp;#...&lt;NO"',
  'mailto:anoy%*@(*&amp;#...&lt;NO',
  index: 24,
  input: '<p>@boomzilla</p>\n<p><a href="mailto:anoy%*@(*&amp;#...&lt;NO">anoy%<em>@(</em>&amp;#...&lt;NO</a></p>\n' ]
```

This requires having html turned on in the markdown plugin. We also use @BenLubar's html-cleaner plugin. I believe that v0.0.24 was updated to fix this problem by stripping out the invalid href.
