### ISSUE TITLE
Exception in /api/admin/advanced/database

### ISSUE THREAD

**Issue by juangl** [NodeBB/NodeBB#4725]
I get the next log when I'm trying to active new users:

```
6/6 16:12 [2425] - info: [app] Database connection closed.
6/6 16:12 [2425] - info: [app] Web server closed to connections.
6/6 16:12 [2425] - info: [app] Shutdown complete.
[cluster] Child Process (2425) has exited (code: 0, signal: null)
6/6 16:12 [2511] - info: Time: Mon Jun 06 2016 16:12:47 GMT-0500 (CDT)
6/6 16:12 [2511] - info: Initializing NodeBB v1.0.3
6/6 16:12 [2511] - info: [database] Checking database indices.
6/6 16:12 [2511] - warn: [socket.io] Clustering detected, you are advised to configure Redis as a websocket store.
6/6 16:12 [2511] - info: NodeBB Ready
6/6 16:12 [2511] - info: Enabling 'trust proxy'
6/6 16:12 [2511] - info: NodeBB is now listening on: 0.0.0.0:4567
6/6 16:22 [2511] - error: /api/admin/advanced/database
 MongoError: not authorized on nodebb to execute command { serverStatus: 1 }
    at Function.MongoError.create (/home/jn/nodebb/node_modules/mongodb-core/lib/error.js:31:11)
    at commandCallback (/home/jn/nodebb/node_modules/mongodb-core/lib/topologies/server.js:1239:66)
    at Callbacks.emit (/home/jn/nodebb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at .messageHandler (/home/jn/nodebb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
    at Socket.<anonymous> (/home/jn/nodebb/node_modules/mongodb-core/lib/connection/connection.js:302:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
6/6 16:29 [2511] - error: TypeError: Cannot read property 'frequency' of undefined
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at LogStream.Writable.write (_stream_writable.js:217:5)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:542:20)

```

**Comment by julianlam** [comment]
Hi @juangl -- this is due to the user in MongoDB not having the proper privileges to view database statistics.

**Comment by julianlam** [comment]
However I do think we should handle this error gracefully, so it is a bug nevertheless.

**Comment by barisusakli** [comment]
Looks like a different error, `.frequency` is only used in the registration part.

https://github.com/NodeBB/NodeBB/blob/master/src/user/approval.js#L183

Seems like body is empty there. Just to clarify you get a crash when you try to approve new users, but no crash(just a log because of mongodb permissions) when you go to `/admin/advanced/database`?

**Comment by juangl** [comment]
Yes. That's exactly what happens.
