### ISSUE TITLE
502 When trying to login through any of steam sso plugin

### ISSUE THREAD

**Issue by jffz** [NodeBB/NodeBB#4777]
i triied some steam login plugins, both were working, but after i deleted one user, i'm always redirected to nginx / 502 when i try to login / register with a steam account

Logs : 

````
22/6 10:27 [20849] - error: TypeError: params.hasOwnProperty is not a function
    at _checkSignatureUsingProvider (/opt/nodebb/node_modules/openid/openid.js:1148:15)
    at _checkSignature (/opt/nodebb/node_modules/openid/openid.js:1083:5)
    at _verifyAssertionAgainstProviders (/opt/nodebb/node_modules/openid/openid.js:1047:12)
    at /opt/nodebb/node_modules/openid/openid.js:1012:7
    at /opt/nodebb/node_modules/openid/openid.js:545:7
    at /opt/nodebb/node_modules/openid/openid.js:411:16
    at Request._callback (/opt/nodebb/node_modules/openid/openid.js:174:7)
    at Request.self.callback (/opt/nodebb/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/opt/nodebb/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/opt/nodebb/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
TypeError: params.hasOwnProperty is not a function
    at _checkSignatureUsingProvider (/opt/nodebb/node_modules/openid/openid.js:1148:15)
    at _checkSignature (/opt/nodebb/node_modules/openid/openid.js:1083:5)
    at _verifyAssertionAgainstProviders (/opt/nodebb/node_modules/openid/openid.js:1047:12)
    at /opt/nodebb/node_modules/openid/openid.js:1012:7
    at /opt/nodebb/node_modules/openid/openid.js:545:7
    at /opt/nodebb/node_modules/openid/openid.js:411:16
    at Request._callback (/opt/nodebb/node_modules/openid/openid.js:174:7)
    at Request.self.callback (/opt/nodebb/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/opt/nodebb/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/opt/nodebb/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
22/6 10:27 [20849] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
22/6 10:27 [20849] - info: [app] Database connection closed.
22/6 10:27 [20849] - info: [app] Web server closed to connections.
22/6 10:27 [20849] - info: [app] Shutdown complete.
[cluster] Child Process (20849) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
````

Thanks guys

**Comment by pichalite** [comment]
@jffz that's probably a problem with the plugin. post the issue on the plugins github repo. 3rd party plugin issues can't be fixed here.

**Comment by jffz** [comment]
So there is no "builtin" feature to allow steamlogin ?
