### ISSUE TITLE
Unable to logout - unknown command 'del'

### ISSUE THREAD

**Issue by Pascal666** [NodeBB/NodeBB#4839]
NodeBB v1.0.3
git hash: 61404be94b1ad0487256065a4030c1a9df8b54cd

12/7 00:58 [10900] - ^[[31merror^[[39m: /logout
 Error: ERR unknown command 'del'
    at JavascriptReplyParser._parseResult (/home/nodebb/nodebb/node_modules/redis/lib/parsers/javascript.js:43:16)
    at JavascriptReplyParser.try_parsing (/home/nodebb/nodebb/node_modules/redis/lib/parsers/javascript.js:114:21)
    at JavascriptReplyParser.run (/home/nodebb/nodebb/node_modules/redis/lib/parsers/javascript.js:135:22)
    at JavascriptReplyParser.execute (/home/nodebb/nodebb/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/home/nodebb/nodebb/node_modules/redis/index.js:131:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

**Comment by julianlam** [comment]
Hi @Pascal666, does this issue persist on the latest NodeBB version (`master` branch)?

**Comment by Pascal666** [comment]
My guess would be yes, as "nodebb upgrade" gives the same error:

$ ./nodebb upgrade
1. Bringing base dependencies up to date... OK
2. Checking installed plugins for updates... OK
3. Updating NodeBB data store schema...
12/7 15:51 [13788] - info: Beginning database schema update
12/7 15:51 [13788] - info: [2015/12/15] Chats upgrade skipped!
12/7 15:51 [13788] - info: [2015/12/23] Chats room hashes upgrade skipped!
12/7 15:51 [13788] - info: [2015/12/23] Adding theme to active plugins sorted set skipped!
12/7 15:51 [13788] - info: [2016/01/14] Creating user best post sorted sets skipped!
12/7 15:51 [13788] - info: [2016/01/20] Creating users:notvalidated skipped!
12/7 15:51 [13788] - info: [2016/01/23] Creating Global moderators group skipped!
12/7 15:51 [13788] - info: [2016/02/25] Social: Post Sharing skipped!
12/7 15:51 [13788] - info: [2016/04/14] Group title from settings to user profile
12/7 15:51 [13788] - info: upgraded 0 users
12/7 15:51 [13788] - info: [2016/04/14] Group title from settings to user profile done
12/7 15:51 [13788] - info: [2016/04/19] Users post count per tid
12/7 15:51 [13788] - info: upgraded 0 topics
12/7 15:51 [13788] - error: [upgrade] Errors were encountered while updating the NodeBB schema: ERR unknown command 'del'
OK

                            NodeBB Upgrade Complete!

**Comment by Pascal666** [comment]
Sorry, my fault.  The NodeBB installation guide I followed linked to a hardening Redis guide.  One of the lines of the sample redis.conf was 'rename-command DEL ""'.  Nodebb works fine once I remove that.

**Comment by julianlam** [comment]
Thanks @Pascal666 for following up once you've found a resolution :smile: Hopefully this will help others who stumble upon this error.
