### ISSUE TITLE
[1.1.0] Setup with MongoDB doesn't save password. 

### ISSUE THREAD

**Issue by NaGeL182** [NodeBB/NodeBB#4865]
* v1.1.0 - 296dc77c7bb2bbf92f711089d77e4f32f729951f
* Exact steps to cause this issue
    1. Install new instance of NobeBB
    2. Set up MongoDB 3.2.x with: 
```
security:  
  authorization: enabled
```
and a database with user and password
    3. Initiate NodeBB setup with MongoDB database, give user and password.
    4. Finish the setup and restart
* What you expected
    * A working copy of Nodebb
* What happened instead
    * Got the Following Error:

```
$ ./nodebb dev

NodeBB v1.1.0 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

19/7 18:02 [13309] - verbose: * using configuration stored in: /home/nagel/workspace/nodejs/nodebb/config.json
19/7 18:02 [13309] - info: Time: Tue Jul 19 2016 18:02:05 GMT+0200 (CEST)
19/7 18:02 [13309] - info: Initializing NodeBB v1.1.0
19/7 18:02 [13309] - verbose: * using mongo store at 127.0.0.1:27017
19/7 18:02 [13309] - verbose: * using themes stored in: /home/nagel/workspace/nodejs/nodebb/node_modules
19/7 18:02 [13309] - warn: You have no mongo password setup!
19/7 18:02 [13309] - info: [database] Checking database indices.
Unhandled rejection MongoError: not authorized on nodebb to execute command { listIndexes: "sessions", cursor: {} }
    at Function.MongoError.create (/home/nagel/workspace/nodejs/nodebb/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/nagel/workspace/nodejs/nodebb/node_modules/mongodb-core/lib/cursor.js:200:36)
    at Callbacks.emit (/home/nagel/workspace/nodejs/nodebb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at .messageHandler (/home/nagel/workspace/nodejs/nodebb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
    at Socket.<anonymous> (/home/nagel/workspace/nodejs/nodebb/node_modules/mongodb-core/lib/connection/connection.js:302:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
From previous event:
    at MongoStore.setAutoRemoveAsync (/home/nagel/workspace/nodejs/nodebb/node_modules/connect-mongo/src-es5/index.js:152:48)
    at MongoStore.handleNewConnectionAsync (/home/nagel/workspace/nodejs/nodebb/node_modules/connect-mongo/src-es5/index.js:141:79)
    at new MongoStore (/home/nagel/workspace/nodejs/nodebb/node_modules/connect-mongo/src-es5/index.js:116:27)
    at /home/nagel/workspace/nodejs/nodebb/src/database/mongo.js:109:27
    at /home/nagel/workspace/nodejs/nodebb/node_modules/mongodb/lib/mongo_client.js:406:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

19/7 18:02 [13309] - error: Error creating index not authorized on nodebb to execute command { listIndexes: "objects", cursor: {} }
19/7 18:02 [13309] - error: MongoError: not authorized on nodebb to execute command { listIndexes: "objects", cursor: {} }
    at Function.MongoError.create (/home/nagel/workspace/nodejs/nodebb/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/nagel/workspace/nodejs/nodebb/node_modules/mongodb-core/lib/cursor.js:200:36)
    at Callbacks.emit (/home/nagel/workspace/nodejs/nodebb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at .messageHandler (/home/nagel/workspace/nodejs/nodebb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
    at Socket.<anonymous> (/home/nagel/workspace/nodejs/nodebb/node_modules/mongodb-core/lib/connection/connection.js:302:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
[cluster] Child Process (13309) has exited (code: 0, signal: null)
```

Checked the `config.json` after the error and i saw this:

```
{
    "url": "http://localhost:4567",
    "secret": "sssh-its-a-secret",
    "database": "mongo",
    "port": 4567,
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "user",
        "database": "nodebb"
    }
}
```
it was missing the `password` line. after i added it. it worked fine.

**Comment by nodebb-misty** [comment]
Issue closed due to inactivity.

----

*This is an automated message. If you feel this action was in error, please comment on this issue so it can be looked at again*

**Comment by julianlam** [comment]
Actually, haven't checked this one yet... @pichalite, can you repo?

**Comment by pichalite** [comment]
can't repro. works fine for me.

**Comment by barisusakli** [comment]
Works fine for me as well, not sure why ./nodebb setup wouldn't save the value into config.json

Can you put a `console.log(server_conf);` [here](https://github.com/NodeBB/NodeBB/blob/master/src/install.js#L539) and let us know the output.

**Comment by NaGeL182** [comment]
I used the browser and not ./nodebb setup
I might have worded all that wrongly..  i will redo this  then with logs screenshots and everything.

**Comment by pichalite** [comment]
Tried the setup with `npm start` using browser as well. Not able to reproduce.

**Comment by NaGeL182** [comment]
I did a video of me redoing my steps, and i experience the same.
here is the video
https://drive.google.com/file/d/0Bznx_V6IWGBQOUZMWUdxLUZIV2M/view?usp=sharing

**Comment by barisusakli** [comment]
I have tracked it down to https://github.com/NodeBB/NodeBB/blob/master/src/install.js#L80-L83, looks like the setup values are not passed to the main application from the web installer.
