### ISSUE TITLE
async lib error

### ISSUE THREAD

**Issue by ralic** [NodeBB/NodeBB#4892]
Please include the following information when submitting a bug report/issue:

NodeBB v1.1.0
* Exact steps to cause this issue
1. node nodebb dev 
2. error message

26/7 18:08 [27582] - error: TypeError: Cannot read property 'split' of undefined
    at Object.Plugins.registerHook (/home/ec2-user/newTHAA/src/plugins/hooks.js:37:25)
    at /home/ec2-user/newTHAA/src/plugins/load.js:93:14
    at /home/ec2-user/newTHAA/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/home/ec2-user/newTHAA/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/home/ec2-user/newTHAA/node_modules/async/lib/async.js:209:22)
    at registerHooks (/home/ec2-user/newTHAA/src/plugins/load.js:92:11)
    at /home/ec2-user/newTHAA/src/plugins/load.js:31:6
    at /home/ec2-user/newTHAA/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/home/ec2-user/newTHAA/node_modules/async/lib/async.js:233:13)
    at _parallel (/home/ec2-user/newTHAA/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/home/ec2-user/newTHAA/node_modules/async/lib/async.js:731:9)
    at /home/ec2-user/newTHAA/src/plugins/load.js:29:10
    at /home/ec2-user/newTHAA/src/plugins/load.js:291:5
    at /home/ec2-user/newTHAA/node_modules/async/lib/async.js:726:13
    at /home/ec2-user/newTHAA/node_modules/async/lib/async.js:52:16
    at done (/home/ec2-user/newTHAA/node_modules/async/lib/async.js:246:17)
    at /home/ec2-user/newTHAA/node_modules/async/lib/async.js:44:16
    at /home/ec2-user/newTHAA/node_modules/async/lib/async.js:723:17
    at /home/ec2-user/newTHAA/node_modules/async/lib/async.js:167:37
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

Thank you!

**Comment by barisusakli** [comment]
Do you have any non-bundled plugins activated?
