### ISSUE TITLE
Nodebb crash 1.1.2 on user account information page

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4939]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.1.2
* Exact steps to cause this issue
    1. I sent a test report to one user
    2. Then, I clicked user account information to see the flags
* What you expected
    * to work :D
* What happened instead
    * crash

13/8 01:29 [12329] - error: RangeError: Invalid time value
    at Date.toISOString (native)
    at /volume1/web/nodebb/nodebb/src/user/info.js:43:53
    at Array.map (native)
    at /volume1/web/nodebb/nodebb/src/user/info.js:40:29
    at Multi.callback (/volume1/web/nodebb/nodebb/src/database/redis/hash.js:66:4)
    at Multi.execute_callback (/volume1/web/nodebb/nodebb/node_modules/redis/index.js:1224:14)
    at Command.callback (/volume1/web/nodebb/nodebb/node_modules/redis/index.js:1169:14)
    at RedisClient.return_reply (/volume1/web/nodebb/nodebb/node_modules/redis/index.js:664:25)
    at JavascriptReplyParser.reply_parser.send_reply (/volume1/web/nodebb/nodebb/node_modules/redis/index.js:332:14)
    at JavascriptReplyParser.run (/volume1/web/nodebb/nodebb/node_modules/redis/lib/parsers/javascript.js:132:18)
    at JavascriptReplyParser.execute (/volume1/web/nodebb/nodebb/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/volume1/web/nodebb/nodebb/node_modules/redis/index.js:131:27)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
RangeError: Invalid time value
    at Date.toISOString (native)
    at /volume1/web/nodebb/nodebb/src/user/info.js:43:53
    at Array.map (native)
    at /volume1/web/nodebb/nodebb/src/user/info.js:40:29
    at Multi.callback (/volume1/web/nodebb/nodebb/src/database/redis/hash.js:66:4)
    at Multi.execute_callback (/volume1/web/nodebb/nodebb/node_modules/redis/index.js:1224:14)
    at Command.callback (/volume1/web/nodebb/nodebb/node_modules/redis/index.js:1169:14)
    at RedisClient.return_reply (/volume1/web/nodebb/nodebb/node_modules/redis/index.js:664:25)
    at JavascriptReplyParser.reply_parser.send_reply (/volume1/web/nodebb/nodebb/node_modules/redis/index.js:332:14)
    at JavascriptReplyParser.run (/volume1/web/nodebb/nodebb/node_modules/redis/lib/parsers/javascript.js:132:18)
    at JavascriptReplyParser.execute (/volume1/web/nodebb/nodebb/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/volume1/web/nodebb/nodebb/node_modules/redis/index.js:131:27)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
13/8 01:29 [12329] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.

Thank you!

**Comment by MegaGM** [comment]
The same error should occur when a user is banned or was banned and you try to go to the user's account information page.
