### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by bubbleatgit** [NodeBB/NodeBB#4947]
Nodebb Version :  v1.1.3-auto.0
git hash : 69f9c7fc41a1f6cbec37f3c86a86288eb0ddf1c9
Database: Redis server v=3.0.7 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=869e89100d5ea8c2

## ErrorInfo
```
16/8 10:52 [1946] - error: TypeError: Cannot read property 'length' of undefined
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at LogStream.Writable.write (_stream_writable.js:211:5)
    at Socket.ondata (_stream_readable.js:542:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:536:20)
```

**Comment by barisusakli** [comment]
Do you have reproduction steps?

**Comment by lo1tuma** [comment]
This might be related to callback errors not being handled in some places. So there might be an error which gets swallowed silently and then some callback tries to access data which is not present due to the previous error. See also: #4951.

**Comment by nodebb-misty** [comment]
Issue closed due to inactivity.

----

*This is an automated message. If you feel this action was in error, please comment on this issue so it can be looked at again*
