### ISSUE TITLE
flag page crash

### ISSUE THREAD

**Issue by exomarty** [NodeBB/NodeBB#4981]
Please include the following information when submitting a bug report/issue:

* NodeBB 1.1.2
* Database (mongo
* Exact steps to cause this issue
    1. search user flags
* What happened instead
    * server crash, it only happens with some users...

```
26/8 19:22 [4400] - [31merror[39m: TypeError: This library (validator.js) validates strings only
    at assertString (/var/foroexodo/nodebb/node_modules/validator/lib/util/assertString.js:9:11)
    at Object.escape (/var/foroexodo/nodebb/node_modules/validator/lib/escape.js:15:34)
    at /var/foroexodo/nodebb/src/posts/summary.js:120:30
    at Array.map (native)
    at /var/foroexodo/nodebb/src/posts/summary.js:118:22
    at /var/foroexodo/nodebb/src/database/mongo/hash.js:136:4
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:849:16
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
    at setCursorDeadAndNotified (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:553:3)
    at nextFunction (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:732:7)
    at Cursor.next [as _next] (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:773:3)
    at fetchDocs (/var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:845:10)
    at /var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:868:7
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
    at nextFunction (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:763:5)
TypeError: This library (validator.js) validates strings only
    at assertString (/var/foroexodo/nodebb/node_modules/validator/lib/util/assertString.js:9:11)
    at Object.escape (/var/foroexodo/nodebb/node_modules/validator/lib/escape.js:15:34)
    at /var/foroexodo/nodebb/src/posts/summary.js:120:30
    at Array.map (native)
    at /var/foroexodo/nodebb/src/posts/summary.js:118:22
    at /var/foroexodo/nodebb/src/database/mongo/hash.js:136:4
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:849:16
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
    at setCursorDeadAndNotified (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:553:3)
    at nextFunction (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:732:7)
    at Cursor.next [as _next] (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:773:3)
    at fetchDocs (/var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:845:10)
    at /var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:868:7
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
    at nextFunction (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:763:5)
26/8 19:22 [4400] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
26/8 19:22 [4400] - [31merror[39m: /posts/flags
 MongoError: server 127.0.0.1:27017 sockets closed
    at Server.destroy (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:679:47)
    at Server.close (/var/foroexodo/nodebb/node_modules/mongodb/lib/server.js:372:17)
    at Db.close (/var/foroexodo/nodebb/node_modules/mongodb/lib/db.js:334:19)
    at Object.module.close (/var/foroexodo/nodebb/src/database/mongo.js:227:6)
    at shutdown (/var/foroexodo/nodebb/app.js:311:28)
    at process.<anonymous> (/var/foroexodo/nodebb/app.js:173:3)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:224:26)
26/8 19:22 [4400] - [32minfo[39m: [app] Database connection closed.
26/8 19:22 [4400] - [32minfo[39m: [app] Web server closed to connections.
26/8 19:22 [4400] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (4400) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
26/8 19:22 [4529] - [31merror[39m: TypeError: This library (validator.js) validates strings only
    at assertString (/var/foroexodo/nodebb/node_modules/validator/lib/util/assertString.js:9:11)
    at Object.escape (/var/foroexodo/nodebb/node_modules/validator/lib/escape.js:15:34)
    at /var/foroexodo/nodebb/src/posts/summary.js:120:30
    at Array.map (native)
    at /var/foroexodo/nodebb/src/posts/summary.js:118:22
    at /var/foroexodo/nodebb/src/database/mongo/hash.js:136:4
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:849:16
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
    at setCursorDeadAndNotified (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:553:3)
    at nextFunction (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:732:7)
    at Cursor.next [as _next] (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:773:3)
    at fetchDocs (/var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:845:10)
    at /var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:868:7
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
    at nextFunction (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:763:5)
TypeError: This library (validator.js) validates strings only
    at assertString (/var/foroexodo/nodebb/node_modules/validator/lib/util/assertString.js:9:11)
    at Object.escape (/var/foroexodo/nodebb/node_modules/validator/lib/escape.js:15:34)
    at /var/foroexodo/nodebb/src/posts/summary.js:120:30
    at Array.map (native)
    at /var/foroexodo/nodebb/src/posts/summary.js:118:22
    at /var/foroexodo/nodebb/src/database/mongo/hash.js:136:4
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/lib/utils.js:96:12)
    at /var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:849:16
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
    at setCursorDeadAndNotified (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:553:3)
    at nextFunction (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:732:7)
    at Cursor.next [as _next] (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:773:3)
    at fetchDocs (/var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:845:10)
    at /var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:868:7
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:5)
    at nextFunction (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:763:5)
26/8 19:22 [4529] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
26/8 19:22 [4529] - [31merror[39m: /posts/flags
 MongoError: server 127.0.0.1:27017 sockets closed
    at Server.destroy (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:679:47)
    at Server.close (/var/foroexodo/nodebb/node_modules/mongodb/lib/server.js:372:17)
    at Db.close (/var/foroexodo/nodebb/node_modules/mongodb/lib/db.js:334:19)
    at Object.module.close (/var/foroexodo/nodebb/src/database/mongo.js:227:6)
    at shutdown (/var/foroexodo/nodebb/app.js:311:28)
    at process.<anonymous> (/var/foroexodo/nodebb/app.js:173:3)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:224:26)
26/8 19:22 [4529] - [32minfo[39m: [app] Database connection closed.
26/8 19:22 [4529] - [32minfo[39m: [app] Web server closed to connections.
26/8 19:22 [4529] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (4529) has exited (code: 1, signal: null)
```

Thank you!

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/blob/v1.1.2/src/posts/summary.js#L120

@exomarty erm... any reason why you have topics that have no titles?

**Comment by barisusakli** [comment]
He probably has a title but if is `1234` then it gets saved as a number and validator crashes on anything that is not a string.

**Comment by exomarty** [comment]
Not sure about that @juliannam never seen a topic without title :D
Actually i delete all flags and was still crashing with some user 
Before that the count flag was negative on several users
So strange because already cleared all flags a weeks ago
