### ISSUE TITLE
Crash with TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by gnimmelf** [NodeBB/NodeBB#5024]
NodeBB v1.1.2, 89f550ce7cb4cbfecdf40d73f38c773310784ef7
Mongo v3.2.9

Made my first post as an administrator, then clicked the `Administrators`-link: `/groups/administrators`

```
10/9 17:10 [28983] - error: TypeError: Cannot read property 'filter' of undefined
    at async.waterfall.posts.getPostSummaryByPids.stripTags (/opt/NodeBB/src/groups.js:366:21)
    at fn (/opt/NodeBB/node_modules/async/lib/async.js:746:34)
    at /opt/NodeBB/node_modules/async/lib/async.js:1213:16
    at /opt/NodeBB/node_modules/async/lib/async.js:166:37
    at /opt/NodeBB/node_modules/async/lib/async.js:706:43
    at /opt/NodeBB/node_modules/async/lib/async.js:167:37
    at /opt/NodeBB/node_modules/async/lib/async.js:1209:30
    at /opt/NodeBB/src/database/mongo/sorted.js:159:5
    at handleCallback (/opt/NodeBB/node_modules/mongodb/lib/utils.js:96:12)
    at /opt/NodeBB/node_modules/mongodb/lib/cursor.js:839:16
    at handleCallback (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at setCursorDeadAndNotified (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:501:3)
    at nextFunction (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:652:7)
    at Cursor.next [as _next] (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:693:3)
    at fetchDocs (/opt/NodeBB/node_modules/mongodb/lib/cursor.js:835:10)
    at /opt/NodeBB/node_modules/mongodb/lib/cursor.js:858:7
    at handleCallback (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at nextFunction (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:683:5)
    at /opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:7
    at queryCallback (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:220:18)
    at Callbacks.emit (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
TypeError: Cannot read property 'filter' of undefined
    at async.waterfall.posts.getPostSummaryByPids.stripTags (/opt/NodeBB/src/groups.js:366:21)
    at fn (/opt/NodeBB/node_modules/async/lib/async.js:746:34)
    at /opt/NodeBB/node_modules/async/lib/async.js:1213:16
    at /opt/NodeBB/node_modules/async/lib/async.js:166:37
    at /opt/NodeBB/node_modules/async/lib/async.js:706:43
    at /opt/NodeBB/node_modules/async/lib/async.js:167:37
    at /opt/NodeBB/node_modules/async/lib/async.js:1209:30
    at /opt/NodeBB/src/database/mongo/sorted.js:159:5
    at handleCallback (/opt/NodeBB/node_modules/mongodb/lib/utils.js:96:12)
    at /opt/NodeBB/node_modules/mongodb/lib/cursor.js:839:16
    at handleCallback (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at setCursorDeadAndNotified (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:501:3)
    at nextFunction (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:652:7)
    at Cursor.next [as _next] (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:693:3)
    at fetchDocs (/opt/NodeBB/node_modules/mongodb/lib/cursor.js:835:10)
    at /opt/NodeBB/node_modules/mongodb/lib/cursor.js:858:7
    at handleCallback (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at nextFunction (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:683:5)
    at /opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:7
    at queryCallback (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:220:18)
    at Callbacks.emit (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/opt/NodeBB/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
```

No changes in MongoDB logs when the crash happens.

**Comment by gnimmelf** [comment]
Upgrading solved it =)
