### ISSUE TITLE
Heroku App Crashed

### ISSUE THREAD

**Issue by setpixel** [NodeBB/NodeBB#5068]
I've attempted a heroku install 2 times: https://docs.nodebb.org/en/latest/installing/cloud/heroku.html

I get through the whole installation but the app crashes every time.

Logs say: 

2016-09-28T18:13:19.517332+00:00 app[web.1]: 28/9 18:13 [3] - info: Initializing NodeBB v1.1.2
2016-09-28T18:13:21.348942+00:00 app[web.1]: 28/9 18:13 [3] - error: Error: Ready check failed: NOAUTH Authentication required.
2016-09-28T18:13:21.348961+00:00 app[web.1]:     at JavascriptReplyParser._parseResult (/app/node_modules/redis/lib/parsers/javascript.js:43:16)
2016-09-28T18:13:21.348962+00:00 app[web.1]:     at JavascriptReplyParser.try_parsing (/app/node_modules/redis/lib/parsers/javascript.js:114:21)
2016-09-28T18:13:21.348962+00:00 app[web.1]:     at JavascriptReplyParser.run (/app/node_modules/redis/lib/parsers/javascript.js:126:22)
2016-09-28T18:13:21.348963+00:00 app[web.1]:     at JavascriptReplyParser.execute (/app/node_modules/redis/lib/parsers/javascript.js:107:10)
2016-09-28T18:13:21.348964+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/redis/index.js:131:27)
2016-09-28T18:13:21.348965+00:00 app[web.1]:     at emitOne (events.js:90:13)
2016-09-28T18:13:21.349069+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/redis/index.js:131:27)
2016-09-28T18:13:21.348965+00:00 app[web.1]:     at Socket.emit (events.js:182:7)
2016-09-28T18:13:21.349070+00:00 app[web.1]:     at emitOne (events.js:90:13)
2016-09-28T18:13:21.348966+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:153:18)
2016-09-28T18:13:21.349071+00:00 app[web.1]:     at Socket.emit (events.js:182:7)
2016-09-28T18:13:21.348967+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:111:10)
2016-09-28T18:13:21.349071+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:153:18)
2016-09-28T18:13:21.349067+00:00 app[web.1]:     at JavascriptReplyParser._parseResult (/app/node_modules/redis/lib/parsers/javascript.js:43:16)
2016-09-28T18:13:21.348968+00:00 app[web.1]:     at TCP.onread (net.js:534:20)
2016-09-28T18:13:21.349067+00:00 app[web.1]:     at JavascriptReplyParser.try_parsing (/app/node_modules/redis/lib/parsers/javascript.js:114:21)

config.json:

{
    "url": "https://XXXX.herokuapp.com/",
    "secret": "XXXX-dd58a9fcc495",
    "database": "redis",
    "redis": {
        "host": "sculpin.redistogo.com",
        "port": "10027",
        "password": "XXXX",
        "database": "0"
    }
}

Any idea what I should do to fix it?

**Comment by julianlam** [comment]
Please direct all installation queries to our support forum: https://community.nodebb.org

Thanks!

**Comment by setpixel** [comment]
Well - in the installation instructions: If these instructions are unclear or if you run into trouble, please let us know by filing an issue.

It would seem to me that there is a problem with the instructions. FYI
