### ISSUE TITLE
Error while uploading file

### ISSUE THREAD

**Issue by bangbang93** [NodeBB/NodeBB#5137]
Please include the following information when submitting a bug report/issue:

NodeBB git hash: f3c30cbec035b08bf87c5a7e622871e5ad78b1ea

mongodb
db version v3.2.10
git version: 79d9b3ab5ce20f51c272b4411202710a082d0317
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel70
    distarch: x86_64
    target_arch: x86_64

NodeJS V6.3.1

When I uploading file in post editor,I got a Error

```
0|nodebb   | 20/10 21:50 [32061] - error: /api/post/upload
0|nodebb   |  Error: Expected CR Received 10
0|nodebb   |     at Form._write (/home/nodejs/NodeBB/node_modules/.4.1.2@multiparty/index.js:245:49)
0|nodebb   |     at doWrite (_stream_writable.js:307:12)
0|nodebb   |     at writeOrBuffer (_stream_writable.js:293:5)
0|nodebb   |     at Form.Writable.write (_stream_writable.js:220:11)
0|nodebb   |     at IncomingMessage.ondata (_stream_readable.js:556:20)
0|nodebb   |     at emitOne (events.js:96:13)
0|nodebb   |     at IncomingMessage.emit (events.js:188:7)
0|nodebb   |     at IncomingMessage.Readable.read (_stream_readable.js:382:10)
0|nodebb   |     at flow (_stream_readable.js:762:34)
0|nodebb   |     at resume_ (_stream_readable.js:744:3)
0|nodebb   |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
0|nodebb   |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

And uploading prograss stop at 100%,can't get url.

I found that chrome devtools shows my request payload was

```
------WebKitFormBoundaryivhhom2r7QUUoz5f
Content-Disposition: form-data; name="files[]"; filename="WechatIMG10.jpeg"
Content-Type: image/jpeg


------WebKitFormBoundaryivhhom2r7QUUoz5f
Content-Disposition: form-data; name="cid"


------WebKitFormBoundaryivhhom2r7QUUoz5f--
```

But content-type

```
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryivhhom2r7QUUoz5f
```

**Comment by barisusakli** [comment]
Are you getting the same error on nodejs 4.x?

**Comment by bangbang93** [comment]
I had never try this.
I will reply after testing.

**Comment by bangbang93** [comment]
I tried nodejs 4.6.1，but nothing changed.
Same error
```
22/10 16:22 [16345] - error: /api/post/upload
 Error: Expected CR Received 10
    at Form._write (/home/nodejs/NodeBB/node_modules/.4.1.2@multiparty/index.js:245:49)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at Form.Writable.write (_stream_writable.js:214:11)
    at IncomingMessage.ondata (_stream_readable.js:542:20)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:368:10)
    at flow (_stream_readable.js:759:26)
    at resume_ (_stream_readable.js:739:3)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by bangbang93** [comment]
I found this
https://github.com/expressjs/node-multiparty/issues/98

But It's in 2014.

I'm using Chrome 54.0.2840.59 (64-bit),And Safari 10 has same error.

**Comment by barisusakli** [comment]
I can't reproduce this. Is your forum public?

**Comment by bangbang93** [comment]
yes
<https://www.bangbang93.com>

**Comment by bangbang93** [comment]
I forget this issue.
But now it had been fixed……
git hash d5ec36f45aa0b1630559d1f1d109ab0968741a0e
