### ISSUE TITLE
Occasionally crash on qtdream.com

### ISSUE THREAD

**Issue by jiangcaiyang** [NodeBB/NodeBB#5195]
NodeBB occasionally crashed.
Here is log:
```
TypeError: Cannot read property 'loggedIn' of undefined
    at helpers.displayMenuItem (/root/WebProject/QtDream/public/src/modules/helpers.js:20:44)
    at checkConditionalHelpers (/root/WebProject/QtDream/node_modules/templates.js/lib/templates.js:269:76)
    at parse (/root/WebProject/QtDream/node_modules/templates.js/lib/templates.js:424:15)
    at parseTemplate (/root/WebProject/QtDream/node_modules/templates.js/lib/templates.js:133:14)
    at Object.templates.parse (/root/WebProject/QtDream/node_modules/templates.js/lib/templates.js:119:11)
    at View.express [as engine] (/root/WebProject/QtDream/node_modules/templates.js/lib/templates.js:172:30)
    at View.render (/root/WebProject/QtDream/node_modules/express/lib/view.js:126:8)
    at tryRender (/root/WebProject/QtDream/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/root/WebProject/QtDream/node_modules/express/lib/application.js:591:3)
    at /root/WebProject/QtDream/src/middleware/header.js:159:13
    at fireFilterHook (/root/WebProject/QtDream/src/plugins/hooks.js:103:11)
    at Object.Plugins.fireHook (/root/WebProject/QtDream/src/plugins/hooks.js:87:5)
    at /root/WebProject/QtDream/src/middleware/header.js:154:12
    at /root/WebProject/QtDream/node_modules/async/lib/async.js:726:13
    at /root/WebProject/QtDream/node_modules/async/lib/async.js:52:16
    at done (/root/WebProject/QtDream/node_modules/async/lib/async.js:246:17)
10/11 13:56 [25990] - [31merror[39m: Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)
Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)
10/11 13:56 [25990] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
10/11 13:56 [25990] - [32minfo[39m: [app] Database connection closed.
10/11 13:56 [25990] - [32minfo[39m: [app] Web server closed to connections.
10/11 13:56 [25990] - [32minfo[39m: [app] Shutdown complete.
```

* NodeBB version and git hash 40db65d2554016952aa38f9cfa49ead6f74040ed
* Database (mongo or redis) and it's version. MongoDB 3.2
* Exact steps to cause this issue
Refreshing the forum, may cause this forum to crash.

**Comment by pichalite** [comment]
Can you list the plugins you are using?

**Comment by jiangcaiyang** [comment]
nodebb-plugin-composer-default
nodebb-plugin-dbsearch
nodebb-plugin-emoji-extended
nodebb-plugin-emoji-one
nodebb-plugin-markdown
nodebb-plugin-mentions
nodebb-plugin-qtdream
nodebb-plugin-soundpack-default
nodebb-plugin-spam-be-gone
----
nodebb-plugin-qtdream is our private plugin.

**Comment by barisusakli** [comment]
Disable your custom plugin and see if it happens.

**Comment by jiangcaiyang** [comment]
I need to see it in the long term. Close it temporarily.
