### ISSUE TITLE
Cannot upgrade to latest version

### ISSUE THREAD

**Issue by huegelc** [NodeBB/NodeBB#5203]
git rev-parse HEAD

```
4db89407c4dbe9850d925bd9529a1d106419531f
```

Hi, Im on the v1.x.x branch and dit a git fetch/git merge origin/v1.x.x but nodebb upgrade fails with following error.

```
Error: Command failed: npm WARN engine postcss-clean@1.0.2: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.46","npm":"2.15.1"})
npm WARN engine pngjs@3.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.46","npm":"2.15.1"})
npm WARN engine form-data@2.0.0: wanted: {"node":">= 0.12"} (current: {"node":"0.10.46","npm":"2.15.1"})
gyp ERR! clean error
gyp ERR! stack Error: EACCES, rmdir 'build'
gyp ERR! System Linux 3.19.0-64-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/nodebb/node_modules/heapdump
gyp ERR! node -v v0.10.46
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

npm ERR! Linux 3.19.0-64-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "--production"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! heapdump@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heapdump@0.3.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heapdump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs heapdump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls heapdump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/nodebb/npm-debug.log
```

Any help is much appreciated. Thank you

**Comment by julianlam** [comment]
Likely your global node modules folder got it's permissions messed up. As root, uninstall node-gyp package and then drop down to regular user and try running NodeBB update again.

Closing this as it is neither a bug not related to NodeBB, thanks.

**Comment by huegelc** [comment]
Thx for your reply. I do not have a regular user. nodebb is running as root

**Comment by huegelc** [comment]
ok got rid of the node-gyp error but run into another:

```
 root@forum:/var/www/nodebb# ./nodebb stop
Stopping NodeBB. Goodbye!
root@forum:/var/www/nodebb# git fetch
remote: Counting objects: 12930, done.
remote: Compressing objects: 100% (367/367), done.
remote: Total 12930 (delta 5879), reused 5801 (delta 5763), pack-reused 6800
Receiving objects: 100% (12930/12930), 4.08 MiB | 2.22 MiB/s, done.
Resolving deltas: 100% (10450/10450), completed with 1154 local objects.
From https://github.com/NodeBB/NodeBB
   a196c83..4db8940  v1.x.x     -> origin/v1.x.x
 * [new branch]      close-4956 -> origin/close-4956
   f4599e2..0bf51c7  master     -> origin/master
 * [new branch]      registration-interstitial -> origin/registration-interstitial
 * [new branch]      temp-bans  -> origin/temp-bans
 * [new branch]      topics-read-privileges -> origin/topics-read-privileges
 * [new branch]      update-chartjs -> origin/update-chartjs
 * [new branch]      user-flairs -> origin/user-flairs
 * [new branch]      webpack    -> origin/webpack
   6e27e9a..5b9809c  weekly     -> origin/weekly
 * [new tag]         v1.2.2-auto.0 -> v1.2.2-auto.0
 * [new tag]         v1.3.0     -> v1.3.0
From https://github.com/NodeBB/NodeBB
 * [new tag]         v1.0.4-auto.10 -> v1.0.4-auto.10
 * [new tag]         v1.0.4-auto.11 -> v1.0.4-auto.11
 * [new tag]         v1.0.4-auto.12 -> v1.0.4-auto.12
 * [new tag]         v1.0.4-auto.4 -> v1.0.4-auto.4
 * [new tag]         v1.0.4-auto.5 -> v1.0.4-auto.5
 * [new tag]         v1.0.4-auto.6 -> v1.0.4-auto.6
 * [new tag]         v1.0.4-auto.7 -> v1.0.4-auto.7
 * [new tag]         v1.0.4-auto.8 -> v1.0.4-auto.8
 * [new tag]         v1.0.4-auto.9 -> v1.0.4-auto.9
 * [new tag]         v1.1.0     -> v1.1.0
 * [new tag]         v1.1.1     -> v1.1.1
 * [new tag]         v1.1.1-auto.0 -> v1.1.1-auto.0
 * [new tag]         v1.1.1-auto.1 -> v1.1.1-auto.1
 * [new tag]         v1.1.1-auto.2 -> v1.1.1-auto.2
 * [new tag]         v1.1.1-auto.3 -> v1.1.1-auto.3
 * [new tag]         v1.1.2     -> v1.1.2
 * [new tag]         v1.1.3-auto.0 -> v1.1.3-auto.0
 * [new tag]         v1.1.3-auto.1 -> v1.1.3-auto.1
 * [new tag]         v1.1.3-auto.2 -> v1.1.3-auto.2
 * [new tag]         v1.1.3-auto.3 -> v1.1.3-auto.3
 * [new tag]         v1.1.3-auto.4 -> v1.1.3-auto.4
 * [new tag]         v1.1.3-auto.5 -> v1.1.3-auto.5
 * [new tag]         v1.1.3-auto.6 -> v1.1.3-auto.6
 * [new tag]         v1.2.0     -> v1.2.0
 * [new tag]         v1.2.1     -> v1.2.1
 * [new tag]         v1.2.1-auto.0 -> v1.2.1-auto.0
 * [new tag]         v1.2.1-auto.1 -> v1.2.1-auto.1
root@forum:/var/www/nodebb# git merge origin/v1.x.x
Updating a196c83..4db8940
error: Your local changes to the following files would be overwritten by merge:
	package.json
Please, commit your changes or stash them before you can merge.
Aborting
root@forum:/var/www/nodebb# git reset --hard origin/v1.x.x
HEAD is now at 4db8940 Incremented version number
root@forum:/var/www/nodebb# git merge origin/v1.x.x
Already up-to-date.
root@forum:/var/www/nodebb# ./nodebb upgrade
1. Bringing base dependencies up to date... OK
2. Checking installed plugins for updates... OK

A total of 5 package(s) can be upgraded:
  * nodebb-plugin-imagemagick (1.0.1 -> 2.0.4)
  * nodebb-plugin-poll (0.2.6 -> 0.2.8)
  * nodebb-plugin-sso-facebook (2.1.0 -> 3.0.3)
  * nodebb-plugin-sso-google (2.0.0 -> 2.0.1)
  * nodebb-theme-material (2.8.10 -> 2.9.3)

Proceed with upgrade (y|n)? y

Upgrading packages... OK
3. Updating NodeBB data store schema...
{"level":"warn","message":"Your version of Node.js is too outdated for NodeBB. Please update your version of Node.js.","timestamp":"2016-11-13T15:10:26.836Z"}
{"level":"warn","message":"Recommended \u001b[32m>=4\u001b[39m\u001b[0m, \u001b[0m\u001b[33m0.10.46\u001b[39m\u001b[0m provided\n\u001b[0m","timestamp":"2016-11-13T15:10:26.838Z"}
node_redis: Warning: Redis server does not require a password, but a password was supplied.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
{"level":"info","message":"Beginning database schema update","timestamp":"2016-11-13T15:10:27.933Z"}
{"level":"info","message":"[2015/12/15] Chats upgrade skipped!","timestamp":"2016-11-13T15:10:27.935Z"}
{"level":"info","message":"[2015/12/23] Chats room hashes upgrade skipped!","timestamp":"2016-11-13T15:10:27.936Z"}
{"level":"info","message":"[2015/12/23] Adding theme to active plugins sorted set skipped!","timestamp":"2016-11-13T15:10:27.936Z"}
{"level":"info","message":"[2016/01/14] Creating user best post sorted sets skipped!","timestamp":"2016-11-13T15:10:27.937Z"}
{"level":"info","message":"[2016/01/20] Creating users:notvalidated skipped!","timestamp":"2016-11-13T15:10:27.937Z"}
{"level":"info","message":"[2016/01/23] Creating Global moderators group skipped!","timestamp":"2016-11-13T15:10:27.937Z"}
{"level":"info","message":"[2016/02/25] Social: Post Sharing skipped!","timestamp":"2016-11-13T15:10:27.937Z"}
{"level":"info","message":"[2016/04/14] Group title from settings to user profile","timestamp":"2016-11-13T15:10:27.937Z"}

/var/www/nodebb/public/src/modules/translator.js:38
	var assign = Object.assign || jQuery.extend;
	                              ^
ReferenceError: jQuery is not defined
    at /var/www/nodebb/public/src/modules/translator.js:38:32
    at /var/www/nodebb/public/src/modules/translator.js:31:21
    at assign (/var/www/nodebb/public/src/modules/translator.js:32:4)
    at Object.<anonymous> (/var/www/nodebb/public/src/modules/translator.js:36:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

Error: undefined
root@forum:/var/www/nodebb#

```

**Comment by barisusakli** [comment]
>{"level":"warn","message":"Your version of Node.js is too outdated for NodeBB. Please update your version of Node.js.","timestamp":"2016-11-13T15:10:26.836Z"}

Try with node 4+

**Comment by huegelc** [comment]
Yes, thank you:

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

sudo ln -sf /usr/local/n/versions/node/<VERSION>/bin/node /usr/bin/node 
```
did the trick
