### ISSUE TITLE
Accessing Themes Tab in Admin Panel causes 404

### ISSUE THREAD

**Issue by Lazalatin** [NodeBB/NodeBB#5289]
* NodeBB: 1.4.0 ; git hash: e17b37edb637fccb4445fdba1ef6860e93a9c807
* MongoDB: v2.6.12 ; git hash: d73c92b1c85703828b55c2916a5dd4ad46535f6a
* Exact steps to cause this issue
    1. On a fresh install I logged in to Admin Panel, changed some settings (translation and other things, went from left to the right in the settings)
    2. Then I tried to access Appearance/Themes, with no success. Consulting Network-Tab in Debugger gave me a 404 for /admin/appearance/themes
* What you expected
    * The Themes Tab to work
* What happened instead
    * The loading circle circles and circles and circles... ;)

Thank you in advance for your appreciated help!
Lazalatin

EDIT: On a side note: this 404 does NOT appear in the "Advanced/Errors" Tab ;-)
EDIT2: It appears that the Advanced/Database Tab is also not working. Log gives:
```
15/12 12:15:20 [31063] - error: /api/admin/advanced/database
 MongoError: not authorized on xxx_nodeBB to execute command { serverStatus: 1 }
    at Function.MongoError.create (/home/xxx/nodebb/node_modules/mongodb-core/lib/error.js:31:11)
    at /home/xxx/nodebb/node_modules/mongodb-core/lib/connection/pool.js:462:72
    at authenticateStragglers (/home/xxx/nodebb/node_modules/mongodb-core/lib/connection/pool.js:410:16)
    at Connection.messageHandler (/home/xxx/nodebb/node_modules/mongodb-core/lib/connection/pool.js:444:5)
    at Socket.<anonymous> (/home/xxx/nodebb/node_modules/mongodb-core/lib/connection/connection.js:306:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```
This maybe requires a separate issue...

**Comment by barisusakli** [comment]
>MongoError: not authorized on xxx_nodeBB to execute command { serverStatus: 1 }
seems like your mongodb user isn't configured properly, you can ask at https://community.nodebb.org or look at the mongodb docs.
