### ISSUE TITLE
The following error occurred while starting.What is the reason?(redis no password)

### ISSUE THREAD

**Issue by unreal0** [NodeBB/NodeBB#5330]
The following error occurred while starting.What is the reason?(redis no password)
/nodebb log :
at /Users/unreal/Downloads/NodeBB-master/src/database/redis.js:153:4
    at Object.callbackOrEmit [as callback_or_emit] (/Users/unreal/Downloads/NodeBB-master/node_modules/redis/lib/utils.js:89:9)
    at Command.callback (/Users/unreal/Downloads/NodeBB-master/node_modules/redis/lib/individualCommands.js:157:15)
    at normal_reply (/Users/unreal/Downloads/NodeBB-master/node_modules/redis/index.js:714:21)
    at RedisClient.return_reply (/Users/unreal/Downloads/NodeBB-master/node_modules/redis/index.js:816:9)
    at JavascriptRedisParser.returnReply (/Users/unreal/Downloads/NodeBB-master/node_modules/redis/index.js:188:18)
    at JavascriptRedisParser.execute (/Users/unreal/Downloads/NodeBB-master/node_modules/redis-parser/lib/parser.js:491:12)
    at Socket.<anonymous> (/Users/unreal/Downloads/NodeBB-master/node_modules/redis/index.js:267:27)
    at emitOne (events.js:96:13)
[cluster] Child Process (1141) has exited (code: 0, signal: null)

redis info:
[4966] 01 Jan 22:39:39.911 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
[4966] 01 Jan 22:39:39.913 * Max number of open files set to 10032
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 2.6.9 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in stand alone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 4966
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

[4966] 01 Jan 22:39:39.915 # Server started, Redis version 2.6.9
[4966] 01 Jan 22:39:39.915 * The server is now ready to accept connections on port 6379
[4966] 01 Jan 22:40:40.003 * 10000 changes in 60 seconds. Saving...
[4966] 01 Jan 22:40:40.003 * Background saving started by pid 4981
[4981] 01 Jan 22:40:40.005 * DB saved on disk
[4966] 01 Jan 22:40:40.013 * Background saving terminated with success
[4966] 01 Jan 22:41:41.005 * 10000 changes in 60 seconds. Saving...
[4966] 01 Jan 22:41:41.006 * Background saving started by pid 4983
[4983] 01 Jan 22:41:41.283 * DB saved on disk
[4966] 01 Jan 22:41:41.290 * Background saving terminated with success
[4966] 01 Jan 22:42:42.008 * 10000 changes in 60 seconds. Saving...
[4966] 01 Jan 22:42:42.009 * Background saving started by pid 4997
[4997] 01 Jan 22:42:42.411 * DB saved on disk
[4966] 01 Jan 22:42:42.419 * Background saving terminated with success
[4966] 01 Jan 22:43:43.003 * 10000 changes in 60 seconds. Saving...
[4966] 01 Jan 22:43:43.004 * Background saving started by pid 4999
[4999] 01 Jan 22:43:43.332 * DB saved on disk
[4966] 01 Jan 22:43:43.338 * Background saving terminated with success
[4966] 01 Jan 22:51:26.023 * 100 changes in 300 seconds. Saving...
[4966] 01 Jan 22:51:26.025 * Background saving started by pid 5108
[5108] 01 Jan 22:51:26.381 * DB saved on disk
[4966] 01 Jan 22:51:26.387 * Background saving terminated with success
[4966] 01 Jan 22:56:27.001 * 100 changes in 300 seconds. Saving...
[4966] 01 Jan 22:56:27.002 * Background saving started by pid 5151
[5151] 01 Jan 22:56:27.475 * DB saved on disk
[4966] 01 Jan 22:56:27.482 * Background saving terminated with success

**Comment by julianlam** [comment]
Stack Trace incomplete. Please provide full stack trace

**Comment by unreal0** [comment]
ReplyError: ERR wrong number of arguments for 'set' command
    at parseError (/Users/unreal/Downloads/NodeBB-master/node_modules/redis-parser/lib/parser.js:181:12)
    at parseType (/Users/unreal/Downloads/NodeBB-master/node_modules/redis-parser/lib/parser.js:269:14)

**Comment by unreal0** [comment]
Hit Ctrl-C to exit

2/1 20:45:47 [13850] - info: initializing NodeBB ...
2/1 20:45:47 [13850] - info: Routes added
2/1 20:45:47 [13850] - info: NodeBB Ready
2/1 20:45:47 [13850] - info: Enabling 'trust proxy'
2/1 20:45:47 [13850] - info: NodeBB is now listening on: 0.0.0.0:4567
2/1 20:46:11 [13850] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2/1 20:46:11 [13850] - info: [app] Database connection closed.
2/1 20:46:11 [13850] - info: [app] Web server closed to connections.
2/1 20:46:11 [13850] - info: [app] Shutdown complete.
[cluster] Child Process (13850) has exited (code: 0, signal: null)

**Comment by unreal0** [comment]
ok .Find out the why.Redis version is too low
