### ISSUE TITLE
MongoDB 3.4 error

### ISSUE THREAD

**Issue by KitsuneSolar** [NodeBB/NodeBB#5364]
* NodeBB 1.4.2
* MongoDB 3.4
* NodeJS 6.9.4

Open "search" page, get error:

```
13/1 00:44:14 [3992] - [31merror[39m: /api/search
 MongoError: pipeline requires text score metadata, but there is no text score available
    at Function.MongoError.create (/example.org/domain/public_html/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/example.org/domain/public_html/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /example.org/domain/public_html/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
13/1 00:44:16 [3992] - [31merror[39m: [plugins] filter:search.query,  pipeline requires text score metadata, but there is no text score available
13/1 00:44:16 [3992] - [31merror[39m: /api/search
 MongoError: pipeline requires text score metadata, but there is no text score available
    at Function.MongoError.create (/example.org/domain/public_html/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/example.org/domain/public_html/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /example.org/domain/public_html/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
13/1 00:44:17 [3992] - [31merror[39m: [plugins] filter:search.query,  pipeline requires text score metadata, but there is no text score available
13/1 00:44:17 [3992] - [31merror[39m: /search
 MongoError: pipeline requires text score metadata, but there is no text score available
    at Function.MongoError.create (/example.org/domain/public_html/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/example.org/domain/public_html/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /example.org/domain/public_html/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

And, MongoDB sometimes dies...

**Comment by barisusakli** [comment]
Looks like
https://github.com/barisusakli/nodebb-plugin-dbsearch/issues/28

Does it work if you provide a query?
`https://forum.com/search?term=nodebb&in=titles&showAs=posts`

**Comment by KitsuneSolar** [comment]
> Looks like

Yes.

> Does it work if you provide a query?

I returned to MongoDB 3.2 - work perfect!

**Comment by julianlam** [comment]
@barisusakli can this be closed?

**Comment by barisusakli** [comment]
Nope gotto test on mongodb 3.4
