### ISSUE TITLE
Error: Cannot find module '/bcrypt'

### ISSUE THREAD

**Issue by frodesigns** [NodeBB/NodeBB#5365]
Please include the following information when submitting a bug report/issue:

* NodeBB version 
    1.4.2
* Database 
    redis
* Exact steps to cause this issue
    1. Start server
    2. Try to log in or register
    3. Check ./nodebb status
* What you expected
    To log in.
* What happened instead
```
module.js:471
    throw err;
    ^
Error: Cannot find module '/bcrypt'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I have tried 
```
sudo npm install node-gyp -g
sudo npm install bcrypt -g
sudo npm install bcrypt -save
```
No luck :(

Could be related to this issue: https://github.com/kelektiv/node.bcrypt.js/issues/476

**Comment by frodesigns** [comment]
Right, tried it without too.

**Comment by pitaj** [comment]
Is that the full error stack?

**Comment by frodesigns** [comment]
That's what is thrown after a login request.

`npm install bcrypt -g` produces some other weird errors. There is an open issue on the bcrypt repo: https://github.com/kelektiv/node.bcrypt.js/issues/476

**Comment by julianlam** [comment]
You edited bcrypt.js, yes?

Don't put a slash before bcrypt.

**Comment by frodesigns** [comment]
Hmm no it should be the vanilla file from the 1.4.2 master.

**Comment by julianlam** [comment]
Odd. What are the first couple lines of `bcrypt.js`?

What happens when you `git status`?

**Comment by frodesigns** [comment]
bcrypt.js:
```
'use strict';

var bcrypt = require('bcryptjs'),
	async = require('async');
```

git status
```
HEAD detached at v1.4.2
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        binding.gyp
        build/
        node_modules.old-2017-01-11.tar.gz
        public/pie/

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by julianlam** [comment]
Then as @pitaj says, you'll either need to provide a full stack trace, or perhaps this is not a NodeBB issue, but a nodejs issue with how it is installed. Honestly can't tell right now.

**Comment by frodesigns** [comment]
How can I get you a full stack trace? That was the full error in the ./nodebb status.

**Comment by pitaj** [comment]
Run it in dev mode with `./nodebb dev` and then repro

**Comment by julianlam** [comment]
Unable to repro:

```
julian@arya ~ $ cd /tmp
julian@arya /tmp $ git clone https://github.com/NodeBB/NodeBB test
Cloning into 'test'...
remote: Counting objects: 116714, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 116714 (delta 2), reused 2 (delta 2), pack-reused 116704
Receiving objects: 100% (116714/116714), 36.72 MiB | 627.00 KiB/s, done.
Resolving deltas: 100% (87632/87632), done.
Checking connectivity... done.
julian@arya /tmp $ cd test
gjulian@arya /tmp/test (master) $ git checkout v1.x.x
Branch v1.x.x set up to track remote branch v1.x.x from origin.
Switched to a new branch 'v1.x.x'
julian@arya /tmp/test (v1.x.x) $ npm i --production && node app --setup

... npm stuff here ...

12/1 22:04:10 [15175] - info: NodeBB v1.4.2 Copyright (C) 2013-2017 NodeBB Inc.
12/1 22:04:10 [15175] - info: This program comes with ABSOLUTELY NO WARRANTY.
12/1 22:04:10 [15175] - info: This is free software, and you are welcome to redistribute it under certain conditions.
12/1 22:04:10 [15175] - info:  
12/1 22:04:10 [15175] - info: NodeBB Setup Triggered via Command Line

Welcome to NodeBB!

This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
Press enter to accept the default setting (shown in brackets).
URL used to access this NodeBB (http://localhost:4567) 
Please enter a NodeBB secret (aad7cdd4-b98f-45e1-af1f-a14d032621e4) 
Which database to use (mongo) 

12/1 22:04:15 [15175] - info: Now configuring mongo database:
Host IP or address of your MongoDB instance (127.0.0.1) 
Host port of your MongoDB instance (27017) 
MongoDB username 
Password of your MongoDB database 
MongoDB database name (nodebb) test
Configuration Saved OK
12/1 22:04:21 [15175] - warn: You have no mongo password setup!
12/1 22:04:21 [15175] - info: [database] Checking database indices.
12/1 22:04:21 [15175] - info: [database] Checking database indices done!
Populating database with default configs, if not already set...
Enabling default theme: nodebb-theme-persona
No categories found, populating instance with default categories
12/1 22:04:23 [15175] - warn: No administrators have been detected, running initial user setup
Administrator username julian
Administrator email address b@c.com
Password 
Confirm Password 
Creating welcome post!
Enabling default plugins
12/1 22:04:30 [15175] - info: [install/defaultPlugins] customDefaults
12/1 22:04:30 [15175] - info: [install/enableDefaultPlugins] activating default plugins 0=nodebb-plugin-composer-default, 1=nodebb-plugin-markdown, 2=
nodebb-plugin-mentions, 3=nodebb-widget-essentials, 4=nodebb-rewards-essentials, 5=nodebb-plugin-soundpack-default, 6=nodebb-plugin-emoji-extended, 7=
nodebb-plugin-emoji-one
12/1 22:04:30 [15175] - info: Beginning database schema update
12/1 22:04:30 [15175] - info: [2015/12/15] Chats upgrade skipped!
12/1 22:04:30 [15175] - info: [2015/12/23] Chats room hashes upgrade skipped!
12/1 22:04:30 [15175] - info: [2015/12/23] Adding theme to active plugins sorted set skipped!
12/1 22:04:30 [15175] - info: [2016/01/14] Creating user best post sorted sets skipped!
12/1 22:04:30 [15175] - info: [2016/01/20] Creating users:notvalidated skipped!
12/1 22:04:30 [15175] - info: [2016/01/23] Creating Global moderators group skipped!
12/1 22:04:30 [15175] - info: [2016/02/25] Social: Post Sharing skipped!
12/1 22:04:30 [15175] - info: [2016/04/14] Group title from settings to user profile skipped!
12/1 22:04:30 [15175] - info: [2016/04/19] Users post count per tid skipped!
12/1 22:04:30 [15175] - info: [2016/04/29] Dismiss flags from deleted topics skipped!
12/1 22:04:30 [15175] - info: [2016/05/28] Giving topics:read privs to any group that was previously allowed to Find & Access Category - skipped!
12/1 22:04:30 [15175] - info: [2016/06/13] Store upvotes/downvotes separately skipped!
12/1 22:04:30 [15175] - info: [2016/07/12] Upload privileges skipped!
12/1 22:04:30 [15175] - info: [2016/08/05] Removing best posts with negative scores skipped!
12/1 22:04:30 [15175] - info: [2016/08/07] Granting edit/delete/delete topic on existing categories - skipped!
12/1 22:04:30 [15175] - info: [2016/09/22] Setting category recent tids - skipped!
12/1 22:04:30 [15175] - info: [2016/10/8] favourite -> bookmark refactor - skipped!
12/1 22:04:30 [15175] - info: [2016/10/14] Creating sorted sets for post replies - skipped!
12/1 22:04:30 [15175] - info: [2016/11/22] Update global and user language keys - skipped!
12/1 22:04:30 [15175] - info: [2016/11/25] Creating sorted sets for pinned topcis
12/1 22:04:30 [15175] - info: [2016/11/25] Creating sorted sets for pinned topics - done
12/1 22:04:30 [15175] - info: [upgrade] Schema update complete!
12/1 22:04:30 [15175] - warn: You have no mongo password setup!
12/1 22:04:30 [15175] - info: [build] Building javascript
12/1 22:04:30 [15175] - info: [build] Building client-side CSS
12/1 22:04:36 [15175] - info: [build] clientCSS => Completed in 5.687s
12/1 22:04:36 [15175] - info: [build] Building admin control panel CSS
12/1 22:04:43 [15175] - info: [build] acpCSS => Completed in 7.912s
12/1 22:04:43 [15175] - info: [build] Building templates
12/1 22:04:43 [15175] - info: [build] js => Completed in 13.649s
12/1 22:04:44 [15175] - info: [build] tpl => Completed in 0.126s
12/1 22:04:44 [15175] - info: [build] Asset compilation successful. Completed in 13.774s.

     ============================================================================================================================================

NodeBB Setup Completed. Run './nodebb start' to manually start your NodeBB server.
julian@arya /tmp/test (v1.x.x) $ ./nodebb dev

NodeBB v1.4.2 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

12/1 22:06:46 [15650] - verbose: * using configuration stored in: /tmp/test/config.json
12/1 22:06:46 [15650] - info: Time: Thu Jan 12 2017 22:06:46 GMT-0500 (EST)
12/1 22:06:46 [15650] - info: Initializing NodeBB v1.4.2
12/1 22:06:46 [15650] - verbose: * using mongo store at 127.0.0.1:27017
12/1 22:06:46 [15650] - verbose: * using themes stored in: /tmp/test/node_modules
12/1 22:06:46 [15650] - warn: You have no mongo password setup!
12/1 22:06:47 [15650] - verbose: Checking dependencies for outdated modules
12/1 22:06:47 [15650] - verbose: [notifications.init] Registering jobs.
12/1 22:06:47 [15650] - verbose: [user/jobs] (Re-)starting user jobs...
12/1 22:06:47 [15650] - verbose: [user/jobs] 0 jobs terminated
12/1 22:06:47 [15650] - verbose: [user/jobs] Starting job (digest.daily)
12/1 22:06:47 [15650] - verbose: [user/jobs] Starting job (digest.weekly)
12/1 22:06:47 [15650] - verbose: [user/jobs] Starting job (digest.monthly)
12/1 22:06:47 [15650] - verbose: [user/jobs] Starting job (reset.clean)
12/1 22:06:47 [15650] - verbose: [user/jobs] 4 jobs started
 
... some nodebb stuff ...

12/1 22:06:48 [15650] - info: [plugins] Plugins OK
12/1 22:06:48 [15650] - verbose: [meta/js] 15 of 15 modules bridged
12/1 22:06:48 [15650] - verbose: [hotswap] Router with id `plugins` replaced successfully
12/1 22:06:48 [15650] - verbose: [plugins] All plugins reloaded and rerouted
12/1 22:06:48 [15650] - verbose: [hotswap] Router with id `auth` replaced successfully
12/1 22:06:48 [15650] - info: Routes added
12/1 22:06:48 [15650] - verbose: [meta/css] Reading stylesheet stylesheet.css from file
12/1 22:06:48 [15650] - verbose: [meta/css] Reading stylesheet admin.css from file
12/1 22:06:48 [15650] - verbose: [sounds] Sounds OK
12/1 22:06:48 [15650] - verbose: [meta/blacklist] Loading 0 blacklist rules
12/1 22:06:48 [15650] - info: NodeBB Ready
12/1 22:06:48 [15650] - info: Enabling 'trust proxy'
12/1 22:06:48 [15650] - info: NodeBB is now listening on: 0.0.0.0:4567
```

**Comment by frodesigns** [comment]
So running in dev mode it worked fine.  Turns out this was related to a system d startup script we had created two days ago.  We modified the system d script to set the WorkingDirectory to the proper path for the NodeBB install, and now everything is working correctly.

Thank you so much for your help!
