### ISSUE TITLE
FreeBSD: NodeBB could not connect to your Mongo database.

### ISSUE THREAD

**Issue by UnR34L** [NodeBB/NodeBB#5579]
git hash: 12a426b7b91d53b217b01b945a9c6336fab18217
mongo/redis version is what ever got installed with with npm.

Trying to install in a FreeBSD 10.3-STABLE Jail, followed to steps exactly from "https://docs.nodebb.org/en/latest/installing/os/freebsd.html" used the default option for everything during setup.
When I installed npm, I used www/npm, 

```
./nodebb setup
9/4 07:06:53 [88271] - info: NodeBB Setup Triggered via Command Line

Welcome to NodeBB!

This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
Press enter to accept the default setting (shown in brackets).

9/4 07:06:53 [88271] - info: Now configuring mongo database:
Configuration Saved OK
9/4 07:06:53 [88271] - error: NodeBB could not connect to your Mongo database. Mongo returned the following error: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
9/4 07:06:53 [88271] - warn: NodeBB Setup Aborted.
 MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/root/NodeBB/node_modules/mongodb-core/lib/topologies/server.js:327:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:191:7)
    at Connection.<anonymous> (/root/NodeBB/node_modules/mongodb-core/lib/connection/pool.js:274:12)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at Socket.<anonymous> (/root/NodeBB/node_modules/mongodb-core/lib/connection/connection.js:177:49)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
```

> **error: NodeBB could not connect to your Mongo database. Mongo returned the following error: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]**

**Comment by pitaj** [comment]
Check that mongod is running. `ps -ax | grep mongo`

**Comment by UnR34L** [comment]
mongodb is not running and I don't know why.

**Comment by UnR34L** [comment]
I got it working, the instructions for FreeBSD didn't say that I had to install mongodb, I assumed npm handled all the dependencies. -.-

**Comment by pitaj** [comment]
Yes the FreeBSD instructions assume you're using redis.
