### ISSUE TITLE
server side error

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#5693]
**nodebb origin master

when a user post a new replies on a topic:
```
20/5 01:37:20 [12349] - error:  TypeError: callFn.apply is not a function     
    at /home/nodeBB/forum/node_modules/async/dist/async.js:421:16             
    at next (/home/nodeBB/forum/node_modules/async/dist/async.js:5279:29)     
    at /home/nodeBB/forum/node_modules/async/dist/async.js:906:16             
    at /home/nodeBB/forum/src/topics/unread.js:145:5                          
    at nextTask (/home/nodeBB/forum/node_modules/async/dist/async.js:5274:14) 
    at next (/home/nodeBB/forum/node_modules/async/dist/async.js:5281:9)      
    at /home/nodeBB/forum/node_modules/async/dist/async.js:906:16             
    at fireFilterHook (/home/nodeBB/forum/src/plugins/hooks.js:110:11)        
    at Object.Plugins.fireHook (/home/nodeBB/forum/src/plugins/hooks.js:94:4) 
    at /home/nodeBB/forum/src/topics/unread.js:137:13                         
    at nextTask (/home/nodeBB/forum/node_modules/async/dist/async.js:5274:14) 
    at next (/home/nodeBB/forum/node_modules/async/dist/async.js:5281:9)      
    at /home/nodeBB/forum/node_modules/async/dist/async.js:906:16             
    at /home/nodeBB/forum/node_modules/async/dist/async.js:421:16             
    at next (/home/nodeBB/forum/node_modules/async/dist/async.js:5279:29)     
    at /home/nodeBB/forum/node_modules/async/dist/async.js:906:16             
```
Thank you!

**Comment by barisusakli** [comment]
Works fine for me, make sure you don't have any plugins that is causing it.

**Comment by sohrabafard** [comment]
How do I know? I can't disable all of plugins!

**Comment by pitaj** [comment]
Does this happen on every reply?

**Comment by sohrabafard** [comment]
yes And will restart the NodeBB

**Comment by pitaj** [comment]
Then in that case, if a restart doesn't fix it, I'd suggest disabling all plugins.

**Comment by sohrabafard** [comment]
i will disable these plugins : 
- nodebb-plugin-bbcode-to-markdown
- nodebb-plugin-calendar
- nodebb-plugin-category-sections
- nodebb-plugin-emailer-local
- nodebb-plugin-emailer-mailjet
- nodebb-plugin-emoji-one
- nodebb-plugin-featured-threads
- nodebb-plugin-iframely
- nodebb-plugin-imgur
- nodebb-plugin-newsletter
- nodebb-plugin-ns-custom-fields
- nodebb-plugin-poll
- nodebb-plugin-shoutbox

**Comment by sohrabafard** [comment]
```./ nodebb reset``` has this error:
```
/home/nodeBB/forum/node_modules/mongodb/lib/mongo_client.js:369
            throw err
            ^

TypeError: invalid data
    at WriteStream.Socket.write (net.js:641:11)
    at /home/nodeBB/forum/src/reset.js:58:19
    at /home/nodeBB/forum/src/database/mongo.js:107:3
    at connectCallback (/home/nodeBB/forum/node_modules/mongodb/lib/mongo_client.js:428:5)
    at /home/nodeBB/forum/node_modules/mongodb/lib/mongo_client.js:366:13
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
````

**Comment by pitaj** [comment]
You need to run `./nodebb reset -p [plugin name]`

**Comment by pitaj** [comment]
or `./nodebb reset -p` to disable all plugins I think

**Comment by sohrabafard** [comment]
after that I don't have any composer to make reply on a topic 😄

**Comment by sohrabafard** [comment]
I'm going to enable `nodebb-plugin-composer-default`

**Comment by sohrabafard** [comment]
Ok every thing is fine and I don't have any error on replies!

**Comment by sohrabafard** [comment]
**`nodebb-plugin-ignore-users` cause this error**
