### ISSUE TITLE
MongoError: Topology was destroyed

### ISSUE THREAD

**Issue by cheenid** [NodeBB/NodeBB#5726]
Hi,guys 
I got the following issue, when i restart nodebb service using './nodebb restart' , it works for few hours ,then the application crashed with the following exception stack.  Please help me ,thanks. 
- **NodeBB version:** v1.5.1
- **Database type:** mongo 
- **Database version:** 3.2.13
OS:ubuntu 12.04 LTS

when I visit the index page I got this:

 MongoError: Topology was destroyed
    at nextFunction (/root/nodebb/node_modules/mongodb-core/lib/cursor.js:540:25)
    at Cursor.next [as _next] (/root/nodebb/node_modules/mongodb-core/lib/cursor.js:692:3)
    at nextObject (/root/nodebb/node_modules/mongodb/lib/cursor.js:679:8)
    at Cursor.next (/root/nodebb/node_modules/mongodb/lib/cursor.js:269:12)
    at findOne (/root/nodebb/node_modules/mongodb/lib/collection.js:1415:10)
    at Collection.findOne (/root/nodebb/node_modules/mongodb/lib/collection.js:1401:44)
    at Collection.tryCatcher (/root/nodebb/node_modules/bluebird/js/release/util.js:16:23)
    at Collection.ret [as findOneAsync] (eval at makeNodePromisifiedEval (/root/nodebb/node_modules/bluebird/js/release/promisify.js:1:0), <anonymous>:14:23)
    at collectionReady.then.collection (/root/nodebb/node_modules/connect-mongo/src/index.js:195:48)
    at tryCatcher (/root/nodebb/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/nodebb/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/root/nodebb/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/root/nodebb/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/root/nodebb/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/root/nodebb/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/root/nodebb/node_modules/bluebird/js/release/async.js:17:14)

**Comment by julianlam** [comment]
The error suggests your MongoDB database crashed and NodeBB can no longer connect to it.
