### ISSUE TITLE
Upgrading from v1.4.0 to v1.5.x

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/NodeBB#5756]
- **NodeBB version:** 1.5.1
- **NodeBB git hash:** e64104786ffdd8471119dc54660c3fc12f3202a1

- **Database type:** mongo
- **Database version:** v3.4.1

I have switched branch to `v.1.5.x`.

- `npm install`
- `./nodebb upgrade`
- `./nodebb build`
- `./nodebb dev`

As a result, ACP does not work.
<img width="1431" alt="screen shot 2017-06-13 at 10 08 35 pm" src="https://user-images.githubusercontent.com/135263/27112484-80ede394-5085-11e7-8034-b7ea2f3a752e.png">

What am I missing?

**Comment by julianlam** [comment]
Please attach logs of the upgrade and build processes.

Upgrade path should work without a hitch...

**Comment by NicolasSiver** [comment]
Where can I find them?
Or you are asking to do `upgrade` and `build` again, and share console output?

**Comment by pitaj** [comment]
Yes

**Comment by RoiEXLab** [comment]
Interesting, the same thing happened to a colleague of mine.
This error only seems present on Chrome, switching to Firefox seemed to work for him...

**Comment by NicolasSiver** [comment]
@julianlam 

### `./nodebb upgrade`

```
$ ./nodebb upgrade
1. Bringing base dependencies up to date... OK
2. Checking installed plugins for updates... OK
3. Updating NodeBB data store schema...
[deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.

Parsing upgrade scripts... OK | 0 script(s) found, 29 skipped
Upgrade complete!

14/6 18:13:12 [28323] - info: [build] Building in parallel mode
14/6 18:13:12 [28323] - info: [build]         plugin static dirs  build started
14/6 18:13:12 [28323] - info: [build]          requirejs modules  build started
14/6 18:13:12 [28323] - info: [build]           client js bundle  build started
14/6 18:13:12 [28323] - info: [build]            admin js bundle  build started
14/6 18:13:12 [28323] - info: [build]         client side styles  build started
14/6 18:13:12 [28323] - info: [build] admin control panel styles  build started
14/6 18:13:12 [28323] - info: [build]                  templates  build started
14/6 18:13:12 [28323] - info: [build]                  languages  build started
14/6 18:13:12 [28323] - info: [build]                     sounds  build started
14/6 18:13:12 [28323] - info: [build]                     sounds  build completed in 0.395sec
14/6 18:13:12 [28323] - info: [build]         plugin static dirs  build completed in 0.617sec
14/6 18:13:12 [28323] - warn: [plugins] Skipping /Users/nicolas/Documents/Works/JavaScript/NodeBB/node_modules/nodebb-theme-overseers/templates/.DS_Store by plugin nodebb-theme-overseers
14/6 18:13:13 [28323] - warn: [meta/templates] Partial not loaded: partials/requirejs-config.tpl
14/6 18:13:14 [28323] - info: [build]            admin js bundle  build completed in 2.124sec
14/6 18:13:14 [28323] - info: [build]                  templates  build completed in 2.19sec
14/6 18:13:14 [28323] - info: [build]                  languages  build completed in 2.676sec
14/6 18:13:15 [28323] - info: [build]         client side styles  build completed in 3.847sec
14/6 18:13:16 [28323] - info: [build] admin control panel styles  build completed in 4.017sec
14/6 18:13:16 [28323] - info: [build]           client js bundle  build completed in 4.618sec
14/6 18:13:17 [28323] - info: [build]          requirejs modules  build completed in 5.036sec
14/6 18:13:17 [28323] - info: [build] Asset compilation successful. Completed in 5.039sec.
OK

         NodeBB Upgrade Complete!
```

### `./nodebb build`

```
$ ./nodebb build
[deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.
14/6 18:14:24 [28359] - info: [build] Building in parallel mode
14/6 18:14:24 [28359] - info: [build]         plugin static dirs  build started
14/6 18:14:24 [28359] - info: [build]          requirejs modules  build started
14/6 18:14:24 [28359] - info: [build]           client js bundle  build started
14/6 18:14:24 [28359] - info: [build]            admin js bundle  build started
14/6 18:14:24 [28359] - info: [build]         client side styles  build started
14/6 18:14:24 [28359] - info: [build] admin control panel styles  build started
14/6 18:14:24 [28359] - info: [build]                  templates  build started
14/6 18:14:24 [28359] - info: [build]                  languages  build started
14/6 18:14:24 [28359] - info: [build]                     sounds  build started
14/6 18:14:25 [28359] - info: [build]                     sounds  build completed in 0.415sec
14/6 18:14:25 [28359] - info: [build]         plugin static dirs  build completed in 0.686sec
14/6 18:14:25 [28359] - warn: [plugins] Skipping /Users/nicolas/Documents/Works/JavaScript/NodeBB/node_modules/nodebb-theme-overseers/templates/.DS_Store by plugin nodebb-theme-overseers
14/6 18:14:26 [28359] - warn: [meta/templates] Partial not loaded: partials/requirejs-config.tpl
14/6 18:14:26 [28359] - info: [build]            admin js bundle  build completed in 2.068sec
14/6 18:14:27 [28359] - info: [build]                  templates  build completed in 2.4sec
14/6 18:14:27 [28359] - info: [build]                  languages  build completed in 2.908sec
14/6 18:14:28 [28359] - info: [build]         client side styles  build completed in 3.934sec
14/6 18:14:28 [28359] - info: [build] admin control panel styles  build completed in 4.058sec
14/6 18:14:29 [28359] - info: [build]           client js bundle  build completed in 4.6sec
14/6 18:14:29 [28359] - info: [build]          requirejs modules  build completed in 5.116sec
14/6 18:14:29 [28359] - info: [build] Asset compilation successful. Completed in 5.119sec.
```

**Comment by psychobunny** [comment]
Are you using nginx to serve assets? I have a feeling that there is something to do with this. Check your served /nodebb.min.js and compare with the one on your server please :)

**Comment by psychobunny** [comment]
And/or acp min'd files

**Comment by orweinberger** [comment]
I'm having the exact same issue. Upgraded from v1.4.5 to v1.5.1 and no errors while upgrading. @psychobunny I'm not serving anything via nginx, just a regular `./nodebb start` and also tried `./nodebb dev` both load ok but cannot use admin cp

**Comment by pitaj** [comment]
Try opening the ACP in either a different browser or in your browser's private mode. Does it work then? If so, this is a caching problem.

**Comment by NicolasSiver** [comment]
@psychobunny it's a local machine for the development. I just upgraded NodeBB to adjust plugins for compatibility, and can not proceed ;)

@pitaj cache is disabled. I'm always developing with a disabled cache. Note: Firefox does not work either.

**Comment by julianlam** [comment]
Can you upload acp.min.js to pastebin?

**Comment by NicolasSiver** [comment]
`/build/public/acp.min.js` is empty. It has only one string - `undefined`.

<img width="592" alt="screen shot 2017-06-15 at 6 22 01 pm" src="https://user-images.githubusercontent.com/135263/27204174-8ebab31c-51f7-11e7-93f2-f6ee597bb1e0.png">

**Comment by NicolasSiver** [comment]
<img width="346" alt="screen shot 2017-06-15 at 6 22 46 pm" src="https://user-images.githubusercontent.com/135263/27204199-af9a3bd4-51f7-11e7-8172-06014a8039a3.png">

**Comment by julianlam** [comment]
Well, that'd certainly do it. Run ./nodebb plugins?

Let us know which plugins​ you are running

**Comment by NicolasSiver** [comment]
```
$ ./nodebb plugins
16/6 17:48:51 [30778] - info: Active plugins:
	 - nodebb-theme-overseers
	 - nodebb-widget-essentials
	 - nodebb-plugin-spam-be-gone
	 - nodebb-plugin-soundpack-default
	 - nodebb-plugin-mentions
	 - nodebb-plugin-markdown
	 - nodebb-plugin-emoji-extended
	 - nodebb-plugin-composer-default
	 - nodebb-plugin-ns-api
	 - nodebb-plugin-ns-likes
	 - nodebb-plugin-ns-login
	 - nodebb-plugin-ns-points
	 - nodebb-plugin-ns-slugify
	 - nodebb-plugin-write-api
	 - nodebb-plugin-ns-embed
	 - nodebb-plugin-dbsearch
	 - nodebb-plugin-ns-custom-fields
	 - nodebb-plugin-ns-awards
	 - nodebb-widget-ns-birthdays
	 - nodebb-plugin-emailer-mailgun
	 - nodebb-widget-ns-stats
	 - nodebb-plugin-google-analytics
	 - nodebb-plugin-emoji-static
	 - nodebb-plugin-newsletter
	 - nodebb-plugin-emoji-apple
	 - nodebb-plugin-ns-spoiler
	 - nodebb-plugin-ns-twitch-monitor
```

**Comment by paviro** [comment]
I am using nginx to serve assets and I have the same problem after updating to v1.5.x.

```
19/6 01:00:34 [12518] - info: Active plugins: 
	 - nodebb-theme-persona
	 - nodebb-plugin-mentions
	 - nodebb-widget-essentials
	 - nodebb-rewards-essentials
	 - nodebb-plugin-soundpack-default
	 - nodebb-plugin-emoji-extended
	 - nodebb-plugin-emoji-one
	 - nodebb-plugin-dbsearch
	 - nodebb-plugin-poll
	 - nodebb-plugin-pushbullet
	 - nodebb-plugin-recent-cards
	 - nodebb-widget-ns-stats
	 - nodebb-plugin-cards
	 - nodebb-plugin-twitter
	 - nodebb-plugin-2factor
	 - nodebb-plugin-gallery
	 - nodebb-plugin-sso-github
	 - nodebb-plugin-ns-custom-fields
	 - nodebb-plugin-emailer-mailgun
	 - nodebb-plugin-github-card
	 - nodebb-plugin-gravatar
	 - nodebb-plugin-google-analytics
	 - nodebb-plugin-question-and-answer
	 - nodebb-plugin-asset-manager
	 - nodebb-plugin-embed-videos
	 - nodebb-plugin-sanitizehtml
	 - nodebb-plugin-color
	 - nodebb-plugin-codeinput
	 - nodebb-plugin-markdown
	 - nodebb-plugin-ns-embed
	 - nodebb-plugin-ns-spoiler
	 - nodebb-plugin-spam-be-gone
	 - nodebb-plugin-composer-default
	 - nodebb-plugin-newsletter
	 - nodebb-plugin-codepen
```

**Comment by julianlam** [comment]
Reset all plugins and reenable one by one until you find the culprit(s)

**Comment by paviro** [comment]
Looks like `nodebb-plugin-ns-custom-fields` was the problem... Thanks!

**Comment by barisusakli** [comment]
@NicolasSiver should take a look at his plugin then 👍

**Comment by NicolasSiver** [comment]
I have tried different `reset` commands, response is always the same:

```
$ ./nodebb reset all
/Users/nicolas/Documents/Works/JavaScript/NodeBB/node_modules/mongodb/lib/mongo_client.js:408
            throw err
            ^

TypeError: Invalid data, chunk must be a string or buffer, not function
    at WriteStream.Socket.write (net.js:667:11)
    at /Users/nicolas/Documents/Works/JavaScript/NodeBB/src/reset.js:58:19
    at /Users/nicolas/Documents/Works/JavaScript/NodeBB/src/database/mongo.js:105:3
    at connectCallback (/Users/nicolas/Documents/Works/JavaScript/NodeBB/node_modules/mongodb/lib/mongo_client.js:467:5)
    at /Users/nicolas/Documents/Works/JavaScript/NodeBB/node_modules/mongodb/lib/mongo_client.js:405:13
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by pitaj** [comment]
`./nodebb help reset` says this: 
```
$> node ./nodebb help reset
Disable plugins and restore the default theme
Usage: ./nodebb reset {-t|-p|-w|-s|-a}
    -t <theme>  use specified theme
    -p <plugin> disable specified plugin

    -t          use default theme
    -p          disable all but core plugins
    -w          widgets
    -s          settings
    -a          all of the above
```

Try just disabling your plugin first: `./nodebb reset -p ns-custom-fields`

**Comment by NicolasSiver** [comment]
Yep. now it compiles well. Thank you @pitaj
