### ISSUE TITLE
problem in setting up mongodb on cloud9

### ISSUE THREAD

**Issue by abhinov2** [NodeBB/NodeBB#5840]
20/7 15:56:15 [2203] - error: NodeBB could not connect to your Mongo database. Mongo returned the following error: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
20/7 15:56:15 [2203] - warn: NodeBB Setup Aborted.
 MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at null.<anonymous> (/home/ubuntu/workspace/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:327:35)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/home/ubuntu/workspace/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:274:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/home/ubuntu/workspace/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:177:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)

what to do after this .

Help ASAP, urgently needed help

**Comment by julianlam** [comment]
> `error: NodeBB could not connect to your Mongo database. Mongo returned the following error: failed to connect to server`

The error message is right there. Mongo is not running or cannot be reached. Fix that issue first, and direct all follow-up comments to a new topic on our [community support forum](//community.nodebb.org). This is not the place.
