### ISSUE TITLE
Web installer does not work on benchpress.js

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#5928]
**This is a 1.6.0 showstopper**

```
evalmachine.<anonymous>:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token <
    at createScript (vm.js:56:10)
    at Object.runInNewContext (vm.js:93:10)
    at Object.evaluate (/home/julian/nodebb/node_modules/benchpressjs/build/lib/benchpress.js:119:5)
    at fs.readFile.e (/home/julian/nodebb/node_modules/benchpressjs/build/lib/benchpress.js:98:61)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
```

**Comment by julianlam** [comment]
cea4b553fca9a24a6df66d7cba12fee73d527a3f
