### ISSUE TITLE
Upgrade script for v1.6.x fails if logo is an SVG

### ISSUE THREAD

**Issue by An-dz** [NodeBB/NodeBB#5947]
- **NodeBB version:** 1.5.3
- **NodeBB git hash:** b1b02bd
- **Database type:** redis
- **Database version:** 3.2.8

- **Exact steps to cause this issue:**
1. I was using NodeBB 1.4.6 so I upgraded to 1.5.3 first, all went fine
2. Then, I upgraded to 1.6.0 (both upgrades just as the upgrading steps in docs say)
3. When I get to the point to run `./nodebb upgrade` I get an error when generating the email logo

As I could notice from [generate-email-logo.js](https://github.com/NodeBB/NodeBB/blob/master/src/upgrades/1.6.0/generate-email-logo.js) the code does not seem to expect an SVG logo and so it fails.
- **What you expected:**
NodeBB upgrades fine. It should simply use the SVG, generate a PNG from it or simply skip this step.
- **What happened instead:**
Upgrade failed with the following output in the terminal:

```
Generate email logo for use in email header...
error
29/9 04:16:00 [11430] - error: Error: Invalid file signature
    at Parser._parseSignature (/opt/nodebb/node_modules/pngjs/lib/parser.js:50:18)
    at ChunkStream._processRead (/opt/nodebb/node_modules/pngjs/lib/chunkstream.js:174:13)
    at ChunkStream._process (/opt/nodebb/node_modules/pngjs/lib/chunkstream.js:193:14)
    at ChunkStream.write (/opt/nodebb/node_modules/pngjs/lib/chunkstream.js:61:8)
    at ChunkStream.end (/opt/nodebb/node_modules/pngjs/lib/chunkstream.js:74:10)
    at PNG.end (/opt/nodebb/node_modules/pngjs/lib/png.js:98:16)
    at PNG.parse (/opt/nodebb/node_modules/pngjs/lib/png.js:88:8)
    at Jimp.parseBitmap (/opt/nodebb/node_modules/jimp/index.js:297:17)
    at /opt/nodebb/node_modules/jimp/index.js:202:29
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
```

**Comment by julianlam** [comment]
Thanks @An-dz -- looks to be a pretty serious blocker if you're using an SVG logo!

**Comment by An-dz** [comment]
I think you could also take a look if it works with other common formats, like jpeg or gif. I don't remember if NodeBB forbids any type or not.

**Comment by julianlam** [comment]
Any bitmap type should be supported, gifs included.

https://github.com/oliver-moran/jimp/issues/118 suggests SVG is not supported, and as it is currently, attempting to upload SVG will not work in NodeBB anyways.

However if you manually set svg that is fine, and upload script should simply ignore it as it is unable to convert it to PNG.
