### ISSUE TITLE
TypeError: Cannot read property 'writeQueueSize' of null

### ISSUE THREAD

**Issue by Marcel2508** [NodeBB/NodeBB#6049]
- **NodeBB version:** 1.6.1 
- **NodeBB git hash:** #1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf

- **Database type:** mongo
- **Database version:** db version v3.2.17
- **Nginx:** nginx version: nginx/1.10.3 (Ubuntu)
- **Node:** v8.8.0

- **Exact steps to cause this issue:**

The server randomly crashes with the following error code:
```
7/11 05:47:50 [12264] - [32minfo[39m: Initializing NodeBB v1.6.1 http://xxx.xxx.xx
7/11 05:48:20 [12264] - [32minfo[39m: [socket.io] Restricting access to origin: *:*
7/11 05:48:23 [12264] - [32minfo[39m: [plugins/anti-spam-question] Settings loaded
7/11 05:48:23 [12264] - [32minfo[39m: Routes added
7/11 05:48:23 [12264] - [32minfo[39m: NodeBB Ready
7/11 05:48:23 [12264] - [32minfo[39m: Enabling 'trust proxy'
7/11 05:48:23 [12264] - [32minfo[39m: NodeBB is now listening on: 0.0.0.0:xxxx
7/11 17:00:00 [12264] - [32minfo[39m: [user/jobs] Did not send digests (day) because subscription system is disabled.
7/11 22:17:35 [12264] - [31merror[39m:  TypeError: Cannot read property 'writeQueueSize' of null
    at Socket._onTimeout (net.js:401:43)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
7/11 22:17:35 [12264] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
7/11 22:17:35 [12264] - [32minfo[39m: [app] Database connection closed.
7/11 22:17:35 [12264] - [32minfo[39m: [app] Web server closed to connections.
7/11 22:17:35 [12264] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (12264) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
7/11 22:17:44 [15675] - [32minfo[39m: Initializing NodeBB v1.6.1 http://xxx.xxx.xx
7/11 22:18:02 [15675] - [32minfo[39m: [socket.io] Restricting access to origin: *:*
7/11 22:18:05 [15675] - [32minfo[39m: [plugins/anti-spam-question] Settings loaded
7/11 22:18:05 [15675] - [32minfo[39m: Routes added
7/11 22:18:05 [15675] - [32minfo[39m: NodeBB Ready
7/11 22:18:05 [15675] - [32minfo[39m: Enabling 'trust proxy'
7/11 22:18:05 [15675] - [32minfo[39m: NodeBB is now listening on: 0.0.0.0:xxxx
8/11 06:59:17 [15675] - [31merror[39m:  TypeError: Cannot read property 'writeQueueSize' of null
[EOF - till restart]
```
The last line, is the Last Line, logged. The Server process, and the nodebb process both crashed.
Thats the reason, why not auto-restart is happening.

I dont know whats causing this issue, and what I can do against it.

Thanks for your support. I hope this issue was not already mentioned

**Comment by barisusakli** [comment]
@Marcel2508 https://github.com/nodejs/node/issues/16484

Try updating to nodejs 8.9.1

**Comment by Marcel2508** [comment]
Im updating NodeJS now.
Ill reopen this issue if its still not working after the update.
Otherwise: thanks a lot for the fast support :+1:
