### ISSUE TITLE
Ability to resolve a flag with a comment

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/NodeBB#6088]
- **NodeBB version:** 1.6.1

- **NodeBB git hash:** 1dbd038aef9ef5c5ffce78eaa9594ca2231a1dbf

- **Database type:** mongo
- **Database version:** 3.4.9

- **Exact steps to cause this issue:**
1.  Went to Flags Management
2.  Picked a flag
3.  Added a comment
4.  Resolved the flag.  

- **What you expected:** It would be nice to be able to resolve and comment at the same time.  

- **What happened instead:** I currently have to do two separate actions.  

```
18/11 16:30:16 [2896] - warn: Route requested but not found: /assets/socket.io.js.map
18/11 16:30:16 [2896] - error:  TypeError: Cannot read property 'message' of undefined
    at fs.readFile.e (C:\web\nodebb\NodeBB\node_modules\benchpressjs\build\lib\express.js:44:66)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
18/11 16:30:16 [2896] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
18/11 16:30:16 [2896] - info: [app] Database connection closed.
18/11 16:30:16 [2896] - info: [app] Web server closed to connections.
18/11 16:30:16 [2896] - info: [app] Shutdown complete.
```

**Comment by julianlam** [comment]
:point_up: What's with the error?

**Comment by dangerusslee** [comment]
@julianlam Copy and paste error.

**Comment by mySebbe** [comment]
This remains two independent operations in current Core: adding a note uses `POST /flags/:id/notes`, while resolving uses `PUT /flags/:id`. Should the desired behavior be only a UI sequence, or a single API operation that atomically appends the note and changes state/history? The expected result when the note succeeds but the state update fails (and whether an empty note is allowed) needs to be defined before choosing the implementation.
