### ISSUE TITLE
nodebb v1.7.0 crashing/dying after running for some hours

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#6093]
This has happened a few times over the last few days.

- **NodeBB version:**  v1.7.0
- **NodeBB git hash:** 6be3e7cc8c44bdc2b263702b2b0234220f681b08
- **Database type:** mongodb
- **Database version:** v3.4.10
- **Exact steps to cause this issue:**
Start nodebb. After some time the forum goes down.

The log shows an error when this happens:

```
20/11 22:16:37 [26220] - ESC[31merrorESC[39m:  TypeError: Cannot read property 'disabled' of undefined
    at nodebb/src/controllers/composer.js:22:26
    at nextTask (nodebb/node_modules/async/dist/async.js:5297:14)
    at next (nodebb/node_modules/async/dist/async.js:5304:9)
    at nodebb/node_modules/async/dist/async.js:906:16
    at nodebb/node_modules/nodebb-plugin-composer-default/library.js:160:12
    at nodebb/node_modules/async/dist/async.js:3861:9
    at nodebb/node_modules/async/dist/async.js:421:16
    at iterateeCallback (nodebb/node_modules/async/dist/async.js:928:24)
    at nodebb/node_modules/async/dist/async.js:906:16
    at Immediate._onImmediate (nodebb/node_modules/async/dist/async.js:3858:13)
    at runCallback (timers.js:793:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
20/11 22:16:37 [26220] - ESC[32minfoESC[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
20/11 22:16:37 [26220] - ESC[32minfoESC[39m: [app] Database connection closed.
20/11 22:16:37 [26220] - ESC[32minfoESC[39m: [app] Web server closed to connections.
20/11 22:16:37 [26220] - ESC[32minfoESC[39m: [app] Shutdown complete.
20/11 22:16:37 [26226] - ESC[31merrorESC[39m:  TypeError: Cannot read property 'disabled' of undefined
```

config

```
{
    "url": "https://retropie.org.uk/forum",
    "bind_address": "127.0.0.1",
    "secret": "REMOVED",
    "database": "mongo",
    "port": [4567, 4568, 4569, 4570],
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "REMOVED",
        "database": "REMOVED",
        "password": "REMOVED"
    },
    "redis": {
        "host":"127.0.0.1",
        "port":"6379",
        "database": 0
    }
}
```

plugins installed:
```
20/11 22:27:41 [28204] - info: Active plugins: 
	 - nodebb-theme-persona
	 - nodebb-plugin-composer-default
	 - nodebb-plugin-dbsearch
	 - nodebb-widget-essentials
	 - nodebb-plugin-mentions
	 - nodebb-plugin-soundpack-default
	 - nodebb-plugin-spam-be-gone
	 - nodebb-plugin-recent-cards
	 - nodebb-plugin-markdown
	 - nodebb-plugin-ns-embed
	 - nodebb-plugin-gravatar
	 - nodebb-plugin-category-notifications
	 - nodebb-plugin-google-analytics
```

**Comment by barisusakli** [comment]
What version of composer-default?

**Comment by joolswills** [comment]
nodebb-plugin-composer-default

Default composer for NodeBB
Installed 6.0.5 | Latest 6.0.5

**Comment by joolswills** [comment]
thanks.
