### ISSUE TITLE
nodebb v1.7.2 crashed / died 

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#6161]
NodeBB version: v1.7.2
    NodeBB git hash: 5ff5b6c699827efce6823277b95869a776477dd3
    nodejs version: 8.9.3-1nodesource1
    Database type: mongodb
    Database version: v3.4.10
    Exact steps to cause this issue:
    Start nodebb. After some time the forum crashed. Have only seen this once since v1.7.2

```
10/12 22:28:30 [1638] - error:  TypeError: hasTags.every is not a function
    at nodebb/src/search.js:306:26
    at Array.filter (<anonymous>)
    at filterByTags (nodebb/src/search.js:303:17)
    at nodebb/src/search.js:129:12
    at nextTask (nodebb/node_modules/async/dist/async.js:5310:14)
    at next (nodebb/node_modules/async/dist/async.js:5317:9)
    at nodebb/node_modules/async/dist/async.js:958:16
    at nodebb/node_modules/async/dist/async.js:473:16
    at next (nodebb/node_modules/async/dist/async.js:5315:29)
    at nodebb/node_modules/async/dist/async.js:958:16
    at nodebb/src/search.js:263:4
    at nextTask (nodebb/node_modules/async/dist/async.js:5310:14)
    at next (nodebb/node_modules/async/dist/async.js:5317:9)
    at nodebb/node_modules/async/dist/async.js:958:16
    at nodebb/node_modules/async/dist/async.js:3874:9
    at nodebb/node_modules/async/dist/async.js:473:16
10/12 22:28:30 [1638] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
10/12 22:28:30 [1638] - info: [app] Database connection closed.
10/12 22:28:30 [1638] - info: [app] Web server closed to connections.
10/12 22:28:30 [1638] - info: [app] Shutdown complete.
10/12 22:28:31 [1650] - error:  TypeError: hasTags.every is not a function
```

config

```
{
    "url": "https://retropie.org.uk/forum",
    "bind_address": "127.0.0.1",
    "secret": "REMOVED",
    "database": "mongo",
    "port": [4567, 4568, 4569, 4570],
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "REMOVED",
        "database": "REMOVED",
        "password": "REMOVED"
    },
    "redis": {
        "host":"127.0.0.1",
        "port":"6379",
        "database": 0
    }
}
```

plugins installed:
```
	 - nodebb-theme-persona
	 - nodebb-plugin-composer-default
	 - nodebb-plugin-dbsearch
	 - nodebb-widget-essentials
	 - nodebb-plugin-mentions
	 - nodebb-plugin-soundpack-default
	 - nodebb-plugin-spam-be-gone
	 - nodebb-plugin-recent-cards
	 - nodebb-plugin-markdown
	 - nodebb-plugin-ns-embed
	 - nodebb-plugin-gravatar
	 - nodebb-plugin-category-notifications
	 - nodebb-plugin-google-analytics
```

**Comment by julianlam** [comment]
Node version?

**Comment by joolswills** [comment]
Sorry - 8.9.3-1nodesource1

**Comment by joolswills** [comment]
I edited original post - it didn't happen a few times - just once since v1.7.2 - I was copying and pasting from another ticket (since most specs/configs were same etc - apart from nodebb version).
