### ISSUE TITLE
[Crash] TypeError: Cannot read property 'datetime' of undefined

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#6172]
- **NodeBB version:** 1.7.2
- **NodeBB git hash:** 5ff5b6c699827efce6823277b95869a776477dd3

After upgrading to 1.7.2 we see a new error popping up in logs (few times a day) that leads to a crash and child process restart:

```
15/12 08:57:09 [154] - [error]: TypeError: Cannot read property 'datetime' of undefined
at /home/app/nodebb/src/user/auth.js:132:55
at Array.map (<anonymous>)
at /home/app/nodebb/src/user/auth.js:131:25
at nextTask (/home/app/nodebb/node_modules/async/dist/async.js:5310:14)
at next (/home/app/nodebb/node_modules/async/dist/async.js:5317:9)
at /home/app/nodebb/node_modules/async/dist/async.js:958:16
at /home/app/nodebb/src/user/auth.js:127:6
at /home/app/nodebb/node_modules/async/dist/async.js:473:16
at eachOfArrayLike (/home/app/nodebb/node_modules/async/dist/async.js:1043:9)
at eachOf (/home/app/nodebb/node_modules/async/dist/async.js:1103:5)
at Object.eachLimit (/home/app/nodebb/node_modules/async/dist/async.js:3158:5)
at /home/app/nodebb/src/user/auth.js:124:11
at nextTask (/home/app/nodebb/node_modules/async/dist/async.js:5310:14)
at next (/home/app/nodebb/node_modules/async/dist/async.js:5317:9)
at /home/app/nodebb/node_modules/async/dist/async.js:958:16
at /home/app/nodebb/node_modules/async/dist/async.js:1126:9
15/12 08:57:09 [154] - [info]: [app] Shutdown (SIGTERM/SIGINT) Initialised.
15/12 08:57:09 [154] - [info]: [app] Database connection closed.
15/12 08:57:09 [154] - [info]: [app] Web server closed to connections.
15/12 08:57:09 [154] - [info]: [app] Shutdown complete.
[cluster] Child Process (154) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
15/12 08:57:09 [229] - [info]: Initializing NodeBB v1.7.2 https://forums.opera.com
[...]
```

**Comment by barisusakli** [comment]
This was fixed a couple days ago. https://github.com/NodeBB/NodeBB/commit/ee398d397943642f8ffae60826950d3e9fb771f7

**Comment by lots0logs** [comment]
@barisusakli I'm seeing this same error triggered from `/nodebb/src/middleware/user.js:181:19`

**Comment by barisusakli** [comment]
What is your git hash?
