### ISSUE TITLE
we can't start NodeBB after upgrade to master verstion

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#6197]
git pull origin master
./nodebb upgrade

we have this error:

Updating NodeBB...

1. Updating package.json file with defaults...  OK

2. Bringing base dependencies up to date...
up to date in 5.934s
  OK

3. Checking installed plugins for updates...  OK
4. Updating NodeBB data store schema...
Parsing upgrade scripts...
OK | 1 script(s) found, 39 skipped
  → [2017/12/18] Change the schema of simple keys so they don't use value field (mongodb only)...
/home/Nodebb/forum/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

RangeError: Invalid array length
    at Object.Upgrade.incrementProgress [as incr] (/home/Nodebb/forum/src/upgrade.js:212:79)
    at /home/Nodebb/forum/src/upgrades/1.7.3/key_value_schema_change.js:46:18
    at nextTask (/home/Nodebb/forum/node_modules/async/dist/async.js:5310:14)
    at next (/home/Nodebb/forum/node_modules/async/dist/async.js:5317:9)
    at /home/Nodebb/forum/node_modules/async/dist/async.js:958:16
    at handleCallback (/home/Nodebb/forum/node_modules/mongodb/lib/utils.js:120:56)
    at /home/Nodebb/forum/node_modules/mongodb/lib/cursor.js:683:5
    at handleCallback (/home/Nodebb/forum/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorDeadAndNotified (/home/Nodebb/forum/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:505:3)
    at nextFunction (/home/Nodebb/forum/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:658:7)

**Comment by sohrabafard** [comment]
version:  1.7.2
  Node ver: v8.9.1
  git hash: 23dbb42130a4cb0a43dc4abdb4131715721a6edf

  database: mongo
        version: 3.2.11
        engine:  wiredTiger
