### ISSUE TITLE
program.name is not a function while upgrading NodeBB

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB/NodeBB#6226]
- **NodeBB version:**  1.6.1
- **NodeBB git hash:** 95f7b7b8e828e7203af6e6b815358ae973c0dff6
- **New NodeBB version:** 1.7.3
- **New NodeBB git hash:** dabb1e8d6dbeb143976a9ad76d0233daae450467

- **Database type:** redis
- **Database version:** 3.2.9

- **Exact steps to cause this issue:**
1. Upgrade code with git from v1.6.1 to 1.7.3 following the documentation
    1. `git fetch`
    2. `git checkout v1.7.x`
    3. `git merge origin/v1.7.x`
2. Run `./nodebb upgrade`
- **What you expected:**
Upgrade
- **What happened instead:**
```sh
$ ./nodebb upgrade
/www/http/src/cli/index.js:60
	.description('Welcome to NodeBB')
	 ^

TypeError: program.name(...).description is not a function
    at Object.<anonymous> (/www/http/src/cli/index.js:60:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/www/http/nodebb:5:1)
    at Module._compile (module.js:571:32)
```

**Comment by antoine-pous** [comment]
Fixed with `npm i commander` on branch `v1.7.x`
