### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by Doc1337** [NodeBB/NodeBB#6243]
```
net.js:654
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not undefined
    at WriteStream.Socket.write (net.js:654:11)
    at Object.installAll (/var/nodebb/src/cli/package-install.js:33:17)
    at Object.<anonymous> (/var/nodebb/src/cli/index.js:41:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

I followed the guide installed Node v 6 and all stuff I am using ubuntu 16.04 and I just ran ./nodebb setup as root and this happened

**Comment by Doc1337** [comment]
```
root@54977:/var/nodebb# ./nodebb setup
Dependencies not yet installed.
Installing them now...

net.js:654
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not undefined
    at WriteStream.Socket.write (net.js:654:11)
    at Object.installAll (/var/nodebb/src/cli/package-install.js:33:17)
    at Object.<anonymous> (/var/nodebb/src/cli/index.js:41:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
root@54977:/var/nodebb# 
```

full output

**Comment by julianlam** [comment]
Please see @6237 😄

**Comment by Doc1337** [comment]
Thank you 👍
