### ISSUE TITLE
Can't open `registration queue` with `Admin Approval`.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [NodeBB/NodeBB#6265]
NodeBB version: 1.7.3
	1. First open `/admin/settings/user#user-registration`.
	2. Select `Admin Approval`.
        3. A new user post a register requrie.
        4. The administrator try to open the `manager -> registration queue`

And the page not works, here the logs:
```
Missing translation "admin/menu:plugins/emoji"
2018-01-20T08:42:03.799Z [23] - error: Error parsing plugins Error: getaddrinfo EAI_AGAIN packages.nodebb.org:443
    at Object._errnoException (util.js:1024:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  started
```

```
2018-01-20T08:42:43.628Z [23] - error: /general/dashboard
 Error: ENOENT: no such file or directory, open '/usr/src/nodebb/build/public/templates/admin/general/dashboard.tpl'
Error: Failed to lookup view "500" in views directory "/usr/src/nodebb/build/public/templates"
    at Function.render (/usr/src/nodebb/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/usr/src/nodebb/node_modules/express/lib/response.js:1008:7)
    at content (/usr/src/nodebb/src/middleware/render.js:83:15)
    at /usr/src/nodebb/node_modules/async/dist/async.js:3866:24
    at replenish (/usr/src/nodebb/node_modules/async/dist/async.js:998:17)
    at /usr/src/nodebb/node_modules/async/dist/async.js:1002:9
    at eachOfLimit (/usr/src/nodebb/node_modules/async/dist/async.js:1027:24)
    at /usr/src/nodebb/node_modules/async/dist/async.js:1032:16
    at eachOf (/usr/src/nodebb/node_modules/async/dist/async.js:1103:5)
    at _parallel (/usr/src/nodebb/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit [as parallel] (/usr/src/nodebb/node_modules/async/dist/async.js:3948:5)
    at async.waterfall.str (/usr/src/nodebb/src/middleware/render.js:78:12)
    at nextTask (/usr/src/nodebb/node_modules/async/dist/async.js:5310:14)
    at next (/usr/src/nodebb/node_modules/async/dist/async.js:5317:9)
    at /usr/src/nodebb/node_modules/async/dist/async.js:958:16
    at /usr/src/nodebb/node_modules/async/dist/async.js:473:16
```

```
2018-01-20T08:44:23.843Z [55] - error:  TypeError: next is not a function
    at /usr/src/nodebb/src/socket.io/admin.js:86:4
    at nextTask (/usr/src/nodebb/node_modules/async/dist/async.js:5310:14)
    at next (/usr/src/nodebb/node_modules/async/dist/async.js:5317:9)
    at /usr/src/nodebb/node_modules/async/dist/async.js:958:16
    at /usr/src/nodebb/src/meta/build.js:215:3
    at /usr/src/nodebb/node_modules/async/dist/async.js:3874:9
    at /usr/src/nodebb/node_modules/async/dist/async.js:473:16
    at replenish (/usr/src/nodebb/node_modules/async/dist/async.js:993:25)
    at iterateeCallback (/usr/src/nodebb/node_modules/async/dist/async.js:983:17)
    at /usr/src/nodebb/node_modules/async/dist/async.js:958:16
    at /usr/src/nodebb/node_modules/async/dist/async.js:3871:13
    at /usr/src/nodebb/node_modules/async/dist/async.js:473:16
    at next (/usr/src/nodebb/node_modules/async/dist/async.js:5315:29)
    at /usr/src/nodebb/node_modules/async/dist/async.js:958:16
    at /usr/src/nodebb/node_modules/graceful-fs/graceful-fs.js:99:16
    at /usr/src/nodebb/node_modules/graceful-fs/graceful-fs.js:43:10
```

```
2018-01-20T08:47:34.717Z [71] - error:  Error: connect ETIMEDOUT 192.124.249.168:80
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```

**Comment by julianlam** [comment]
Rebuild templates: `./nodebb build tpl`, restart NodeBB, and try again

**Comment by zhengxiaoyao0716** [comment]
@julianlam thanks, it works now.

**Comment by blueboy09** [comment]
The error in output.log is as follows.
```
2018-04-04T18:50:15.709Z` [12176] - ^[[32minfo^[[39m: Routes added
2018-04-04T18:50:15.711Z [12176] - ^[[32minfo^[[39m: NodeBB Ready
2018-04-04T18:50:15.715Z [12176] - ^[[32minfo^[[39m: Enabling 'trust proxy'
2018-04-04T18:50:15.718Z [12176] - ^[[32minfo^[[39m: NodeBB is now listening on: 0.0.0.0:4567
2018-04-04T18:58:07.033Z [12176] - ^[[31merror^[[39m:  Error: connect ETIMEDOUT 192.124.249.168:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
2018-04-04T18:59:04.375Z [12176] - ^[[31merror^[[39m:  Error: connect ETIMEDOUT 192.124.249.168:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
```
