### ISSUE TITLE
Unable to setup. child_process.js:516

### ISSUE THREAD

**Issue by KyleTryon** [NodeBB/NodeBB#6289]
Following this doc on Ubuntu 16.04 on AWS https://docs.nodebb.org/installing/os/ubuntu/

```
ubuntu@ip-172-31-23-167:~/nodebb$ ./nodebb setup
package.json not found.
Populating package.json...
OK
Dependencies outdated or not yet installed.
Installing them now...


> uws@0.14.5 install /home/ubuntu/nodebb/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0



child_process.js:516
    throw err;
    ^

Error: Command failed: npm install --production
    at checkExecSyncError (child_process.js:473:13)
    at Object.execSync (child_process.js:513:13)
    at Object.installAll (/home/ubuntu/nodebb/src/cli/package-install.js:45:8)
    at Object.<anonymous> (/home/ubuntu/nodebb/src/cli/index.js:58:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

- **NodeBB version:**  1.7.2
- **NodeBB git hash:** fad0c5f

**Comment by pitaj** [comment]
What version of Node and npm? Also, why are you installing v1.7.2 instead of the latest version (v1.7.4)? If you cloned from the branch `v1.7.x` then you should have got v1.7.4

**Comment by KyleTryon** [comment]
mistyped .2, should be .4 yes.

I am following this guide precisely. 

npm/npm
```
ubuntu@ip-172-31-14-226:~/nodebb$ node -v
v6.12.3
ubuntu@ip-172-31-14-226:~/nodebb$ npm -v
3.10.10
ubuntu@ip-172-31-14-226:~/nodebb$
```

Started a new AWS container Ubuntu 16.04 and followed this guide until step 

` ./nodebb setup`

```
 ./nodebb setup
package.json not found.
Populating package.json...
OK
Dependencies outdated or not yet installed.
Installing them now...


> uws@0.14.5 install /home/ubuntu/nodebb/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0



child_process.js:516
    throw err;
    ^

Error: Command failed: npm install --production
    at checkExecSyncError (child_process.js:473:13)
    at Object.execSync (child_process.js:513:13)
    at Object.installAll (/home/ubuntu/nodebb/src/cli/package-install.js:45:8)
    at Object.<anonymous> (/home/ubuntu/nodebb/src/cli/index.js:58:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by pitaj** [comment]
Hmmm. Can you try running `npm install` and see what that outputs? It could be that node-gyp is failing.

**Comment by barisusakli** [comment]
@KyleTryon can you apply the above commit and let me know what about you get?

**Comment by nodebb-misty** [comment]
Issue closed due to inactivity.

----

*This is an automated message. If you feel this action was in error, please comment on this issue so it can be looked at again*
