### ISSUE TITLE
Edit Post doesn't work in v1.7.5

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#6324]
- **NodeBB version:** 1.7.5
- **NodeBB git hash:** 

- **Database type:** mongodb
- **Database version:** db version v3.2.19

- **Exact steps to cause this issue:** edit a post and try to save it

- **What you expected:** saved changes

- **What happened instead:** nothing was saved

**Comment by barisusakli** [comment]
Works fine for me, any errors in your browser/server logs?

**Comment by awunnenb** [comment]
There is nothing in the logs but there is an nodebb-popup at the bottom of the page with "... lost connection to nodebb..." every time i try to save. The popup hides to fast to read it complete or take a screenshot.

**Comment by barisusakli** [comment]
Sounds like your socket connection to the forum is not working, if you open the browser console F12 in chrome you should see errors. You prolly have something misconfigured (nginx,proxy settings etc). Feel free to post at https://community.nodebb.org/category/16/technical-support if you can't figure it out.

**Comment by awunnenb** [comment]
i have downgraded to v.1.7.4 and everything works fine. In my opinion something is wrong with v1.7.5.

**Comment by FinancedHydra** [comment]
@barisusakli We have the same issue appear as soon as we updated to v1.7.5 and we do have server log errors.

**Error**:
```
2018-02-18T17:56:44.986Z [1466] - error:  TypeError: Cannot read property 'tid' of undefined
    at editMainPost (/opt/NodeBB/src/posts/edit.js:84:21)
    at topic (/opt/NodeBB/src/posts/edit.js:58:7)
    at /opt/NodeBB/node_modules/async/dist/async.js:3866:24
    at replenish (/opt/NodeBB/node_modules/async/dist/async.js:998:17)
    at /opt/NodeBB/node_modules/async/dist/async.js:1002:9
    at eachOfLimit (/opt/NodeBB/node_modules/async/dist/async.js:1027:24)
    at /opt/NodeBB/node_modules/async/dist/async.js:1032:16
    at eachOf (/opt/NodeBB/node_modules/async/dist/async.js:1103:5)
    at _parallel (/opt/NodeBB/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit [as parallel] (/opt/NodeBB/node_modules/async/dist/async.js:3948:5)
    at async.waterfall.results (/opt/NodeBB/src/posts/edit.js:53:11)
    at nextTask (/opt/NodeBB/node_modules/async/dist/async.js:5310:14)
    at next (/opt/NodeBB/node_modules/async/dist/async.js:5317:9)
    at /opt/NodeBB/node_modules/async/dist/async.js:958:16
    at /opt/NodeBB/node_modules/async/dist/async.js:473:16
    at /opt/NodeBB/node_modules/async/dist/async.js:2507:9
2018-02-18T17:56:44.988Z [1466] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-02-18T17:56:44.991Z [1466] - info: [app] Database connection closed.
2018-02-18T17:56:44.992Z [1466] - info: [app] Web server closed to connections.
2018-02-18T17:56:44.992Z [1466] - info: [app] Shutdown complete.
2018-02-18T17:56:46.326Z [2128] - info: Initializing NodeBB v1.7.5 https://forums.fogproject.org
```

**Server Information**:
- **NodeBB git hash**: 2b95b1339792676bfbcc5f973567919dfb284fbb
- **Web server type**: nginx reverse proxy
- **Database type**: mongodb
- **Exact steps to cause this issue**: edit a post and try to save it

**Comment by pitaj** [comment]
What plugins are you running? `./nodebb plugins`

**Comment by barisusakli** [comment]
Make sure you have `nodebb-plugin-spam-be-gone@0.5.3`

**Comment by FinancedHydra** [comment]
@barisusakli manually updating that plugin solved the issue, thanks! (The plugin admin page had stale cache, reporting v0.5.2 as the latest)
