### ISSUE TITLE
nodebb problem

### ISSUE THREAD

**Issue by xedom** [NodeBB/NodeBB#6376]
hi,
someone can help me?
```
Hit Ctrl-C to exit


    at eachOfLimit (/root/nodebb/node_modules/async/dist/async.js:1027:24)
    at /root/nodebb/node_modules/async/dist/async.js:1032:16
    at Object.reduce (/root/nodebb/node_modules/async/dist/async.js:2501:5)
    at fireFilterHook (/root/nodebb/src/plugins/hooks.js:107:9)
    at Object.Plugins.fireHook (/root/nodebb/src/plugins/hooks.js:87:4)
    at /root/nodebb/src/widgets/index.js:77:12
    at nextTask (/root/nodebb/node_modules/async/dist/async.js:5310:14)
    at next (/root/nodebb/node_modules/async/dist/async.js:5317:9)
    at /root/nodebb/node_modules/async/dist/async.js:958:16
    at async.waterfall.userLang (/root/nodebb/src/widgets/index.js:71:5)
```

**Comment by julianlam** [comment]
Please follow the issue template guidelines. We can't help you like this.

**Comment by barisusakli** [comment]
We need to see the beginning of the stack trace to help, open the file logs/output.log and paste the rest of the error.
