### ISSUE TITLE
uploading certain content as cover image crashes nodebb

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/NodeBB#6379]
seems like a issue in jimp or one of it's dependencies.

use `socket.emit("user.updateCover", {uid: "1", imageData: "<data>"});`

for certain data this results in 

```
Error: There are some read requests waiting on finished stream
    at module.exports.ChunkStream._end (c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\pngjs\lib\chunkstream.js:100:7)
    at module.exports.ChunkStream.end (c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\pngjs\lib\chunkstream.js:86:10)
    at exports.PNG.PNG.end (c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\pngjs\lib\png.js:98:16)
    at exports.PNG.PNG.parse (c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\pngjs\lib\png.js:88:8)
    at Jimp.parseBitmap (c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\jimp\index.js:297:17)
    at c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\jimp\index.js:202:29
    at c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
2018-03-22T12:38:44.435Z [9632] - error:  Error: invalid block type
    at Inflate.zlibOnError (zlib.js:153:15)
```

**Comment by barisusakli** [comment]
https://github.com/oliver-moran/jimp/issues/420

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/pull/6682
