### ISSUE TITLE
Recent / unread not responding after upgrade to v1.8.1

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#6381]
- **NodeBB version:** v1.8.1
- **NodeBB git hash:** ad8e121f54fa775d224fcf42c95d30837a54cbb4
- **Database type:** mongo or redis mongodb
- **Database version:** 3.4.10

```
./nodebb stop
Updated to v1.8.1 (git pull on 1.8.x branch)
./nodebb upgrade
,/nodebb start

Navigate to https://retropie.org.uk/forum/unread

the page never completes loading. Other parts seem fine.
```

see the following in the nodebb log - may be relevant or not. (Relates to search so I assume it's not but thought to post it anyway - possibly it's another issue)

```
(note i removed the full install path from log)
2018-03-22T13:54:35.570Z [18805] - error: /forum/api/search
 TypeError: Cannot read property 'split' of undefined
    at Object.exports.search (nodebb/node_modules/nodebb-plugin-dbsearch/lib/mongo.js:71:27)
    at Object.search.searchQuery [as method] (nodebb/node_modules/nodebb-plugin-dbsearch/lib/dbsearch.js:156:5)
    at nodebb/src/plugins/hooks.js:115:12
    at nodebb/node_modules/async/dist/async.js:2502:9
    at replenish (nodebb/node_modules/async/dist/async.js:998:17)
    at nodebb/node_modules/async/dist/async.js:1002:9
    at eachOfLimit (nodebb/node_modules/async/dist/async.js:1027:24)
    at nodebb/node_modules/async/dist/async.js:1032:16
    at Object.reduce (nodebb/node_modules/async/dist/async.js:2501:5)
    at fireFilterHook (nodebb/src/plugins/hooks.js:107:9)
    at Object.Plugins.fireHook (nodebb/src/plugins/hooks.js:87:4)
    at Object.search.searchQuery (nodebb/src/search.js:435:10)
    at doSearch (nodebb/src/search.js:60:13)
    at pids (nodebb/src/search.js:67:6)
    at nodebb/node_modules/async/dist/async.js:3866:24
    at replenish (nodebb/node_modules/async/dist/async.js:998:17)
```

**Comment by joolswills** [comment]
Strange it seems to be working now but I am seeing errors in firebug - are these related ?

```
Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Resource URL: https://retropie.org.uk/forum/assets/src/modules/pulling.js?v=40n19njc5m1
Source Map URL: node_modules/pulling/build/pulling-drawer.js.map[Learn More]
Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Resource URL: https://retropie.org.uk/forum/assets/src/modules/composer/drafts.js?v=40n19njc5m1
Source Map URL: node_modules/nodebb-plugin-composer-default/static/lib/composer/drafts.js.map[Learn More]
Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Resource URL: https://retropie.org.uk/forum/assets/src/modules/sounds.js?v=40n19njc5m1
Source Map URL: public/src/modules/sounds.js.map[Learn More]
Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Resource URL: https://retropie.org.uk/forum/assets/src/client/chats/recent.js?v=40n19njc5m1
Source Map URL: public/src/client/chats/recent.js.map[Learn More]
Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Resource URL: https://retropie.org.uk/forum/assets/src/client/chats/messages.js?v=40n19njc5m1
Source Map URL: public/src/client/chats/messages.js.map[Learn More]
Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Resource URL: https://retropie.org.uk/forum/assets/src/client/chats/search.js?v=40n19njc5m1
Source Map URL: public/src/client/chats/search.js.map[Learn More]
Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Resource URL: https://retropie.org.uk/forum/assets/src/modules/scrollStop.js?v=40n19njc5m1
Source Map URL: public/src/modules/scrollStop.js.map[Learn More]
```

**Comment by julianlam** [comment]
@pitaj any thoughts re: pulling?

**Comment by pitaj** [comment]
Looks like the minify mucked with the sourcemaps.

**Comment by barisusakli** [comment]
The search error is from dbsearch I will fix it now.

**Comment by barisusakli** [comment]
nodebb-plugin-dbsearch@2.0.11 fixes the search error

**Comment by barisusakli** [comment]
Let us know if this happens again.

**Comment by joolswills** [comment]
thanks.
