### ISSUE TITLE
 Error: Render failed for template footer

### ISSUE THREAD

**Issue by zrweng** [NodeBB/NodeBB#6443]
Install NodeBB from Github（Centos7+Mongodb 3.6.5) 

./nodebb start ,access 127.0.0.1:4567 Internal Server Error

output.log  
---------------------------------------------------------------

Error: Render failed for template <footer id="footer" :
 Script execution timed out.
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at Object.runInNewContext (vm.js:135:38)
    at evaluate (/root/NodeBB/node_modules/benchpressjs/build/lib/evaluate.js:17:6)
    at precompile.then.code (/root/NodeBB/node_modules/benchpressjs/build/lib/compile-render.js:34:74)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

How to resolve this problem？

**Comment by pitaj** [comment]
Have you tried `./nodebb stop && ./nodebb build && ./nodebb start`?

**Comment by zrweng** [comment]
Thanks @pitaj , executing this command resolve the problem!
