### ISSUE TITLE
[acp] Failed to fetch latest version TypeError: The header content contains invalid characters

### ISSUE THREAD

**Issue by Relsoul** [NodeBB/NodeBB#6447]
- **NodeBB version:** 1.8.1
- **NodeBB git hash:** 

- **Database type:** mongo or redis
- **Database version:**  redis

- **Exact steps to cause this issue:**

get /admin and cat log 
``
2018-04-11T10:59:26.650Z [10773] - error: [acp] Failed to fetch latest version TypeError: The header content contains invalid characters
    at ClientRequest.setHeader (_http_outgoing.js:374:11)
    at new ClientRequest (_http_client.js:131:14)
    at Object.request (http.js:26:10)
    at Object.request (https.js:206:15)
    at Request.start (/home/wwwroot/NodeBB/node_modules/request/request.js:748:32)
    at Request.end (/home/wwwroot/NodeBB/node_modules/request/request.js:1512:10)
    at end (/home/wwwroot/NodeBB/node_modules/request/request.js:561:14)
    at Immediate.<anonymous> (/home/wwwroot/NodeBB/node_modules/request/request.js:575:7)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Missing translation "admin/menu:alerts.version"
Missing translation "admin/menu:alerts.version"
Missing translation "admin/general/dashboard:latest-lookup-failed"
2018-04-11T11:01:00.731Z [10773] - error: [acp] Failed to fetch latest version TypeError: The header content contains invalid characters
    at ClientRequest.setHeader (_http_outgoing.js:374:11)
    at new ClientRequest (_http_client.js:131:14)
    at Object.request (http.js:26:10)
    at Object.request (https.js:206:15)
    at Request.start (/home/wwwroot/NodeBB/node_modules/request/request.js:748:32)
    at Request.end (/home/wwwroot/NodeBB/node_modules/request/request.js:1512:10)
    at end (/home/wwwroot/NodeBB/node_modules/request/request.js:561:14)
    at Immediate.<anonymous> (/home/wwwroot/NodeBB/node_modules/request/request.js:575:7)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Missing translation "admin/menu:alerts.version"
Missing translation "admin/menu:alerts.version"
Missing translation "admin/general/dashboard:latest-lookup-failed"

```

- **What you expected:**
<!-- e.g. I expected *abc* to *xyz* -->
- **What happened instead:**
<!-- e.g. Instead, I got *zyx* and NodeBB set fire to my house -->

<!-- Thank you! -->

**Comment by Relsoul** [comment]
ok use ./nodebb reset -a

**Comment by Relsoul** [comment]
but i open solr plugin  and view /admin then system is over 500

**Comment by a632079** [comment]
could you give us your error log?

**Comment by Relsoul** [comment]
@a632079 
```
2018-04-11T13:12:19.056Z [20612] - error: [acp] Failed to fetch latest version TypeError: The header content contains invalid characters
    at ClientRequest.setHeader (_http_outgoing.js:374:11)
    at new ClientRequest (_http_client.js:131:14)
    at Object.request (http.js:26:10)
    at Object.request (https.js:206:15)
    at Request.start (/home/wwwroot/NodeBB/node_modules/request/request.js:748:32)
    at Request.end (/home/wwwroot/NodeBB/node_modules/request/request.js:1512:10)
    at end (/home/wwwroot/NodeBB/node_modules/request/request.js:561:14)
    at Immediate.<anonymous> (/home/wwwroot/NodeBB/node_modules/request/request.js:575:7)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
2018-04-11T13:12:19.065Z [20612] - error: [acp] Failed to fetch latest version TypeError: The header content contains invalid characters
    at ClientRequest.setHeader (_http_outgoing.js:374:11)
    at new ClientRequest (_http_client.js:131:14)
    at Object.request (http.js:26:10)
    at Object.request (https.js:206:15)
    at Request.start (/home/wwwroot/NodeBB/node_modules/request/request.js:748:32)
    at Request.end (/home/wwwroot/NodeBB/node_modules/request/request.js:1512:10)
    at end (/home/wwwroot/NodeBB/node_modules/request/request.js:561:14)
    at Immediate.<anonymous> (/home/wwwroot/NodeBB/node_modules/request/request.js:575:7)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Missing translation "admin/menu:alerts.version"
Missing translation "admin/menu:alerts.version"
Missing translation "admin/general/dashboard:latest-lookup-failed"

```

**Comment by julianlam** [comment]
Did you run `./nodebb build` after activating the Solr plugin?

**Comment by Relsoul** [comment]
@pitaj Unable to access the admin, it looks like timeout,not error log ...504 Gateway Time-out

**Comment by Relsoul** [comment]
@pitaj But I visit the home page, It is no problem, when i visit admin so... 504 Gateway Time-out

**Comment by pitaj** [comment]
So when the door plugin is enabled, your forum breaks, but when you disable it, your forum works fine? In that case, it's a problem with the solr plugin.

**Comment by Relsoul** [comment]
@pitaj yes... I open other plugins and restart ... is no problem... so i also tried reinstalling the solr plugin.. But still have problems. I can only choose to close the solr plugin

**Comment by Relsoul** [comment]
@pitaj @julianlam @a632079 Thank you for your answers

**Comment by Relsoul** [comment]
i delete redis solr plugin key and nodee is normal
