### ISSUE TITLE
Nodebb not running

### ISSUE THREAD

**Issue by abhinov2** [NodeBB/NodeBB#6453]
NodeBB v1.8.2 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

2018-04-13T16:24:53.081Z [2933] - info: Initializing NodeBB v1.8.2 http://sample.com/doubtforum
2018-04-13T16:24:53.083Z [2933] - verbose: * using mongo store at 127.0.0.1:27017
2018-04-13T16:24:53.084Z [2933] - verbose: * using themes stored in: /home/aaravkr/nodebb/NodeBB/node_modules
2018-04-13T16:24:53.183Z [2933] - warn: You have no mongo username/password setup!
2018-04-13T16:24:54.587Z [2933] - verbose: [minifier] utilizing a maximum of 3 additional threads
2018-04-13T16:24:54.606Z [2933] - verbose: Checking dependencies for outdated modules
2018-04-13T16:24:54.948Z [2933] - warn: You have no mongo username/password setup!
2018-04-13T16:24:54.963Z [2933] - verbose: [notifications.init] Registering jobs.
2018-04-13T16:24:54.964Z [2933] - verbose: [user/jobs] (Re-)starting user jobs...
2018-04-13T16:24:54.965Z [2933] - verbose: [user/jobs] Starting job (digest.daily)
2018-04-13T16:24:54.966Z [2933] - verbose: [user/jobs] Starting job (digest.weekly)
2018-04-13T16:24:54.967Z [2933] - verbose: [user/jobs] Starting job (digest.monthly)
2018-04-13T16:24:54.967Z [2933] - verbose: [user/jobs] Starting job (reset.clean)
2018-04-13T16:24:54.968Z [2933] - verbose: [user/jobs] 4 jobs started
2018-04-13T16:24:54.968Z [2933] - verbose: [emailer] Setting up SMTP fallback transport
2018-04-13T16:24:54.997Z [2933] - verbose: [emailer] Built custom email templates
2018-04-13T16:24:54.999Z [2933] - info: [themes] Using theme nodebb-theme-persona
2018-04-13T16:24:55.000Z [2933] - verbose: [plugins] Initializing plugins system
2018-04-13T16:24:55.007Z [2933] - verbose: [plugins] Loaded plugin: nodebb-plugin-composer-default
2018-04-13T16:24:55.009Z [2933] - verbose: [plugins] Loaded plugin: nodebb-theme-persona
2018-04-13T16:24:55.040Z [2933] - verbose: [plugins] Loaded plugin: nodebb-plugin-markdown
2018-04-13T16:24:55.062Z [2933] - verbose: [plugins] Loaded plugin: nodebb-plugin-mentions
2018-04-13T16:24:55.064Z [2933] - verbose: [plugins] Loaded plugin: nodebb-widget-essentials
2018-04-13T16:24:55.067Z [2933] - verbose: [plugins] Loaded plugin: nodebb-rewards-essentials
2018-04-13T16:24:55.069Z [2933] - verbose: [plugins] Found 3 sound file(s) for plugin nodebb-plugin-soundpack-default
2018-04-13T16:24:55.069Z [2933] - verbose: [plugins] Loaded plugin: nodebb-plugin-soundpack-default
2018-04-13T16:24:55.154Z [2933] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji
2018-04-13T16:24:55.167Z [2933] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji-android
2018-04-13T16:24:55.168Z [2933] - info: [plugins] Plugins OK
2018-04-13T16:24:55.201Z [2933] - verbose: [hotswap] Router with id plugins replaced successfully
2018-04-13T16:24:55.201Z [2933] - verbose: [plugins] All plugins reloaded and rerouted
2018-04-13T16:24:55.201Z [2933] - verbose: [hotswap] Router with id auth replaced successfully
2018-04-13T16:24:55.202Z [2933] - info: Routes added
2018-04-13T16:24:55.204Z [2933] - verbose: [meta/blacklist] Loading 0 blacklist rule(s)
2018-04-13T16:24:55.204Z [2933] - info: NodeBB Ready
2018-04-13T16:24:55.211Z [2933] - info: Enabling 'trust proxy'
2018-04-13T16:24:55.216Z [2933] - error: NodeBB address in use, exiting... Error: listen EADDRINUSE 0.0.0.0:4567
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at Server.setupListenHandle [as _listen2] (net.js:1367:14)
at listenInCluster (net.js:1408:12)
at doListen (net.js:1517:7)
at _combinedTickCallback (internal/process/next_tick.js:141:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
2018-04-13T16:24:55.217Z [2933] - error: Error: listen EADDRINUSE 0.0.0.0:4567
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at Server.setupListenHandle [as _listen2] (net.js:1367:14)
at listenInCluster (net.js:1408:12)
at doListen (net.js:1517:7)
at _combinedTickCallback (internal/process/next_tick.js:141:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
2018-04-13T16:24:55.217Z [2933] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-04-13T16:24:55.218Z [2933] - error: Error: Not running
at Server.close (net.js:1620:12)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:111:20)
at Server.emit (events.js:208:7)
at emitCloseNT (net.js:1671:8)
at _combinedTickCallback (internal/process/next_tick.js:135:11)
at Immediate._tickCallback (internal/process/next_tick.js:180:9)
at runCallback (timers.js:794:20)
at tryOnImmediate (timers.js:752:5)
at processImmediate [as _immediateCallback] (timers.js:729:5)
[cluster] Child Process (2933) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2018-04-13T16:24:55.777Z [2947] - info: Initializing NodeBB v1.8.2 http://sample.com/doubtforum
2018-04-13T16:24:55.780Z [2947] - verbose: * using mongo store at 127.0.0.1:27017
2018-04-13T16:24:55.780Z [2947] - verbose: * using themes stored in: /home/aaravkr/nodebb/NodeBB/node_modules
2018-04-13T16:24:55.879Z [2947] - warn: You have no mongo username/password setup!
2018-04-13T16:24:57.195Z [2947] - verbose: [minifier] utilizing a maximum of 3 additional threads
2018-04-13T16:24:57.212Z [2947] - verbose: Checking dependencies for outdated modules
2018-04-13T16:24:57.508Z [2947] - warn: You have no mongo username/password setup!
2018-04-13T16:24:57.522Z [2947] - verbose: [notifications.init] Registering jobs.
2018-04-13T16:24:57.523Z [2947] - verbose: [user/jobs] (Re-)starting user jobs...
2018-04-13T16:24:57.523Z [2947] - verbose: [user/jobs] Starting job (digest.daily)
2018-04-13T16:24:57.524Z [2947] - verbose: [user/jobs] Starting job (digest.weekly)
2018-04-13T16:24:57.525Z [2947] - verbose: [user/jobs] Starting job (digest.monthly)
2018-04-13T16:24:57.525Z [2947] - verbose: [user/jobs] Starting job (reset.clean)
2018-04-13T16:24:57.525Z [2947] - verbose: [user/jobs] 4 jobs started
2018-04-13T16:24:57.526Z [2947] - verbose: [emailer] Setting up SMTP fallback transport
2018-04-13T16:24:57.556Z [2947] - verbose: [emailer] Built custom email templates
2018-04-13T16:24:57.558Z [2947] - info: [themes] Using theme nodebb-theme-persona
2018-04-13T16:24:57.558Z [2947] - verbose: [plugins] Initializing plugins system
2018-04-13T16:24:57.564Z [2947] - verbose: [plugins] Loaded plugin: nodebb-plugin-composer-default
2018-04-13T16:24:57.567Z [2947] - verbose: [plugins] Loaded plugin: nodebb-theme-persona
2018-04-13T16:24:57.594Z [2947] - verbose: [plugins] Loaded plugin: nodebb-plugin-markdown
2018-04-13T16:24:57.610Z [2947] - verbose: [plugins] Loaded plugin: nodebb-plugin-mentions
2018-04-13T16:24:57.612Z [2947] - verbose: [plugins] Loaded plugin: nodebb-widget-essentials
2018-04-13T16:24:57.615Z [2947] - verbose: [plugins] Loaded plugin: nodebb-rewards-essentials
2018-04-13T16:24:57.616Z [2947] - verbose: [plugins] Found 3 sound file(s) for plugin nodebb-plugin-soundpack-default
2018-04-13T16:24:57.616Z [2947] - verbose: [plugins] Loaded plugin: nodebb-plugin-soundpack-default
2018-04-13T16:24:57.693Z [2947] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji
2018-04-13T16:24:57.705Z [2947] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji-android
2018-04-13T16:24:57.706Z [2947] - info: [plugins] Plugins OK
2018-04-13T16:24:57.738Z [2947] - verbose: [hotswap] Router with id plugins replaced successfully
2018-04-13T16:24:57.738Z [2947] - verbose: [plugins] All plugins reloaded and rerouted
2018-04-13T16:24:57.739Z [2947] - verbose: [hotswap] Router with id auth replaced successfully
2018-04-13T16:24:57.739Z [2947] - info: Routes added
2018-04-13T16:24:57.742Z [2947] - verbose: [meta/blacklist] Loading 0 blacklist rule(s)
2018-04-13T16:24:57.742Z [2947] - info: NodeBB Ready
2018-04-13T16:24:57.748Z [2947] - info: Enabling 'trust proxy'
2018-04-13T16:24:57.752Z [2947] - error: NodeBB address in use, exiting... Error: listen EADDRINUSE 0.0.0.0:4567
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at Server.setupListenHandle [as _listen2] (net.js:1367:14)
at listenInCluster (net.js:1408:12)
at doListen (net.js:1517:7)
at _combinedTickCallback (internal/process/next_tick.js:141:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
2018-04-13T16:24:57.752Z [2947] - error: Error: listen EADDRINUSE 0.0.0.0:4567
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at Server.setupListenHandle [as _listen2] (net.js:1367:14)
at listenInCluster (net.js:1408:12)
at doListen (net.js:1517:7)
at _combinedTickCallback (internal/process/next_tick.js:141:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
2018-04-13T16:24:57.753Z [2947] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-04-13T16:24:57.754Z [2947] - error: Error: Not running
at Server.close (net.js:1620:12)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:111:20)
at Server.emit (events.js:208:7)
at emitCloseNT (net.js:1671:8)
at _combinedTickCallback (internal/process/next_tick.js:135:11)
at Immediate._tickCallback (internal/process/next_tick.js:180:9)
at runCallback (timers.js:794:20)
at tryOnImmediate (timers.js:752:5)
at processImmediate [as _immediateCallback] (timers.js:729:5)
[cluster] Child Process (2947) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2018-04-13T16:24:58.309Z [2961] - info: Initializing NodeBB v1.8.2 http://sample.com/doubtforum
2018-04-13T16:24:58.312Z [2961] - verbose: * using mongo store at 127.0.0.1:27017
2018-04-13T16:24:58.312Z [2961] - verbose: * using themes stored in: /home/aaravkr/nodebb/NodeBB/node_modules
2018-04-13T16:24:58.405Z [2961] - warn: You have no mongo username/password setup!
2018-04-13T16:24:59.715Z [2961] - verbose: [minifier] utilizing a maximum of 3 additional threads
2018-04-13T16:24:59.733Z [2961] - verbose: Checking dependencies for outdated modules
2018-04-13T16:25:00.070Z [2961] - warn: You have no mongo username/password setup!
2018-04-13T16:25:00.086Z [2961] - verbose: [notifications.init] Registering jobs.
2018-04-13T16:25:00.087Z [2961] - verbose: [user/jobs] (Re-)starting user jobs...
2018-04-13T16:25:00.087Z [2961] - verbose: [user/jobs] Starting job (digest.daily)
2018-04-13T16:25:00.088Z [2961] - verbose: [user/jobs] Starting job (digest.weekly)
2018-04-13T16:25:00.089Z [2961] - verbose: [user/jobs] Starting job (digest.monthly)
2018-04-13T16:25:00.090Z [2961] - verbose: [user/jobs] Starting job (reset.clean)
2018-04-13T16:25:00.090Z [2961] - verbose: [user/jobs] 4 jobs started
2018-04-13T16:25:00.090Z [2961] - verbose: [emailer] Setting up SMTP fallback transport
2018-04-13T16:25:00.122Z [2961] - verbose: [emailer] Built custom email templates
2018-04-13T16:25:00.124Z [2961] - info: [themes] Using theme nodebb-theme-persona
2018-04-13T16:25:00.125Z [2961] - verbose: [plugins] Initializing plugins system
2018-04-13T16:25:00.132Z [2961] - verbose: [plugins] Loaded plugin: nodebb-plugin-composer-default
2018-04-13T16:25:00.134Z [2961] - verbose: [plugins] Loaded plugin: nodebb-theme-persona
2018-04-13T16:25:00.165Z [2961] - verbose: [plugins] Loaded plugin: nodebb-plugin-markdown
2018-04-13T16:25:00.184Z [2961] - verbose: [plugins] Loaded plugin: nodebb-plugin-mentions
2018-04-13T16:25:00.186Z [2961] - verbose: [plugins] Loaded plugin: nodebb-widget-essentials
2018-04-13T16:25:00.189Z [2961] - verbose: [plugins] Loaded plugin: nodebb-rewards-essentials
2018-04-13T16:25:00.190Z [2961] - verbose: [plugins] Found 3 sound file(s) for plugin nodebb-plugin-soundpack-default
2018-04-13T16:25:00.191Z [2961] - verbose: [plugins] Loaded plugin: nodebb-plugin-soundpack-default
2018-04-13T16:25:00.268Z [2961] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji
2018-04-13T16:25:00.281Z [2961] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji-android
2018-04-13T16:25:00.281Z [2961] - info: [plugins] Plugins OK
2018-04-13T16:25:00.314Z [2961] - verbose: [hotswap] Router with id plugins replaced successfully
2018-04-13T16:25:00.314Z [2961] - verbose: [plugins] All plugins reloaded and rerouted
2018-04-13T16:25:00.315Z [2961] - verbose: [hotswap] Router with id auth replaced successfully
2018-04-13T16:25:00.315Z [2961] - info: Routes added
2018-04-13T16:25:00.317Z [2961] - verbose: [meta/blacklist] Loading 0 blacklist rule(s)
2018-04-13T16:25:00.318Z [2961] - info: NodeBB Ready
2018-04-13T16:25:00.324Z [2961] - info: Enabling 'trust proxy'
2018-04-13T16:25:00.328Z [2961] - error: NodeBB address in use, exiting... Error: listen EADDRINUSE 0.0.0.0:4567
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at Server.setupListenHandle [as _listen2] (net.js:1367:14)
at listenInCluster (net.js:1408:12)
at doListen (net.js:1517:7)
at _combinedTickCallback (internal/process/next_tick.js:141:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
2018-04-13T16:25:00.329Z [2961] - error: Error: listen EADDRINUSE 0.0.0.0:4567
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at Server.setupListenHandle [as _listen2] (net.js:1367:14)
at listenInCluster (net.js:1408:12)
at doListen (net.js:1517:7)
at _combinedTickCallback (internal/process/next_tick.js:141:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
2018-04-13T16:25:00.329Z [2961] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-04-13T16:25:00.330Z [2961] - error: Error: Not running
at Server.close (net.js:1620:12)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:111:20)
at Server.emit (events.js:208:7)
at emitCloseNT (net.js:1671:8)
at _combinedTickCallback (internal/process/next_tick.js:135:11)
at Immediate._tickCallback (internal/process/next_tick.js:180:9)
at runCallback (timers.js:794:20)
at tryOnImmediate (timers.js:752:5)
at processImmediate [as _immediateCallback] (timers.js:729:5)
[cluster] Child Process (2961) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2018-04-13T16:25:00.865Z [2975] - info: Initializing NodeBB v1.8.2 http://sample.com/doubtforum
2018-04-13T16:25:00.868Z [2975] - verbose: * using mongo store at 127.0.0.1:27017
2018-04-13T16:25:00.868Z [2975] - verbose: * using themes stored in: /home/aaravkr/nodebb/NodeBB/node_modules
2018-04-13T16:25:00.959Z [2975] - warn: You have no mongo username/password setup!
2018-04-13T16:25:02.293Z [2975] - verbose: [minifier] utilizing a maximum of 3 additional threads
2018-04-13T16:25:02.312Z [2975] - verbose: Checking dependencies for outdated modules
2018-04-13T16:25:02.611Z [2975] - warn: You have no mongo username/password setup!
2018-04-13T16:25:02.625Z [2975] - verbose: [notifications.init] Registering jobs.
2018-04-13T16:25:02.626Z [2975] - verbose: [user/jobs] (Re-)starting user jobs...
2018-04-13T16:25:02.627Z [2975] - verbose: [user/jobs] Starting job (digest.daily)
2018-04-13T16:25:02.628Z [2975] - verbose: [user/jobs] Starting job (digest.weekly)
2018-04-13T16:25:02.628Z [2975] - verbose: [user/jobs] Starting job (digest.monthly)
2018-04-13T16:25:02.629Z [2975] - verbose: [user/jobs] Starting job (reset.clean)
2018-04-13T16:25:02.629Z [2975] - verbose: [user/jobs] 4 jobs started
2018-04-13T16:25:02.630Z [2975] - verbose: [emailer] Setting up SMTP fallback transport
2018-04-13T16:25:02.658Z [2975] - verbose: [emailer] Built custom email templates
2018-04-13T16:25:02.660Z [2975] - info: [themes] Using theme nodebb-theme-persona
2018-04-13T16:25:02.660Z [2975] - verbose: [plugins] Initializing plugins system
2018-04-13T16:25:02.667Z [2975] - verbose: [plugins] Loaded plugin: nodebb-plugin-composer-default
2018-04-13T16:25:02.669Z [2975] - verbose: [plugins] Loaded plugin: nodebb-theme-persona
2018-04-13T16:25:02.697Z [2975] - verbose: [plugins] Loaded plugin: nodebb-plugin-markdown
2018-04-13T16:25:02.714Z [2975] - verbose: [plugins] Loaded plugin: nodebb-plugin-mentions
2018-04-13T16:25:02.716Z [2975] - verbose: [plugins] Loaded plugin: nodebb-widget-essentials
2018-04-13T16:25:02.719Z [2975] - verbose: [plugins] Loaded plugin: nodebb-rewards-essentials
2018-04-13T16:25:02.720Z [2975] - verbose: [plugins] Found 3 sound file(s) for plugin nodebb-plugin-soundpack-default
2018-04-13T16:25:02.720Z [2975] - verbose: [plugins] Loaded plugin: nodebb-plugin-soundpack-default
2018-04-13T16:25:02.796Z [2975] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji
2018-04-13T16:25:02.807Z [2975] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji-android
2018-04-13T16:25:02.808Z [2975] - info: [plugins] Plugins OK
2018-04-13T16:25:02.856Z [2975] - verbose: [hotswap] Router with id plugins replaced successfully
2018-04-13T16:25:02.856Z [2975] - verbose: [plugins] All plugins reloaded and rerouted
2018-04-13T16:25:02.858Z [2975] - verbose: [hotswap] Router with id auth replaced successfully
2018-04-13T16:25:02.858Z [2975] - info: Routes added
2018-04-13T16:25:02.861Z [2975] - verbose: [meta/blacklist] Loading 0 blacklist rule(s)
2018-04-13T16:25:02.861Z [2975] - info: NodeBB Ready
2018-04-13T16:25:02.869Z [2975] - info: Enabling 'trust proxy'
2018-04-13T16:25:02.875Z [2975] - error: NodeBB address in use, exiting... Error: listen EADDRINUSE 0.0.0.0:4567
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at Server.setupListenHandle [as _listen2] (net.js:1367:14)
at listenInCluster (net.js:1408:12)
at doListen (net.js:1517:7)
at _combinedTickCallback (internal/process/next_tick.js:141:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
2018-04-13T16:25:02.876Z [2975] - error: Error: listen EADDRINUSE 0.0.0.0:4567
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at Server.setupListenHandle [as _listen2] (net.js:1367:14)
at listenInCluster (net.js:1408:12)
at doListen (net.js:1517:7)
at _combinedTickCallback (internal/process/next_tick.js:141:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
2018-04-13T16:25:02.876Z [2975] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-04-13T16:25:02.877Z [2975] - error: Error: Not running
at Server.close (net.js:1620:12)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:111:20)
at Server.emit (events.js:208:7)
at emitCloseNT (net.js:1671:8)
at _combinedTickCallback (internal/process/next_tick.js:135:11)
at Immediate._tickCallback (internal/process/next_tick.js:180:9)
at runCallback (timers.js:794:20)
at tryOnImmediate (timers.js:752:5)
at processImmediate [as _immediateCallback] (timers.js:729:5)
3 restarts in 10 seconds, most likely an error on startup. Halting.

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
