### ISSUE TITLE
Upgrade / database update script fails updating to nodebb 1.9.x due to invalid date

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#6485]
- **NodeBB version:** 1.9.x (Upgrading from v1.8.2)
- **NodeBB git hash:** 136aa65d1bc8f5b7564b03df1ecef6de542662b0

- **Database type:** mongo
- **Database version:** 3.4.10
- **NodeJs Version:** v8.11.1

- **Exact steps to cause this issue:**
./nodebb stop
git pull
git checkout v1.9.x
./nodebb upgrade
- **What you expected:**
Upgrade script to run and finish successfully
- **What happened instead:**
Failed with error relating to invalid date

Log here - install path has been stripped only.
```
./nodebb upgrade

Updating NodeBB...

1. Updating package.json file with defaults...  OK

2. Bringing base dependencies up to date...  started
npm WARN eslint-config-airbnb-base@12.1.0 requires a peer of eslint@^4.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.8.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.

up to date in 9.8s


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.6.0 → 6.0.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


3. Checking installed plugins for updates...  OK
4. Updating NodeBB data store schema...
Parsing upgrade scripts... 
OK | 1 script(s) found, 52 skipped
  → [2018/4/16] Refresh post-upload associations...
    [#####        ] (60200/143369) 41% Error occurred
Error occurred during upgrade: Error: [[error:invalid-data]]
    at sortedSetAddBulk (nodebb/src/database/mongo/sorted/add.js:30:20)
    at Object.module.sortedSetAdd (nodebb/src/database/mongo/sorted/add.js:12:11)
    at nodebb/node_modules/async/dist/async.js:66:19
    at nodebb/node_modules/async/dist/async.js:3866:24
    at eachOfArrayLike (nodebb/node_modules/async/dist/async.js:1055:9)
    at eachOf (nodebb/node_modules/async/dist/async.js:1103:5)
    at _parallel (nodebb/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit [as parallel] (nodebb/node_modules/async/dist/async.js:3948:5)
    at nodebb/src/posts/uploads.js:92:10
    at nodebb/node_modules/async/dist/async.js:3363:9
nodebb/src/cli/upgrade.js:68
			throw err;
			^

Error: [[error:invalid-data]]
    at sortedSetAddBulk (nodebb/src/database/mongo/sorted/add.js:30:20)
    at Object.module.sortedSetAdd (nodebb/src/database/mongo/sorted/add.js:12:11)
    at nodebb/node_modules/async/dist/async.js:66:19
    at nodebb/node_modules/async/dist/async.js:3866:24
    at eachOfArrayLike (nodebb/node_modules/async/dist/async.js:1055:9)
    at eachOf (nodebb/node_modules/async/dist/async.js:1103:5)
    at _parallel (nodebb/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit [as parallel] (nodebb/node_modules/async/dist/async.js:3948:5)
    at nodebb/src/posts/uploads.js:92:10
    at nodebb/node_modules/async/dist/async.js:3363:9

```

**Comment by barisusakli** [comment]
@joolswills you can git pull on the 1.9.x branch.

**Comment by joolswills** [comment]
Thanks for the speedy reply and fix! Will do. Was just restoring db from backup - will try the upgrade again.

**Comment by joolswills** [comment]
Thanks - confirmed working now.
