### ISSUE TITLE
NodeBB dies in user/blocks.js:88

### ISSUE THREAD

**Issue by attis** [NodeBB/NodeBB#6496]
- **NodeBB version:** 1.9.0
- **NodeBB git hash:**  da38b1fac275adc943be11d56d746ab49ba6a61d
- **Database type:** mongo and redis
- **Database version:** MongoDB 3.4.9, Redis 3.2.4
- **Exact steps to cause this issue:**
Not sure what triggers it precisely but after upgrading to 1.9.0 I see a lot of these in our logs:
```
018-05-10T08:45:20.857Z [137] - error: TypeError: Cannot read property 'hasOwnProperty' of undefined
at User.blocks.filter (/home/app/nodebb/src/user/blocks.js:88:54)
at /home/app/nodebb/node_modules/async/dist/async.js:66:19
at nextTask (/home/app/nodebb/node_modules/async/dist/async.js:5310:14)
at next (/home/app/nodebb/node_modules/async/dist/async.js:5317:9)
at /home/app/nodebb/node_modules/async/dist/async.js:958:16
at /home/app/nodebb/node_modules/async/dist/async.js:1126:9
at /home/app/nodebb/node_modules/async/dist/async.js:473:16
at iteratorCallback (/home/app/nodebb/node_modules/async/dist/async.js:1050:13)
at /home/app/nodebb/node_modules/async/dist/async.js:958:16
at /home/app/nodebb/node_modules/async/dist/async.js:1123:13
at /home/app/nodebb/src/posts.js:57:13
at /home/app/nodebb/node_modules/async/dist/async.js:1121:9
at eachOfArrayLike (/home/app/nodebb/node_modules/async/dist/async.js:1055:9)
at eachOf (/home/app/nodebb/node_modules/async/dist/async.js:1103:5)
at _asyncMap (/home/app/nodebb/node_modules/async/dist/async.js:1119:5)
at Object.map (/home/app/nodebb/node_modules/async/dist/async.js:1108:16)
2018-05-10T08:45:20.858Z [137] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-05-10T08:45:20.881Z [137] - info: [app] Web server closed to connections.
2018-05-10T08:45:20.883Z [137] - info: [app] Database connection closed.
2018-05-10T08:45:20.883Z [137] - info: [app] Shutdown complete.
[cluster] Child Process (137) has exited (code: 1, signal: null)
```

**Comment by julianlam** [comment]
Can you try with latest `master` (or v1.9.1, which will be released in the next hour or so?)

Likely fixed here: https://github.com/NodeBB/NodeBB/commit/9751c4b8dbbe55394eb0ff8f64fe54e149e000fd

**Comment by julianlam** [comment]
Will re-open if you still see it in logs :smile:
