### ISSUE TITLE
Update NodeBB Forum to 1.8.0

### ISSUE THREAD

**Issue by xedom** [NodeBB/NodeBB#6531]
- **NodeBB version:** 1.8.0
- **Database type:** mongo
- **Database version:** 3.2.11

- **Exact steps to cause this issue:**
1. `./nodebb stop`
1. `git pull`
1. `git fetch`
1. `cd install`
1. `npm install`
1. `cd ..`
1. `./nodebb upgrade`
        i got this in console: https://pastebin.com/Jj1Ahwkp
1. `./nodebb start`
        i got this in browser: Internal Server Error
1. `./nodebb stop`
1. `./nodebb dev`
        i got this in console: https://pastebin.com/3sXKiCY3
        and i got this in browser: http://prntscr.com/jon52t
```
Error: Failed to lookup view "500" in views directory "/root/nodebb/build/public/templates"
    at Function.render (/root/nodebb/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/root/nodebb/node_modules/express/lib/response.js:1008:7)
    at content (/root/nodebb/src/middleware/render.js:82:15)
    at /root/nodebb/node_modules/async/dist/async.js:3866:24
    at replenish (/root/nodebb/node_modules/async/dist/async.js:998:17)
    at /root/nodebb/node_modules/async/dist/async.js:1002:9
    at eachOfLimit (/root/nodebb/node_modules/async/dist/async.js:1027:24)
    at /root/nodebb/node_modules/async/dist/async.js:1032:16
    at eachOf (/root/nodebb/node_modules/async/dist/async.js:1103:5)
    at _parallel (/root/nodebb/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit [as parallel] (/root/nodebb/node_modules/async/dist/async.js:3948:5)
    at async.waterfall.str (/root/nodebb/src/middleware/render.js:77:12)
    at nextTask (/root/nodebb/node_modules/async/dist/async.js:5310:14)
    at next (/root/nodebb/node_modules/async/dist/async.js:5317:9)
    at /root/nodebb/node_modules/async/dist/async.js:958:16
    at /root/nodebb/node_modules/async/dist/async.js:473:16
```

- **What you expected:** Update NodeBB Forum to 1.8.0
- **What happened instead:** Internal Server Error

**Comment by julianlam** [comment]
Build failed, reset some plugins that aren't compatible via `./nodebb reset -p` and then `./nodebb build` again.

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!

**Comment by xedom** [comment]
Thanks
