### ISSUE TITLE
"Internal server error" after a period of inactivity

### ISSUE THREAD

**Issue by Per0x** [NodeBB/NodeBB#6538]
- **NodeBB version:** 1.9.3
- **NodeBB git hash:** 6cb41e63586eede259e0f5162b82c9a197b31cf5 

- **Database type:** redis
- **Database version:** 3.0.6
- **Theme used:** Persona
- **Skin used:** Sandstone

After a more or less long time, the nodeBB page displays me "Internal server error" for no particular reason. To solve the problem, sometimes after a few hours everything comes back in order or then I just have to restart the docker container,
Here is what the server logs repeat, when there is this error.

> Render failed for template <div class="panel pa:
>  Error: Render failed for template <div class="panel pa:
>  Script execution timed out.
>     at ContextifyScript.Script.runInContext (vm.js:59:29)
>     at ContextifyScript.Script.runInNewContext (vm.js:65:15)
>     at Object.runInNewContext (vm.js:135:38)
>     at evaluate (/usr/src/app/node_modules/benchpressjs/build/lib/evaluate.js:17:6)
>     at precompile.then.code (/usr/src/app/node_modules/benchpressjs/build/lib/compile-render.js:34:74)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)'

**Comment by julianlam** [comment]
Could it be possible that the docker container is... going to sleep or something?

**Comment by Per0x** [comment]
Is something like that is possible ? I run others containers on this docker and I never noticed the containers going to sleep mode. I also noticed that it could go 7 days without problems, but when I did the last update (1.9.3) and restarted the docker container, 2 days later I had the error.

**Comment by pitaj** [comment]
Looks like widget parsing is failing. Have you made any modifications to widgets?

**Comment by Per0x** [comment]
Yes, I added a Global Sidebar widget for recent posts, and in "Draft zone" there is this widget HTML (wich is hidden)

><footer id="footer" class="container footer">
	<div>
		Powered by <a target="_blank" href="https://nodebb.org">NodeBB</a> | <a target="_blank" href="//github.com/NodeBB/NodeBB/graphs/contributors">Contributors</a>
	</div>
</footer>

**Comment by Per0x** [comment]
I still have the error that appears today

Always internal server error but this time in logs:

error: /categories
 Render failed for template <div class="panel ui:
 Error: Render failed for template <div class="panel ui:
 Script execution timed out.
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at Object.runInNewContext (vm.js:135:38)
    at evaluate (/usr/src/app/node_modules/benchpressjs/build/lib/evaluate.js:17:6)
    at precompile.then.code (/usr/src/app/node_modules/benchpressjs/build/lib/compile-render.js:34:74)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[10/Jun/2018:13:57:25 +0000] "GET / HTTP/1.1" 500 148 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 Google Favicon"
Render failed for template <div class="panel ui:
 Render failed for template <div class="panel ui:
 Error: Render failed for template <div class="panel ui:
 Script execution timed out.
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at Object.runInNewContext (vm.js:135:38)
    at evaluate (/usr/src/app/node_modules/benchpressjs/build/lib/evaluate.js:17:6)
    at precompile.then.code (/usr/src/app/node_modules/benchpressjs/build/lib/compile-render.js:34:74)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by barisusakli** [comment]
This can randomly happen during `npm test` as well.

```
error: /this-route-does-not-exist
 Evaluate failed for template c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\build\public\templates\404.js:
 Error: Evaluate failed for template c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\build\public\templates\404.js:
 Script execution timed out.
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at Object.runInNewContext (vm.js:135:38)
    at evaluate (c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\benchpressjs\build\lib\evaluate.js:17:6)
    at fs.readFile (c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\benchpressjs\build\lib\express.js:45:47)
    at c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by pitaj** [comment]
Maybe it's a problem with md5 or something else to do with the cache

**Comment by pitaj** [comment]
#6493

**Comment by Per0x** [comment]
@pitaj Ok thanks, but how can I fix the MD5 or compileRender cache ?

**Comment by pitaj** [comment]
I'm not sure what the problem is yet. I was just thinking of possible root causes for this issue. Continue discussion in the linked issue, this is a duplicate.
