### ISSUE TITLE
 Render failed for template <footer id="footer" :

### ISSUE THREAD

**Issue by co-owner** [NodeBB/NodeBB#6566]
NodeBB version:1.9.3
Database type:mongo
Database version:3.4.15

1. First the NodeBB-1.9.3 wokrs.
2. Then,a few hours later,the NodeBB-1.9.3 has crashed.

The error message is as follows:

```
Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Render failed for template <footer id="footer" :
 Error: Render failed for template <footer id="footer" :
 Script execution timed out.
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at Object.runInNewContext (vm.js:135:38)
    at evaluate (C:\openbu.org\group\group1\node_modules\benchpressjs\build\lib\evaluate.js:17:6)
    at precompile.then.code (C:\openbu.org\group\group1\node_modules\benchpressjs\build\lib\compile-render.js:34:74)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/6538
