### ISSUE TITLE
nodebb/docker attempts to take CLI input

### ISSUE THREAD

**Issue by Jameskmonger** [NodeBB/NodeBB#6623]
- **NodeBB version:** docker image ad1b306d7d2b
- **Database type:** mongo
- **Database version:** docker image 9a63ed32fc2b
- **Exact steps to cause this issue:**

    - docker pull nodebb/docker
    - docker pull mongo
   - docker run -p 27017:27017 mongo -d
   - docker run -p 4567:4567 nodebb/docker
   - Visit web installer at http://localhost:4567/
   - Fill in installer and press "Install NodeBB"

- **What you expected:**
The installer to set up the database using the credentials provided
- **What happened instead:**
It looks like it attempts to use the normal CLI input and fails

```
2018-07-02T13:44:54.239Z [5] - info: Starting setup process
2018-07-02T13:44:54.240Z [5] - info:  base_dir=/usr/src/app/, themes_path=/usr/src/app/node_modules, upload_path=/usr/src/app/public/uploads, views_dir=/usr/src/app/build/public/templates, version=1.10.0, type=literal, isPrimary=true, isCluster=false, core_templates_path=/usr/src/app/src/views, base_templates_path=/usr/src/app/node_modules/nodebb-theme-persona/templates, runJobs=true, NODE_VERSION=8.11.3, HOSTNAME=258221e86e9f, YARN_VERSION=1.6.0, daemon=false, HOME=/root, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, PWD=/usr/src/app, NODE_ENV=production, silent=false, _=["start"], $0=nodebb, url=http://localhost:4567, admin__username=admin, admin__email=adminemail@example.com, admin__password=password, admin__passwordConfirm=password, database=mongo, mongo__host=127.0.0.1, mongo__port=27017, mongo__username=nodebb, mongo__password=abc123, mongo__database=nodebb
2018-07-02T13:44:54.972Z [15] - info: NodeBB Setup Triggered via Command Line

Welcome to NodeBB v1.10.0!

This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
Press enter to accept the default setting (shown in brackets).
2018-07-02T13:44:55.007Z [15] - info:
Now configuring mongo database:
2018-07-02T13:44:55.111Z [15] - error: NodeBB could not connect to your Mongo database. Mongo returned the following error message=failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017], name=MongoNetworkError, stack=MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:505:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:329:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
2018-07-02T13:44:55.114Z [15] - warn: NodeBB Setup Aborted.
 MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:505:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:329:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
```

**Comment by Jameskmonger** [comment]
Even if I supply `-it` to `docker run`, it just hangs on:

```
2018-07-02T13:59:23.711Z [5] - info: Web installer listening on http://0.0.0.0:4567
```

It then immediately goes through the rest of the logs posted above, with no opportunity for me to enter values into the command line.

I am able to visit 127.0.0.1:27017 in both Google Chrome and also in Robo 3T.

**Comment by Jameskmonger** [comment]
I have also tried with a Redis instance not using Docker to try to eliminate issues. Here is the output:

```
2018-07-02T14:05:38.979Z [5] - info: Launching web installer on port 4567
2018-07-02T14:05:39.764Z [5] - info: Web installer listening on http://0.0.0.0:4567
2018-07-02T14:06:08.813Z [5] - info: Starting setup process
2018-07-02T14:06:08.814Z [5] - info:  base_dir=/usr/src/app/, themes_path=/usr/src/app/node_modules, upload_path=/usr/src/app/public/uploads, views_dir=/usr/src/app/build/public/templates, version=1.10.0, type=literal, isPrimary=true, isCluster=false, core_templates_path=/usr/src/app/src/views, base_templates_path=/usr/src/app/node_modules/nodebb-theme-persona/templates, runJobs=true, NODE_VERSION=8.11.3, HOSTNAME=8df7075912ac, YARN_VERSION=1.6.0, daemon=false, HOME=/root, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, PWD=/usr/src/app, NODE_ENV=production, silent=false, _=["start"], $0=nodebb, url=http://localhost:4567, admin__username=admin, admin__email=foo@bar.com, admin__password=password, admin__passwordConfirm=password, database=redis, redis__host=127.0.0.1, redis__port=6379, redis__password=, redis__database=0
2018-07-02T14:06:09.663Z [15] - info: NodeBB Setup Triggered via Command Line

Welcome to NodeBB v1.10.0!

This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
Press enter to accept the default setting (shown in brackets).
2018-07-02T14:06:09.707Z [15] - info:
Now configuring redis database:
2018-07-02T14:06:09.715Z [15] - error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
2018-07-02T14:06:09.716Z [15] - error: NodeBB could not connect to your Redis database. Redis returned the following error message=Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379, stack=Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14), code=ECONNREFUSED, errno=ECONNREFUSED, syscall=connect, address=127.0.0.1, port=6379
2018-07-02T14:06:09.716Z [15] - warn: NodeBB Setup Aborted.
 Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
```

And, to ensure it was running:

```
redis-cli -h 127.0.0.1 -p 6379 ping
PONG
```

**Comment by Dravere** [comment]
The problem is that docker container are running in their own network. They can't see your Redis or MongoDB exposed on the host IP address. You either have to supply in the configuration the IP address of your running database container or create your own docker network and then supply the docker container name which then can be resolved to the correct IP address.

I highly recommend that you take a look at the [network overview](https://docs.docker.com/network/) and especially at the [bridge network](https://docs.docker.com/network/bridge/) configuration in the docker documentation.
