### ISSUE TITLE
noddebb upgrade script timeout

### ISSUE THREAD

**Issue by sohrabafard** [NodeBB/NodeBB#6661]
```
  version:  1.10.1
  Node ver: v8.11.3
  git hash: c1e98eefa7fe93431ac312ecc0d90314db2c49b1

  database: mongo
        version: 3.6.3
        engine:  wiredTiger
```
```
Parsing upgrade scripts...
OK | 4 script(s) found, 53 skipped
  → [2017/6/22] Hash all IP addresses stored in Recent IPs zset...
    [###########  ] (686800/802153) 85% Error occurred
Error occurred during upgrade: MongoError: cursor id 23654971494 not found
    at /home/alaa/Nodebb/forum/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:598:61
    at authenticateStragglers (/home/alaa/Nodebb/forum/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:516:16)
    at Connection.messageHandler (/home/alaa/Nodebb/forum/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:552:5)
    at emitMessageHandler (/home/alaa/Nodebb/forum/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:309:10)
    at Socket.<anonymous> (/home/alaa/Nodebb/forum/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:452:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)

/home/alaa/Nodebb/forum/node_modules/mongodb/lib/utils.js:132
      throw err;
```

**Comment by barisusakli** [comment]
Please see https://community.nodebb.org/topic/12360/upgrade-refresh-post-upload-associations-in-1-9-x-causes-error/14
