### ISSUE TITLE
MondoDB 4.x supported ?

### ISSUE THREAD

**Issue by Pummelchen** [NodeBB/NodeBB#6748]
Hello,

does NodeBB support MongoDB 4.x ? I did a general server all-app-update and now have some issues with my node.exe instances restarting every couple of minutes and at some point they dont respawn anymore. Not sure yet if the issue is with Node 10.10.0 upgrade 🐍 or Mongo 4 upgrade 🐤 or nginx 1.53 upgrade 🐀

Update: forums works fine, new threads can be created and edited without issues. Just you see connection lost while node.js respawns and it reconnects after some seconds.

Logs:

2018-09-09T10:11:48.922Z [9648] - [32minfo[39m: NodeBB is now listening on: 127.0.0.1:4569
2018-09-09T10:16:43.603Z [11388] - [31merror[39m: MongoError: cursor id 27285299524 not found
at X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:598:61
at authenticateStragglers (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:516:16)
at Connection.messageHandler (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:552:5)
at emitMessageHandler (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:309:10)
at Socket.<anonymous> (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:452:17)
at Socket.emit (events.js:182:13)
at addChunk (_stream_readable.js:283:12)
at readableAddChunk (_stream_readable.js:264:11)
at Socket.Readable.push (_stream_readable.js:219:10)
at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
2018-09-09T10:16:43.603Z [11388] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-09-09T10:16:43.605Z [11388] - [32minfo[39m: [app] Web server closed to connections.
2018-09-09T10:16:43.606Z [11388] - [32minfo[39m: [app] Database connection closed.
2018-09-09T10:16:43.606Z [11388] - [32minfo[39m: [app] Shutdown complete.
2018-09-09T10:16:43.621Z [5504] - [31merror[39m: MongoError: cursor id 28811112366 not found
at X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:598:61
at authenticateStragglers (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:516:16)
at Connection.messageHandler (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:552:5)
at emitMessageHandler (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:309:10)
at Socket.<anonymous> (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:452:17)
at Socket.emit (events.js:182:13)
at addChunk (_stream_readable.js:283:12)
at readableAddChunk (_stream_readable.js:264:11)
at Socket.Readable.push (_stream_readable.js:219:10)
at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
2018-09-09T10:16:43.625Z [5504] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-09-09T10:16:43.627Z [5504] - [32minfo[39m: [app] Web server closed to connections.
2018-09-09T10:16:43.632Z [5504] - [32minfo[39m: [app] Database connection closed.
2018-09-09T10:16:43.632Z [5504] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (11388) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
[cluster] Child Process (5504) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2018-09-09T10:16:43.723Z [9648] - [31merror[39m: MongoError: cursor id 28796318791 not found
at X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:598:61
at authenticateStragglers (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:516:16)
at Connection.messageHandler (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:552:5)
at emitMessageHandler (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:309:10)
at Socket.<anonymous> (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:452:17)
at Socket.emit (events.js:182:13)
at addChunk (_stream_readable.js:283:12)
at readableAddChunk (_stream_readable.js:264:11)
at Socket.Readable.push (_stream_readable.js:219:10)
at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
2018-09-09T10:16:43.724Z [9648] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-09-09T10:16:43.732Z [9648] - [32minfo[39m: [app] Web server closed to connections.
2018-09-09T10:16:43.734Z [9648] - [32minfo[39m: [app] Database connection closed.
2018-09-09T10:16:43.734Z [9648] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (9648) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2018-09-09T10:16:44.114Z [9396] - [31merror[39m: MongoError: cursor id 28075153536 not found
at X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:598:61
at authenticateStragglers (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:516:16)
at Connection.messageHandler (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:552:5)
at emitMessageHandler (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:309:10)
at Socket.<anonymous> (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:452:17)
at Socket.emit (events.js:182:13)
at addChunk (_stream_readable.js:283:12)
at readableAddChunk (_stream_readable.js:264:11)
at Socket.Readable.push (_stream_readable.js:219:10)
at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
2018-09-09T10:16:44.114Z [9396] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-09-09T10:16:44.115Z [9396] - [32minfo[39m: [app] Web server closed to connections.
2018-09-09T10:16:44.118Z [9396] - [32minfo[39m: [app] Database connection closed.
2018-09-09T10:16:44.118Z [9396] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (9396) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2018-09-09T10:16:45.087Z [12300] - [32minfo[39m: Initializing NodeBB v1.10.1 https://beep.com/forum

**Comment by Pummelchen** [comment]
https://community.nodebb.org/topic/12779/mondodb-4-x-supported

**Comment by barisusakli** [comment]
I did a fresh install on mongodb4.0.2 and didn't have issues, are you running on linux or windows? Do you get those errors randomly or on a specific action?

**Comment by Pummelchen** [comment]
Windows. The node.exe respawn happens every couple of minutes, the forum is private with no traffic. Maybe its a Node.js bug, will see if a downgrade helps and report back.

**Comment by barisusakli** [comment]
I tested on ubuntu, so might be windows related, I will test it on windows as well.

**Comment by Pummelchen** [comment]
Same with Node 10.11.0. The node.exe master process stays alive but the 4 client processes of node.exe respawn every couple of minutes. I updated NodeBB with the latest master version just now, same isue.

It seems as the result of that mondodb cannot keep track of sessions:

Mongo Log:

2018-09-21T10:49:07.356+0000 I NETWORK  [conn459] Error sending response to client: HostUnreachable: Connection was closed. Ending connection from 127.0.0.1:60923 (connection id: 459)
2018-09-21T10:49:07.357+0000 I NETWORK  [conn459] end connection 127.0.0.1:60923 (31 connections now open)
2018-09-21T10:49:07.818+0000 I QUERY    [conn435] removing cursor 27841829049 after completing batch: CursorKilled: operation was interrupted
2018-09-21T10:49:07.820+0000 I QUERY    [conn444] removing cursor 29677660255 after completing batch: CursorKilled: operation was interrupted

NodeBB Log:

2018-09-21T10:54:07.440Z [7064] - [31merror[39m:  MongoError: cursor id 27248834277 not found
    at X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:598:61
    at authenticateStragglers (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:516:16)
    at Connection.messageHandler (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:552:5)
    at emitMessageHandler (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:309:10)
    at Socket.<anonymous> (X:\NodeBB\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:452:17)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
2018-09-21T10:54:07.441Z [7064] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-09-21T10:54:07.443Z [7064] - [32minfo[39m: [app] Web server closed to connections.
[cluster] Child Process (6904) has exited (code: 1, signal: null)
2018-09-21T10:54:07.444Z [7064] - [32minfo[39m: [app] Database connection closed.
[cluster] Spinning up another process...
2018-09-21T10:54:07.444Z [7064] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (7112) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
[cluster] Child Process (7064) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2018-09-21T10:54:08.313Z [3712] - [32minfo[39m: Initializing NodeBB v1.10.1 https://beep.com/forum

Not really sure what happens and if Node.js changed something on version 10 related to the lifetime of client processes.  Maybe its a Windows related bug somewhere.

**Comment by barisusakli** [comment]
This might be related https://jira.mongodb.org/browse/NODE-1482

**Comment by barisusakli** [comment]
also https://jira.mongodb.org/browse/SERVER-34810

**Comment by Pummelchen** [comment]
Update:

Installed Node 8.12.0 with the usual cleanup of the NodeBB folder of node.js stuff .. same issue
Installed the latest nightly MongoDB 4.x version .. same issue

Did not downgrade MongoDB to 3.6.8 yet but thats in the works, sry for being so slow due to busy life (wife).

What worries me is that I have TruDesk running which is fairly complex too based on dependencies and it just keeps on going on the same VPS like in the Duracell bunny commercial while NodeBB crashes under my hands with disconnect messages.

**Comment by barisusakli** [comment]
Been using it for a while now and it's working fine.
