### ISSUE TITLE
Docker Swarm NodeBB exits and cannot restart properly.

### ISSUE THREAD

**Issue by rushsteve1** [NodeBB/NodeBB#6775]
- **NodeBB version:** 1.10.1
- **NodeBB git hash:** c8d3c31

- **Database type:** mongo
- **Database version:** 4.0.2

- **Exact steps to cause this issue:**
        1. Start a NodeBB docker container as a Docker Swarm service.
	2. Completed the admin config, wait for build then click the "Launch NodeBB" button.
        3. Loads indefinitely. The Docker task had been `COMPLETE`d and the container had been stopped.
        4. A new container had been started by the service.
- **What you expected:**
    I expected NodeBB to not exit when clicking "Launch NodeBB"
- **What happened instead:**
The NodeBB exits with error code 0 after the launch button is clicked. This causes a service to make the task as `COMPLETE` and depending on your restart policy start a new container.
The new container does not have the build or config from the old one, and there is no documentation on what/how to mount the files to be persistent between containers.
On non-swarm Docker using `restart: always` restarts the same container, which cannot be done with a service. Omitting that setting causes the same problem.

This is related to #6109

**Comment by rushsteve1** [comment]
Attempting to start again with `./nodebb start` after the first one exits causes the following error 3 times and then it quits:
```
2018-09-21T00:26:08.879Z [112] - error: NodeBB address in use, exiting... message=listen EADDRINUSE 0.0.0.0:4567, stack=Error: listen EADDRINUSE 0.0.0.0:4567
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at doListen (net.js:1505:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9), code=EADDRINUSE, errno=EADDRINUSE, syscall=listen, address=0.0.0.0, port=4567
2018-09-21T00:26:08.879Z [112] - error:  message=listen EADDRINUSE 0.0.0.0:4567, stack=Error: listen EADDRINUSE 0.0.0.0:4567
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at doListen (net.js:1505:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9), code=EADDRINUSE, errno=EADDRINUSE, syscall=listen, address=0.0.0.0, port=4567
2018-09-21T00:26:08.880Z [112] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-09-21T00:26:08.880Z [112] - error:  message=Not running, stack=Error: Not running
    at Server.close (net.js:1608:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Server.emit (events.js:208:7)
    at emitCloseNT (net.js:1659:8)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at Immediate._tickCallback (internal/process/next_tick.js:180:9)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
[cluster] Child Process (112) has exited (code: 1, signal: null)
```

**Comment by rushsteve1** [comment]
After further investigation NodeBB does run in the container fine, but the container exits when `./nodebb start` does after clicking "Launch NodeBB" even though node, and the forum, are still running fine.

So solve this I wrote a little while loop script as a temporary holdover. It can be found here: https://gitlab.com/rushsteve1/nodebb and there is an auto-built container with the fix.
