### ISSUE TITLE
libvips-cpp.so.42: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yuyao110120** [NodeBB/NodeBB#6839]
- **NodeBB version:** 1.10.2
- **NodeBB git hash:** d84030d55f154b4b7ad81931498875e15d264941

- **Database type:** redis
- **Database version:** 3.2.12

- **Exact steps to cause this issue:**

I always fail when I upload pictures.
I tried uploading images of *.jpeg and *.png types.
The error log is as follows

```
2018-10-16T17:47:02.528Z [19540] - [31merror[39m:  message=libvips-cpp.so.42: cannot open shared object file: No such file or directory, stack=Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/spbee/nodebb/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/spbee/nodebb/node_modules/sharp/lib/index.js:3:15)
2018-10-16T17:47:02.530Z [19540] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-10-16T17:47:02.532Z [19540] - [32minfo[39m: [app] Web server closed to connections.
2018-10-16T17:47:02.533Z [19540] - [32minfo[39m: [app] Database connection closed.
2018-10-16T17:47:02.533Z [19540] - [32minfo[39m: [app] Shutdown complete.
[cluster] Child Process (19540) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2018-10-16T17:47:02.868Z [19604] - [32minfo[39m: Initializing NodeBB v1.10.2 http://bbs.spbee.com
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version
2018-10-16T17:47:04.798Z [19604] - [32minfo[39m: [socket.io] Restricting access to origin: *:*
2018-10-16T17:47:05.200Z [19604] - [32minfo[39m: Routes added
2018-10-16T17:47:05.202Z [19604] - [32minfo[39m: NodeBB Ready
2018-10-16T17:47:05.205Z [19604] - [32minfo[39m: Enabling 'trust proxy'
2018-10-16T17:47:05.209Z [19604] - [32minfo[39m: NodeBB is now listening on: 0.0.0.0:4567
```
Thank you!

**Comment by pitaj** [comment]
What version of node are you on? What platform?

**Comment by yuyao110120** [comment]
@pitaj I installed the latest version of node (v10.12.0) through NVM, but the problem remains.

**Comment by yuyao110120** [comment]
Hi, guys. I fixed it!
This problem is caused by the manual compilation of libvips.
I uninstalled libvips from the system and then reinstalled sharp.

The sharp documentation helps me a lot.
If I install libvips separately, it will conflict with nodebb.
How do you solve that?
What do you have in mind?

OK，thanks @pitaj .

**Comment by julianlam** [comment]
Oh that's really odd... unfortunately doesn't look like that would fall under NodeBB's code since it's something related to sharp. Perhaps you could report the issue there?
