### ISSUE TITLE
Connection temporarily lost when deleting a post

### ISSUE THREAD

**Issue by jtsimoes** [NodeBB/NodeBB#6892]
- **NodeBB version:** 1.10.2
- **NodeBB git hash:** d84030d55f154b4b7ad81931498875e15d264941
- **Database type:** Redis
- **Database version:** 4.0.9
- **Exact steps to cause this issue:**

	1. Write a post on any topic
	2. Delete the post
	3. Watch the topic page and the server log with ./nodebb log

- **What you expected:** The post appear deleted and ready to purge (deleted definitively)
- **What happened instead:** Connection temporarily lost and need to refresh the page for the message to appear deleted (and then, you can purge them but the purge feature is fine)

Console log:
>2018-10-30T14:09:17.370Z [408] - info: NodeBB is now listening on: 0.0.0.0:4567
2018-10-30T14:12:51.177Z [408] - error:  message=The "last argument" argument must be of type function, stack=TypeError [ERR_INVALID_ARG_TYPE]: The "last argument" argument must be of type function
    at Object.deleteEvent [as method] (util.js:1014:13)
    at /home/ectua/NodeBB/src/plugins/hooks.js:137:12
    at /home/ectua/NodeBB/node_modules/async/dist/async.js:3110:16
    at eachOfArrayLike (/home/ectua/NodeBB/node_modules/async/dist/async.js:1069:9)
    at eachOf (/home/ectua/NodeBB/node_modules/async/dist/async.js:1117:5)
    at Object.eachLimit (/home/ectua/NodeBB/node_modules/async/dist/async.js:3172:5)
    at fireActionHook (/home/ectua/NodeBB/src/plugins/hooks.js:129:9)
    at Object.Plugins.fireHook (/home/ectua/NodeBB/src/plugins/hooks.js:96:4)
    at /home/ectua/NodeBB/src/posts/delete.js:45:13
    at nextTask (/home/ectua/NodeBB/node_modules/async/dist/async.js:5324:14)
    at next (/home/ectua/NodeBB/node_modules/async/dist/async.js:5331:9)
    at /home/ectua/NodeBB/node_modules/async/dist/async.js:969:16
    at /home/ectua/NodeBB/node_modules/async/dist/async.js:3888:9
    at /home/ectua/NodeBB/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/ectua/NodeBB/node_modules/async/dist/async.js:1064:13)
    at /home/ectua/NodeBB/node_modules/async/dist/async.js:969:16
2018-10-30T14:12:51.182Z [408] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-10-30T14:12:51.184Z [408] - info: [app] Web server closed to connections.
2018-10-30T14:12:51.187Z [408] - info: [app] Database connection closed.
2018-10-30T14:12:51.188Z [408] - info: [app] Shutdown complete.
[cluster] Child Process (408) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2018-10-30T14:12:51.537Z [483] - info: Initializing NodeBB v1.10.2 https://novo.ect-ua.com
2018-10-30T14:12:53.510Z [483] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-sso-oauth`. Skipping.
2018-10-30T14:12:53.514Z [483] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-ns-custom-fields`. Skipping.
2018-10-30T14:12:53.926Z [483] - info: [socket.io] Restricting access to origin: https://novo.ect-ua.com:*
2018-10-30T14:12:54.801Z [483] - info: Routes added
2018-10-30T14:12:54.804Z [483] - info: NodeBB Ready
2018-10-30T14:12:54.807Z [483] - info: Enabling 'trust proxy'
2018-10-30T14:12:54.811Z [483] - info: NodeBB is now listening on: 0.0.0.0:4567

I don't know if it's an internal problem on my forum or it's a bug on NodeBB... I already deleted the `node_modules` folder, used `npm install` again, rebuild and nothing... Did not solve.

Let me know below if someone has the same problem.
Thanks.

**Comment by pitaj** [comment]
Yes your NodeBB is crashing resulting in it restarting automatically. Are you running the calendar plugin by chance?

**Comment by jtsimoes** [comment]
> Yes your NodeBB is crashing resulting in it restarting automatically. Are you running the calendar plugin by chance?

Yes, I'm using this one: 
![image](https://user-images.githubusercontent.com/34691647/47740528-de11f700-dc6f-11e8-8db6-6c06995076fb.png)

**Comment by pitaj** [comment]
Yeah this is a known issue with that plugin. Visit the following issue for a temp fix:

pitaj/nodebb-plugin-calendar#106
