### ISSUE TITLE
Error loading nodebb-plugin-sso-facebook

### ISSUE THREAD

**Issue by miwels** [NodeBB/NodeBB#6898]
- **NodeBB version:** 1.10.2
- **NodeBB git hash:** dbc7c2cc466601321e01714421f28cde6ca6cbd6
- **Database type:** mongo
- **Database version:** 4.0.3
- **Exact steps to cause this issue:**
1. Download and install nodebb-plugin-sso-facebook plugin from the plugins section (Admin -> Plugins -> Install plugin -> Find Plugins -> Search for 'facebook' -> click install
2. Activate plugin
3. Restar the server
4. In the "Social Authentication" tab click on Facebook

- **What you expected:**
I expected the plugin page to load
- **What happened instead:**
The plugin fails to load, a spinner is displayed but the page fails to load. The browser's console shows the following errors:

```
ajaxify.js:335 Unable to load template: admin/plugins/sso-facebook
(anonymous) @ ajaxify.js:335
(anonymous) @ require.js:7
(anonymous) @ require.js:23
y @ require.js:6
emit @ require.js:23
(anonymous) @ require.js:11
y @ require.js:6
c @ require.js:11
onScriptError @ require.js:30
error (async)
g.load @ require.js:34
load @ require.js:29
load @ require.js:17
fetch @ require.js:17
check @ require.js:17
enable @ require.js:23
enable @ require.js:27
(anonymous) @ require.js:22
(anonymous) @ require.js:7
y @ require.js:6
enable @ require.js:21
init @ require.js:16
(anonymous) @ require.js:26
setTimeout (async)
g.nextTick @ require.js:32
l @ require.js:26
requirejs @ require.js:32
ajaxify.loadTemplate @ ajaxify.js:334
(anonymous) @ benchpress.js:164
o @ benchpress.js:163
(anonymous) @ benchpress.js:185
(anonymous) @ benchpress.js:78
e @ benchpress.js:77
a @ benchpress.js:184
l @ benchpress.js:223
c @ ajaxify.js:185
(anonymous) @ ajaxify.js:99
success @ ajaxify.js:317
l @ jquery.js:3268
fireWith @ jquery.js:3398
T @ jquery.js:9305
(anonymous) @ jquery.js:9548
load (async)
send @ jquery.js:9567
ajax @ jquery.js:9206
ajaxify.loadData @ ajaxify.js:291
ajaxify.go @ ajaxify.js:87
a @ ajaxify.js:364
(anonymous) @ ajaxify.js:424
dispatch @ jquery.js:5183
g.handle @ jquery.js:4991
require.js:7 Uncaught Error: Script error for "/forum/assets/templates/admin/plugins/sso-facebook.js"
http://requirejs.org/docs/errors.html#scripterror
    at F (require.js:7)
    at HTMLScriptElement.onScriptError (require.js:30)
F @ require.js:7
onScriptError @ require.js:30
error (async)
g.load @ require.js:34
load @ require.js:29
load @ require.js:17
fetch @ require.js:17
check @ require.js:17
enable @ require.js:23
enable @ require.js:27
(anonymous) @ require.js:22
(anonymous) @ require.js:7
y @ require.js:6
enable @ require.js:21
init @ require.js:16
(anonymous) @ require.js:26
setTimeout (async)
g.nextTick @ require.js:32
l @ require.js:26
requirejs @ require.js:32
ajaxify.loadTemplate @ ajaxify.js:334
(anonymous) @ benchpress.js:164
o @ benchpress.js:163
(anonymous) @ benchpress.js:185
(anonymous) @ benchpress.js:78
e @ benchpress.js:77
a @ benchpress.js:184
l @ benchpress.js:223
c @ ajaxify.js:185
(anonymous) @ ajaxify.js:99
success @ ajaxify.js:317
l @ jquery.js:3268
fireWith @ jquery.js:3398
T @ jquery.js:9305
(anonymous) @ jquery.js:9548
load (async)
send @ jquery.js:9567
ajax @ jquery.js:9206
ajaxify.loadData @ ajaxify.js:291
ajaxify.go @ ajaxify.js:87
a @ ajaxify.js:364
(anonymous) @ ajaxify.js:424
dispatch @ jquery.js:5183
g.handle @ jquery.js:4991
ajaxify.js:335 Unable to load template: admin/plugins/sso-facebook
(anonymous) @ ajaxify.js:335
(anonymous) @ require.js:7
(anonymous) @ require.js:23
y @ require.js:6
emit @ require.js:23
d @ require.js:12
(anonymous) @ require.js:12
y @ require.js:6
d @ require.js:12
(anonymous) @ require.js:13
y @ require.js:6
p @ require.js:13
(anonymous) @ require.js:13
setTimeout (async)
p @ require.js:13
(anonymous) @ require.js:13
setTimeout (async)
p @ require.js:13
(anonymous) @ require.js:26
setTimeout (async)
g.nextTick @ require.js:32
l @ require.js:26
requirejs @ require.js:32
ajaxify.loadTemplate @ ajaxify.js:334
(anonymous) @ benchpress.js:164
o @ benchpress.js:163
(anonymous) @ benchpress.js:185
(anonymous) @ benchpress.js:78
e @ benchpress.js:77
a @ benchpress.js:184
l @ benchpress.js:223
c @ ajaxify.js:185
(anonymous) @ ajaxify.js:99
success @ ajaxify.js:317
l @ jquery.js:3268
fireWith @ jquery.js:3398
T @ jquery.js:9305
(anonymous) @ jquery.js:9548
load (async)
send @ jquery.js:9567
ajax @ jquery.js:9206
ajaxify.loadData @ ajaxify.js:291
ajaxify.go @ ajaxify.js:87
a @ ajaxify.js:364
(anonymous) @ ajaxify.js:424
dispatch @ jquery.js:5183
g.handle @ jquery.js:4991
require.js:7 Uncaught Error: Script error for "/forum/assets/templates/admin/plugins/sso-facebook.js"
http://requirejs.org/docs/errors.html#scripterror
    at F (require.js:7)
    at HTMLScriptElement.onScriptError (require.js:30)
```

Also, if I reset the server and go to the forum again I get the following error in the server log:

```
Error: Failed to lookup view "admin/plugins/sso-facebook" in views directory "/var/www/html/nodebb/build/public/templates"
    at Function.render (/var/www/html/nodebb/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/var/www/html/nodebb/node_modules/express/lib/response.js:1008:7)
    at content (/var/www/html/nodebb/src/middleware/render.js:84:15)
    at /var/www/html/nodebb/node_modules/async/dist/async.js:3880:24
    at replenish (/var/www/html/nodebb/node_modules/async/dist/async.js:1011:17)
    at /var/www/html/nodebb/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/var/www/html/nodebb/node_modules/async/dist/async.js:1041:24)
    at /var/www/html/nodebb/node_modules/async/dist/async.js:1046:16
    at eachOf (/var/www/html/nodebb/node_modules/async/dist/async.js:1117:5)
    at _parallel (/var/www/html/nodebb/node_modules/async/dist/async.js:3879:5)
    at Object.parallelLimit [as parallel] (/var/www/html/nodebb/node_modules/async/dist/async.js:3962:5)
    at async.waterfall.str (/var/www/html/nodebb/src/middleware/render.js:79:12)
    at nextTask (/var/www/html/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/var/www/html/nodebb/node_modules/async/dist/async.js:5331:9)
    at /var/www/html/nodebb/node_modules/async/dist/async.js:969:16
    at /var/www/html/nodebb/node_modules/async/dist/async.js:473:16
```

And get the following error in the view:

```
Internal Error.
Oops! Looks like something went wrong!

/forum/admin/plugins/sso-facebook

ENOENT: no such file or directory, open '/var/www/html/nodebb/build/public/templates/admin/plugins/sso-facebook.js'
```

I have checked the following folder:
/var/www/html/nodebb/build/public/templates/admin/plugins

And I can verify that the template or the JS files don't exist.
I have also checked that the plugin has been successfully installed and I can see it in the *node_modules* folder.

**Comment by robin4002** [comment]
Hi,
Did you restart or rebuild and restart NodeBB ?
When a new plugin with template or a theme is installed, you need to rebuild NodeBB.

**Comment by julianlam** [comment]
:point_up:
