### ISSUE TITLE
/nodebb start error

### ISSUE THREAD

**Issue by xiaomiwujiecao** [NodeBB/NodeBB#6908]
at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Server.emit (events.js:208:7)
    at emitCloseNT (net.js:1664:8)
    at _combinedTickCallback (internal/process/next_tick.js:136:11)
    at Immediate._tickCallback (internal/process/next_tick.js:181:9)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
3 restarts in 10 seconds, most likely an error on startup. Halting.
^C

**Comment by pitaj** [comment]
Please follow the issue template. This isn't even a complete stack trace.
