### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by bonaccorsop** [NodeBB/NodeBB#6970]
- NodeBB v1.10.2  branch: **master** **#bccfa7**
- OS: Windows 10 pro with WSL 
- **Database type:** mongo  v3.4.10

executed:  `./nodebb build`

- **What you expected:**
Assets built successfully 

- **What really happens :**
```
2018-11-19T09:17:45.489Z [1163] - info: [build]                     sounds  build started
2018-11-19T09:17:51.093Z [1163] - info: [build]                     sounds  build completed in 5.604sec
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open '....NodeBB/node_modules/caniuse-lite/data/features/url.js'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:698:20)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (.../NodeBB/node_modules/caniuse-lite/data/features.js:1:24755)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module './features/woff2'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (.../NodeBB/node_modules/caniuse-lite/data/features.js:1:26065)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

**Comment by bonaccorsop** [comment]
Theme active: **nodebb-theme-persona**

**Comment by bonaccorsop** [comment]
`./nodebb build ---series`

build successfully instead...

**Comment by julianlam** [comment]
Do parallel builds still fail?

**Comment by nodebb-misty** [comment]
Issue closed due to inactivity.

----

*This is an automated message. If you feel this action was in error, please comment on this issue so it can be looked at again*
