### ISSUE TITLE
connect Module, Error: Forbidden

### ISSUE THREAD

**Issue by akhoury** [NodeBB/NodeBB#702]
occasionally, I see this, it doesn't crash NodeBB, but it annoys me 

``` bash
info: [Auth] Session -R2aX7ifnT_L6bQ7vHUcXFqV logout (uid: 1)
Error: Forbidden
    at Object.exports.error (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/utils.js:60:13)
    at Object.handle (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/csrf.js:54:41)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.session [as handle] (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/session.js:302:7)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.cookieParser [as handle] (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at multipart (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/multipart.js:60:27)
    at /home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
    at IncomingMessage.<anonymous> (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:70:11)
Error: Forbidden
    at Object.exports.error (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/utils.js:60:13)
    at Object.handle (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/csrf.js:54:41)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.session [as handle] (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/session.js:302:7)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.cookieParser [as handle] (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at multipart (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/multipart.js:60:27)
    at /home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
    at IncomingMessage.<anonymous> (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:70:11)
Error: Forbidden
    at Object.exports.error (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/utils.js:60:13)
    at Object.handle (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/csrf.js:54:41)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.session [as handle] (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/session.js:302:7)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.cookieParser [as handle] (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at multipart (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/multipart.js:60:27)
    at /home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
    at IncomingMessage.<anonymous> (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:70:11)
Error: Forbidden
    at Object.exports.error (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/utils.js:60:13)
    at Object.handle (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/csrf.js:54:41)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.session [as handle] (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/session.js:302:7)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.cookieParser [as handle] (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at multipart (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/multipart.js:60:27)
    at /home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
    at IncomingMessage.<anonymous> (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:70:11)
Error: Forbidden
    at Object.exports.error (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/utils.js:60:13)
    at Object.handle (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/csrf.js:54:41)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.session [as handle] (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/session.js:302:7)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.cookieParser [as handle] (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at multipart (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/multipart.js:60:27)
    at /home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
    at IncomingMessage.<anonymous> (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:70:11)
Error: Forbidden
    at Object.exports.error (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/utils.js:60:13)
    at Object.handle (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/csrf.js:54:41)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.session [as handle] (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/session.js:302:7)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.cookieParser [as handle] (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
    at next (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at multipart (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/multipart.js:60:27)
    at /home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
    at IncomingMessage.<anonymous> (/home/admin/NodeBB/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:70:11)
info: [Auth] Session -R2aX7ifnT_L6bQ7vHUcXFqV logout (uid: 2)
```

**Comment by lots0logs** [comment]
I am seeing this using with 0.6.x. I cannot log in. I've tried reloading the page and clearing my cookies. Here is the error that shows in the log:
```
24/1 06:27 [36] - error: /forum/login
 Error: invalid csrf token
    at verifytoken (/opt/nodebb/node_modules/csurf/index.js:237:11)
    at csrf (/opt/nodebb/node_modules/csurf/index.js:100:7)
    at Layer.handle [as handle_request] (/opt/nodebb/node_modules/express/lib/router/layer.js:82:5)
    at next (/opt/nodebb/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/opt/nodebb/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/opt/nodebb/node_modules/express/lib/router/layer.js:82:5)
    at /opt/nodebb/node_modules/express/lib/router/index.js:235:24
    at Function.proto.process_params (/opt/nodebb/node_modules/express/lib/router/index.js:313:12)
    at /opt/nodebb/node_modules/express/lib/router/index.js:229:12
    at Function.match_layer (/opt/nodebb/node_modules/express/lib/router/index.js:296:3)
```
