### ISSUE TITLE
Docker Persist data and configuration

### ISSUE THREAD

**Issue by Laul0** [NodeBB/NodeBB#7107]
- **NodeBB version:** 1.11.0
- **NodeBB git hash:** ab5035f

- **Database type:** redis
- **Database version:** 4.0.9

- **Exact steps to cause this issue:**

1. I'm using the docker `nodebb/docker:latest`
2. Here, my docker compose :
```bash
blog-nodebb:
    image: nodebb/docker:latest
    container_name: blog-nodebb
    ports:
      - "80"
    networks:
      - nodebb
      - default
    volumes:
      - type: bind
        source: /apps/data/nodebb/public
        target: /usr/src/app/public
      - type: bind
        source: /apps/data/nodebb/data
        target: /data
    environment:
      - VIRTUAL_HOST=myowndomain.ltd
      - VIRTUAL_PORT=4567
    restart: always
```
3. If I add a volume for the config file, I have an error not file found.
4. So, I execute the first time without mount config.json file, configure my NodeBB server and backup the json file (It work's like a charm)
5. I add the bind config.json
```bash
- type: bind
        source: /apps/data/nodebb/conf/config.json
        target: /usr/src/app/config.json
```
6. Bam, several error from log and internal error from the web
```bash
blog-nodebb    | 2018-12-14T11:05:53.804Z [24] - warn: [cache-buster] could not read cache buster {"errno":-2,"code":"ENOENT","syscall":"open","path":"/usr/src/app/build/cache-buster","meta":{"errno":-2,"code":"ENOENT","syscall":"open","path":"/usr/src/app/build/cache-buster"}}
blog-nodebb    | 2018-12-14T11:05:54.407Z [24] - info: [socket.io] Restricting access to origin: https://myowndomain.ltd:*
blog-nodebb    | 2018-12-14T11:05:54.443Z [24] - error: [emailer] Failed to build custom email templates
blog-nodebb    | Error: ENOENT: no such file or directory, scandir '/usr/src/app/build/public/templates/emails'
blog-nodebb    | 2018-12-14T11:05:54.849Z [24] - info: Routes added
blog-nodebb    | 2018-12-14T11:05:54.852Z [24] - info: NodeBB Ready
blog-nodebb    | 2018-12-14T11:05:54.857Z [24] - info: Enabling 'trust proxy'
blog-nodebb    | 2018-12-14T11:05:54.863Z [24] - info: NodeBB is now listening on: 0.0.0.0:4567
blog-nodebb    | 2018-12-14T11:06:18.641Z [24] - error: /
blog-nodebb    | 
blog-nodebb    | Error: Failed to lookup view "admin/general/dashboard" in views directory "/usr/src/app/build/public/templates"
blog-nodebb    |     at Function.render (/usr/src/app/node_modules/express/lib/application.js:580:17)
blog-nodebb    |     at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1008:7)
blog-nodebb    |     at content (/usr/src/app/src/middleware/render.js:84:15)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:3880:24
blog-nodebb    |     at replenish (/usr/src/app/node_modules/async/dist/async.js:1011:17)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1016:9
blog-nodebb    |     at eachOfLimit (/usr/src/app/node_modules/async/dist/async.js:1041:24)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1046:16
blog-nodebb    |     at eachOf (/usr/src/app/node_modules/async/dist/async.js:1117:5)
blog-nodebb    |     at _parallel (/usr/src/app/node_modules/async/dist/async.js:3879:5)
blog-nodebb    |     at Object.parallelLimit [as parallel] (/usr/src/app/node_modules/async/dist/async.js:3962:5)
blog-nodebb    |     at async.waterfall.str (/usr/src/app/src/middleware/render.js:79:12)
blog-nodebb    |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:5324:14)
blog-nodebb    |     at next (/usr/src/app/node_modules/async/dist/async.js:5331:9)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:969:16
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:473:16
blog-nodebb    | Missing translation "language:dir"
blog-nodebb    | Error: Failed to lookup view "500" in views directory "/usr/src/app/build/public/templates"
blog-nodebb    |     at Function.render (/usr/src/app/node_modules/express/lib/application.js:580:17)
blog-nodebb    |     at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1008:7)
blog-nodebb    |     at content (/usr/src/app/src/middleware/render.js:84:15)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:3880:24
blog-nodebb    |     at replenish (/usr/src/app/node_modules/async/dist/async.js:1011:17)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1016:9
blog-nodebb    |     at eachOfLimit (/usr/src/app/node_modules/async/dist/async.js:1041:24)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1046:16
blog-nodebb    |     at eachOf (/usr/src/app/node_modules/async/dist/async.js:1117:5)
blog-nodebb    |     at _parallel (/usr/src/app/node_modules/async/dist/async.js:3879:5)
blog-nodebb    |     at Object.parallelLimit [as parallel] (/usr/src/app/node_modules/async/dist/async.js:3962:5)
blog-nodebb    |     at async.waterfall.str (/usr/src/app/src/middleware/render.js:79:12)
blog-nodebb    |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:5324:14)
blog-nodebb    |     at next (/usr/src/app/node_modules/async/dist/async.js:5331:9)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:969:16
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:473:16
blog-nodebb    | 2018-12-14T11:06:22.064Z [24] - error: /
blog-nodebb    | 
blog-nodebb    | Error: Failed to lookup view "admin/general/dashboard" in views directory "/usr/src/app/build/public/templates"
blog-nodebb    |     at Function.render (/usr/src/app/node_modules/express/lib/application.js:580:17)
blog-nodebb    |     at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1008:7)
blog-nodebb    |     at content (/usr/src/app/src/middleware/render.js:84:15)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:3880:24
blog-nodebb    |     at replenish (/usr/src/app/node_modules/async/dist/async.js:1011:17)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1016:9
blog-nodebb    |     at eachOfLimit (/usr/src/app/node_modules/async/dist/async.js:1041:24)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1046:16
blog-nodebb    |     at eachOf (/usr/src/app/node_modules/async/dist/async.js:1117:5)
blog-nodebb    |     at _parallel (/usr/src/app/node_modules/async/dist/async.js:3879:5)
blog-nodebb    |     at Object.parallelLimit [as parallel] (/usr/src/app/node_modules/async/dist/async.js:3962:5)
blog-nodebb    |     at async.waterfall.str (/usr/src/app/src/middleware/render.js:79:12)
blog-nodebb    |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:5324:14)
blog-nodebb    |     at next (/usr/src/app/node_modules/async/dist/async.js:5331:9)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:969:16
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:473:16
blog-nodebb    | Missing translation "language:dir"
blog-nodebb    | Error: Failed to lookup view "500" in views directory "/usr/src/app/build/public/templates"
blog-nodebb    |     at Function.render (/usr/src/app/node_modules/express/lib/application.js:580:17)
blog-nodebb    |     at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1008:7)
blog-nodebb    |     at content (/usr/src/app/src/middleware/render.js:84:15)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:3880:24
blog-nodebb    |     at replenish (/usr/src/app/node_modules/async/dist/async.js:1011:17)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1016:9
blog-nodebb    |     at eachOfLimit (/usr/src/app/node_modules/async/dist/async.js:1041:24)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1046:16
blog-nodebb    |     at eachOf (/usr/src/app/node_modules/async/dist/async.js:1117:5)
blog-nodebb    |     at _parallel (/usr/src/app/node_modules/async/dist/async.js:3879:5)
blog-nodebb    |     at Object.parallelLimit [as parallel] (/usr/src/app/node_modules/async/dist/async.js:3962:5)
blog-nodebb    |     at async.waterfall.str (/usr/src/app/src/middleware/render.js:79:12)
blog-nodebb    |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:5324:14)
blog-nodebb    |     at next (/usr/src/app/node_modules/async/dist/async.js:5331:9)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:969:16
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:473:16
blog-nodebb    | 2018-12-14T11:06:22.479Z [24] - error: /categories
blog-nodebb    | 
blog-nodebb    | Error: Failed to lookup view "categories" in views directory "/usr/src/app/build/public/templates"
blog-nodebb    |     at Function.render (/usr/src/app/node_modules/express/lib/application.js:580:17)
blog-nodebb    |     at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1008:7)
blog-nodebb    |     at content (/usr/src/app/src/middleware/render.js:84:15)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:3880:24
blog-nodebb    |     at replenish (/usr/src/app/node_modules/async/dist/async.js:1011:17)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1016:9
blog-nodebb    |     at eachOfLimit (/usr/src/app/node_modules/async/dist/async.js:1041:24)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1046:16
blog-nodebb    |     at eachOf (/usr/src/app/node_modules/async/dist/async.js:1117:5)
blog-nodebb    |     at _parallel (/usr/src/app/node_modules/async/dist/async.js:3879:5)
blog-nodebb    |     at Object.parallelLimit [as parallel] (/usr/src/app/node_modules/async/dist/async.js:3962:5)
blog-nodebb    |     at async.waterfall.str (/usr/src/app/src/middleware/render.js:79:12)
blog-nodebb    |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:5324:14)
blog-nodebb    |     at next (/usr/src/app/node_modules/async/dist/async.js:5331:9)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:969:16
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:473:16
blog-nodebb    | Missing translation "language:dir"
blog-nodebb    | Missing translation "language:dir"
blog-nodebb    | Missing translation "pages:home"
blog-nodebb    | Error: Failed to lookup view "500" in views directory "/usr/src/app/build/public/templates"
blog-nodebb    |     at Function.render (/usr/src/app/node_modules/express/lib/application.js:580:17)
blog-nodebb    |     at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1008:7)
blog-nodebb    |     at content (/usr/src/app/src/middleware/render.js:84:15)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:3880:24
blog-nodebb    |     at replenish (/usr/src/app/node_modules/async/dist/async.js:1011:17)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1016:9
blog-nodebb    |     at eachOfLimit (/usr/src/app/node_modules/async/dist/async.js:1041:24)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1046:16
blog-nodebb    |     at eachOf (/usr/src/app/node_modules/async/dist/async.js:1117:5)
blog-nodebb    |     at _parallel (/usr/src/app/node_modules/async/dist/async.js:3879:5)
blog-nodebb    |     at Object.parallelLimit [as parallel] (/usr/src/app/node_modules/async/dist/async.js:3962:5)
blog-nodebb    |     at async.waterfall.str (/usr/src/app/src/middleware/render.js:79:12)
blog-nodebb    |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:5324:14)
blog-nodebb    |     at next (/usr/src/app/node_modules/async/dist/async.js:5331:9)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:969:16
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:473:16
blog-nodebb    | 2018-12-14T11:06:22.530Z [24] - error: /categories
blog-nodebb    | 
blog-nodebb    | Error: Failed to lookup view "categories" in views directory "/usr/src/app/build/public/templates"
blog-nodebb    |     at Function.render (/usr/src/app/node_modules/express/lib/application.js:580:17)
blog-nodebb    |     at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1008:7)
blog-nodebb    |     at content (/usr/src/app/src/middleware/render.js:84:15)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:3880:24
blog-nodebb    |     at replenish (/usr/src/app/node_modules/async/dist/async.js:1011:17)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1016:9
blog-nodebb    |     at eachOfLimit (/usr/src/app/node_modules/async/dist/async.js:1041:24)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1046:16
blog-nodebb    |     at eachOf (/usr/src/app/node_modules/async/dist/async.js:1117:5)
blog-nodebb    |     at _parallel (/usr/src/app/node_modules/async/dist/async.js:3879:5)
blog-nodebb    |     at Object.parallelLimit [as parallel] (/usr/src/app/node_modules/async/dist/async.js:3962:5)
blog-nodebb    |     at async.waterfall.str (/usr/src/app/src/middleware/render.js:79:12)
blog-nodebb    |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:5324:14)
blog-nodebb    |     at next (/usr/src/app/node_modules/async/dist/async.js:5331:9)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:969:16
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:473:16
blog-nodebb    | Missing translation "language:dir"
blog-nodebb    | Missing translation "pages:home"
blog-nodebb    | Missing translation "language:dir"
blog-nodebb    | Error: Failed to lookup view "500" in views directory "/usr/src/app/build/public/templates"
blog-nodebb    |     at Function.render (/usr/src/app/node_modules/express/lib/application.js:580:17)
blog-nodebb    |     at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1008:7)
blog-nodebb    |     at content (/usr/src/app/src/middleware/render.js:84:15)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:3880:24
blog-nodebb    |     at replenish (/usr/src/app/node_modules/async/dist/async.js:1011:17)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1016:9
blog-nodebb    |     at eachOfLimit (/usr/src/app/node_modules/async/dist/async.js:1041:24)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:1046:16
blog-nodebb    |     at eachOf (/usr/src/app/node_modules/async/dist/async.js:1117:5)
blog-nodebb    |     at _parallel (/usr/src/app/node_modules/async/dist/async.js:3879:5)
blog-nodebb    |     at Object.parallelLimit [as parallel] (/usr/src/app/node_modules/async/dist/async.js:3962:5)
blog-nodebb    |     at async.waterfall.str (/usr/src/app/src/middleware/render.js:79:12)
blog-nodebb    |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:5324:14)
blog-nodebb    |     at next (/usr/src/app/node_modules/async/dist/async.js:5331:9)
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:969:16
blog-nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:473:16
```
6. So, if I keep my compose without config.json :
    * I loose all installer plugin
    * I have to fill out the Web installer form
    * etc.

- **What you expected:**

Can persist all my configuration, data and plugin when I have to down and up my container !

- **What happened instead:**

**Comment by tom-rade** [comment]
Add following volumes:

```
      - type: bind
        source: /apps/data/nodebb/build
        target: /usr/src/app/build
      - type: bind
        source: /apps/data/nodebb/public/uploads
        target: /usr/src/app/public/uploads
```

Don't forget to run ./nodebb build or add this temporarly to your docker-compose.yml (first-time build):

`command: /bin/sh -c "node src/cli build && node src/cli start"`
