### ISSUE TITLE
Server crashes when saving /admin/manage/groups/groupname while default cover is set

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7150]
**NodeBB version:** v1.11.1
**NodeBB git hash:** 1ecedefae78ecdfb28c7e9e4b9cf634bd4de47f6

**Database type:** mongo
**Database version:** v4.0.4

Exact steps to cause this issue:

```
nodebb    | 2018-12-21T23:57:40.240Z [4568/510] - error: uncaughtException: Cannot read property 'startsWith' of undefined
nodebb    | TypeError: Cannot read property 'startsWith' of undefined
nodebb    |     at getCover (/usr/src/app/src/coverPhoto.js:26:19)
nodebb    |     at Object.coverPhoto.getDefaultGroupCover (/usr/src/app/src/coverPhoto.js:10:9)
nodebb    |     at modifyGroup (/usr/src/app/src/groups/data.js:100:50)
nodebb    |     at groupData.forEach.group (/usr/src/app/src/groups/data.js:45:32)
nodebb    |     at Array.forEach (<anonymous>)
nodebb    |     at /usr/src/app/src/groups/data.js:45:15
nodebb    |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:5324:14)
nodebb    |     at next (/usr/src/app/node_modules/async/dist/async.js:5331:9)
nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:969:16
nodebb    |     at /usr/src/app/src/database/mongo/hash.js:130:4
nodebb    |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
nodebb    |     at process._tickCallback (internal/process/next_tick.js:181:9) {"error":{},"stack":"TypeError: Cannot read property 'startsWith' of undefined\n    at getCover (/usr/src/app/src/coverPhoto.js:26:19)\n    at Object.coverPhoto.getDefaultGroupCover (/usr/src/app/src/coverPhoto.js:10:9)\n    at modifyGroup (/usr/src/app/src/groups/data.js:100:50)\n    at groupData.forEach.group (/usr/src/app/src/groups/data.js:45:32)\n    at Array.forEach (<anonymous>)\n    at /usr/src/app/src/groups/data.js:45:15\n    at nextTask (/usr/src/app/node_modules/async/dist/async.js:5324:14)\n    at next (/usr/src/app/node_modules/async/dist/async.js:5331:9)\n    at /usr/src/app/node_modules/async/dist/async.js:969:16\n    at /usr/src/app/src/database/mongo/hash.js:130:4\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickCallback (internal/process/next_tick.js:181:9)","exception":true,"date":"Fri Dec 21 2018 23:57:40 GMT+0000 (UTC)","process":{"pid":510,"uid":0,"gid":0,"cwd":"/usr/src/app","execPath":"/usr/local/bin/node","version":"v8.14.0","argv":["/usr/local/bin/node","/usr/src/app/app.js"],"memoryUsage":{"rss":140722176,"heapTotal":104394752,"heapUsed":92899784,"external":37063862}},"os":{"loadavg":[0.57763671875,0.36181640625,0.19384765625],"uptime":1437773},"trace":[{"column":19,"file":"/usr/src/app/src/coverPhoto.js","function":"getCover","line":26,"method":null,"native":false},{"column":9,"file":"/usr/src/app/src/coverPhoto.js","function":"Object.coverPhoto.getDefaultGroupCover","line":10,"method":"getDefaultGroupCover","native":false},{"column":50,"file":"/usr/src/app/src/groups/data.js","function":"modifyGroup","line":100,"method":null,"native":false},{"column":32,"file":"/usr/src/app/src/groups/data.js","function":"groupData.forEach.group","line":45,"method":"group","native":false},{"column":null,"file":null,"function":"Array.forEach","line":null,"method":"forEach","native":false},{"column":15,"file":"/usr/src/app/src/groups/data.js","function":null,"line":45,"method":null,"native":false},{"column":14,"file":"/usr/src/app/node_modules/async/dist/async.js","function":"nextTask","line":5324,"method":null,"native":false},{"column":9,"file":"/usr/src/app/node_modules/async/dist/async.js","function":"next","line":5331,"method":null,"native":false},{"column":16,"file":"/usr/src/app/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":4,"file":"/usr/src/app/src/database/mongo/hash.js","function":null,"line":130,"method":null,"native":false},{"column":11,"file":"internal/process/next_tick.js","function":"_combinedTickCallback","line":139,"method":null,"native":false},{"column":9,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":181,"method":"_tickCallback","native":false}]}
nodebb    | 2018-12-21T23:57:40.241Z [4568/510] - error: Cannot read property 'startsWith' of undefined
nodebb    | TypeError: Cannot read property 'startsWith' of undefined
nodebb    |     at getCover (/usr/src/app/src/coverPhoto.js:26:19)
nodebb    |     at Object.coverPhoto.getDefaultGroupCover (/usr/src/app/src/coverPhoto.js:10:9)
nodebb    |     at modifyGroup (/usr/src/app/src/groups/data.js:100:50)
nodebb    |     at groupData.forEach.group (/usr/src/app/src/groups/data.js:45:32)
nodebb    |     at Array.forEach (<anonymous>)
nodebb    |     at /usr/src/app/src/groups/data.js:45:15
nodebb    |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:5324:14)
nodebb    |     at next (/usr/src/app/node_modules/async/dist/async.js:5331:9)
nodebb    |     at /usr/src/app/node_modules/async/dist/async.js:969:16
nodebb    |     at /usr/src/app/src/database/mongo/hash.js:130:4
nodebb    |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
nodebb    |     at process._tickCallback (internal/process/next_tick.js:181:9)
nodebb    | 2018-12-21T23:57:40.242Z [4568/510] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
nodebb    | 2018-12-21T23:57:40.250Z [4568/510] - info: [app] Web server closed to connections.
nodebb    | 2018-12-21T23:57:40.250Z [4568/510] - info: [app] Live analytics saved.
nodebb    | 2018-12-21T23:57:40.254Z [4568/510] - info: [app] Database connection closed.
nodebb    | 2018-12-21T23:57:40.255Z [4568/510] - info: [app] Shutdown complete.

```

When default cover for groups is set, then this error happens. When none is set, the server works normally and the saving is successful.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/41fb5cca81c10707c38b1e4c71ca0301af317f38
