### ISSUE TITLE
crash Upgrading from 1.10 to 1.11

### ISSUE THREAD

**Issue by YuanChenmang** [NodeBB/NodeBB#7174]
I got the Error Upgrading from 1.10.x to 1.11.x
### VPS info
node -v  v10.15.0
npm -v 6.4.1
Ubuntu 16.04 LTS
mongod --version
db version v3.6.0
``` sh
NodeBB v1.11.1 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

2018-12-28T15:08:34.834Z [4568/28933] - info: Initializing NodeBB v1.11.1 http://forum.widora.io
2018-12-28T15:08:37.206Z [4568/28933] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-ns-embed`. Skipping.
2018-12-28T15:08:37.207Z [4568/28933] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-poll`. Skipping.
2018-12-28T15:08:37.207Z [4568/28933] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-recent-cards`. Skipping.
2018-12-28T15:08:37.208Z [4568/28933] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-sso-github2`. Skipping.
2018-12-28T15:08:37.901Z [4568/28933] - info: [socket.io] Restricting access to origin: http://forum.widora.io:*
2018-12-28T15:08:37.914Z [4568/28933] - error: uncaughtException: key.split is not a function
TypeError: key.split is not a function
    at module.exports (/home/ubuntu/NodeBB/node_modules/nodemailer/lib/well-known/index.js:45:28)
    at new SMTPTransport (/home/ubuntu/NodeBB/node_modules/nodemailer/lib/smtp-transport/index.js:43:24)
    at Object.module.exports.createTransport (/home/ubuntu/NodeBB/node_modules/nodemailer/lib/nodemailer.js:54:27)
    at Object.Emailer.setupFallbackTransport (/home/ubuntu/NodeBB/src/emailer.js:116:40)
    at Object.Emailer.registerApp (/home/ubuntu/NodeBB/src/emailer.js:158:10)
    at Object.module.exports.listen (/home/ubuntu/NodeBB/src/webserver.js:79:10)
    at /home/ubuntu/NodeBB/src/start.js:55:14
    at nextTask (/home/ubuntu/NodeBB/node_modules/async/dist/async.js:5324:14)
    at next (/home/ubuntu/NodeBB/node_modules/async/dist/async.js:5331:9)
    at /home/ubuntu/NodeBB/node_modules/async/dist/async.js:969:16
    at /home/ubuntu/NodeBB/src/database/index.js:38:3
    at /home/ubuntu/NodeBB/src/database/mongo.js:161:3
    at result (/home/ubuntu/NodeBB/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/home/ubuntu/NodeBB/node_modules/mongodb/lib/utils.js:406:9)
    at err (/home/ubuntu/NodeBB/node_modules/mongodb/lib/operations/mongo_client_ops.js:286:5)
    at connectCallback (/home/ubuntu/NodeBB/node_modules/mongodb/lib/operations/mongo_client_ops.js:241:5) {"error":{},"stack":"TypeError: key.split is not a function\n    at module.exports (/home/ubuntu/NodeBB/node_modules/nodemailer/lib/well-known/index.js:45:28)\n    at new SMTPTransport (/home/ubuntu/NodeBB/node_modules/nodemailer/lib/smtp-transport/index.js:43:24)\n    at Object.module.exports.createTransport (/home/ubuntu/NodeBB/node_modules/nodemailer/lib/nodemailer.js:54:27)\n    at Object.Emailer.setupFallbackTransport (/home/ubuntu/NodeBB/src/emailer.js:116:40)\n    at Object.Emailer.registerApp (/home/ubuntu/NodeBB/src/emailer.js:158:10)\n    at Object.module.exports.listen (/home/ubuntu/NodeBB/src/webserver.js:79:10)\n    at /home/ubuntu/NodeBB/src/start.js:55:14\n    at nextTask (/home/ubuntu/NodeBB/node_modules/async/dist/async.js:5324:14)\n    at next (/home/ubuntu/NodeBB/node_modules/async/dist/async.js:5331:9)\n    at /home/ubuntu/NodeBB/node_modules/async/dist/async.js:969:16\n    at /home/ubuntu/NodeBB/src/database/index.js:38:3\n    at /home/ubuntu/NodeBB/src/database/mongo.js:161:3\n    at result (/home/ubuntu/NodeBB/node_modules/mongodb/lib/utils.js:414:17)\n    at executeCallback (/home/ubuntu/NodeBB/node_modules/mongodb/lib/utils.js:406:9)\n    at err (/home/ubuntu/NodeBB/node_modules/mongodb/lib/operations/mongo_client_ops.js:286:5)\n    at connectCallback (/home/ubuntu/NodeBB/node_modules/mongodb/lib/operations/mongo_client_ops.js:241:5)","exception":true,"date":"Fri Dec 28 2018 23:08:37 GMT+0800 (China Standard Time)","process":{"pid":28933,"uid":500,"gid":500,"cwd":"/home/ubuntu/NodeBB","execPath":"/usr/bin/node","version":"v10.15.0","argv":["/usr/bin/node","/home/ubuntu/NodeBB/app.js"],"memoryUsage":{"rss":148430848,"heapTotal":111874048,"heapUsed":81634560,"external":37782091}},"os":{"loadavg":[0.4169921875,0.3642578125,0.27783203125],"uptime":3825007},"trace":[{"column":28,"file":"/home/ubuntu/NodeBB/node_modules/nodemailer/lib/well-known/index.js","function":"module.exports","line":45,"method":"exports","native":false},{"column":24,"file":"/home/ubuntu/NodeBB/node_modules/nodemailer/lib/smtp-transport/index.js","function":"new SMTPTransport","line":43,"method":null,"native":false},{"column":27,"file":"/home/ubuntu/NodeBB/node_modules/nodemailer/lib/nodemailer.js","function":"Object.module.exports.createTransport","line":54,"method":"createTransport","native":false},{"column":40,"file":"/home/ubuntu/NodeBB/src/emailer.js","function":"Object.Emailer.setupFallbackTransport","line":116,"method":"setupFallbackTransport","native":false},{"column":10,"file":"/home/ubuntu/NodeBB/src/emailer.js","function":"Object.Emailer.registerApp","line":158,"method":"registerApp","native":false},{"column":10,"file":"/home/ubuntu/NodeBB/src/webserver.js","function":"Object.module.exports.listen","line":79,"method":"listen","native":false},{"column":14,"file":"/home/ubuntu/NodeBB/src/start.js","function":null,"line":55,"method":null,"native":false},{"column":14,"file":"/home/ubuntu/NodeBB/node_modules/async/dist/async.js","function":"nextTask","line":5324,"method":null,"native":false},{"column":9,"file":"/home/ubuntu/NodeBB/node_modules/async/dist/async.js","function":"next","line":5331,"method":null,"native":false},{"column":16,"file":"/home/ubuntu/NodeBB/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":3,"file":"/home/ubuntu/NodeBB/src/database/index.js","function":null,"line":38,"method":null,"native":false},{"column":3,"file":"/home/ubuntu/NodeBB/src/database/mongo.js","function":null,"line":161,"method":null,"native":false},{"column":17,"file":"/home/ubuntu/NodeBB/node_modules/mongodb/lib/utils.js","function":"result","line":414,"method":null,"native":false},{"column":9,"file":"/home/ubuntu/NodeBB/node_modules/mongodb/lib/utils.js","function":"executeCallback","line":406,"method":null,"native":false},{"column":5,"file":"/home/ubuntu/NodeBB/node_modules/mongodb/lib/operations/mongo_client_ops.js","function":"err","line":286,"method":null,"native":false},{"column":5,"file":"/home/ubuntu/NodeBB/node_modules/mongodb/lib/operations/mongo_client_ops.js","function":"connectCallback","line":241,"method":null,"native":false}]}
2018-12-28T15:08:37.916Z [4568/28933] - error: key.split is not a function
TypeError: key.split is not a function
    at module.exports (/home/ubuntu/NodeBB/node_modules/nodemailer/lib/well-known/index.js:45:28)
    at new SMTPTransport (/home/ubuntu/NodeBB/node_modules/nodemailer/lib/smtp-transport/index.js:43:24)
    at Object.module.exports.createTransport (/home/ubuntu/NodeBB/node_modules/nodemailer/lib/nodemailer.js:54:27)
    at Object.Emailer.setupFallbackTransport (/home/ubuntu/NodeBB/src/emailer.js:116:40)
    at Object.Emailer.registerApp (/home/ubuntu/NodeBB/src/emailer.js:158:10)
    at Object.module.exports.listen (/home/ubuntu/NodeBB/src/webserver.js:79:10)
    at /home/ubuntu/NodeBB/src/start.js:55:14
    at nextTask (/home/ubuntu/NodeBB/node_modules/async/dist/async.js:5324:14)
    at next (/home/ubuntu/NodeBB/node_modules/async/dist/async.js:5331:9)
    at /home/ubuntu/NodeBB/node_modules/async/dist/async.js:969:16
    at /home/ubuntu/NodeBB/src/database/index.js:38:3
    at /home/ubuntu/NodeBB/src/database/mongo.js:161:3
    at result (/home/ubuntu/NodeBB/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/home/ubuntu/NodeBB/node_modules/mongodb/lib/utils.js:406:9)
    at err (/home/ubuntu/NodeBB/node_modules/mongodb/lib/operations/mongo_client_ops.js:286:5)
    at connectCallback (/home/ubuntu/NodeBB/node_modules/mongodb/lib/operations/mongo_client_ops.js:241:5)
2018-12-28T15:08:37.918Z [4568/28933] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
[cluster] Child Process (28933) has exited (code: 1, signal: null)
[cluster] Spinning up another process...

```

```
ubuntu@VM-0-3-ubuntu:~/NodeBB$ cat config.json 
{
    "url": "http://forum.widora.io",
    "secret": "*********",
    "database": "mongo",
    "port": 4567,
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "nodebb",
        "password": "************",
        "database": "nodebb"
    },
    "socket.io": {
	"transports": ["polling"]
    }
}
```

**Comment by barisusakli** [comment]
https://community.nodebb.org/topic/13502/crash-upgrading-from-1-10-to-1-11/5

**Comment by julianlam** [comment]
Does this error occur on NodeBB startup? Can you please paste the following line into `src/emailer.js` at or around line 83, right after this line: `// Enable Gmail transport if enabled in ACP`

Paste this: 
```
Object.keys(config).filter(key => key.startsWith('email:')).forEach((key) => {
	console.log(key, '=>', config[key]);
});
```

**Comment by YuanChenmang** [comment]
Yes, when ./nodebb start
I got the log
n-google-analytics`. Skipping.
2019-01-01T02:44:13.206Z [4568/3807] - info: [socket.io] Restricting access to origin: https://sns.widora.io:*
email:disableEdit => 0
email:from => noreply@widora.io
email:from_name => Widora Forum
email:GmailTransport:enabled => 0
email:GmailTransport:user => 
email:GmailTransport:pass => 
email:custom:digest => 
email:smtpTransport:enabled => 1
email:smtpTransport:service => 126
email:smtpTransport:host => smtp.exmail.qq.com
email:smtpTransport:port => 587
email:smtpTransport:user => 
email:smtpTransport:pass => 
email:custom:banned => 
email:smtpTransport:security => NONE
added 20181229
{ service: 126 }
2019-01-01T02:44:13.239Z [4568/3807] - error: uncaughtException: key.split is not a function
TypeError: key.split is not a function

**Comment by pitaj** [comment]
Probably a nodemailer update removed that service from the list or something. We just need to check if the service exists before using it, maybe?

**Comment by victorelec14** [comment]
i have too some error on update from v1.10.x to v1.11.2 .

Index dont show categories/post

Forum ist very slowly ..

PS:  wit node 8.10.0  i have utils ist not a function, i need to install node 10.10.0

**Comment by victorelec14** [comment]
Development Tools: 
![image](https://user-images.githubusercontent.com/543450/50575372-765a6280-0dfe-11e9-8d0b-25bbd76eb822.png)

**Comment by YuanChenmang** [comment]
I close the "Use an external email server to send emails" on 1.10.2,
then git pull to 1.11.x
then It seems boot OK.

**Comment by julianlam** [comment]
@victorelec14 this sounds like a separate issue, please open a separate issue

**Comment by julianlam** [comment]
Thanks @yuanchenmang
