### ISSUE TITLE
Uploading Profile & Topic screenshots wont work

### ISSUE THREAD

**Issue by NLBlackEagle** [NodeBB/NodeBB#7201]
NodeBB Site: https://forum.dregora.com
NodeBB version: v1.11.1
NodeBB git hash: 1cdb6af5dcdcbde1ef9627f57b20002b296d9bdb
Database Type: Mongo Version 3.4.18
NodeBB Theme: Persona

Installed Plesk ( Server Management Software - Console )
Installed NodeJs version 9.10.1
Installed NodeBB Forum Software & MongoDB ( Using guide: https://www.howtoforge.com/tutorial/centos-nodebb-installation/ )

Expected being able to change my profile picture which did not work. ( Resulted in lost connection to forum )
Made sure all settings where setup correctly so that filetypes and uploads are permitted.
Changed file permissions to 777 to check if it was a permission issue.

I am getting the error:

```
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at WriteStream.Writable.write (_stream_writable.js:299:11)
    at Socket.<anonymous> (/var/www/vhosts/dregora.com/forum.dregora.com/src/logger.js:201:24)
    at Socket.<anonymous> (/var/www/vhosts/dregora.com/forum.dregora.com/src/logger.js:205:12)
    at Socket.<anonymous> (/var/www/vhosts/dregora.com/forum.dregora.com/src/logger.js:205:12)
    at Socket.<anonymous> (/var/www/vhosts/dregora.com/forum.dregora.com/src/logger.js:205:12)
    at Socket.<anonymous> (/var/www/vhosts/dregora.com/forum.dregora.com/src/logger.js:205:12)
    at Socket.<anonymous> (/var/www/vhosts/dregora.com/forum.dregora.com/src/logger.js:205:12)
    at Socket.<anonymous> (/var/www/vhosts/dregora.com/forum.dregora.com/src/logger.js:205:12)
    at Socket.<anonymous> (/var/www/vhosts/dregora.com/forum.dregora.com/src/logger.js:205:12)
    at Socket.<anonymous> (/var/www/vhosts/dregora.com/forum.dregora.com/src/logger.js:205:12)
    at Socket.<anonymous> (/var/www/vhosts/dregora.com/forum.dregora.com/src/logger.js:205:12)
    at Socket.<anonymous> (/var/www/vhosts/dregora.com/forum.dregora.com/src/logger.js:205:12)
    at Socket.<anonymous> (/var/www/vhosts/dregora.com/forum.dregora.com/src/logger.js:205:12)
    at Socket.<anonymous> (/var/www/vhosts/dregora.com/forum.dregora.com/src/logger.js:205:12)
```

Added Proxy Rules:

```
  location ~ / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;
    proxy_pass http://127.0.0.1:4567;
    proxy_redirect off;
    # Socket.IO Support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade"; 
  }

```

**Comment by julianlam** [comment]
Mmm, yes, that might be it :smile: A rebuild of sharp should hopefully resolve the issue.

**Comment by NLBlackEagle** [comment]
Soo, there appeared to be two errors. One with the nginx config which I solved in the past ( a / typo behind the proxy_pass ) So for anyone having this same issue make sure you double check the nginx rules for a typo. Secondly, after reinstalling the nodebb forum twice a npm rebuild fixed all the issues.

You have no clue how long I have been troubleshooting :P ( I constantly overlooked the / haha )

Im happy! Thanks for the quick response and help
