### ISSUE TITLE
SSL Certificate in config.json?

### ISSUE THREAD

**Issue by seti123** [NodeBB/NodeBB#723]
Is it possible to set the SSL certificate in the configuration? 
If not maybe this could be added? 

http://stackoverflow.com/questions/11804202/how-to-setup-a-ssl-cert-in-express-js-server-now

**Comment by sub-lunar** [comment]
Hi, sorry to comment on this old issue, but when I put my ssl cert and key in the config.json like described above, my nodebb v0.6.1 crashes and logs the following error:

```
@400000005509730b38625574 18/3 13:43 [19728] - ESC[32minfoESC[39m: NodeBB v0.6.1 Copyright (C) 2013-2014 NodeBB Inc.
@400000005509730b38747de4 18/3 13:43 [19728] - ESC[32minfoESC[39m: This program comes with ABSOLUTELY NO WARRANTY.
@400000005509730b387dad74 18/3 13:43 [19728] - ESC[32minfoESC[39m: This is free software, and you are welcome to redistribute it under certain conditions.
@400000005509730b387db544 18/3 13:43 [19728] - ESC[32minfoESC[39m: 
@400000005509730c11203d3c 18/3 13:43 [19728] - ESC[32minfoESC[39m: Time: Wed Mar 18 2015 13:43:46 GMT+0100 (CET)
@400000005509730c1122d164 18/3 13:43 [19728] - ESC[32minfoESC[39m: Initializing NodeBB v0.6.1
@40000000550973190fcf6aac 
@40000000550973190fd2f8d4 /home/edelextr/nodebb/src/webserver.js:101
@40000000550973190fdbce8c       server.setTimeout(10000);
@40000000550973190fdc5744              ^
@400000005509731910240ea4 TypeError: Object #<Server> has no method 'setTimeout'
@400000005509731910241674     at /home/edelextr/nodebb/src/webserver.js:101:9
@400000005509731910241a5c     at Object.<anonymous> (/home/edelextr/nodebb/src/webserver.js:168:2)
@400000005509731910241e44     at Module._compile (module.js:456:26)
@40000000550973191024222c     at Object.Module._extensions..js (module.js:474:10)
@400000005509731910242614     at Module.load (module.js:356:32)
@400000005509731910242614     at Function.Module._load (module.js:312:12)
@40000000550973191024687c     at Module.require (module.js:364:17)
@400000005509731910246c64     at require (module.js:380:17)
@400000005509731910246c64     at start (/home/edelextr/nodebb/app.js:134:18)
@40000000550973191024704c     at Object.<anonymous> (/home/edelextr/nodebb/app.js:75:2)
```
