### ISSUE TITLE
Invalid CSRF Token errors (with Nginx and Docker) 

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7251]
- **NodeBB version:** v1.11.1
- **NodeBB git hash:** 3859d417cea8609c752c88ef868d07cad710d39f
- **Database type:** mongo
- **Database version:**  v4.0.5
- **NodeJS version:** v10.14.2
- **npm version:** 6.4.1
- **Nginx version:** nginx/1.14.2
- **Docker version:** 18.09.1, build 4c52b90

The problem: Some users cannot register. But some can. I personally never had a problem registering or logging in - but some users apparently do and I feel a bit worried about that.

I provided everything I could think of. Any way to debug this? Anything wrong with my config?

Logs:
```
Missing key in translation token "text"
2019-01-13T17:46:52.950Z [4567/59] - error: /register
{"meta":"invalid csrf token"}
2019-01-13T18:00:08.599Z [4567/59] - info: [user/jobs] Digest (day) scheduling completed. 1 email(s) sent.
2019-01-13T18:00:08.831Z [4567/59] - info: [user/jobs] Digest (week) scheduling completed. 7 email(s) sent.
(node:59) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
2019-01-13T21:51:01.793Z [4568/60] - error: /logout
 {"meta":"invalid csrf token"}
2019-01-14T08:14:56.020Z [4567/59] - warn: [user/reset] Invalid email attempt: somedude@example.de by IP 123.456.789.123
(node:60) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
2019-01-14T18:00:08.361Z [4567/59] - info: [user/jobs] Digest (day) scheduling completed. 1 email(s) sent.
2019-01-15T09:28:07.190Z [4568/60] - error: /login
 {"meta":"invalid csrf token"}
(node:59) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'repeats' of null
    at repeats (/usr/src/app/node_modules/nodebb-plugin-calendar/src/lib/event.js:48:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:59) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:59) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

config.json:
```
{
    "url": "https://example.de",
    "secret": "CENSORED",
    "database": "mongo",
    "mongo": {
        "host": "mongo",
        "port": "27017",
        "username": "CENSORED",
        "password": "CENSORED",
        "database": "CENSORED",
        "uri": ""
    },
    "port": ["4567", "4568"]
}

```

Nginx:
```
# configuration file /etc/nginx/nginx.conf:

user nginx;
worker_processes auto;
pcre_jit on;
error_log /var/log/nginx/error.log warn;

events {
  worker_connections 30000;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  server_tokens off;
  client_body_buffer_size 16m;
  client_max_body_size 16m;
  client_header_buffer_size 16k;
  large_client_header_buffers 8 16k;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  types_hash_max_size 2048;
  server_names_hash_bucket_size 64;
  server_tokens off;
  reset_timedout_connection on;
  charset utf-8;
  proxy_read_timeout 5m;

  keepalive_timeout 35;
  sendfile on;
  tcp_nodelay on;
  tcp_nopush on;
  include /etc/nginx/site.d/*;
}

# configuration file /etc/nginx/site.d/example.de:
upstream io_nodes {
  ip_hash;
  server 172.17.0.1:4567; # Docker IPs
  server 172.17.0.1:4568; # Docker IPs
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name example.de;
  root /srv/web/default;

  ssl_certificate /etc/letsencrypt/live/example.de/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/example.de/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/example.de/fullchain.pem;

ssl_session_timeout 1d;
ssl_session_cache shared:SSL:50m;
ssl_session_tickets off;

ssl_dhparam /etc/nginx/dhparam.pem;

ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
ssl_prefer_server_ciphers on;
ssl_stapling on;
ssl_stapling_verify on;
resolver 1.1.1.1 8.8.8.8 valid=300s;

  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header Host $http_host;
  proxy_set_header X-NginX-Proxy true;
  proxy_redirect off;

  # Socket.io Support
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";

  gzip on;
  gzip_min_length 1000;
  gzip_proxied off;
  gzip_types text/plain application/xml text/javascript application/javascript application/x-javascript text/css application/json;

  location @nodebb {
    proxy_pass http://io_nodes;
  }
  location ~ ^/assets/(.*) {
    root /usr/src/app/;
    try_files /build/public/$1 /public/$1 @nodebb;
  }
  location /plugins/ {
    root /usr/src/app/build/public/;
    try_files $uri @nodebb;
  }
  location / {
    proxy_pass http://io_nodes;
  }
}
```

Docker:
```
version: '3.5'

services:

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
        - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: PASSWORD_CENSORED

  nodebb:
    image: nodebb-dev:latest
    restart: unless-stopped
    volumes:
      - ./nodebb/config.json:/usr/src/app/config.json
      - ./nodebb/build:/usr/src/app/build
      - ./nodebb/public/uploads:/usr/src/app/public/uploads
      - ./nodebb/logs:/var/log/nodebb
    ports:
      - 172.30.0.1:4567:4567
      - 172.30.0.1:4568:4568
    command: /bin/bash -c "./nodebb upgrade && ./nodebb start | tee -a /var/log/nodebb/nodebb.log"
```

Plugins:
```
 - nodebb-plugin-poll-updated
 - nodebb-plugin-ns-spoiler
 - nodebb-plugin-calendar
 - nodebb-plugin-modmin
 - nodebb-theme-persona
 - nodebb-plugin-markdown
 - nodebb-plugin-mentions
 - nodebb-widget-essentials
 - nodebb-rewards-essentials
 - nodebb-plugin-soundpack-default
 - nodebb-plugin-emoji
 - nodebb-plugin-emoji-android
 - nodebb-plugin-dbsearch
 - nodebb-plugin-recent-cards
 - nodebb-plugin-newsletter
 - nodebb-plugin-composer-default
 - nodebb-plugin-imgur
 - nodebb-plugin-custom-pages
 - nodebb-plugin-math-captcha
 - nodebb-plugin-pwned-passwords
 - nodebb-plugin-contact-page
 - nodebb-widget-ns-stats
```

**Comment by julianlam** [comment]
> but some users apparently do and I feel a bit worried about that.

Are these actual users you have heard from?

**Comment by tom-rade** [comment]
@julianlam Yes. Real users, and like 10 out of 500 users. It's weird because we constantly get new users coming in without a problem.

**Comment by julianlam** [comment]
Are you using redis for sessions? Please provide us with the output of `INFO`

**Comment by tom-rade** [comment]
@julianlam I am using MongoDB only.

**Comment by tom-rade** [comment]
@julianlam How do I do that? `./nodebb start --log-level INFO` ?

**Comment by balag12** [comment]
I am also encountering this issue, also using docker and Nginx. One of my users (one a small forum, sub-20 users right now) is encountering 403 forbidden due to a CSRF token issue when trying to register, no matter the browser they use.
