### ISSUE TITLE
TypeError: Cannot read property 'gdpr_consent' of undefined

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7262]
- **NodeBB version:** v1.11.1
- **NodeBB git hash:** 2fbb2614f3c6f27f6e53011135e7d4082890525c
- **Database type:** mongo
- **Database version:** 4.0.5

```
2019-01-17T07:21:43.451Z [4567/43] - error: /register/complete

TypeError: Cannot read property 'gdpr_consent' of undefined
    at Object.plugins.registerHook.method.data.interstitials.push.template [as method] (/usr/src/app/src/user/index.js:349:24)
    at /usr/src/app/src/plugins/hooks.js:133:12
    at /usr/src/app/node_modules/async/dist/async.js:2516:9
    at replenish (/usr/src/app/node_modules/async/dist/async.js:1011:17)
    at /usr/src/app/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/usr/src/app/node_modules/async/dist/async.js:1041:24)
    at /usr/src/app/node_modules/async/dist/async.js:1046:16
    at Object.reduce (/usr/src/app/node_modules/async/dist/async.js:2515:5)
    at fireFilterHook (/usr/src/app/src/plugins/hooks.js:125:9)
    at Object.Plugins.fireHook (/usr/src/app/src/plugins/hooks.js:105:4)

```

Probably a language variable problem @julianlam

**Comment by julianlam** [comment]
Stack trace is cut off on the right.

**Comment by tom-rade** [comment]
@julianla What do you mean?

**Comment by julianlam** [comment]
I mean exactly what I said, the stack trace is cut off on the right side.

**Comment by tom-rade** [comment]
@juliamlam I'm sorry, but I don't understand what a stack trace is.

What infos do you need? How do I fix this?

**Comment by julianlam** [comment]
The error you pasted above is incomplete. If you scroll to the right, you'll see that the line is cut off. I need the entire line in order to debug.

**Comment by tom-rade** [comment]
@julianlam Thank you for the clarification. I've now updated the error accordingly.

**Comment by julianlam** [comment]
I still need more info @tom-rade -- under what circumstances does this error occur?

I will need full reproduction steps that allow this to occur.
