### ISSUE TITLE
Npm install not work

### ISSUE THREAD

**Issue by Zaxerone** [NodeBB/NodeBB#7313]
When I do npm install Discord.js it does this to me:

npm ERR! code E404
npm ERR! 404 Not Found: Discord.js@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zaxer\AppData\Roaming\npm-cache\_logs\2019-01-28T19_33_53_301Z-debug.log

logs : 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'Discord.js' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose npm-session bc112ad9868fec35
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/Discord.js 1574ms
8 silly fetchPackageMetaData error for Discord.js@latest 404 Not Found: Discord.js@latest
9 timing stage:rollbackFailedOptional Completed in 4ms
10 timing stage:runTopLevelLifecycles Completed in 7151ms
11 verbose stack Error: 404 Not Found: Discord.js@latest
11 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:705:18)
11 verbose stack     at tryOnImmediate (timers.js:676:5)
11 verbose stack     at processImmediate (timers.js:658:5)
12 verbose cwd D:\Bot\node_modules
13 verbose Windows_NT 10.0.17134
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "Discord.js"
15 verbose node v10.15.0
16 verbose npm  v6.4.1
17 error code E404
18 error 404 Not Found: Discord.js@latest
19 verbose exit [ 1, true ]

**Comment by nodebb-misty** [comment]
Hello there! :smile:

This issue has been closed as it is not related to NodeBB or is a configuration issue that is better solved via our [community support forum](https://community.nodebb.org).

Remember, this issue tracker is just for bugs and defects in NodeBB.

Thanks!
