### ISSUE TITLE
Upgrade from v1.10 to v1.11 failed with postCss error : (Error occurred during upgrade: undefined)

### ISSUE THREAD

**Issue by zipang** [NodeBB/NodeBB#7351]
I relaunched the upgrade script after the last failure.
The process was almost complete but eventually failed on the CSS build step.

Here is the (abreged) log of the error : 

```
5. Rebuilding assets...  started
2019-02-08T20:08:12.288Z [4568/14031] - info: [build] Building in parallel mode
2019-02-08T20:08:12.288Z [4568/14031] - info: [build]         plugin static dirs  build started
2019-02-08T20:08:12.291Z [4568/14031] - info: [build]          requirejs modules  build started
2019-02-08T20:08:12.292Z [4568/14031] - info: [build]           client js bundle  build started
2019-02-08T20:08:12.296Z [4568/14031] - info: [build]            admin js bundle  build started
2019-02-08T20:08:12.297Z [4568/14031] - info: [build]         client side styles  build started
2019-02-08T20:08:12.297Z [4568/14031] - info: [build] admin control panel styles  build started
2019-02-08T20:08:12.298Z [4568/14031] - info: [build]                  templates  build started
2019-02-08T20:08:12.298Z [4568/14031] - info: [build]                  languages  build started
2019-02-08T20:08:12.298Z [4568/14031] - info: [build]                     sounds  build started
2019-02-08T20:08:12.847Z [4568/14031] - info: [build]                     sounds  build completed in 0.549sec
2019-02-08T20:08:13.153Z [4568/14031] - info: [build]         plugin static dirs  build completed in 0.865sec
2019-02-08T20:08:14.276Z [4568/14031] - error: [build]         client side styles  build failed
2019-02-08T20:08:14.278Z [4568/14031] - error: [build] Encountered error during build step {"meta":"CssSyntaxError: ....}
Error occurred during upgrade: undefined
2019-02-08T20:08:14.283Z [4568/14031] - error: uncaughtException: CssSyntaxError: <css input>:3:4: Unknown word
    at Input.error (/nodebb/node_modules/postcss/lib/input.js:130:16)
    at Parser.unknownWord (/nodebb/node_modules/postcss/lib/parser.js:563:22)
    at Parser.decl (/nodebb/node_modules/postcss/lib/parser.js:235:16)
    at Parser.other (/nodebb/node_modules/postcss/lib/parser.js:133:18)
    at Parser.parse (/nodebb/node_modules/postcss/lib/parser.js:77:16)
    at parse (/nodebb/node_modules/postcss/lib/parse.js:17:12)
    at new LazyResult (/nodebb/node_modules/postcss/lib/lazy-result.js:60:16)
    at Processor.<anonymous> (/nodebb/node_modules/postcss/lib/processor.js:138:12)
    at Processor.process (/nodebb/node_modules/postcss/lib/processor.js:117:23)
    at /nodebb/src/meta/minifier.js:281:23
```

And indeed, we can find that code (`undefined`) at line 281 of file `/src/meta/minifier.js` : 

![nodebb-postcss-script-failure-in-minifier](https://user-images.githubusercontent.com/658082/52504196-f89d2a00-2be7-11e9-99e0-d2df3795623f.png)

**Comment by pitaj** [comment]
There's a CSS syntax error, probably in one of your theme's files.

**Comment by zipang** [comment]
Great catch @pitaj ! :)
After some investigations and looking at this postCSS issue : 
["Unknown word" error when commenting with "//"](https://github.com/postcss/postcss/issues/1102)
I looked everywhere and there was that bad `//` comment coming from a less indication left inside one of the many many less files invocated : 
```css
// main: ../../theme.less
```
The error output was absolutely useless, as was the `{ from: undefined }` option indicating the source file.....
So... i may suggest that this error should be catched, and the less output leaved as is, because it didn't cause the rendering to fail before postCSS was introduced in the build process...

**Comment by zipang** [comment]
As a side note, i managed to fix my theme which is a fork of nodebb-theme-persona and is available here : 
https://github.com/zipang/nodebb-theme-mathforu

These indications at the first line of a less file : 
// main: ../../theme.less
are here to enable automatic compilation of the main less file when working in an IDE.

Anyway, when looking at the list of files that were involved in the build process : 

```
@import "./theme";

@import "./bootswatch/lumen/variables.less";
@import "./bootswatch/lumen/bootswatch.less";

@import (inline) "./nodebb-widget-essentials/public/css/widget.css";

@import "./nodebb-plugin-katex-latest/katex/katex.less";
@import "./nodebb-plugin-chats-global/static/style.less";
@import "./nodebb-plugin-spam-be-gone/public/less/styles.less";
@import "./nodebb-plugin-composer-default/static/less/composer.less";
@import "./nodebb-plugin-desktop-notifications/public/less/default.less";
@import "./nodebb-plugin-markdown/public/less/default.less";
@import "./nodebb-plugin-emoji/public/style.less";

@import "font-awesome";
@import (inline) "../public/vendor/jquery/css/smoothness/jquery-ui.css";
@import (inline) "../public/vendor/jquery/bootstrap-tagsinput/bootstrap-tagsinput.css";
@import (inline) "../public/vendor/colorpicker/colorpicker.css";
@import (inline) "../node_modules/cropperjs/dist/public/less/public/less/admin/manage/public/less/public/less/public/less/global.less
```
it is not at all impossible that some other forum admin fall in this trap without being able to identify the source of the problem.
So, i would really recommend that this postCSS error should be catched and ignored if it happens..

**Comment by pitaj** [comment]
If the error occurs, it likely means that the CSS wasn't built. If you were to delete your old CSS files and build, I doubt they would reappear.

What we should do instead is change how we output the error, so the information you need to fix it, like file and line, aren't lost.

**Comment by zipang** [comment]
I mean : the output of the less compiler (`lessOutput`) is good enough to take if the postCSS fails..

**Comment by pitaj** [comment]
Hard disagree.

If less is throwing out bad CSS, then that's a good thing to catch. PostCSS is responsible for minifying and prefixing our CSS. Without it, things can break.

**Comment by zipang** [comment]
Well... not at all ! _Things were not broken before the adjunction of PostCSS_ !

Browsers can cope well with a lot of malformed CSS rules.... (and a lot a malformed HTML too....) even if i do not encourage that..
It reminds me of the strict XHTML parsers that used to throw on any malformed tag.. and were extremely useless as so because they couldn't parse any real DOM...

And besides... because a lot of this Less or CSS come from external plugins or themes that we have installed, it is very hard for the forum admin to correct these issues if they show up !

You first thoughts must be _towards the forum administrator who has to spend hours_ investigating why the upgrade has failed, and what they can do now to revert the upgrade... : it's **BAD** ! 
Using a product that is so unreliable is a really bad experience !
You must take the _most extreme precautions_ and be _extremely conservatives_ not to break things during these upgrades !

That's my point (after 2 or 3 upgrades that were not for the faint of heart 🙈 )
Anyway.. no hard feeling.. NodeBB has still a lot to offer 👍 , but it should be more _reliable_, that's all.. 
Maybe you should have a procedure involving 4 or 5 real forum administrator to test the new releases before making them public.. i don't know ¯\_(ツ)_/¯

**Comment by barisusakli** [comment]
Less errors will display more info now instead of `undefined`

![image](https://user-images.githubusercontent.com/2583394/88425578-9923e180-cdbd-11ea-880b-b3936f0a6983.png)
