### ISSUE TITLE
Cannot set property 'name' of null (topics)

### ISSUE THREAD

**Issue by youhosi** [NodeBB/NodeBB#7490]
Version NodeBB: Latest
Redis: 5.0.3

Logs: 

```
2019-03-25T20:47:57.450Z [8002/6301] - [31merror[39m: /topic/355/noescape-v2-blokada-podczas-rajdu/25
Cannot set property 'name' of null {"stack":"TypeError: Cannot set property 'name' of null\n    at sizes.map (/var/www/src/posts/uploads.js:64:17)\n    at Array.map (<anonymous>)\n    at Object.Posts.uploads.listWithSizes (/var/www/src/posts/uploads.js:63:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
Missing translation "admin/manage/users:force-password-reset"
2019-03-25T20:56:05.534Z [8000/6294] - [31merror[39m: /topic/355/noescape-v2-blokada-podczas-rajdu/25
Cannot set property 'name' of null {"stack":"TypeError: Cannot set property 'name' of null\n    at sizes.map (/var/www/src/posts/uploads.js:64:17)\n    at Array.map (<anonymous>)\n    at Object.Posts.uploads.listWithSizes (/var/www/src/posts/uploads.js:63:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
2019-03-25T20:56:10.029Z [8000/6294] - [31merror[39m: /topic/355/noescape-v2-blokada-podczas-rajdu
Cannot set property 'name' of null {"stack":"TypeError: Cannot set property 'name' of null\n    at sizes.map (/var/www/src/posts/uploads.js:64:17)\n    at Array.map (<anonymous>)\n    at Object.Posts.uploads.listWithSizes (/var/www/src/posts/uploads.js:63:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
2019-03-25T20:56:21.033Z [8000/6294] - [31merror[39m: /topic/355/noescape-v2-blokada-podczas-rajdu
Cannot set property 'name' of null {"stack":"TypeError: Cannot set property 'name' of null\n    at sizes.map (/var/www/src/posts/uploads.js:64:17)\n    at Array.map (<anonymous>)\n    at Object.Posts.uploads.listWithSizes (/var/www/src/posts/uploads.js:63:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
2019-03-25T20:57:11.907Z [8000/6294] - [31merror[39m: /topic/355/noescape-v2-blokada-podczas-rajdu
Cannot set property 'name' of null {"stack":"TypeError: Cannot set property 'name' of null\n    at sizes.map (/var/www/src/posts/uploads.js:64:17)\n    at Array.map (<anonymous>)\n    at Object.Posts.uploads.listWithSizes (/var/www/src/posts/uploads.js:63:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
2019-03-25T20:57:26.414Z [8000/6294] - [31merror[39m: /topic/356/itemshelper-sprawdzaj-id-przedmiot%C3%B3w
Cannot set property 'name' of null {"stack":"TypeError: Cannot set property 'name' of null\n    at sizes.map (/var/www/src/posts/uploads.js:64:17)\n    at Array.map (<anonymous>)\n    at Object.Posts.uploads.listWithSizes (/var/www/src/posts/uploads.js:63:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
2019-03-25T20:57:54.805Z [8000/6294] - [31merror[39m: /api/topic/171/deathmessages-powiadomienia-o-%C5%9Bmierci
Cannot set property 'name' of null {"stack":"TypeError: Cannot set property 'name' of null\n    at sizes.map (/var/www/src/posts/uploads.js:64:17)\n    at Array.map (<anonymous>)\n    at Object.Posts.uploads.listWithSizes (/var/www/src/posts/uploads.js:63:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
```

Console
```
{path: "&#x2F;api&#x2F;topic&#x2F;476&#x2F;admintoolsv2", error: "Cannot set property 'name' of null"}
error: "Cannot set property 'name' of null"
path: "&#x2F;api&#x2F;topic&#x2F;476&#x2F;admintoolsv2"
```

**Comment by youhosi** [comment]
@julianlam Latest commit is not working..

Logs

```
2019-03-28T00:06:07.550Z [8000/11202] - error: /topic/476/admintoolsv2
Cannot set property 'name' of null {"stack":"TypeError: Cannot set property 'name' of null\n    at sizes.map (/var/www/src/posts/uploads.js:64:17)\n    at Array.map (<anonymous>)\n    at Object.Posts.uploads.listWithSizes (/var/www/src/posts/uploads.js:63:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
```

**Comment by julianlam** [comment]
Can't really reproduce to fix, can you add a console log to like 63 and see what `sizeObj` is?

**Comment by pitaj** [comment]
`sizes.filter(Boolean).map...` will probably fix it

**Comment by julianlam** [comment]
@pitaj This would cause problems if filtered because then `sizes` and `paths` will be of uneven lengths.
