### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by MrPupir** [NodeBB/NodeBB#7922]
Updating NodeBB...

1. Updating package.json file with defaults...  OK

2. Bringing base dependencies up to date...  started
audited 4725 packages in 23.497s
found 13 vulnerabilities (1 low, 5 moderate, 6 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

3. Checking installed plugins for updates...errorWarning: An unexpected error occured when attempting to verify plugin upgradability
Error occurred during upgrade: Error: connect ETIMEDOUT 159.203.9.60:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
2019-09-24T15:04:04.387Z [4567/7590] - error: uncaughtException: connect ETIMEDOUT 159.203.9.60:443
Error: connect ETIMEDOUT 159.203.9.60:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14) {"error":{"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"159.203.9.60","port":443},"stack":"Error: connect ETIMEDOUT 159.203.9.60:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)","exception":true,"date":"Tue Sep 24 2019 18:04:04 GMT+0300 (Moscow Standard Time)","process":{"pid":7590,"uid":0,"gid":0,"cwd":"/root/nodebb","execPath":"/usr/bin/node","version":"v10.16.3","argv":["/usr/bin/node","/root/nodebb/nodebb","upgrade"],"memoryUsage":{"rss":55508992,"heapTotal":25993216,"heapUsed":20719496,"external":18328882}},"os":{"loadavg":[0.1318359375,0.23388671875,0.18212890625],"uptime":158524},"trace":[{"column":14,"file":"net.js","function":"TCPConnectWrap.afterConnect [as oncomplete]","line":1106,"method":"afterConnect [as oncomplete]","native":false}]}

**Comment by julianlam** [comment]
Have you tried again since? This looks like maybe nbbpm was down momentarily.

**Comment by pitaj** [comment]
Additionally, you can skip the plugin upgrade attempt step with `./nodebb upgrade -mis`

**Comment by MrPupir** [comment]
> Have you tried again since? This looks like maybe nbbpm was down momentarily.

Sure, five times

**Comment by MrPupir** [comment]
> Additionally, you can skip the plugin upgrade attempt step with `./nodebb upgrade -mis`

It helped me, thanks a lot!
