### ISSUE TITLE
Update from v1.10.x to v1.12.x upgrade script fails on redis schema update

### ISSUE THREAD

**Issue by wellenreiter01** [NodeBB/NodeBB#7972]
- ** OS version:** Ubuntu 16.04.6 LTS
- **NodeBB version:** v1.12.x
- **NodeBB git hash:** 

- **Database type:**  redis
- **Database version:** Redis server v=5.0.6 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=9260170b247e88b

- **Exact steps to cause this issue:**
Originally posted here: https://community.nodebb.org/topic/14291/update-from-v1-10-x-to-v1-12-x-upgrade-script-fails-on-redis-schema-update

- **What you expected:**

- **What happened instead:**

When I run the 'nodebb upgrade' it fails with the following error:

4. Updating NodeBB data store schema...
 ......
 ......
OK | 15 script(s) found, 63 skipped
  → [2018/10/11] Fix category topic zsets...
    [              ] (1/9543) 0% 2019-10-13T09:27:38.996Z [4567/27784] - error: uncaughtException: db.parseIntFields is not a function
TypeError: db.parseIntFields is not a function
    at modifyTopic (/home/forum/nodebb/src/topics/data.js:106:5)
    at topics.forEach.topic (/home/forum/nodebb/src/topics/data.js:33:29)
    at Array.forEach (<anonymous>)
    at /home/forum/nodebb/src/topics/data.js:33:12
    at nextTask (/home/forum/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/home/forum/nodebb/node_modules/async/dist/async.js:5331:9)
    at /home/forum/nodebb/node_modules/async/dist/async.js:969:16
    at /home/forum/nodebb/node_modules/async/dist/async.js:473:16
    at next 
    (/home/forum/nodebb/node_modules/async/dist/async.js:5329:29)
    at /home/forum/nodebb/node_modules/async/dist/async.js:969:16 
    {"error":{},"stack":"TypeError: db.parseIntFields is not a function\n    at modifyTopic (/home/forum/nodebb/src/topics/data.js:106:5)\n    at topics.forEach.topic (/home/forum/nodebb/src/topics/data.js:33:29)\n    at Array.forEach (<anonymous>)\n    at /home/forum/nodebb/src/topics/data.js:33:12\n    at nextTask (/home/forum/nodebb/node_modules/async/dist/async.js:5324:14)\n    at next (/home/forum/nodebb/node_modules/async/dist/async.js:5331:9)\n    at /home/forum/nodebb/node_modules/async/dist/async.js:969:16\n    at /home/forum/nodebb/node_modules/async/dist/async.js:473:16\n    at next (/home/forum/nodebb/node_modules/async/dist/async.js:5329:29)\n    at /home/forum/nodebb/node_modules/async/dist/async.js:969:16","exception":true,"date":"Sun Oct 13 2019 10:27:38 GMT+0100 (British Summer Time)","process":{"pid":27784,"uid":1001,"gid":1001,"cwd":"/home/forum/nodebb","execPath":"/usr/bin/node","version":"v10.16.3","argv":["/usr/bin/node","/home/forum/nodebb/nodebb","upgrade"],"memoryUsage":{"rss":134868992,"heapTotal":98246656,"heapUsed":65464224,"external":885721}},"os":{"loadavg":[0.46044921875,0.2705078125,0.3525390625],"uptime":258020},"trace":[{"column":5,"file":"/home/forum/nodebb/src/topics/data.js","function":"modifyTopic","line":106,"method":null,"native":false},{"column":29,"file":"/home/forum/nodebb/src/topics/data.js","function":"topics.forEach.topic","line":33,"method":"topic","native":false},{"column":null,"file":null,"function":"Array.forEach","line":null,"method":"forEach","native":false},{"column":12,"file":"/home/forum/nodebb/src/topics/data.js","function":null,"line":33,"method":null,"native":false},{"column":14,"file":"/home/forum/nodebb/node_modules/async/dist/async.js","function":"nextTask","line":5324,"method":null,"native":false},{"column":9,"file":"/home/forum/nodebb/node_modules/async/dist/async.js","function":"next","line":5331,"method":null,"native":false},{"column":16,"file":"/home/forum/nodebb/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":16,"file":"/home/forum/nodebb/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":29,"file":"/home/forum/nodebb/node_modules/async/dist/async.js","function":"next","line":5329,"method":null,"native":false},{"column":16,"file":"/home/forum/nodebb/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false}]}

**Comment by barisusakli** [comment]
check if db.parseIntFields is in src/database/index.js https://github.com/NodeBB/NodeBB/blob/v1.12.x/src/database/index.js#L14

It is definitely in 1.12.x so not sure why you are getting an error.

**Comment by wellenreiter01** [comment]
@barisusakli 
I can confirm that db.parseIntFields is in src/database/index.js

@julianlam 

    ~/nodebb$ git rev-parse HEAD
22db818eb40f04e528d95257c5517ded8341493d

**Comment by pitaj** [comment]
Looks like something caused old files to remain in your git repository when you upgraded. Try deleting all of those untracked files and retrying  `./nodebb upgrade`

**Comment by julianlam** [comment]
Yeah this looks to be a configuration issue, so I'll close pending further discussion.

**Comment by wellenreiter01** [comment]
Sorry to bother again.
I have cleaned the files, so git status is clean now

    `~/nodebb$ git status
On branch v1.12.x
Your branch is up-to-date with 'origin/v1.12.x'.
nothing to commit, working directory clean
`

When I do a nodebb upgrade,I don't get the original error anymore, but it shows this errors now:

 
` → [2019/4/1] Convert all poll id votes and options votes to sorted sets...
Error occurred
Error occurred during upgrade: ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value
    at parseError (/home/forum/nodebb/node_modules/redis/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/home/forum/nodebb/node_modules/redis/node_modules/redis-parser/lib/parser.js:303:14)
2019-10-23T09:17:37.577Z [4567/7761] - error: uncaughtException: WRONGTYPE Operation against a key holding the wrong kind of value
ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value
    at parseError (/home/forum/nodebb/node_modules/redis/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/home/forum/nodebb/node_modules/redis/node_modules/redis-parser/lib/parser.js:303:14) {"error":{"command":"ZCOUNT","args":["poll:3:options:0:votes","-inf","+inf"],"code":"WRONGTYPE"},"stack":"ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value\n    at parseError (/home/forum/nodebb/node_modules/redis/node_modules/redis-parser/lib/parser.js:193:12)\n    at parseType (/home/forum/nodebb/node_modules/redis/node_modules/redis-parser/lib/parser.js:303:14)","exception":true,"date":"Wed Oct 23 2019 10:17:37 GMT+0100 (British Summer Time)","process":{"pid":7761,"uid":1001,"gid":1001,"cwd":"/home/forum/nodebb","execPath":"/usr/bin/node","version":"v10.16.3","argv":["/usr/bin/node","/home/forum/nodebb/nodebb","upgrade"],"memoryUsage":{"rss":133918720,"heapTotal":99819520,"heapUsed":72271800,"external":1490966}},"os":{"loadavg":[0.53271484375,0.2705078125,0.2509765625],"uptime":1121419},"trace":[{"column":12,"file":"/home/forum/nodebb/node_modules/redis/node_modules/redis-parser/lib/parser.js","function":"parseError","line":193,"method":null,"native":false},{"column":14,"file":"/home/forum/nodebb/node_modules/redis/node_modules/redis-parser/lib/parser.js","function":"parseType","line":303,"method":null,"native":false}]}
`

**Comment by barisusakli** [comment]
Can you run `type poll:3:options:0:votes` in redis to see the type of that key?

**Comment by barisusakli** [comment]
Seems like the upgrade script from the poll plugin didn't run properly. What does this show `smembers poll:3:options:0:votes`? if it is empty you can delete that key and retry the upgrade script.

**Comment by wellenreiter01** [comment]
I solved the problem by removing the poll plugin and deleting the key in the redis database

running on v1.13.x now
