### ISSUE TITLE
Unhandled promise rejection error on reset failure

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#8051]
```
2019-11-20T18:29:35.434Z [4567/12978] - error: [reset] Could not disable plugin: nodebb-plugin-derp encountered error Error: plugin-not-active
2019-11-20T18:29:35.434Z [4567/12978] - error: [reset] Errors were encountered during reset -- plugin-not-active
(node:12978) UnhandledPromiseRejectionWarning: Error: plugin-not-active
    at resetPlugin (/home/julian/Projects/nodebb/forum/src/cli/reset.js:141:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12978) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12978) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
```

**Comment by julianlam** [comment]
https://github.com/NodeBB/NodeBB/commit/510737726cd3ef75a59ea92b8e52d2636c1f3702
