### ISSUE TITLE
Admin > Plugins crash

### ISSUE THREAD

**Issue by kenvix** [NodeBB/NodeBB#8061]
- **NodeBB version:** 1.13.0
- **NodeBB git hash:** c6ef1486dee5cfb0d435716cf7d4d718fad68359
- **Database type:** mongo
- **Database version:** 4.0.10
- **Exact steps to cause this issue:**
	1. Open Nodebb admin
	2. Click Plugins (/admin/extend/plugins)

- **What you expected:**
Plugin list
- **What happened instead:**
The plugins page continues to load for a few minutes and the nodebb finally crashed.

Related log:

```
2019-11-24T11:49:43.077Z [4567/55835] - error: uncaughtException: Cannot read property 'statusCode' of undefined
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/home/nodebb/src/plugins/index.js:173:11)
    at self.callback (/home/nodebb/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/home/nodebb/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {"error":{},"stack":"TypeError: Cannot read property 'statusCode' of undefined\n    at Request._callback (/home/nodebb/src/plugins/index.js:173:11)\n    at self.callback (/home/nodebb/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:210:5)\n    at Request.onRequestError (/home/nodebb/node_modules/request/request.js:881:8)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at TLSSocket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","exception":true,"date":"Sun Nov 24 2019 19:49:43 GMT+0800 (China Standard Time)","process":{"pid":55835,"uid":1004,"gid":1006,"cwd":"/home/nodebb","execPath":"/usr/local/bin/node","version":"v12.12.0","argv":["/usr/local/bin/node","/home/nodebb/app.js"],"memoryUsage":{"rss":135618560,"heapTotal":85413888,"heapUsed":80893704,"external":37852603}},"os":{"loadavg":[0.115234375,0.30126953125,0.54443359375],"uptime":292289},"trace":[{"column":11,"file":"/home/nodebb/src/plugins/index.js","function":"Request._callback","line":173,"method":"_callback","native":false},{"column":22,"file":"/home/nodebb/node_modules/request/request.js","function":"self.callback","line":185,"method":"callback","native":false},{"column":5,"file":"events.js","function":"Request.emit","line":210,"method":"emit","native":false},{"column":8,"file":"/home/nodebb/node_modules/request/request.js","function":"Request.onRequestError","line":881,"method":"onRequestError","native":false},{"column":5,"file":"events.js","function":"ClientRequest.emit","line":210,"method":"emit","native":false},{"column":9,"file":"_http_client.js","function":"TLSSocket.socketErrorListener","line":406,"method":"socketErrorListener","native":false},{"column":5,"file":"events.js","function":"TLSSocket.emit","line":210,"method":"emit","native":false},{"column":8,"file":"internal/streams/destroy.js","function":"emitErrorNT","line":92,"method":null,"native":false},{"column":3,"file":"internal/streams/destroy.js","function":"emitErrorAndCloseNT","line":60,"method":null,"native":false},{"column":21,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":80,"method":null,"native":false}]}
2019-11-24T11:49:43.077Z [4567/55835] - error: Cannot read property 'statusCode' of undefined
2019-11-24T11:49:43.078Z [4567/55835] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2019-11-24T11:49:43.081Z [4567/55835] - info: [app] Web server closed to connections.
2019-11-24T11:49:43.081Z [4567/55835] - info: [app] Live analytics saved.
2019-11-24T11:49:43.084Z [4567/55835] - info: [app] Database connection closed.
2019-11-24T11:49:43.084Z [4567/55835] - info: [app] Shutdown complete.
[cluster] Child Process (55835) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2019-11-24T11:49:43.318Z [4567/57119] - info: Initializing NodeBB v1.13.0
```

Actived plugins:
```
	 - nodebb-plugin-composer-default
	 - nodebb-plugin-mentions
	 - nodebb-widget-essentials
	 - nodebb-rewards-essentials
	 - nodebb-plugin-soundpack-default
	 - nodebb-plugin-markdown
	 - nodebb-plugin-katex
	 - nodebb-plugin-mega-colors
	 - nodebb-plugin-emoji
	 - nodebb-plugin-emoji-android
	 - nodebb-plugin-dbsearch
	 - nodebb-plugin-recent-cards
	 - nodebb-theme-lavender
```

Is it because of network problem? How can i avoid it? Thank you

**Comment by barisusakli** [comment]
@kenvix most likely network problem reaching nbbpm, you should see the error in your nodebb logs now instead of a crash.
