### ISSUE TITLE
TypeError: db.parseIntFields is not a function

### ISSUE THREAD

**Issue by whuut** [NodeBB/NodeBB#8070]
Hi everyone,

I tried to upgrade from version 1.10.1 to 1.11.0 and got a "TypeError: db.parseIntFields is not a function" exception during the upgrade process. I use nodejs 8.16.2 on Ubuntu 18.04.

I don't use the git install method but the static release archives:

```bash
systemctl stop nodebb
cd /usr/src
wget https://github.com/NodeBB/NodeBB/archive/v1.11.0.tar.gz
tar xfz v1.11.0.tar.gz -C /var/lib/NodeBB --strip-components=1
cd /var/lib/NodeBB
./nodebb upgrade

Updating NodeBB...

1. Updating package.json file with defaults...  OK

2. Bringing base dependencies up to date...  started
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> sharp@0.21.0 install /var/lib/NodeBB/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
added 164 packages from 454 contributors, removed 115 packages, updated 53 packages, moved 2 packages and audited 4652 packages in 33.73s
found 96 vulnerabilities (5 low, 12 moderate, 78 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

3. Checking installed plugins for updates...  OK

A total of 1 package(s) can be upgraded:

  * nodebb-plugin-composer-redactor (3.3.2 -> 3.4.2)

Proceed with upgrade (y|n)? y

Upgrading packages...

4. Updating NodeBB data store schema...
Parsing upgrade scripts...
warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-custom-file-extensions`. Skipping.
OK | 11 script(s) found, 62 skipped
  → [2018/8/28] Record first entry in username/email history...
/var/lib/NodeBB/src/user/data.js:156
                        db.parseIntFields(user, intFields, requestedFields);
                           ^

TypeError: db.parseIntFields is not a function
    at /var/lib/NodeBB/src/user/data.js:156:7
    at Array.forEach (<anonymous>)
    at modifyUserData (/var/lib/NodeBB/src/user/data.js:151:9)
    at /var/lib/NodeBB/src/user/data.js:102:5
    at nextTask (/var/lib/NodeBB/node_modules/async/dist/async.js:5324:14)
    at next (/var/lib/NodeBB/node_modules/async/dist/async.js:5331:9)
    at /var/lib/NodeBB/node_modules/async/dist/async.js:969:16
    at /var/lib/NodeBB/src/database/mongo/hash.js:132:4
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

Trying to upgrade to later nodebb versions like 1.12.0 and updating the modules with `npm audit fix` did not solve the problem. Here is the latest exception message I get:

```json
{
    "error": {},
    "stack": "TypeError: db.parseIntFields is not a function\n    at /var/lib/NodeBB/src/user/data.js:156:7\n    at Array.forEach (<anonymous>)\n    at modifyUserData (/var/lib/NodeBB/src/user/data.js:151:9)\n    at /var/lib/NodeBB/src/user/data.js:102:5\n    at nextTask (/var/lib/NodeBB/node_modules/async/dist/async.js:5324:14)\n    at next (/var/lib/NodeBB/node_modules/async/dist/async.js:5331:9)\n    at /var/lib/NodeBB/node_modules/async/dist/async.js:969:16\n    at /var/lib/NodeBB/src/database/mongo/hash.js:132:4\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickCallback (internal/process/next_tick.js:181:9)",
    "exception": true,
    "date": "Sun Dec 01 2019 18:19:00 GMT+0100 (CET)",
    "process": {
        "pid": 3891,
        "uid": 0,
        "gid": 0,
        "cwd": "/var/lib/NodeBB",
        "execPath": "/usr/bin/node",
        "version": "v8.16.2",
        "argv": [
            "/usr/bin/node",
            "/var/lib/NodeBB/nodebb",
            "upgrade"
        ],
        "memoryUsage": {
            "rss": 145461248,
            "heapTotal": 110104576,
            "heapUsed": 78422696,
            "external": 18450945
        }
    },
    "os": {
        "loadavg": [
            0.263671875,
            0.25927734375,
            0.24853515625
        ],
        "uptime": 2336
    },
    "trace": [
        {
            "column": 7,
            "file": "/var/lib/NodeBB/src/user/data.js",
            "function": null,
            "line": 156,
            "method": null,
            "native": false
        },
        {
            "column": null,
            "file": null,
            "function": "Array.forEach",
            "line": null,
            "method": "forEach",
            "native": false
        },
        {
            "column": 9,
            "file": "/var/lib/NodeBB/src/user/data.js",
            "function": "modifyUserData",
            "line": 151,
            "method": null,
            "native": false
        },
        {
            "column": 5,
            "file": "/var/lib/NodeBB/src/user/data.js",
            "function": null,
            "line": 102,
            "method": null,
            "native": false
        },
        {
            "column": 14,
            "file": "/var/lib/NodeBB/node_modules/async/dist/async.js",
            "function": "nextTask",
            "line": 5324,
            "method": null,
            "native": false
        },
        {
            "column": 9,
            "file": "/var/lib/NodeBB/node_modules/async/dist/async.js",
            "function": "next",
            "line": 5331,
            "method": null,
            "native": false
        },
        {
            "column": 16,
            "file": "/var/lib/NodeBB/node_modules/async/dist/async.js",
            "function": null,
            "line": 969,
            "method": null,
            "native": false
        },
        {
            "column": 4,
            "file": "/var/lib/NodeBB/src/database/mongo/hash.js",
            "function": null,
            "line": 132,
            "method": null,
            "native": false
        },
        {
            "column": 11,
            "file": "internal/process/next_tick.js",
            "function": "_combinedTickCallback",
            "line": 139,
            "method": null,
            "native": false
        },
        {
            "column": 9,
            "file": "internal/process/next_tick.js",
            "function": "process._tickCallback",
            "line": 181,
            "method": "_tickCallback",
            "native": false
        }
    ]
}
```

The function "db.parseIntFields" was present in `/var/lib/NodeBB/src/database/index.js`

**Comment by pitaj** [comment]
Possible dupe of #7972

**Comment by barisusakli** [comment]
Not an expert in this but is this right?

```
systemctl stop nodebb
cd /usr/src
wget https://github.com/NodeBB/NodeBB/archive/v1.11.0.tar.gz
tar xfz v1.11.0.tar.gz -C /var/lib/NodeBB --strip-components=1
cd /var/lib/NodeBB
./nodebb upgrade
```

You are updating the files in `/usr/src/` but then running `./nodebb upgrade` in `/var/lib/NodeBB`

**Comment by barisusakli** [comment]
I see you are extracting the files there but I suggest trying with a clean git clone.
