### ISSUE TITLE
when user modifies and uploads the head picture，nodebb will restart

### ISSUE THREAD

**Issue by malaohu** [NodeBB/NodeBB#8093]
nodebb log

```
[cluster] Child Process (80811) has exited (code: null, signal: SIGSEGV)
[cluster] Spinning up another process...
(node:81442) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version
(node:81442) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:81442) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6

2019-12-20T09:51:26.429Z [4567/81442] - info: [socket.io] Restricting access to origin: https://xxxxxx:*
2019-12-20T09:51:27.126Z [4567/81442] - info: [plugins/spam-be-gone] Settings loaded
2019-12-20T09:51:27.165Z [4567/81442] - info: Routes added
2019-12-20T09:51:27.167Z [4567/81442] - info: NodeBB Ready
2019-12-20T09:51:27.171Z [4567/81442] - info: Enabling 'trust proxy'
2019-12-20T09:51:27.173Z [4567/81442] - info: NodeBB is now listening on: 0.0.0.0:4567

```

node v12.13.0
npm 6.12.0
nodebb v1.13.1

**Comment by julianlam** [comment]
Unfortunately the log you provided does not show any stack trace we can debug with.

Please try disabling all plugins and re-enable one at a time to see if a plugin caused this issue.

**Comment by malaohu** [comment]
I have uninstalled all my installed plug-ins.

but when i use dashboard button  [rebuild-and-restart]  with error

```
2019-12-22T09:05:07.410Z [4567/35544] - info: [build]         client side styles  build completed in 23.282sec
(node:35546) UnhandledPromiseRejectionWarning: Error: Failed to lookup view "account/profile" in views directory "/data/wwwroot/nodebb/build/public/templates"
    at Function.render (/data/wwwroot/nodebb/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/data/wwwroot/nodebb/node_modules/express/lib/response.js:1012:7)
    at /data/wwwroot/nodebb/src/middleware/render.js:63:83
    at internal/util.js:278:30
    at new Promise (<anonymous>)
    at internal/util.js:277:12
    at ServerResponse.renderOverride [as render] (/data/wwwroot/nodebb/src/middleware/render.js:67:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:35546) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:35546) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:35552) UnhandledPromiseRejectionWarning: Error: Failed to lookup view "recent" in views directory "/data/wwwroot/nodebb/build/public/templates"
    at Function.render (/data/wwwroot/nodebb/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/data/wwwroot/nodebb/node_modules/express/lib/response.js:1012:7)
    at /data/wwwroot/nodebb/src/middleware/render.js:63:83
    at internal/util.js:278:30
    at new Promise (<anonymous>)
    at internal/util.js:277:12
    at ServerResponse.renderOverride [as render] (/data/wwwroot/nodebb/src/middleware/render.js:67:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:35552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:35552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```


start nodebb with -d 
`./nodebb start -d`
user modifies and uploads the head picture have more error
```
2019-12-22T09:10:43.521Z [4568/36090] - verbose: [plugins/fireHook] filter:user.getSettings
2019-12-22T09:10:43.521Z [4568/36090] - verbose: [plugins/fireHook] filter:user.notificationTypes
2019-12-22T09:10:43.521Z [4568/36090] - verbose: [plugins/fireHook] filter:users.get
2019-12-22T09:10:43.521Z [4568/36090] - verbose: [plugins/fireHook] filter:groups.get
2019-12-22T09:10:43.521Z [4568/36090] - verbose: [plugins/fireHook] filter:posts.custom_profile_info
2019-12-22T09:10:43.521Z [4568/36090] - verbose: [plugins/fireHook] filter:posts.modifyUserInfo
2019-12-22T09:10:43.522Z [4568/36090] - verbose: [plugins/fireHook] filter:users.addFields
2019-12-22T09:10:43.522Z [4568/36090] - verbose: [plugins/fireHook] filter:userlist.get
2019-12-22T09:10:43.522Z [4568/36090] - verbose: [plugins/fireHook] filter:topics.addPostData
2019-12-22T09:10:44.897Z [4567/36088] - verbose: [plugins/fireHook] static:sockets.validateSession
2019-12-22T09:10:44.898Z [4567/36088] - verbose: [plugins/fireHook] filter:user.whitelistFields
2019-12-22T09:10:44.898Z [4567/36088] - verbose: [plugins/fireHook] filter:users.get
[cluster] Child Process (36088) has exited (code: null, signal: SIGSEGV)
[cluster] Spinning up another process...
2019-12-22T09:10:45.171Z [4567/36174] - verbose: * using configuration stored in: /data/wwwroot/nodebb/config.json
2019-12-22T09:10:45.331Z [4567/36174] - info: Initializing NodeBB v1.13.1 https://jike.info
2019-12-22T09:10:45.331Z [4567/36174] - verbose: * using mongo store at 127.0.0.1:27017
2019-12-22T09:10:45.331Z [4567/36174] - verbose: * using themes stored in: /data/wwwroot/nodebb/node_modules
(node:36174) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:36174) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:36174) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:36174) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:36174) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:36174) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version
2019-12-22T09:10:46.405Z [4567/36174] - verbose: [minifier] utilizing a maximum of 0 additional threads
2019-12-22T09:10:46.514Z [4567/36174] - verbose: Checking dependencies for outdated modules
(node:36174) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:36174) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:36174) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6


```

**Comment by pitaj** [comment]
Can you try running `./nodebb build` on your server? Does it succeed or error?

**Comment by malaohu** [comment]
> Can you try running `./nodebb build` on your server? Does it succeed or error?


```
[root@JIKE nodebb]# ./nodebb build
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version
  started
(node:64769) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:64769) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:64769) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
2019-12-23T01:01:13.717Z [4567,4568,4569/64769] - info: [build] Building in parallel mode
2019-12-23T01:01:13.718Z [4567,4568,4569/64769] - info: [build]         plugin static dirs  build started
2019-12-23T01:01:13.720Z [4567,4568,4569/64769] - info: [build]          requirejs modules  build started
2019-12-23T01:01:13.721Z [4567,4568,4569/64769] - info: [build]           client js bundle  build started
2019-12-23T01:01:13.722Z [4567,4568,4569/64769] - info: [build]            admin js bundle  build started
2019-12-23T01:01:13.723Z [4567,4568,4569/64769] - info: [build]         client side styles  build started
2019-12-23T01:01:13.724Z [4567,4568,4569/64769] - info: [build] admin control panel styles  build started
2019-12-23T01:01:13.724Z [4567,4568,4569/64769] - info: [build]                  templates  build started
2019-12-23T01:01:13.724Z [4567,4568,4569/64769] - info: [build]                  languages  build started
2019-12-23T01:01:13.724Z [4567,4568,4569/64769] - info: [build]                     sounds  build started
2019-12-23T01:01:19.043Z [4567,4568,4569/64769] - info: [build]           client js bundle  build completed in 5.322sec
2019-12-23T01:01:19.044Z [4567,4568,4569/64769] - info: [build]            admin js bundle  build completed in 5.322sec
2019-12-23T01:01:19.229Z [4567,4568,4569/64769] - info: [build]                     sounds  build completed in 5.505sec
2019-12-23T01:01:19.699Z [4567,4568,4569/64769] - info: [build]         plugin static dirs  build completed in 5.98sec
2019-12-23T01:01:30.029Z [4567,4568,4569/64769] - info: [build]         client side styles  build completed in 16.306sec
2019-12-23T01:01:30.029Z [4567,4568,4569/64769] - info: [build] admin control panel styles  build completed in 16.305sec
2019-12-23T01:01:49.675Z [4567,4568,4569/64769] - info: [build]                  languages  build completed in 35.951sec
2019-12-23T01:01:49.677Z [4567,4568,4569/64769] - info: [build]          requirejs modules  build completed in 35.957sec
2019-12-23T01:01:55.198Z [4567,4568,4569/64769] - info: [build]                  templates  build completed in 41.474sec
2019-12-23T01:01:55.199Z [4567,4568,4569/64769] - info: [build] Asset compilation successful. Completed in 41.48sec.
```

**Comment by pitaj** [comment]
Now if you restart your nodebb do the errors continue?

**Comment by malaohu** [comment]
I try to reinstall nodebb ，but it have same error~

then change node version to 10.16.3 ， that show more errer msg

```
Something went wrong installing the "sharp" module

Module did not self-register.

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

[cluster] Child Process (20394) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
```
rm node_modules/sharp
npm install 
the problem is solved~~

**Comment by phit** [comment]
running `npm rb sharp` solved this for me, I believe this is down to changing node version without reinstalling the dependencies
