### ISSUE TITLE
UnhandledPromiseRejectionWarning: MongoError: server is closed at executeWriteOperation

### ISSUE THREAD

**Issue by NormandoHall** [NodeBB/NodeBB#8099]
- **NodeBB version:** v1.31.1
- **NodeBB git hash:** d1e0672fa6bfd0a80e274418fb82dce06562ad3e

- **Installed NodeBB Plugins:** 

```
Active plugins:
        * nodebb-plugin-camo (installed, enabled)
        * nodebb-plugin-cards (installed, enabled)
        * nodebb-plugin-composer-default (installed, enabled)
        * nodebb-plugin-dbsearch (installed, enabled)
        * nodebb-plugin-emoji (installed, enabled)
        * nodebb-plugin-emoji-android (installed, enabled)
        * nodebb-plugin-emoji-one (installed, enabled)
        * nodebb-plugin-iframely (installed, enabled)
        * nodebb-plugin-imgbed (installed, enabled)
        * nodebb-plugin-markdown (installed, enabled)
        * nodebb-plugin-mentions (installed, enabled)
        * nodebb-plugin-ns-embed (installed, enabled)
        * nodebb-plugin-ns-likes (installed, enabled)
        * nodebb-plugin-recent-cards (installed, disabled)
        * nodebb-plugin-solr (installed, disabled)
        * nodebb-plugin-soundpack-default (installed, enabled)
        * nodebb-plugin-spam-be-gone (installed, enabled)
        * nodebb-plugin-sso-nextcloud (installed, enabled)
        * nodebb-plugin-tenor-gif (installed, enabled)
        * nodebb-plugin-youtube-embed (installed, enabled)
        * nodebb-rewards-essentials (installed, enabled)
        * nodebb-theme-lavender (installed, disabled)
        * nodebb-theme-persona (installed, disabled)
        * nodebb-theme-slick (installed, disabled)
        * nodebb-theme-va (installed, enabled)
        * nodebb-theme-vanilla (installed, disabled)
        * nodebb-widget-essentials (installed, enabled)
```

- **Database type:** mongo
- **Database version:** v3.6.16

- **Exact steps to cause this issue:**

1. Rebuild and restart from ACP
2. Logging with ./nodebb log

- **What you expected:**

No warning

- **What happened instead:**

```
2020-01-01T21:19:20.116Z [20001/23665] - info: [app] Live analytics saved.
2020-01-01T21:19:20.119Z [20000/23664] - info: [app] Shutdown complete.
(node:23665) UnhandledPromiseRejectionWarning: MongoError: server is closed
    at executeWriteOperation (/opt/forum/nodebb/node_modules/mongodb/lib/core/sdam/server.js:470:14)
    at Server.update (/opt/forum/nodebb/node_modules/mongodb/lib/core/sdam/server.js:407:5)
    at topology.selectServer (/opt/forum/nodebb/node_modules/mongodb/lib/core/sdam/topology.js:996:15)
    at selectServers (/opt/forum/nodebb/node_modules/mongodb/lib/core/sdam/topology.js:452:9)
    at selectServers (/opt/forum/nodebb/node_modules/mongodb/lib/core/sdam/server_selection.js:297:12)
    at NativeTopology.selectServer (/opt/forum/nodebb/node_modules/mongodb/lib/core/sdam/topology.js:439:5)
    at executeWriteOperation (/opt/forum/nodebb/node_modules/mongodb/lib/core/sdam/topology.js:964:12)
    at NativeTopology.update (/opt/forum/nodebb/node_modules/mongodb/lib/core/sdam/topology.js:617:5)
    at NativeTopology.update (/opt/forum/nodebb/node_modules/mongodb/lib/topologies/native_topology.js:63:11)
    at UnorderedBulkOperation.finalOptionsHandler (/opt/forum/nodebb/node_modules/mongodb/lib/bulk/common.js:1173:25)
(node:23665) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:23665) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-01-01T21:19:20.129Z [20001/23665] - info: [app] Database connection closed.
2020-01-01T21:19:20.129Z [20001/23665] - info: [app] Shutdown complete.
```

**Comment by yariplus** [comment]
I can almost guarantee nodebb-plugin-camo is not compatible with 1.13.x

**Comment by NormandoHall** [comment]
On another instance server, with the same versions of NodeBB, MongoDB, etc, we have these plugins and no warning:

```
Active plugins:
        * nodebb-plugin-camo (installed, enabled)
        * nodebb-plugin-cards (installed, enabled)
        * nodebb-plugin-composer-default (installed, enabled)
        * nodebb-plugin-custom-pages (installed, enabled)
        * nodebb-plugin-dbsearch (installed, enabled)
        * nodebb-plugin-emoji (installed, enabled)
        * nodebb-plugin-emoji-android (installed, disabled)
        * nodebb-plugin-emoji-one (installed, enabled)
        * nodebb-plugin-giphy (installed, enabled)
        * nodebb-plugin-highlights (installed, enabled)
        * nodebb-plugin-iframely (installed, enabled)
        * nodebb-plugin-imgbed (installed, enabled)
        * nodebb-plugin-markdown (installed, enabled)
        * nodebb-plugin-mentions (installed, enabled)
        * nodebb-plugin-ns-custom-fields (installed, enabled)
        * nodebb-plugin-ns-embed (installed, enabled)
        * nodebb-plugin-ns-likes (installed, enabled)
        * nodebb-plugin-question-and-answer (installed, enabled)
        * nodebb-plugin-recent-cards (installed, enabled)
        * nodebb-plugin-solr (installed, disabled)
        * nodebb-plugin-soundpack-default (installed, enabled)
        * nodebb-plugin-spam-be-gone (installed, enabled)
        * nodebb-plugin-sso-facebook (installed, enabled)
        * nodebb-plugin-sso-google (installed, enabled)
        * nodebb-plugin-sso-twitter (installed, enabled)
        * nodebb-plugin-tenor-gif (installed, enabled)
        * nodebb-plugin-youtube-embed (installed, enabled)
        * nodebb-rewards-essentials (installed, enabled)
        * nodebb-theme-lavender (installed, disabled)
        * nodebb-theme-persona (installed, disabled)
        * nodebb-theme-slick (installed, disabled)
        * nodebb-theme-va (installed, enabled)
        * nodebb-theme-vanilla (installed, disabled)
        * nodebb-widget-essentials (installed, enabled)
        * nodebb-widget-ns-birthdays (installed, enabled)

```

**Comment by yariplus** [comment]
Ah, you're right, looks like it's working okay.

**Comment by barisusakli** [comment]
@NormandoHall how did you start nodebb?

I am not getting this error when I click rebuild & restart when using `./nodebb start` Here is the log I get for reference

```
...
2020-01-03T19:26:40.797Z [4567/6948] - info: NodeBB is now listening on: 0.0.0.0:4567
  started
2020-01-03T19:27:42.528Z [4567/6948] - info: [build] Building in parallel mode
2020-01-03T19:27:42.529Z [4567/6948] - info: [build]         plugin static dirs  build started
2020-01-03T19:27:42.533Z [4567/6948] - info: [build]          requirejs modules  build started
2020-01-03T19:27:42.533Z [4567/6948] - info: [build]           client js bundle  build started
2020-01-03T19:27:42.535Z [4567/6948] - info: [build]            admin js bundle  build started
2020-01-03T19:27:42.535Z [4567/6948] - info: [build]         client side styles  build started
2020-01-03T19:27:42.536Z [4567/6948] - info: [build] admin control panel styles  build started
2020-01-03T19:27:42.536Z [4567/6948] - info: [build]                  templates  build started
2020-01-03T19:27:42.536Z [4567/6948] - info: [build]                  languages  build started
2020-01-03T19:27:42.537Z [4567/6948] - info: [build]                     sounds  build started
2020-01-03T19:27:44.907Z [4567/6948] - info: [build]                     sounds  build completed in 2.37sec
2020-01-03T19:27:45.861Z [4567/6948] - info: [build]         plugin static dirs  build completed in 3.332sec
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
2020-01-03T19:27:59.846Z [4567/6948] - warn: [meta/templates] Partial not loaded: partials/account_menu.tpl
2020-01-03T19:28:00.721Z [4567/6948] - info: [build]         client side styles  build completed in 18.186sec
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
2020-01-03T19:28:16.368Z [4567/6948] - info: [build] admin control panel styles  build completed in 33.832sec
2020-01-03T19:28:16.707Z [4567/6948] - info: [build]           client js bundle  build completed in 34.174sec
2020-01-03T19:28:17.947Z [4567/6948] - info: [build]            admin js bundle  build completed in 35.412sec
2020-01-03T19:28:24.922Z [4567/6948] - info: [build]                  languages  build completed in 42.386sec
2020-01-03T19:28:28.174Z [4567/6948] - info: [build]                  templates  build completed in 45.638sec
2020-01-03T19:28:28.174Z [4567/6948] - info: [build]          requirejs modules  build completed in 45.641sec
2020-01-03T19:28:28.176Z [4567/6948] - info: [build] Asset compilation successful. Completed in 45.646sec.
[cluster] Restarting...
Clustering enabled: Spinning up 1 process(es).

[cluster] Child Process (6948) has exited (code: null, signal: SIGTERM)
2020-01-03T19:28:29.150Z [4567/8516] - info: Initializing NodeBB v1.13.0 http://127.0.0.1:4567
2020-01-03T19:28:33.927Z [4567/8516] - info: [socket.io] Restricting access to origin: http://127.0.0.1:*
2020-01-03T19:28:37.056Z [4567/8516] - info: Routes added
2020-01-03T19:28:37.058Z [4567/8516] - info: NodeBB Ready
2020-01-03T19:28:37.064Z [4567/8516] - info: Enabling 'trust proxy'
2020-01-03T19:28:37.069Z [4567/8516] - info: NodeBB is now listening on: 0.0.0.0:4567
```

**Comment by NormandoHall** [comment]
Hi @barisusakli ! The same as you, with `./nodebb start` and rebuild & restar through ACP.

I will do some test, disabling a few plugins and report back again.

**Comment by NormandoHall** [comment]
Well, after research disabling plugins and so on, I discovered a little difference between two instances in config.json file.

In the warning NodeBB instance I have empty "uri" param (added by installation script), and have no in the other instance. So I remove this parameter and now there is no warning at all

Changed from:

```
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "xxxxx",
        "password": "yyyyy",
        "database": "zzzzzz",
        "uri": ""
    },
```

To:

```
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "xxxxx",
        "password": "yyyyy",
        "database": "zzzzzz"
    },
```

I don't know if this is a minor issue to consider in installation script.

Please, close this issue when you consider

Regards

**Comment by mastershaig** [comment]
This error happened to me while using _**mongoose**_, turned out that I missed `await` before saving.
