### ISSUE TITLE
After /api/compose TypeError: Cannot read property 'disabled' of undefined

### ISSUE THREAD

**Issue by NormandoHall** [NodeBB/NodeBB#8112]
- **NodeBB version:** v1.31.1
- **NodeBB git hash:** d1e0672fa6bfd0a80e274418fb82dce06562ad3e

- **Installed NodeBB Plugins:** 

```
Active plugins:
        * nodebb-plugin-camo (installed, enabled)
        * nodebb-plugin-cards (installed, enabled)
        * nodebb-plugin-composer-default (installed, enabled)
        * nodebb-plugin-dbsearch (installed, enabled)
        * nodebb-plugin-emoji (installed, enabled)
        * nodebb-plugin-emoji-android (installed, enabled)
        * nodebb-plugin-emoji-one (installed, enabled)
        * nodebb-plugin-iframely (installed, enabled)
        * nodebb-plugin-imgbed (installed, enabled)
        * nodebb-plugin-markdown (installed, enabled)
        * nodebb-plugin-mentions (installed, enabled)
        * nodebb-plugin-ns-embed (installed, enabled)
        * nodebb-plugin-ns-likes (installed, enabled)
        * nodebb-plugin-recent-cards (installed, disabled)
        * nodebb-plugin-solr (installed, disabled)
        * nodebb-plugin-soundpack-default (installed, enabled)
        * nodebb-plugin-spam-be-gone (installed, enabled)
        * nodebb-plugin-sso-nextcloud (installed, enabled)
        * nodebb-plugin-tenor-gif (installed, enabled)
        * nodebb-plugin-youtube-embed (installed, enabled)
        * nodebb-rewards-essentials (installed, enabled)
        * nodebb-theme-lavender (installed, disabled)
        * nodebb-theme-persona (installed, disabled)
        * nodebb-theme-slick (installed, disabled)
        * nodebb-theme-va (installed, enabled)
        * nodebb-theme-vanilla (installed, disabled)
        * nodebb-widget-essentials (installed, enabled)
```

- **Database type:** mongo
- **Database version:** v3.6.16

- **Exact steps to cause this issue:**

1. Random error
2. Logging with ./nodebb log

- **What you expected:**

No error

- **What happened instead:**

```
2020-01-11T20:23:01.359Z [20001/28533] - [31merror[39m: /api/compose
Cannot read property 'disabled' of undefined {"stack":"TypeError: Cannot read property 'disabled' of undefined\n    at exports.get (/opt/vapor/nodebb/src/controllers/composer.js:25:24)"}
2020-01-11T20:23:01.363Z [20001/28533] - [31merror[39m: uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/opt/vapor/nodebb/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/opt/vapor/nodebb/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/opt/vapor/nodebb/node_modules/express/lib/response.js:267:15)
    at defaultHandler (/opt/vapor/nodebb/src/controllers/errors.js:62:8)
    at /opt/vapor/nodebb/src/controllers/errors.js:83:4
    at /opt/vapor/nodebb/src/promisify.js:46:33
    at cb (util.js:353:39)
    at process._tickCallback (internal/process/next_tick.js:63:19) {"error":{},"stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (_http_outgoing.js:470:11)\n    at ServerResponse.header (/opt/vapor/nodebb/node_modules/express/lib/response.js:767:10)\n    at ServerResponse.send (/opt/vapor/nodebb/node_modules/express/lib/response.js:170:12)\n    at ServerResponse.json (/opt/vapor/nodebb/node_modules/express/lib/response.js:267:15)\n    at defaultHandler (/opt/vapor/nodebb/src/controllers/errors.js:62:8)\n    at /opt/vapor/nodebb/src/controllers/errors.js:83:4\n    at /opt/vapor/nodebb/src/promisify.js:46:33\n    at cb (util.js:353:39)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","exception":true,"date":"Sat Jan 11 2020 17:23:01 GMT-0300 (Argentina Standard Time)","process":{"pid":28533,"uid":508,"gid":509,"cwd":"/opt/vapor/nodebb","execPath":"/usr/bin/node","version":"v10.15.3","argv":["/usr/bin/node","/opt/vapor/nodebb/app.js"],"memoryUsage":{"rss":200302592,"heapTotal":160690176,"heapUsed":134931128,"external":23644196}},"os":{"loadavg":[0.19140625,0.17724609375,0.32177734375],"uptime":8741724},"trace":[{"column":11,"file":"_http_outgoing.js","function":"ServerResponse.setHeader","line":470,"method":"setHeader","native":false},{"column":10,"file":"/opt/vapor/nodebb/node_modules/express/lib/response.js","function":"ServerResponse.header","line":767,"method":"header","native":false},{"column":12,"file":"/opt/vapor/nodebb/node_modules/express/lib/response.js","function":"ServerResponse.send","line":170,"method":"send","native":false},{"column":15,"file":"/opt/vapor/nodebb/node_modules/express/lib/response.js","function":"ServerResponse.json","line":267,"method":"json","native":false},{"column":8,"file":"/opt/vapor/nodebb/src/controllers/errors.js","function":"defaultHandler","line":62,"method":null,"native":false},{"column":4,"file":"/opt/vapor/nodebb/src/controllers/errors.js","function":null,"line":83,"method":null,"native":false},{"column":33,"file":"/opt/vapor/nodebb/src/promisify.js","function":null,"line":46,"method":null,"native":false},{"column":39,"file":"util.js","function":"cb","line":353,"method":null,"native":false},{"column":19,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":63,"method":"_tickCallback","native":false}]}
```

**Comment by julianlam** [comment]
Hi @NormandoHall, do you know what you have to do in the frontend to trigger these log messages, or are you just setting them occasionally in the logs?

Indicative of a bug, but as yet, unreproducible...

**Comment by NormandoHall** [comment]
Hi @julianlam . Yes, it is unreproducible in normal situations, but happens when we have a huge traffic from robots (normal page views: 1500, when robots or "something": 30000). In this situation under stress, get this error, and nodeBB restart.

**Comment by NormandoHall** [comment]
Another one, but different, today, but come from plugin tenor gif. I don't know if these issues are related:

```
2020-01-14T04:50:43.038Z [20001/16862] - [32minfo[39m: NodeBB is now listening on: 0.0.0.0:20001
2020-01-14T04:50:43.040Z [20000/16855] - [32minfo[39m: NodeBB is now listening on: 0.0.0.0:20000
2020-01-14T04:50:51.292Z [20000/16855] - [31merror[39m: uncaughtException: Cannot read property 'reduce' of undefined
TypeError: Cannot read property 'reduce' of undefined
    at Request._callback (/opt/vapor/nodebb/node_modules/nodebb-plugin-tenor-gif/library.js:73:27)
    at Request.self.callback (/opt/vapor/nodebb/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/opt/vapor/nodebb/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/opt/vapor/nodebb/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) {"error":{},"stack":"TypeError: Cannot read property 'reduce' of undefined\n    at Request._callback (/opt/vapor/nodebb/node_modules/nodebb-plugin-tenor-gif/library.js:73:27)\n    at Request.self.callback (/opt/vapor/nodebb/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:189:13)\n    at Request.<anonymous> (/opt/vapor/nodebb/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:189:13)\n    at IncomingMessage.<anonymous> (/opt/vapor/nodebb/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:277:13)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1125:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","exception":true,"date":"Tue Jan 14 2020 01:50:51 GMT-0300 (Argentina Standard Time)","process":{"pid":16855,"uid":508,"gid":509,"cwd":"/opt/vapor/nodebb","execPath":"/usr/bin/node","version":"v10.15.3","argv":["/usr/bin/node","/opt/vapor/nodebb/app.js"],"memoryUsage":{"rss":251260928,"heapTotal":220540928,"heapUsed":178934664,"external":27869493}},"os":{"loadavg":[0.62060546875,0.35693359375,0.4453125],"uptime":8944994},"trace":[{"column":27,"file":"/opt/vapor/nodebb/node_modules/nodebb-plugin-tenor-gif/library.js","function":"Request._callback","line":73,"method":"_callback","native":false},{"column":22,"file":"/opt/vapor/nodebb/node_modules/request/request.js","function":"Request.self.callback","line":185,"method":"callback","native":false},{"column":13,"file":"events.js","function":"Request.emit","line":189,"method":"emit","native":false},{"column":10,"file":"/opt/vapor/nodebb/node_modules/request/request.js","function":null,"line":1161,"method":null,"native":false},{"column":13,"file":"events.js","function":"Request.emit","line":189,"method":"emit","native":false},{"column":12,"file":"/opt/vapor/nodebb/node_modules/request/request.js","function":null,"line":1083,"method":null,"native":false},{"column":13,"file":"events.js","function":"Object.onceWrapper","line":277,"method":"onceWrapper","native":false},{"column":15,"file":"events.js","function":"IncomingMessage.emit","line":194,"method":"emit","native":false},{"column":12,"file":"_stream_readable.js","function":"endReadableNT","line":1125,"method":null,"native":false},{"column":19,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":63,"method":"_tickCallback","native":false}]}
2020-01-14T04:50:51.292Z [20000/16855] - [31merror[39m: Cannot read property 'reduce' of undefined
2020-01-14T04:50:51.293Z [20000/16855] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2020-01-14T04:50:51.299Z [20000/16855] - [32minfo[39m: [app] Web server closed to connections.
2020-01-14T04:50:51.299Z [20000/16855] - [32minfo[39m: [app] Live analytics saved.
2020-01-14T04:50:51.308Z [20000/16855] - [32minfo[39m: [app] Database connection closed.
2020-01-14T04:50:51.308Z [20000/16855] - [32minfo[39m: [app] Shutdown complete.
```

**Comment by barisusakli** [comment]
@NormandoHall can you check if you have any plugins that use `filter:composer.build`? You can run this   in your nodebb folder to look for it.
`grep -rnw "filter:composer.build" node_modules/`

**Comment by barisusakli** [comment]
Please report the tenor plugin issue here https://github.com/julianlam/nodebb-plugin-tenor-gif/issues

**Comment by NormandoHall** [comment]
@barisusakli the only one is default composer plugin:

```
[vapor@pictronix nodebb]$ grep -rnw "filter:composer.build" node_modules/
node_modules/nodebb-plugin-composer-default/plugin.json:8:              { "hook": "filter:composer.build", "method": "build" },
```

**Comment by barisusakli** [comment]
What about `'action:meta.override404'`? Do you have any plugins using that?

**Comment by NormandoHall** [comment]
@barisusakli no one with this hook. I see you fixed this issue. Thank you!

**Comment by barisusakli** [comment]
Yeah I managed to reproduce the issue by using this url `/api/compose?p=123`

**Comment by NormandoHall** [comment]
Hi @barisusakli 

I was added this patch and fixed this issue. But yesterday and today happens this. Are you prefer to open another issue?

```
2020-01-17T03:00:20.873Z [20000/1193] - [31merror[39m: /api/compose
Invalid Data {"stack":"Error: Invalid Data\n    at exports.get (/opt/vapor/nodebb/src/controllers/composer.js:26:18)"}
2020-01-17T03:00:20.878Z [20000/1193] - [31merror[39m: uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/opt/vapor/nodebb/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/opt/vapor/nodebb/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/opt/vapor/nodebb/node_modules/express/lib/response.js:267:15)
    at defaultHandler (/opt/vapor/nodebb/src/controllers/errors.js:62:8)
    at /opt/vapor/nodebb/src/controllers/errors.js:83:4
    at /opt/vapor/nodebb/src/promisify.js:46:33
    at cb (util.js:353:39)
    at process._tickCallback (internal/process/next_tick.js:63:19) {"error":{},"stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (_http_outgoing.js:470:11)\n    at ServerResponse.header (/opt/vapor/nodebb/node_modules/express/lib/response.js:767:10)\n    at ServerResponse.send (/opt/vapor/nodebb/node_modules/express/lib/response.js:170:12)\n    at ServerResponse.json (/opt/vapor/nodebb/node_modules/express/lib/response.js:267:15)\n    at defaultHandler (/opt/vapor/nodebb/src/controllers/errors.js:62:8)\n    at /opt/vapor/nodebb/src/controllers/errors.js:83:4\n    at /opt/vapor/nodebb/src/promisify.js:46:33\n    at cb (util.js:353:39)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","exception":true,"date":"Fri Jan 17 2020 00:00:20 GMT-0300 (Argentina Standard Time)","process":{"pid":1193,"uid":508,"gid":509,"cwd":"/opt/vapor/nodebb","execPath":"/usr/bin/node","version":"v10.15.3","argv":["/usr/bin/node","/opt/vapor/nodebb/app.js"],"memoryUsage":{"rss":252289024,"heapTotal":178384896,"heapUsed":150369784,"external":22352165}},"os":{"loadavg":[0.20361328125,0.16357421875,0.1298828125],"uptime":9197564},"trace":[{"column":11,"file":"_http_outgoing.js","function":"ServerResponse.setHeader","line":470,"method":"setHeader","native":false},{"column":10,"file":"/opt/vapor/nodebb/node_modules/express/lib/response.js","function":"ServerResponse.header","line":767,"method":"header","native":false},{"column":12,"file":"/opt/vapor/nodebb/node_modules/express/lib/response.js","function":"ServerResponse.send","line":170,"method":"send","native":false},{"column":15,"file":"/opt/vapor/nodebb/node_modules/express/lib/response.js","function":"ServerResponse.json","line":267,"method":"json","native":false},{"column":8,"file":"/opt/vapor/nodebb/src/controllers/errors.js","function":"defaultHandler","line":62,"method":null,"native":false},{"column":4,"file":"/opt/vapor/nodebb/src/controllers/errors.js","function":null,"line":83,"method":null,"native":false},{"column":33,"file":"/opt/vapor/nodebb/src/promisify.js","function":null,"line":46,"method":null,"native":false},{"column":39,"file":"util.js","function":"cb","line":353,"method":null,"native":false},{"column":19,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":63,"method":"_tickCallback","native":false}]}
2020-01-17T03:00:20.879Z [20000/1193] - [31merror[39m: Cannot set headers after they are sent to the client
2020-01-17T03:00:20.879Z [20000/1193] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2020-01-17T03:00:20.883Z [20000/1193] - [32minfo[39m: [app] Web server closed to connections.
2020-01-17T03:00:20.890Z [20000/1193] - [32minfo[39m: [app] Live analytics saved.
2020-01-17T03:00:20.895Z [20001/1200] - [31merror[39m: /api/compose
Invalid Data {"stack":"Error: Invalid Data\n    at exports.get (/opt/vapor/nodebb/src/controllers/composer.js:26:18)"}
2020-01-17T03:00:20.898Z [20001/1200] - [31merror[39m: uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/opt/vapor/nodebb/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/opt/vapor/nodebb/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/opt/vapor/nodebb/node_modules/express/lib/response.js:267:15)
    at defaultHandler (/opt/vapor/nodebb/src/controllers/errors.js:62:8)
    at /opt/vapor/nodebb/src/controllers/errors.js:83:4
    at /opt/vapor/nodebb/src/promisify.js:46:33
    at cb (util.js:353:39)
    at process._tickCallback (internal/process/next_tick.js:63:19) {"error":{},"stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (_http_outgoing.js:470:11)\n    at ServerResponse.header (/opt/vapor/nodebb/node_modules/express/lib/response.js:767:10)\n    at ServerResponse.send (/opt/vapor/nodebb/node_modules/express/lib/response.js:170:12)\n    at ServerResponse.json (/opt/vapor/nodebb/node_modules/express/lib/response.js:267:15)\n    at defaultHandler (/opt/vapor/nodebb/src/controllers/errors.js:62:8)\n    at /opt/vapor/nodebb/src/controllers/errors.js:83:4\n    at /opt/vapor/nodebb/src/promisify.js:46:33\n    at cb (util.js:353:39)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","exception":true,"date":"Fri Jan 17 2020 00:00:20 GMT-0300 (Argentina Standard Time)","process":{"pid":1200,"uid":508,"gid":509,"cwd":"/opt/vapor/nodebb","execPath":"/usr/bin/node","version":"v10.15.3","argv":["/usr/bin/node","/opt/vapor/nodebb/app.js"],"memoryUsage":{"rss":328036352,"heapTotal":222949376,"heapUsed":146132640,"external":24835173}},"os":{"loadavg":[0.20361328125,0.16357421875,0.1298828125],"uptime":9197564},"trace":[{"column":11,"file":"_http_outgoing.js","function":"ServerResponse.setHeader","line":470,"method":"setHeader","native":false},{"column":10,"file":"/opt/vapor/nodebb/node_modules/express/lib/response.js","function":"ServerResponse.header","line":767,"method":"header","native":false},{"column":12,"file":"/opt/vapor/nodebb/node_modules/express/lib/response.js","function":"ServerResponse.send","line":170,"method":"send","native":false},{"column":15,"file":"/opt/vapor/nodebb/node_modules/express/lib/response.js","function":"ServerResponse.json","line":267,"method":"json","native":false},{"column":8,"file":"/opt/vapor/nodebb/src/controllers/errors.js","function":"defaultHandler","line":62,"method":null,"native":false},{"column":4,"file":"/opt/vapor/nodebb/src/controllers/errors.js","function":null,"line":83,"method":null,"native":false},{"column":33,"file":"/opt/vapor/nodebb/src/promisify.js","function":null,"line":46,"method":null,"native":false},{"column":39,"file":"util.js","function":"cb","line":353,"method":null,"native":false},{"column":19,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":63,"method":"_tickCallback","native":false}]}
2020-01-17T03:00:20.899Z [20001/1200] - [31merror[39m: Cannot set headers after they are sent to the client
2020-01-17T03:00:20.899Z [20001/1200] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2020-01-17T03:00:20.904Z [20001/1200] - [32minfo[39m: [app] Web server closed to connections.
2020-01-17T03:00:20.907Z [20001/1200] - [32minfo[39m: [app] Live analytics saved.
2020-01-17T03:00:20.917Z [20001/1200] - [32minfo[39m: [app] Database connection closed.
2020-01-17T03:00:20.918Z [20001/1200] - [32minfo[39m: [app] Shutdown complete.
```

**Comment by barisusakli** [comment]
Do you have  composer default 6.3.21 installed as well?

**Comment by NormandoHall** [comment]
Ops. No. Now I added the patch from latest composer. Any news I will comment here. Thanks
