### ISSUE TITLE
 error: [acp] Failed to fetch latest versionETIMEDOUT

### ISSUE THREAD

**Issue by cetcjinjian** [NodeBB/NodeBB#8149]
- **NodeBB version:v1.13.2** 
- **NodeBB git hash:** 

- **Installed NodeBB Plugins:** 

- **Database type:** mongo
- **Database version:v3.4** 

- **Exact steps to cause this issue:**

**The following error occurs after the nodebb has been working normally for some time**

[benchpressjs] Unable to build or find a suitable native module, falling back to JS version
(node:28326) DeprecationWarning: The option `autoReconnect` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:28326) DeprecationWarning: The option `reconnectTries` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
(node:28326) DeprecationWarning: The option `reconnectInterval` is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
2020-02-06T07:21:58.377Z [4567/28326] - info: [socket.io] Restricting access to origin: http://www.xxxxxx.cn:*
2020-02-06T07:22:00.072Z [4567/28326] - info: Routes added
2020-02-06T07:22:00.079Z [4567/28326] - info: NodeBB Ready
2020-02-06T07:22:00.088Z [4567/28326] - info: Enabling 'trust proxy'
2020-02-06T07:22:00.095Z [4567/28326] - info: NodeBB is now listening on: 0.0.0.0:4567
2020-02-06T07:42:44.731Z [4567/28326] - error: [acp] Failed to fetch latest versionETIMEDOUT {"code":"ETIMEDOUT","connect":true,"stack":"Error: ETIMEDOUT\n    at Timeout._onTimeout (/opt/nodebb/node_modules/request/request.js:849:19)\n    at listOnTimeout (timers.js:324:15)\n    at processTimers (timers.js:268:5)"}

**Comment by pitaj** [comment]
Your nodebb instance can't reach GitHub to check whether nodebb is up to date.

**Comment by cetcjinjian** [comment]
> Your nodebb instance can't reach GitHub to check whether nodebb is up to date.

so how can i close the update function ？

**Comment by pitaj** [comment]
This error is not fatal and is logged only so people know what is happening. It's not actually an issue.

We can provide an option to disable this check, that's a good idea.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/6540
