### ISSUE TITLE
parsing configuration file Error 

### ISSUE THREAD

**Issue by raiots** [NodeBB/NodeBB#8195]
- **NodeBB version:*1.13.2* 
- **NodeBB git hash:*71f4607db4e2252995d488b1968f7e9bb1d97efc* 

- **Installed NodeBB Plugins:** 

- **Database type:** redis
- **Database version:*3.2.12* 

- **Exact steps to cause this issue:**
	1. Because of the socket.io 403 forbiden,so I change the config.json
```json
{
    "url": "http://localhost:4567",
    "secret": "b5fe9a2e-819a-4901-a948-5a028d3ba02b",
    "database": "redis",
    "redis": {
        "host": "127.0.0.1",
        "port": "6379",
        "password": "",
        "database": "0"
    },
    "port": "4567"
    "socket.io":{
        "origins":"*:*"
    }
}
```
	2. Then, I run ./nodebb upgrade and find this
```shell
2020-03-04T12:56:22.618Z [undefined/20208] - error: uncaughtException: Error parsing your configuration file: [/root/nodebb/config.json]: Unexpected string in JSON at position 263
Error: Error parsing your configuration file: [/root/nodebb/config.json]: Unexpected string in JSON at position 263
    at exports.File.File.loadSync (/root/nodebb/node_modules/nconf/lib/nconf/stores/file.js:170:11)
    at exports.Provider.Provider.add (/root/nodebb/node_modules/nconf/lib/nconf/provider.js:136:23)
    at exports.Provider.Provider.file (/root/nodebb/node_modules/nconf/lib/nconf/provider.js:63:15)
    at Object.loadConfig (/root/nodebb/src/prestart.js:47:8)
    at Object.<anonymous> (/root/nodebb/src/cli/index.js:104:10)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
```
- **What you expected:**

- **What happened instead:**

Thanks for your attention!

**Comment by raiots** [comment]
find it miss a ","😂
