### ISSUE TITLE
Admin user created automatically due to mis-configuration, no way of finding credentials by official methods (I know I can probably query the redis db)

### ISSUE THREAD

**Issue by dnk8n** [NodeBB/NodeBB#8246]
- **NodeBB version:** 
`NodeBB v1.13.2`
- **NodeBB git hash:** 

`71f4607db4e2252995d488b1968f7e9bb1d97efc`
- **Installed NodeBB Plugins:** 

```
Active plugins:
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, disabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, disabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)
```
- **Database type:** redis
- **Database version:** 
Redis server v=5.0.8 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=aa269712cec6b555
- **Exact steps to cause this issue:**

	1. First I did this (by error) ... I had an incorrectly configured config.json... I had (note port instead of host which I later corrected to):
```
{
    "url": "http://***",
    "secret": "***",
    "database": "redis",
    "port": "4567",
    "redis": {
        "port": "/home/dnk8n/.redis/sock",
        "password": "",
        "database": "0"
    }
}
```
It then ran through some setup but failed with some code error. It must have connected to redis in some way in doing so it created an @admin account. I do not know the credentials of this account. Error log at this point (note my answers to the prompts):
```
Welcome to NodeBB v1.13.2!

This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
Press enter to accept the default setting (shown in brackets).
URL used to access this NodeBB (http://localhost:4567) https://mypeople.dnk8n.dev
Please enter a NodeBB secret (67372c4b-a81a-47f7-8e6c-8ba6084261b2) 
Would you like to submit anonymous plugin usage to nbbpm? (yes) 
Which database to use (mongo) redis
2020-04-10T07:58:02.781Z [27935] - info: 
Now configuring redis database:
Host IP or address of your Redis instance (127.0.0.1) 0.0.0.0
Host port of your Redis instance (6379) 
Password of your Redis database 
Which database to use (0..n) (0) 
2020-04-10T07:58:20.009Z [27935] - error: Error: Redis connection to 0.0.0.0:6379 failed - connect ECONNREFUSED 0.0.0.0:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
2020-04-10T07:58:20.010Z [27935] - error: NodeBB could not connect to your Redis database. Redis returned the following errorRedis connection to 0.0.0.0:6379 failed - connect ECONNREFUSED 0.0.0.0:6379 {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"0.0.0.0","port":6379,"stack":"Error: Redis connection to 0.0.0.0:6379 failed - connect ECONNREFUSED 0.0.0.0:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)"}
2020-04-10T07:58:20.010Z [27935] - warn: NodeBB Setup Aborted.
 Error: Redis connection to 0.0.0.0:6379 failed - connect ECONNREFUSED 0.0.0.0:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)

```
I corrected the config.json and re-ran ./nodebb setup. This time, as part of the logs I see `Administrator found, skipping Admin setup`

- **What you expected:**
I expected the setup to start from scratch and allow me to set admin user
- **What happened instead:**
Instead, I missed out on admin credentials and I don't see a way of creating/deleting users/admins via the CLI

How does one recreate an admin user if initial credentials are lost?

**Comment by dnk8n** [comment]
I did a Redis FLUSHALL and started from scratch.

This time I got:

```
An administrative user was automatically created for you:
    Username: admin
    Password: ***

NodeBB Setup Completed. Run "./nodebb start" to manually start your NodeBB server.

```

My config.json looked like this at time of running:

```
{
    "url": "http://***",
    "secret": "***",
    "database": "redis",
    "port": "4567",
    "redis": {
        "host": "/home/dnk8n/.redis/sock",
        "password": "",
        "database": "0"
    }
}
```

**Comment by julianlam** [comment]
Sounds like you figured it out... for others experiencing similar issues -- we don't have a route or command to arbitrarily create an admin user (since that'd be dangerous).

Easiest way would be to enter the administrative email in the `/reset` route, and check the database for the appropriate reset token, then navigate to `/reset/:token`
