### ISSUE TITLE
BUG: Moderators and Global Moderator are not able to flag posts

### ISSUE THREAD

**Issue by mdorda** [NodeBB/NodeBB#8255]
- **NodeBB version:** 1.13.2
- **NodeBB git hash:** 71f4607db4e2252995d488b1968f7e9bb1d97efc

- **Database type:** mongo
- **Database version:** 3.6

- **Exact steps to cause this issue:**
        1. Be a Moderator or a Global Moderator
        2. Try to flag a **post** (not topic or user, only post) for moderation
        3. Web socket returns 400 and nothing happens

- **What you expected:**
Same behaviour as for Registred user or Administrator. It means the post is flaged for moderation. It worked for NodeBB version 1.12.2 as expected.

- **What happened instead:**
Web socket returns 400 and nothing happens. Even the flag modal remains open.

**Comment by julianlam** [comment]
Hi there -- I don't actually have any issues flagging a post as a moderator. Could you try disabling all non-essential plugins and trying again?

**Comment by mdorda** [comment]
You are right, this bug is caused by `nodebb-plugin-knowledge-base` version `1.0.4`. It causes the following error when moderator tries to flag any post:

```
2020-04-15T07:06:34.992Z [33388/17534] - error: uncaughtException: Callback was already called.
Error: Callback was already called.
    at /nodebb/node_modules/async/dist/async.js:318:36
    at Immediate.<anonymous> (/nodebb/node_modules/async/dist/async.js:1633:17)
    at processImmediate (internal/timers.js:458:21)
    at process.topLevelDomainCallback (domain.js:137:15) {"error":{},"stack":"Error: Callback was already called.\n    at /nodebb/node_modules/async/dist/async.js:318:36\n    at Immediate.<anonymous> (/nodebb/node_modules/async/dist/async.js:1633:17)\n    at processImmediate (internal/timers.js:458:21)\n    at process.topLevelDomainCallback (domain.js:137:15)","exception":true,"date":"Wed Apr 15 2020 07:06:34 GMT+0000 (Coordinated Universal Time)","process":{"pid":17534,"uid":0,"gid":0,"cwd":"/nodebb","execPath":"/usr/local/bin/node","version":"v12.16.1","argv":["/usr/local/bin/node","/nodebb/app.js"],"memoryUsage":{"rss":175636480,"heapTotal":129679360,"heapUsed":107472112,"external":38238165}},"os":{"loadavg":[4.94140625,5.22509765625,5.23828125],"uptime":25218769},"trace":[{"column":36,"file":"/nodebb/node_modules/async/dist/async.js","function":null,"line":318,"method":null,"native":false},{"column":17,"file":"/nodebb/node_modules/async/dist/async.js","function":null,"line":1633,"method":null,"native":false},{"column":21,"file":"internal/timers.js","function":"processImmediate","line":458,"method":null,"native":false},{"column":15,"file":"domain.js","function":"process.topLevelDomainCallback","line":137,"method":"topLevelDomainCallback","native":false}]}
```

**Comment by barisusakli** [comment]
@mdorda thanks for reporting
