### ISSUE TITLE
upgrade error v1.13.3 

### ISSUE THREAD

**Issue by sweetppro** [NodeBB/NodeBB#8305]
running Postgres
updating from v1.13.2
```
4. Updating NodeBB data store schema...
Parsing upgrade scripts... 
OK | 1 script(s) found, 83 skipped
  → [2020/5/2] Fix user sorted sets...
    [######       ] (500/1021) 48% (node:14753) UnhandledPromiseRejectionWarning: error: null value in column "score" violates not-null constraint
    at Connection.parseE (/var/www/vhosts/website.com/NodeBB/node_modules/pg/lib/connection.js:581:48)
    at Connection.parseMessage (/var/www/vhosts/website.com/NodeBB/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/var/www/vhosts/website.com/NodeBB/node_modules/pg/lib/connection.js:116:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:14753) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14753) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

**Comment by barisusakli** [comment]
@sweetppro let me know if the upgrade script works after you apply the above change.

**Comment by sweetppro** [comment]
yup,
that did it!
thx for the quick fix
