### ISSUE TITLE
 Cannot start NodebB: "Cannot find module ./undefined" 

### ISSUE THREAD

**Issue by LM1LC3N7** [NodeBB/NodeBB#8331]
- **NodeBB version:** v1.13.4-4
- **NodeBB git hash:** ecaa9b76f3645638e0816c30dd14fb34a38b4c4e

- **Installed NodeBB Plugins:** None
Active plugins:
        * nodebb-plugin-composer-default (installed, disabled)
        * nodebb-plugin-dbsearch (installed, disabled)
        * nodebb-plugin-emoji (installed, disabled)
        * nodebb-plugin-emoji-android (installed, disabled)
        * nodebb-plugin-markdown (installed, disabled)
        * nodebb-plugin-mentions (installed, disabled)
        * nodebb-plugin-soundpack-default (installed, disabled)
        * nodebb-plugin-spam-be-gone (installed, disabled)
        * nodebb-rewards-essentials (installed, disabled)
        * nodebb-theme-lavender (installed, disabled)
        * nodebb-theme-persona (installed, disabled)
        * nodebb-theme-slick (installed, disabled)
        * nodebb-theme-vanilla (installed, disabled)
        * nodebb-widget-essentials (installed, disabled)

- **Database type:** redis
- **Database version:** Redis server v=6.0.2

- **Exact steps to cause this issue:**

Hello,

I cannot start NodeBB using the following Dockerfile. I have a weird error that I never saw in the forum or GitHub:

```bash
[...]
Schema update complete!

2020-05-25T08:29:29.588Z [4567/92] - error: Cannot find module './undefined'
Require stack:
- /nodebb/src/database/index.js
- /nodebb/src/start.js
- /nodebb/require-main.js
- /nodebb/app.js {"code":"MODULE_NOT_FOUND","requireStack":["/nodebb/src/database/index.js","/nodebb/src/start.js","/nodebb/require-main.js","/nodebb/app.js"]}
[cluster] Child Process (92) has exited (code: 0, signal: null)
```

**Dockerfile**
Note: I tried also cloning the main GitHub repo, same error.

```bash
FROM node:lts as build

SHELL ["/bin/bash", "-c"]

ENV NODE_ENV=production \
    daemon=false \
    silent=false

WORKDIR /nodebb

RUN echo \
 && echo "[*] Installing build dependencies" \
 && apt-get update && apt-get install -y \
    git \
    curl \
    wget \
    unzip

RUN echo \
 && echo "[*] Cloning NodeBB" \
 && wget https://github.com/NodeBB/NodeBB/archive/v1.13.3.zip \
 && unzip v1.* \
 && find ./NodeBB-* -maxdepth 1 -mindepth 1 -exec mv -t . {} + \
 && cp install/package.json package.json

RUN echo \
 && echo "[*] Installing NodeBB dependencies" \
 && npm install --only=prod \
 && npm cache clean --force

COPY rootfs/nodebb/config.json /nodebb/config.json

VOLUME /nodebb/public/uploads /etc/nodebb /var/lib/redis

EXPOSE 4567

CMD node ./nodebb build ; node ./nodebb start ; echo ; echo "ERROR, opening bash for debug" ; bash
```

**config.json**

```bash
{
  "url": "http://sub.domain.tld",
  "secret": "random-password-9_aHYo9eczr3WO8vSTItJH",
  "database": "redis",
  "redis": {
    "host": "nodebb-redis",
    "port": "6379",
    "password": "",
    "database": "0"
  },
  "port": "4567",
  "bcrypt_rounds": "21",
  "upload_path": "/public/uploads",
  "jobDisabled": "false",
  "bind_address": "0.0.0.0",
  "isCluster": "false",
  "session_store": "redis",
  "logFile": "logs/output.log"
}
```

**Start Redis and NodeBB**

```bash
docker run --name nodebb-redis -d --rm redis
docker build -t my/nodebb:debian .
docker run --name nodebb -ti --rm -p 4567:4567 my/nodebb:debian
```

Once started, I connect inside the docker container to debug.
The following commands are running with success:

```bash
# node ./nodebb build
# node ./nodebb upgrade
```

But **impossible** to start nodebb using either:

```bash
# node ./nodebb start
# node app.js
# node loader.js
```

```bash
NodeBB v1.13.3 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

2020-05-25T09:26:16.897Z [4567/425] - info: Initializing NodeBB v1.13.3 http://leclos.lmilcent.com
2020-05-25T09:26:18.331Z [4567/425] - error: Error: Cannot find module './undefined'
Require stack:
- /nodebb/src/database/index.js
- /nodebb/src/start.js
- /nodebb/require-main.js
- /nodebb/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.primaryDB.initSessionStore (/nodebb/src/database/index.js:27:20)
    at Object.start.start (/nodebb/src/start.js:33:12)
[cluster] Child Process (425) has exited (code: 0, signal: null)
```

Note: I also have created a new post in the forum at https://community.nodebb.org/topic/14782/cannot-start-nodebb-cannot-find-module-undefined/2

**Comment by barisusakli** [comment]
Your session_store field should be an object.

```
session_store: {
  "name": "redis",
  "host": "127.0.0.1",
  "port": "6379",
   "password": "",
   "database": "0"
}
```

**Comment by LM1LC3N7** [comment]
Thanks a lot! No more errors :-)
