### ISSUE TITLE
got error while setup :  npm ERR! Unexpected end of JSON input while parsing near '..."shasum":"8f9ee78db28'

### ISSUE THREAD

**Issue by makeitworks** [NodeBB/NodeBB#8530]
on my ubuntu 18.04

**nodebb version** : commit 28970b030d21a9e839804b0c40e0ed1c520502ac (HEAD -> v1.14.x, tag: v1.14.2, origin/v1.14.x)

node version :  12.17.0
npm version :  6.14
-------------------------------------------

clone the source code from github,  then configred my mongodb , then just run the command :  ./nodebb setup . 

while installing , got an error :/
 
`Dependencies outdated or not yet installed.
Installing them now...

npm ERR! Unexpected end of JSON input while parsing near '..."shasum":"8f9ee78db28'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hs/.npm/_logs/2020-07-28T13_18_33_380Z-debug.log
Error installing dependencies!
message: Command failed: npm install --production
stdout: null
stderr: null
/home/hs/Workspace/nodebb_demo/src/cli/package-install.js:72
		throw e;
		^

Error: Command failed: npm install --production
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.installAll (/home/hs/Workspace/nodebb_demo/src/cli/package-install.js:63:9)
    at Object.<anonymous> (/home/hs/Workspace/nodebb_demo/src/cli/index.js:60:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18395,
  stdout: null,
  stderr: null
}
`

**Comment by pitaj** [comment]
Try running `npm cache clean --force`, deleting `node_modules`, and retrying setup.

**Comment by julianlam** [comment]
Comment again to reopen if the above steps do not work, thanks!

**Comment by makeitworks** [comment]
it works,  thank you !
its my fault , I have been installed  an order version of nodebb couple weeks ago.
