### ISSUE TITLE
error with nodebb setup

### ISSUE THREAD

**Issue by bi-kai** [NodeBB/NodeBB#8589]
NodeBB version: v1.14.3
node version: v12.18.3
npm version: 6.14.6

run with `./nodebb setup`, comes with error:
```
root@localhost:/starlab/www/nodejs/NodeBB-1.14.3# ./nodebb setup
package.json not found.
Populating package.json...
OK
Dependencies outdated or not yet installed.
Installing them now...

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.

> benchpressjs@2.0.3 install /starlab/www/nodejs/NodeBB-1.14.3/node_modules/benchpressjs
> cd rust/benchpress-rs && npm install

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1001:0 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /root/.npm/_cacache/index-v5/bb/d6/e0cd0284d3669bb9ead49f0ea002b37c874cea5dea935a13848414fbb157
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1001:0 "/root/.npm"
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN nodebb-plugin-emoji-android@2.0.0 requires a peer of nodebb-plugin-emoji@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN textcomplete.contenteditable@0.1.1 requires a peer of textcomplete@^0.14.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@14.1.0 requires a peer of eslint@^5.16.0 || ^6.8.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! benchpressjs@2.0.3 install: `cd rust/benchpress-rs && npm install`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the benchpressjs@2.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-29T03_42_54_510Z-debug.log
Error installing dependencies!
message: Command failed: npm install --production
stdout: null
stderr: null
/starlab/www/nodejs/NodeBB-1.14.3/src/cli/package-install.js:72
                throw e;
                ^

Error: Command failed: npm install --production
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.installAll (/starlab/www/nodejs/NodeBB-1.14.3/src/cli/package-install.js:63:9)
    at Object.<anonymous> (/starlab/www/nodejs/NodeBB-1.14.3/src/cli/index.js:60:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  status: 243,
  signal: null,
  output: [ null, null, null ],
  pid: 18192,
  stdout: null,
  stderr: null
}
```

what shall I do with this?

I used docker version too, but there is no office doc about this version. Could you give some guide with docs?

**Comment by pitaj** [comment]
Looks like you're trying to use root/sudo to setup NodeBB. NodeBB should not be installed, setup, or run as root/sudo. Instead, you should create a new unprivileged user and use that for NodeBB.

Utilities such as npm can be messed up when run be root/sudo, as the above error message shows. Installing NodeBB as root/sudo makes running NodeBB without root/sudo impossible. Running NodeBB as root/sudo exposes your server to unnecessary risks and has no benefits.
