### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by StefanROM** [NodeBB/NodeBB#8724]
pls someone help me 

SyntaxError: Unexpected token }
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by julianlam** [comment]
Sorry, this is the bug tracker for NodeBB forum software, not Nodejs.
