### ISSUE TITLE
NodeBB 1.14.3 frequently crashing

### ISSUE THREAD

**Issue by sm2x** [NodeBB/NodeBB#8775]
- Ubuntu 18.04
- NodeBB 1.14.3
- Redis 4.0.9
- Nginx 1.14.0
After running for a while, it crashes with the following logs

2020-10-19T02:19:40.401Z [4567/15226] - info: Routes added
2020-10-19T02:19:40.402Z [4567/15226] - info: NodeBB Ready
2020-10-19T02:19:40.403Z [4567/15226] - info: Enabling 'trust proxy'
2020-10-19T02:19:40.405Z [4567/15226] - info: NodeBB is now listening on: 0.0.0.0:4567
2020-10-19T02:19:46.971Z [4567/15226] - error: uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:526:11)
    at ServerResponse.header (/var/www/html/nodebb/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/var/www/html/nodebb/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/var/www/html/nodebb/node_modules/express/lib/response.js:267:15)
    at /var/www/html/nodebb/src/controllers/index.js:301:19
    at /var/www/html/nodebb/src/promisify.js:46:33
    at cb (util.js:207:31)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {"error":{"code":"ERR_HTTP_HEADERS_SENT"},"stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (_http_outgoing.js:526:11)\n    at ServerResponse.header (/var/www/html/nodebb/node_modules/express/lib/response.js:771:10)\n    at ServerResponse.send (/var/www/html/nodebb/node_modules/express/lib/response.js:170:12)\n    at ServerResponse.json (/var/www/html/nodebb/node_modules/express/lib/response.js:267:15)\n    at /var/www/html/nodebb/src/controllers/index.js:301:19\n    at /var/www/html/nodebb/src/promisify.js:46:33\n    at cb (util.js:207:31)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","exception":true,"date":"Mon Oct 19 2020 10:19:46 GMT+0800 (Philippine Standard Time)","process":{"pid":15226,"uid":0,"gid":0,"cwd":"/var/www/html/nodebb","execPath":"/usr/bin/node","version":"v12.19.0","argv":["/usr/bin/node","/var/www/html/nodebb/app.js"],"memoryUsage":{"rss":166813696,"heapTotal":120291328,"heapUsed":90347800,"external":2008761,"arrayBuffers":454496}},"os":{"loadavg":[0.5,0.14,0.09],"uptime":2447523},"trace":[{"column":11,"file":"_http_outgoing.js","function":"ServerResponse.setHeader","line":526,"method":"setHeader","native":false},{"column":10,"file":"/var/www/html/nodebb/node_modules/express/lib/response.js","function":"ServerResponse.header","line":771,"method":"header","native":false},{"column":12,"file":"/var/www/html/nodebb/node_modules/express/lib/response.js","function":"ServerResponse.send","line":170,"method":"send","native":false},{"column":15,"file":"/var/www/html/nodebb/node_modules/express/lib/response.js","function":"ServerResponse.json","line":267,"method":"json","native":false},{"column":19,"file":"/var/www/html/nodebb/src/controllers/index.js","function":null,"line":301,"method":null,"native":false},{"column":33,"file":"/var/www/html/nodebb/src/promisify.js","function":null,"line":46,"method":null,"native":false},{"column":31,"file":"util.js","function":"cb","line":207,"method":null,"native":false},{"column":21,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":84,"method":null,"native":false}]}
2020-10-19T02:19:46.972Z [4567/15226] - error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:526:11)
    at ServerResponse.header (/var/www/html/nodebb/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/var/www/html/nodebb/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/var/www/html/nodebb/node_modules/express/lib/response.js:267:15)
    at /var/www/html/nodebb/src/controllers/index.js:301:19
    at /var/www/html/nodebb/src/promisify.js:46:33
    at cb (util.js:207:31)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-10-19T02:19:46.972Z [4567/15226] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2020-10-19T02:19:46.975Z [4567/15226] - info: [app] Web server closed to connections.
2020-10-19T02:19:46.976Z [4567/15226] - info: [app] Live analytics saved.
2020-10-19T02:19:46.976Z [4567/15226] - info: [app] Database connection closed.
2020-10-19T02:19:46.976Z [4567/15226] - info: [app] Shutdown complete.

**Comment by julianlam** [comment]
Hey there, can you provide the output of ./nodebb plugins?

It could be a plugin interfering and you'll be wanting to disable it using `./nodebb reset -p pluginname`

**Comment by sm2x** [comment]
./nodebb plugins
Active plugins:
	* nodebb-plugin-add-registration-fields (installed, disabled)
	* nodebb-plugin-announcements (installed, enabled)
	* nodebb-plugin-calendar (installed, enabled)
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-poll2 (installed, enabled)
	* nodebb-plugin-private-forum (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, disabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, enabled)
	* nodebb-theme-persona (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

**Comment by sm2x** [comment]
> > at /var/www/html/nodebb/src/controllers/index.js:301:19
> 
> Do you have any plugins that use `filter:manifest.build`? You can check from `/admin/advanced/hooks`

None

**Comment by julianlam** [comment]
At this point you will need to reset plugins one by one, or if you want, disable them all using `./nodebb reset -p` and re-enabling them one by one until you find the offending plugin.

It looks like this is not a bug with NodeBB as we are unable to reproduce it on our end using vanilla NodeBB plugin set.
