### ISSUE TITLE
TypeError: rdb.connect & TypeError: Cannot read property 'uploads'

### ISSUE THREAD

**Issue by rez0n** [NodeBB/NodeBB#8814]
Hi, this issue has been fixed by @barisusakli a while ago, but again appeared in the `v1.15.0-rc.1`
Previous issue #8560 

> NodeBB upgrade script crashing if system have less than 4GB RAM.
Once I expanded my DO droplet to the 4GB of RAM it goes works, then I shrink droplet configuration to the 1GB RAM and again getting error.

- **NodeBB version:** v1.15.0-rc.1
- **NodeBB git hash:** 8d48455
- **Installed NodeBB Plugins:** clear installation
- **Database type:** mongo and redis
- **Database version:** redis:latest and mongo:latest
- **Exact steps to cause this issue:**
Just try to start clear NodeBB in the Docker on MacOS, it will crash on migrations.

**NodeBB/Redis logs**
```
nodebb_1  |   → [2017/4/16] Delete accidentally long-lived sessions...Error occurred
nodebb_1  | Error occurred during upgrade: TypeError: rdb.connect is not a function
nodebb_1  |     at /usr/src/app/src/upgrades/1.4.6/delete_sessions.js:26:23
nodebb_1  |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:4576:27)
nodebb_1  |     at Object.waterfall (/usr/src/app/node_modules/async/dist/async.js:4587:9)
nodebb_1  |     at Object.awaitable [as waterfall] (/usr/src/app/node_modules/async/dist/async.js:208:32)
nodebb_1  |     at Object.method (/usr/src/app/src/upgrades/1.4.6/delete_sessions.js:22:9)
nodebb_1  |     at internal/util.js:297:30
nodebb_1  |     at new Promise (<anonymous>)
nodebb_1  |     at Object.method (internal/util.js:296:12)
nodebb_1  |     at Upgrade.process (/usr/src/app/src/upgrade.js:156:6)
nodebb_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
nodebb_1  | 2020-11-01T22:57:05.298Z [4567/86] - error: uncaughtException: rdb.connect is not a function
nodebb_1  | TypeError: rdb.connect is not a function
nodebb_1  |     at /usr/src/app/src/upgrades/1.4.6/delete_sessions.js:26:23
nodebb_1  |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:4576:27)
nodebb_1  |     at Object.waterfall (/usr/src/app/node_modules/async/dist/async.js:4587:9)
nodebb_1  |     at Object.awaitable [as waterfall] (/usr/src/app/node_modules/async/dist/async.js:208:32)
nodebb_1  |     at Object.method (/usr/src/app/src/upgrades/1.4.6/delete_sessions.js:22:9)
nodebb_1  |     at internal/util.js:297:30
nodebb_1  |     at new Promise (<anonymous>)
nodebb_1  |     at Object.method (internal/util.js:296:12)
nodebb_1  |     at Upgrade.process (/usr/src/app/src/upgrade.js:156:6)
nodebb_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {"error":{},"stack":"TypeError: rdb.connect is not a function\n    at /usr/src/app/src/upgrades/1.4.6/delete_sessions.js:26:23\n    at nextTask (/usr/src/app/node_modules/async/dist/async.js:4576:27)\n    at Object.waterfall (/usr/src/app/node_modules/async/dist/async.js:4587:9)\n    at Object.awaitable [as waterfall] (/usr/src/app/node_modules/async/dist/async.js:208:32)\n    at Object.method (/usr/src/app/src/upgrades/1.4.6/delete_sessions.js:22:9)\n    at internal/util.js:297:30\n    at new Promise (<anonymous>)\n    at Object.method (internal/util.js:296:12)\n    at Upgrade.process (/usr/src/app/src/upgrade.js:156:6)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","exception":true,"date":"Sun Nov 01 2020 22:57:05 GMT+0000 (Coordinated Universal Time)","process":{"pid":86,"uid":0,"gid":0,"cwd":"/usr/src/app","execPath":"/usr/local/bin/node","version":"v12.19.0","argv":["/usr/local/bin/node","/usr/src/app/nodebb","upgrade","-sbi"],"memoryUsage":{"rss":129355776,"heapTotal":88567808,"heapUsed":61585368,"external":1761576,"arrayBuffers":264407}},"os":{"loadavg":[1.54,0.84,0.45],"uptime":600},"trace":[{"column":23,"file":"/usr/src/app/src/upgrades/1.4.6/delete_sessions.js","function":null,"line":26,"method":null,"native":false},{"column":27,"file":"/usr/src/app/node_modules/async/dist/async.js","function":"nextTask","line":4576,"method":null,"native":false},{"column":9,"file":"/usr/src/app/node_modules/async/dist/async.js","function":"Object.waterfall","line":4587,"method":"waterfall","native":false},{"column":32,"file":"/usr/src/app/node_modules/async/dist/async.js","function":"Object.awaitable [as waterfall]","line":208,"method":"awaitable [as waterfall]","native":false},{"column":9,"file":"/usr/src/app/src/upgrades/1.4.6/delete_sessions.js","function":"Object.method","line":22,"method":"method","native":false},{"column":30,"file":"internal/util.js","function":null,"line":297,"method":null,"native":false},{"column":null,"file":null,"function":"new Promise","line":null,"method":null,"native":false},{"column":12,"file":"internal/util.js","function":"Object.method","line":296,"method":"method","native":false},{"column":6,"file":"/usr/src/app/src/upgrade.js","function":"Upgrade.process","line":156,"method":"process","native":false},{"column":5,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":97,"method":null,"native":false}]}
```

**NodeBB/Mongo logs**
```
nodebb_1  |   → [2019/3/16] Calculate image sizes of all uploaded images...Error occurred
nodebb_1  | Error occurred during upgrade: TypeError: Cannot read property 'uploads' of undefined
nodebb_1  |     at /usr/src/app/src/upgrades/1.12.1/post_upload_sizes.js:16:33
nodebb_1  |     at /usr/src/app/node_modules/async/dist/async.js:148:38
nodebb_1  |     at /usr/src/app/node_modules/async/dist/async.js:2154:44
nodebb_1  |     at replenish (/usr/src/app/node_modules/async/dist/async.js:440:21)
nodebb_1  |     at /usr/src/app/node_modules/async/dist/async.js:445:13
nodebb_1  |     at eachLimit$1 (/usr/src/app/node_modules/async/dist/async.js:2243:34)
nodebb_1  |     at awaitable (/usr/src/app/node_modules/async/dist/async.js:208:32)
nodebb_1  |     at Object.eachSeries (/usr/src/app/node_modules/async/dist/async.js:2271:16)
nodebb_1  |     at Object.awaitable (/usr/src/app/node_modules/async/dist/async.js:208:32)
nodebb_1  |     at batch.processSortedSet.progress (/usr/src/app/src/upgrades/1.12.1/post_upload_sizes.js:15:10)
nodebb_1  | 2020-11-01T22:45:46.887Z [4567/10] - error: uncaughtException: Cannot read property 'uploads' of undefined
nodebb_1  | TypeError: Cannot read property 'uploads' of undefined
nodebb_1  |     at /usr/src/app/src/upgrades/1.12.1/post_upload_sizes.js:16:33
nodebb_1  |     at /usr/src/app/node_modules/async/dist/async.js:148:38
nodebb_1  |     at /usr/src/app/node_modules/async/dist/async.js:2154:44
nodebb_1  |     at replenish (/usr/src/app/node_modules/async/dist/async.js:440:21)
nodebb_1  |     at /usr/src/app/node_modules/async/dist/async.js:445:13
nodebb_1  |     at eachLimit$1 (/usr/src/app/node_modules/async/dist/async.js:2243:34)
nodebb_1  |     at awaitable (/usr/src/app/node_modules/async/dist/async.js:208:32)
nodebb_1  |     at Object.eachSeries (/usr/src/app/node_modules/async/dist/async.js:2271:16)
nodebb_1  |     at Object.awaitable (/usr/src/app/node_modules/async/dist/async.js:208:32)
nodebb_1  |     at batch.processSortedSet.progress (/usr/src/app/src/upgrades/1.12.1/post_upload_sizes.js:15:10) {"error":{},"stack":"TypeError: Cannot read property 'uploads' of undefined\n    at /usr/src/app/src/upgrades/1.12.1/post_upload_sizes.js:16:33\n    at /usr/src/app/node_modules/async/dist/async.js:148:38\n    at /usr/src/app/node_modules/async/dist/async.js:2154:44\n    at replenish (/usr/src/app/node_modules/async/dist/async.js:440:21)\n    at /usr/src/app/node_modules/async/dist/async.js:445:13\n    at eachLimit$1 (/usr/src/app/node_modules/async/dist/async.js:2243:34)\n    at awaitable (/usr/src/app/node_modules/async/dist/async.js:208:32)\n    at Object.eachSeries (/usr/src/app/node_modules/async/dist/async.js:2271:16)\n    at Object.awaitable (/usr/src/app/node_modules/async/dist/async.js:208:32)\n    at batch.processSortedSet.progress (/usr/src/app/src/upgrades/1.12.1/post_upload_sizes.js:15:10)","exception":true,"date":"Sun Nov 01 2020 22:45:46 GMT+0000 (Coordinated Universal Time)","process":{"pid":10,"uid":0,"gid":0,"cwd":"/usr/src/app","execPath":"/usr/local/bin/node","version":"v10.22.1","argv":["/usr/local/bin/node","/usr/src/app/nodebb","upgrade","-sbi"],"memoryUsage":{"rss":138084352,"heapTotal":105312256,"heapUsed":66252920,"external":18876325}},"os":{"loadavg":[1.4619140625,1.3134765625,1.0869140625],"uptime":260314},"trace":[{"column":33,"file":"/usr/src/app/src/upgrades/1.12.1/post_upload_sizes.js","function":null,"line":16,"method":null,"native":false},{"column":38,"file":"/usr/src/app/node_modules/async/dist/async.js","function":null,"line":148,"method":null,"native":false},{"column":44,"file":"/usr/src/app/node_modules/async/dist/async.js","function":null,"line":2154,"method":null,"native":false},{"column":21,"file":"/usr/src/app/node_modules/async/dist/async.js","function":"replenish","line":440,"method":null,"native":false},{"column":13,"file":"/usr/src/app/node_modules/async/dist/async.js","function":null,"line":445,"method":null,"native":false},{"column":34,"file":"/usr/src/app/node_modules/async/dist/async.js","function":"eachLimit$1","line":2243,"method":null,"native":false},{"column":32,"file":"/usr/src/app/node_modules/async/dist/async.js","function":"awaitable","line":208,"method":null,"native":false},{"column":16,"file":"/usr/src/app/node_modules/async/dist/async.js","function":"Object.eachSeries","line":2271,"method":"eachSeries","native":false},{"column":32,"file":"/usr/src/app/node_modules/async/dist/async.js","function":"Object.awaitable","line":208,"method":"awaitable","native":false},{"column":10,"file":"/usr/src/app/src/upgrades/1.12.1/post_upload_sizes.js","function":"batch.processSortedSet.progress","line":15,"method":"progress","native":false}]}
```

**Comment by barisusakli** [comment]
There is no `rdb.connect` at line 26 in that upgrade script anymore. 

```
Error occurred during upgrade: TypeError: rdb.connect is not a function
nodebb_1  |     at /usr/src/app/src/upgrades/1.4.6/delete_sessions.js:26:23
```

Seems like you don't have the code from this fix. https://github.com/NodeBB/NodeBB/commit/29e3ab247d336220cdddd123fc8703a3a97b1013

Not sure about the `uploads` error but it might be related.

**Comment by rez0n** [comment]
Hi, sorry, seems I have been mixed the local codebase.
