### ISSUE TITLE
Installer not loading in Alpine environment

### ISSUE THREAD

**Issue by nilsramsperger** [NodeBB/NodeBB#8828]
I just tried to update my Docker image (https://github.com/nilsramsperger/docker-nodebb) to NodeBB 1.15.0. On first run I get an "internal server error". The log tells the following:

```
2020-11-05T08:17:57.790Z [undefined/9] - info: NodeBB v1.15.0 Copyright (C) 2013-2020 NodeBB Inc.
2020-11-05T08:17:57.791Z [undefined/9] - info: This program comes with ABSOLUTELY NO WARRANTY.
2020-11-05T08:17:57.792Z [undefined/9] - info: This is free software, and you are welcome to redistribute it under certain conditions.
2020-11-05T08:17:57.792Z [undefined/9] - info: 
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version.
[benchpressjs] This will result in much longer template build times.
[benchpressjs] prebuilt module failed to load: linux_72
[benchpressjs] If the above module is not available at `node_modules/benchpressjs/rust/benchpress-rs/pre-built/`,
[benchpressjs] you can manually build benchpress-rs following the instructions here:
[benchpressjs] `https://github.com/benchpressjs/benchpressjs/blob/master/README.md#manually-building-native-module`
2020-11-05T08:17:58.160Z [9] - info: Launching web installer on port 4567
2020-11-05T08:17:58.166Z [9] - info: [installer] Found setup.json, populating default values
2020-11-05T08:18:00.315Z [9] - info: Web installer listening on http://0.0.0.0:4567
Error: Failed to lookup view "install/index" in views directory "/opt/nodebb/build/public/templates"
    at Function.render (/opt/nodebb/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/opt/nodebb/node_modules/express/lib/response.js:1012:7)
    at welcome (/opt/nodebb/install/web.js:130:6)
    at Layer.handle [as handle_request] (/opt/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/nodebb/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/nodebb/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at /opt/nodebb/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/opt/nodebb/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/nodebb/node_modules/express/lib/router/index.js:275:10)
```

It looks like benchpress was not able to compile the templates, as the directory `/opt/nodebb/build/public/templates` does not exist. The Benchpress js fallback seems to have stopped working.

An interesting detail is the message stating that the benchpress module linux_72 is missing. It can be found at the stated location. May be it is a special behavior when using a Docker Apline environment.
Anyway, it should not be the cause of the current problem, since I know this error from NodeBB 1.14.3.

The old log for comparison:
```
2020-11-05T08:39:54.862Z [undefined/9] - info: NodeBB v1.14.3 Copyright (C) 2013-2020 NodeBB Inc.
2020-11-05T08:39:54.863Z [undefined/9] - info: This program comes with ABSOLUTELY NO WARRANTY.
2020-11-05T08:39:54.863Z [undefined/9] - info: This is free software, and you are welcome to redistribute it under certain conditions.
2020-11-05T08:39:54.863Z [undefined/9] - info: 
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version.
[benchpressjs] This will result in much longer template build times.
[benchpressjs] prebuilt module failed to load: linux_72
[benchpressjs] If the above module is not available at `node_modules/benchpressjs/rust/benchpress-rs/pre-built/`,
[benchpressjs] you can manually build benchpress-rs following the instructions here:
[benchpressjs] `https://github.com/benchpressjs/benchpressjs/blob/master/README.md#manually-building-native-module`
2020-11-05T08:39:55.221Z [9] - info: Launching web installer on port 4567
2020-11-05T08:39:56.974Z [9] - info: Web installer listening on http://0.0.0.0:4567
```
The web installer loads, as expected here.

**Comment by pitaj** [comment]
I haven't been able to verify this locally, but it looks like @barisusakli broke the web installer with this commit 3881ac309f3c8c8f6de158b775e21df06e82ddf6

**Comment by pitaj** [comment]
I'm working on a fix.

**Comment by barisusakli** [comment]
@pitaj thanks.
