### ISSUE TITLE
Error upgrading from 1.14.x to 1.15.x during "Create fullname search set"

### ISSUE THREAD

**Issue by joolswills** [NodeBB/NodeBB#8836]
- **NodeBB version:** 1.15.x
- **NodeBB git hash:** a30aa5629cb51c881ea99431e739c8813ecfded8

- **Installed NodeBB Plugins:** 

Active plugins:
	* nodebb-plugin-category-notifications (installed, enabled)
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emoji (installed, disabled)
	* nodebb-plugin-emoji-android (installed, disabled)
	* nodebb-plugin-gdpr (installed, enabled)
	* nodebb-plugin-google-analytics (installed, enabled)
	* nodebb-plugin-gravatar (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-ns-embed (installed, enabled)
	* nodebb-plugin-recent-cards (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-rewards-essentials (installed, disabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

- **Database type:** mongo + redis
- **Database version:** 4.2.10

- **Exact steps to cause this issue:**
run ./nodebb upgrade
- **What you expected:**
Database updates to succeed
- **What happened instead:**
Fails during
```
4. Updating NodeBB data store schema...
Parsing upgrade scripts... 
OK | 4 script(s) found, 95 skipped
  → [2020/9/11] Create fullname search set...
    [############ ] (28000/31605) 88% Error occurred
```

Looks like a user on our forum has a long fullname with lots of non ascii characters which it fails on - I will probably just remove their account and re-do the upgrade.

here's a log (removed only the install path of nodebb for security)

```
3. Checking installed plugins for updates...  OK
4. Updating NodeBB data store schema...
Parsing upgrade scripts... 
OK | 4 script(s) found, 95 skipped
  → [2020/9/11] Create fullname search set...
    [############ ] (28000/31605) 88% Error occurred
Error occurred during upgrade: BulkWriteError: Index key too large to index, failing 1271 { : "fullname:sorted", : "ͤ ͬ ͬ ͦ ͬ⅁ᴌ̽̽̽̽̽̽ᴉᴛᴄʜ͓͓͓xⷯᴘⷵʟøⷯɪᴛ̲̲̲̲̲я  ꙱꙱꙱꙱꙱꙱꙱꙱꙱꙱�..." }
    at UnorderedBulkOperation.handleWriteError (nodebb/node_modules/mongodb/lib/bulk/common.js:1257:9)
    at UnorderedBulkOperation.handleWriteError (nodebb/node_modules/mongodb/lib/bulk/unordered.js:117:18)
    at resultHandler (nodebb/node_modules/mongodb/lib/bulk/common.js:521:23)
    at handler (nodebb/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
    at nodebb/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
    at handleOperationResult (nodebb/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (nodebb/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:314:20)
    at processIncomingData (nodebb/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (nodebb/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
2020-11-05T19:46:45.465Z [4567,4568,4569,4570/25806] - error: uncaughtException: Index key too large to index, failing 1271 { : "fullname:sorted", : "ͤ ͬ ͬ ͦ ͬ⅁ᴌ̽̽̽̽̽̽ᴉᴛᴄʜ͓͓͓xⷯᴘⷵʟøⷯɪᴛ̲̲̲̲̲я  ꙱꙱꙱꙱꙱꙱꙱꙱꙱꙱�..." }
BulkWriteError: Index key too large to index, failing 1271 { : "fullname:sorted", : "ͤ ͬ ͬ ͦ ͬ⅁ᴌ̽̽̽̽̽̽ᴉᴛᴄʜ͓͓͓xⷯᴘⷵʟøⷯɪᴛ̲̲̲̲̲я  ꙱꙱꙱꙱꙱꙱꙱꙱꙱꙱�..." }
    at UnorderedBulkOperation.handleWriteError (nodebb/node_modules/mongodb/lib/bulk/common.js:1257:9)
    at UnorderedBulkOperation.handleWriteError (nodebb/node_modules/mongodb/lib/bulk/unordered.js:117:18)
    at resultHandler (nodebb/node_modules/mongodb/lib/bulk/common.js:521:23)
    at handler (nodebb/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
    at nodebb/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
    at handleOperationResult (nodebb/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (nodebb/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:314:20)
    at processIncomingData (nodebb/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (nodebb/node_modules/mongodb/lib/cmap/message_stream.js:42:5) {"error":{"name":"BulkWriteError","driver":true,"code":17280,"writeErrors":[{"code":17280,"index":5,"errmsg":"Index key too large to index, failing 1271 { : \"fullname:sorted\", : \"ͤ ͬ ͬ ͦ ͬ⅁ᴌ̽̽̽̽̽̽ᴉᴛᴄʜ͓͓͓xⷯᴘⷵʟøⷯɪᴛ̲̲̲̲̲я  ꙱꙱꙱꙱꙱꙱꙱꙱꙱꙱�...\" }","op":{"q":{"_key":"fullname:sorted","value":"ͤ ͬ ͬ ͦ ͬ⅁ᴌ̽̽̽̽̽̽ᴉᴛᴄʜ͓͓͓xⷯᴘⷵʟøⷯɪᴛ̲̲̲̲̲я  ꙱꙱꙱꙱꙱꙱꙱꙱꙱꙱   ͦͬͬͤ ͬͦͬͬͤ ͤͬͦͬͬͤ ͬͤͬͦͬͬͤ ͬͬͤͬͦͬͬͤ ͦͬͬͤͬͦͬͬͤ ͬͦͬͬͤͬͦͬͬͤ ͤͬͦͬͬͤͬͦͬͬ ͬͦͬͬͤͬͦͬͬͤ ͦͬͬͤͬͦͬͬͤ ͬͬͤͬͦͬͬͤ ͬͤͬͦͬͬͤ ͤͬͦͬͬͤ ͬͦͬͬͤ ͦͬͬͤ ͬͬͤ ͬͤ ͤ ͬͬͤ ͦͬͬͤ ͬͦͬͬͤ ͤͬͦͬͬͤ ͬͤͬͦͬͬͤ ͬͬͤͬͦͬͬͤ ͦͬͬͤͬͦͬͬͤ ͬͦͬͬͤͬͦͬͬͤ ͤͬͦͬͬͤͬͦͬͬ ͬͦͬͬͤͬͦͬͬͤ ͦͬͬͤͬͦͬͬͤ ͬͬͤͬͦͬͬͤ ͬͤͬͦͬͬͤ ͤͬͦͬͬͤ ͬͦͬͬͤ ͦͬͬͤ ͬͬͤ ͬͤ ͤ ͬͬͤ ͦͬͬͤ ͬͦͬͬͤ ͤͬͦͬͬͤ ͬͤͬͦͬͬͤ ͬͬͤͬͦͬͬͤ ͦͬͬͤͬͦͬͬͤ ͬͦͬͬͤͬͦͬͬͤ ͤͬͦͬͬͤͬͦͬͬ ͬͦͬͬͤͬͦͬͬͤ ͦͬͬͤͬͦͬͬͤ ͬͬͤͬͦͬͬͤ ͬͤͬͦͬͬͤ ͤͬͦͬͬͤ ͬͦͬͬͤ ͦͬͬͤ ͬͬͤ ͬͤ ͤ  https://https://www.facebook.com/glitch.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0                       twitter.com/glitchxploitr                        t.me/glitchxploitr                               github.com/glitchxploitr:31407"},"u":{"$set":{"score":0}},"multi":false,"upsert":true}}],"result":{"ok":1,"writeErrors":[{"code":17280,"index":5,"errmsg":"Index key too large to index, failing 1271 { : \"fullname:sorted\", : \"ͤ ͬ ͬ ͦ ͬ⅁ᴌ̽̽̽̽̽̽ᴉᴛᴄʜ͓͓͓xⷯᴘⷵʟøⷯɪᴛ̲̲̲̲̲я  ꙱꙱꙱꙱꙱꙱꙱꙱꙱꙱�...\" }","op":{"q":{"_key":"fullname:sorted","value":"ͤ ͬ ͬ ͦ ͬ⅁ᴌ̽̽̽̽̽̽ᴉᴛᴄʜ͓͓͓xⷯᴘⷵʟøⷯɪᴛ̲̲̲̲̲я  ꙱꙱꙱꙱꙱꙱꙱꙱꙱꙱   ͦͬͬͤ ͬͦͬͬͤ ͤͬͦͬͬͤ ͬͤͬͦͬͬͤ ͬͬͤͬͦͬͬͤ ͦͬͬͤͬͦͬͬͤ ͬͦͬͬͤͬͦͬͬͤ ͤͬͦͬͬͤͬͦͬͬ ͬͦͬͬͤͬͦͬͬͤ ͦͬͬͤͬͦͬͬͤ ͬͬͤͬͦͬͬͤ ͬͤͬͦͬͬͤ ͤͬͦͬͬͤ ͬͦͬͬͤ ͦͬͬͤ ͬͬͤ ͬͤ ͤ ͬͬͤ ͦͬͬͤ ͬͦͬͬͤ ͤͬͦͬͬͤ ͬͤͬͦͬͬͤ ͬͬͤͬͦͬͬͤ ͦͬͬͤͬͦͬͬͤ ͬͦͬͬͤͬͦͬͬͤ ͤͬͦͬͬͤͬͦͬͬ ͬͦͬͬͤͬͦͬͬͤ ͦͬͬͤͬͦͬͬͤ ͬͬͤͬͦͬͬͤ ͬͤͬͦͬͬͤ ͤͬͦͬͬͤ ͬͦͬͬͤ ͦͬͬͤ ͬͬͤ ͬͤ ͤ ͬͬͤ ͦͬͬͤ ͬͦͬͬͤ ͤͬͦͬͬͤ ͬͤͬͦͬͬͤ ͬͬͤͬͦͬͬͤ ͦͬͬͤͬͦͬͬͤ ͬͦͬͬͤͬͦͬͬͤ ͤͬͦͬͬͤͬͦͬͬ ͬͦͬͬͤͬͦͬͬͤ ͦͬͬͤͬͦͬͬͤ ͬͬͤͬͦͬͬͤ ͬͤͬͦͬͬͤ ͤͬͦͬͬͤ ͬͦͬͬͤ ͦͬͬͤ ͬͬͤ ͬͤ ͤ  https://https://www.facebook.com/glitch.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0                       twitter.com/glitchxploitr                        t.me/glitchxploitr                               github.com/glitchxploitr:31407"},"u":{"$set":{"score":0}},"multi":false,"upsert":true}}],"writeConcernErrors":[],"insertedIds":[],"nInserted":0,"nUpserted":0,"nMatched":11,"nModified":0,"nRemoved":0,"upserted":[]}},"stack":"BulkWriteError: Index key too large to index, failing 1271 { : \"fullname:sorted\", : \"ͤ ͬ ͬ ͦ ͬ⅁ᴌ̽̽̽̽̽̽ᴉᴛᴄʜ͓͓͓xⷯᴘⷵʟøⷯɪᴛ̲̲̲̲̲я  ꙱꙱꙱꙱꙱꙱꙱꙱꙱꙱�...\" }\n    at UnorderedBulkOperation.handleWriteError (nodebb/node_modules/mongodb/lib/bulk/common.js:1257:9)\n    at UnorderedBulkOperation.handleWriteError (nodebb/node_modules/mongodb/lib/bulk/unordered.js:117:18)\n    at resultHandler (nodebb/node_modules/mongodb/lib/bulk/common.js:521:23)\n    at handler (nodebb/node_modules/mongodb/lib/core/sdam/topology.js:942:24)\n    at nodebb/node_modules/mongodb/lib/cmap/connection_pool.js:350:13\n    at handleOperationResult (nodebb/node_modules/mongodb/lib/core/sdam/server.js:558:5)\n    at MessageStream.messageHandler (nodebb/node_modules/mongodb/lib/cmap/connection.js:277:5)\n    at MessageStream.emit (events.js:314:20)\n    at processIncomingData (nodebb/node_modules/mongodb/lib/cmap/message_stream.js:144:12)\n    at MessageStream._write (nodebb/node_modules/mongodb/lib/cmap/message_stream.js:42:5)","exception":true,"date":"Thu Nov 05 2020 19:46:45 GMT+0000 (Greenwich Mean Time)","process":{"pid":25806,"uid":1004,"gid":1004,"cwd":"nodebb","execPath":"/usr/bin/node","version":"v12.19.0","argv":["/usr/bin/node","nodebb/nodebb","upgrade"],"memoryUsage":{"rss":177446912,"heapTotal":130854912,"heapUsed":109944256,"external":21565460,"arrayBuffers":20057801}},"os":{"loadavg":[1.89,2.24,2.03],"uptime":884846},"trace":[{"column":9,"file":"nodebb/node_modules/mongodb/lib/bulk/common.js","function":"UnorderedBulkOperation.handleWriteError","line":1257,"method":"handleWriteError","native":false},{"column":18,"file":"nodebb/node_modules/mongodb/lib/bulk/unordered.js","function":"UnorderedBulkOperation.handleWriteError","line":117,"method":"handleWriteError","native":false},{"column":23,"file":"nodebb/node_modules/mongodb/lib/bulk/common.js","function":"resultHandler","line":521,"method":null,"native":false},{"column":24,"file":"nodebb/node_modules/mongodb/lib/core/sdam/topology.js","function":"handler","line":942,"method":null,"native":false},{"column":13,"file":"nodebb/node_modules/mongodb/lib/cmap/connection_pool.js","function":null,"line":350,"method":null,"native":false},{"column":5,"file":"nodebb/node_modules/mongodb/lib/core/sdam/server.js","function":"handleOperationResult","line":558,"method":null,"native":false},{"column":5,"file":"nodebb/node_modules/mongodb/lib/cmap/connection.js","function":"MessageStream.messageHandler","line":277,"method":"messageHandler","native":false},{"column":20,"file":"events.js","function":"MessageStream.emit","line":314,"method":"emit","native":false},{"column":12,"file":"nodebb/node_modules/mongodb/lib/cmap/message_stream.js","function":"processIncomingData","line":144,"method":null,"native":false},{"column":5,"file":"nodebb/node_modules/mongodb/lib/cmap/message_stream.js","function":"MessageStream._write","line":42,"method":"_write","native":false}]}
```

Restoring db backup I made and switching back to 1.14.x for now.

**Comment by barisusakli** [comment]
Thanks for reporting @joolswills I'll fix this.

**Comment by barisusakli** [comment]
@joolswills let me know if this resolves your issue

**Comment by joolswills** [comment]
Thanks - I can confirm this resolves the issue.
