### ISSUE TITLE
error: [build] - client js bundle & admin js bundle

### ISSUE THREAD

**Issue by rez0n** [NodeBB/NodeBB#8846]
Hi, since few release-candidate versions and released 1.15.0 I faced building error on forum set-up.
This happens in the Docker images that are I maintaining, and reproduced on clear, local NodeBB copy.
Any advice to handle this issue?

```
2020-11-06T17:00:25.120Z [41858] - info: [build] Building in parallel mode
2020-11-06T17:00:25.120Z [41858] - info: [build]         plugin static dirs  build started
2020-11-06T17:00:25.124Z [41858] - info: [build]          requirejs modules  build started
2020-11-06T17:00:25.125Z [41858] - info: [build]           client js bundle  build started
2020-11-06T17:00:25.159Z [41858] - info: [build]            admin js bundle  build started
2020-11-06T17:00:25.160Z [41858] - info: [build]         client side styles  build started
2020-11-06T17:00:25.160Z [41858] - info: [build] admin control panel styles  build started
2020-11-06T17:00:25.161Z [41858] - info: [build]                  templates  build started
2020-11-06T17:00:25.161Z [41858] - info: [build]                  languages  build started
2020-11-06T17:00:25.420Z [41858] - error: [build]           client js bundle  build failed
2020-11-06T17:00:25.421Z [41858] - error: [build] Encountered error during build step
Error: ENOENT: no such file or directory, open '/Users/dv/Downloads/NodeBB-1.15.0/build/public/rjs-bundle-client.js'

     =========================================================================================================================================================================================================================================================================================

2020-11-06T17:00:25.421Z [41858] - error: There was a problem completing NodeBB setup {"0":"E","1":"r","2":"r","3":"o","4":"r","5":":","6":" ","7":"E","8":"N","9":"O","10":"E","11":"N","12":"T","13":":","14":" ","15":"n","16":"o","17":" ","18":"s","19":"u","20":"c","21":"h","22":" ","23":"f","24":"i","25":"l","26":"e","27":" ","28":"o","29":"r","30":" ","31":"d","32":"i","33":"r","34":"e","35":"c","36":"t","37":"o","38":"r","39":"y","40":",","41":" ","42":"o","43":"p","44":"e","45":"n","46":" ","47":"'","48":"/","49":"U","50":"s","51":"e","52":"r","53":"s","54":"/","55":"d","56":"v","57":"/","58":"D","59":"o","60":"w","61":"n","62":"l","63":"o","64":"a","65":"d","66":"s","67":"/","68":"N","69":"o","70":"d","71":"e","72":"B","73":"B","74":"-","75":"1","76":".","77":"1","78":"5","79":".","80":"0","81":"/","82":"b","83":"u","84":"i","85":"l","86":"d","87":"/","88":"p","89":"u","90":"b","91":"l","92":"i","93":"c","94":"/","95":"r","96":"j","97":"s","98":"-","99":"b","100":"u","101":"n","102":"d","103":"l","104":"e","105":"-","106":"c","107":"l","108":"i","109":"e","110":"n","111":"t","112":".","113":"j","114":"s","115":"'"}
2020-11-06T17:00:25.424Z [41858] - error: uncaughtException: ENOENT: no such file or directory, open '/Users/dv/Downloads/NodeBB-1.15.0/build/public/rjs-bundle-client.js'
Error: ENOENT: no such file or directory, open '/Users/dv/Downloads/NodeBB-1.15.0/build/public/rjs-bundle-client.js' {"error":{"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/dv/Downloads/NodeBB-1.15.0/build/public/rjs-bundle-client.js"},"stack":"Error: ENOENT: no such file or directory, open '/Users/dv/Downloads/NodeBB-1.15.0/build/public/rjs-bundle-client.js'","exception":true,"date":"Fri Nov 06 2020 19:00:25 GMT+0200 (Eastern European Standard Time)","process":{"pid":41858,"uid":501,"gid":20,"cwd":"/Users/dv/Downloads/NodeBB-1.15.0","execPath":"/usr/local/Cellar/node/14.11.0/bin/node","version":"v14.11.0","argv":["/usr/local/Cellar/node/14.11.0/bin/node","/Users/dv/Downloads/NodeBB-1.15.0/nodebb","setup"],"memoryUsage":{"rss":113627136,"heapTotal":83378176,"heapUsed":70908152,"external":1885880,"arrayBuffers":124804}},"os":{"loadavg":[2.375,2.36474609375,2.26611328125],"uptime":409860},"trace":[]}
2020-11-06T17:00:25.424Z [41858] - error: uncaughtException: ENOENT: no such file or directory, open '/Users/dv/Downloads/NodeBB-1.15.0/build/public/rjs-bundle-client.js'
Error: ENOENT: no such file or directory, open '/Users/dv/Downloads/NodeBB-1.15.0/build/public/rjs-bundle-client.js' {"error":{"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/dv/Downloads/NodeBB-1.15.0/build/public/rjs-bundle-client.js"},"stack":"Error: ENOENT: no such file or directory, open '/Users/dv/Downloads/NodeBB-1.15.0/build/public/rjs-bundle-client.js'","exception":true,"date":"Fri Nov 06 2020 19:00:25 GMT+0200 (Eastern European Standard Time)","process":{"pid":41858,"uid":501,"gid":20,"cwd":"/Users/dv/Downloads/NodeBB-1.15.0","execPath":"/usr/local/Cellar/node/14.11.0/bin/node","version":"v14.11.0","argv":["/usr/local/Cellar/node/14.11.0/bin/node","/Users/dv/Downloads/NodeBB-1.15.0/nodebb","setup"],"memoryUsage":{"rss":113676288,"heapTotal":83378176,"heapUsed":70948776,"external":1894136,"arrayBuffers":133020}},"os":{"loadavg":[2.375,2.36474609375,2.26611328125],"uptime":409860},"trace":[]}
2020-11-06T17:00:25.425Z [41858] - error: [build]            admin js bundle  build failed
2020-11-06T17:00:25.554Z [41858] - info: [build]         plugin static dirs  build completed in 0.434sec
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:831:20)
    at process.target.send (internal/child_process.js:702:19)
    at /Users/dv/Downloads/NodeBB-1.15.0/src/meta/minifier.js:125:13
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on process instance at:
    at internal/child_process.js:835:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:831:20)
    at process.target.send (internal/child_process.js:702:19)
    at /Users/dv/Downloads/NodeBB-1.15.0/src/meta/minifier.js:125:13
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on process instance at:
    at internal/child_process.js:835:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

- **NodeBB version:** 1.15.0
- **NodeBB git hash:** 540a32c

- **Installed NodeBB Plugins:** default

- **Database type:** mongo, redis, or postgres
- **Database version:** redis (any)

- **Exact steps to cause this issue:**
Just need to run `./nodebb setup`

**Comment by rez0n** [comment]
Additional information.
If I run `./nodebb setup` twice, it is built correctly for the second run.
If I use `./nodebb build` instead of `./nodebb setup` it is not building even if I run twice or more times.

**Comment by julianlam** [comment]
Any chance you can use [`git bisect`](https://git-scm.com/docs/git-bisect) to help us figure out which commit causes issues for you?

**Comment by barisusakli** [comment]
>If I use ./nodebb build instead of ./nodebb setup it is not building even if I run twice or more times.
This doesn't sound right. Is the file getting created in `build/public` when you use `./nodebb build --series` ?

**Comment by rez0n** [comment]
@julianlam thanks for the answer. 
I using the release [tarball](https://github.com/NodeBB/NodeBB/archive/v1.15.0.tar.gz) file instead of pulling code from the repo. 
Should I try to use git repo for the debug? Anyway, the code version is from the latest tarball.

**Comment by rez0n** [comment]
Hi, @barisusakli thank you for the attention.
I used `build` only for the tests.

`./nodebb build --series` builts assets with no errors.

```
ls -la build
total 32
drwxrwxr-x@  6 dv  staff   192 Nov  6 19:26 .
drwxrwxr-x@ 37 dv  staff  1184 Nov  6 18:59 ..
-rw-r--r--@  1 dv  staff  6148 Nov  6 18:40 .DS_Store
-rw-rw-r--@  1 dv  staff    25 Nov  4 22:56 .gitignore
-rw-r--r--   1 dv  staff    11 Nov  6 19:19 cache-buster
drwxrwxr-x@  4 dv  staff   128 Nov  4 22:56 export
dv@dvm NodeBB-1.15.0 % ./nodebb build --series
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version.
[benchpressjs] This will result in much longer template build times.
[benchpressjs] prebuilt module failed to load: darwin_83
[benchpressjs] If the above module is not available at `node_modules/benchpressjs/rust/benchpress-rs/pre-built/`,
[benchpressjs] you can manually build benchpress-rs following the instructions here:
[benchpressjs] `https://github.com/benchpressjs/benchpressjs/blob/master/README.md#manually-building-native-module`
  started
2020-11-06T17:26:56.330Z [4567/43099] - info: [build] Building in series mode
2020-11-06T17:26:56.331Z [4567/43099] - info: [build]         plugin static dirs  build started
2020-11-06T17:26:56.335Z [4567/43099] - info: [build]         plugin static dirs  build completed in 0.004sec
2020-11-06T17:26:56.336Z [4567/43099] - info: [build]          requirejs modules  build started
2020-11-06T17:26:59.071Z [4567/43099] - info: [build]          requirejs modules  build completed in 2.735sec
2020-11-06T17:26:59.071Z [4567/43099] - info: [build]           client js bundle  build started
2020-11-06T17:27:00.219Z [4567/43099] - info: [build]           client js bundle  build completed in 1.147sec
2020-11-06T17:27:00.219Z [4567/43099] - info: [build]            admin js bundle  build started
2020-11-06T17:27:01.252Z [4567/43099] - info: [build]            admin js bundle  build completed in 1.033sec
2020-11-06T17:27:01.253Z [4567/43099] - info: [build]         client side styles  build started
2020-11-06T17:27:04.013Z [4567/43099] - info: [build]         client side styles  build completed in 2.76sec
2020-11-06T17:27:04.013Z [4567/43099] - info: [build] admin control panel styles  build started
2020-11-06T17:27:05.904Z [4567/43099] - info: [build] admin control panel styles  build completed in 1.891sec
2020-11-06T17:27:05.904Z [4567/43099] - info: [build]                  templates  build started
2020-11-06T17:27:16.899Z [4567/43099] - info: [build]                  templates  build completed in 10.995sec
2020-11-06T17:27:16.900Z [4567/43099] - info: [build]                  languages  build started
2020-11-06T17:27:19.141Z [4567/43099] - info: [build]                  languages  build completed in 2.241sec
2020-11-06T17:27:19.141Z [4567/43099] - info: [build] Asset compilation successful. Completed in 22.811sec.
```

Just after that, I was deleted `build/public` directory and re-run the`./nodebb setup` and get the error again.

What `--series` is doing? Maybe running in a single thread?
If yes, seems a problem in multithreading, because when building runs from the `setup` script it is outputs
```[minifier] utilizing a maximum of 11 additional threads```

**Comment by barisusakli** [comment]
series build everything in order, but all the javascript is built in the `   client js bundle  build started` step.

How much memory does your system has? `./nodebb build` uses more memory than `./nodebb build --series` since everything runs in parallel

**Comment by rez0n** [comment]
Docker limited to 3GB
System 
![image](https://user-images.githubusercontent.com/725860/98397685-61892e80-2068-11eb-9831-2df6aa706992.png)
btw, it fails not only for me, I work on an issue for the `nibrev/nodebb` Docker image that was reported by the user.
I will test it now on a few DigitalOcean instances and report you.

**Comment by barisusakli** [comment]
Yeah let us know, try adding the above change as well, it might effect parallel builds.

**Comment by rez0n** [comment]
In general, I would not like to use `./nodebb build --series` since I use an automatic installation (`node app --setup`) and would like to leave the parallel build.

**Comment by rez0n** [comment]
Works good on both Droplet types (1GB and 2GB) locally and in the Docker.
I'm confused.

**Comment by barisusakli** [comment]
The build process checks # of cpus avaiable and uses --series if there is only 2 cores if I remember correctly.

**Comment by rez0n** [comment]
So, I think the issue can be closed (maybe), but anyway, some incorrect behavior is present in MacOS (Docker and local), I have much more free RAM than on the DO Droplet is total but it fails.
I have 12 cores and 3GB free RAM, maybe here is a problem. 11 build processes is starting, but have a lack of memory.
Not sure it worth having a lot of work to debug it. Correct?

**Comment by barisusakli** [comment]
Yeah not sure how much memory each of those forked processes use on macos as opposed to linux.
But this seems like a memory issue since `./nodebb build --series` doesn't fork anything and uses a lot less memory. 
Maybe try freeing up some memory and assigning more ram to docker, see if it resolves the issue.
