### ISSUE TITLE
NodeBB setup aborted: NodeBB/node_modules/klona' do not define a valid '.' target

### ISSUE THREAD

**Issue by vinukumar-vs** [NodeBB/NodeBB#8859]
- **NodeBB version:** NA

- **NodeBB git hash:** git clone -b v1.13.x https://github.com/NodeBB/NodeBB.git nodebb

- **Database type:** mongo

- **Database version:**  4.4.1

- **Exact steps to cause this issue:**
1. All the mongodb related issues were resolved while doing the first time installation(especially auth issues)
2. After mongo installed successfully, I did the below steps as per [documentation](https://docs.nodebb.org/installing/os/ubuntu/#installing-nodebb)
 ```
git clone -b v1.13.x https://github.com/NodeBB/NodeBB.git nodebb
cd NodeBB
npm i
./nodebb setup
```
**NodeBB** -> Is my project folder name

- **What you expected:**
I was expecting setup to complete successfully.

- **What happened instead:**
I got the below error

```
~/Projects/NodeBB$ ./nodebb setup
2020-11-09T02:50:43.276Z [32643] - info: NodeBB Setup Triggered via Command Line

Welcome to NodeBB v1.15.0-rc.3!

This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
Press enter to accept the default setting (shown in brackets).
URL used to access this NodeBB (http://localhost:4567) 
Please enter a NodeBB secret (---XXX---) 
Would you like to submit anonymous plugin usage to nbbpm? (yes) 
Which database to use (mongo) 
2020-11-09T02:50:46.423Z [32643] - info: 
Now configuring mongo database:
MongoDB connection URI: (leave blank if you wish to specify host, port, username/password and database individually)
Format: mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]] 
Host IP or address of your MongoDB instance (127.0.0.1) 
Host port of your MongoDB instance (27017) 
MongoDB username nodebb
Password of your MongoDB database 
MongoDB database name (nodebb) 
2020-11-09T02:50:59.159Z [32643] - info: [database] Checking database indices.
2020-11-09T02:50:59.167Z [32643] - info: [database] Checking database indices done!
2020-11-09T02:50:59.417Z [32643] - warn: NodeBB Setup Aborted.
 Error: Package exports for '/home/vinu/Projects/NodeBB/node_modules/klona' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/vinu/Projects/NodeBB/node_modules/sanitize-html/index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)

```

**Comment by vinukumar-vs** [comment]
I have deleted the cloned project(including the folder "NodeBB".

I cloned the nodebb repo again using the below command
```
git clone -b v1.13.x https://github.com/NodeBB/NodeBB.git nodebb
```

After this also I was facing some issue with different error message while setting up nodebb 
```
./nodebb setup
```

I was getting the below error
```
2020-11-09T05:22:22.187Z [8872] - error: uncaughtException: Package exports for '/home/vinu/Projects/nodebb/node_modules/colorette' do not define a valid '.' target
Error: Package exports for '/home/vinu/Projects/nodebb/node_modules/colorette' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/vinu/Projects/nodebb/node_modules/autoprefixer/lib/autoprefixer.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {"error":{"code":"MODULE_NOT_FOUND"},"stack":"Error: Package exports for '/home/vinu/Projects/nodebb/node_modules/colorette' do not define a valid '.' target\n    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)\n    at applyExports (internal/modules/cjs/loader.js:459:14)\n    at resolveExports (internal/modules/cjs/loader.js:508:12)\n    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)\n    at Function.Module._load (internal/modules/cjs/loader.js:785:27)\n    at Module.require (internal/modules/cjs/loader.js:956:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/home/vinu/Projects/nodebb/node_modules/autoprefixer/lib/autoprefixer.js:5:17)\n    at Module._compile (internal/modules/cjs/loader.js:1063:30)","exception":true,"date":"Mon Nov 09 2020 10:52:22 GMT+0530 (India Standard Time)","process":{"pid":8872,"uid":1001,"gid":1001,"cwd":"/home/vinu/Projects/nodebb","execPath":"/home/vinu/.nvm/versions/node/v13.1.0/bin/node","version":"v13.1.0","argv":["/home/vinu/.nvm/versions/node/v13.1.0/bin/node","/home/vinu/Projects/nodebb/nodebb","setup"],"memoryUsage":{"rss":116781056,"heapTotal":77598720,"heapUsed":46173224,"external":21831657}},"os":{"loadavg":[1.68603515625,1.951171875,2.74951171875],"uptime":87688},"trace":[{"column":13,"file":"internal/modules/cjs/loader.js","function":"resolveExportsTarget","line":545,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"applyExports","line":459,"method":null,"native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"resolveExports","line":508,"method":null,"native":false},{"column":20,"file":"internal/modules/cjs/loader.js","function":"Module._findPath","line":577,"method":"_findPath","native":false},{"column":27,"file":"internal/modules/cjs/loader.js","function":"Module._resolveFilename","line":879,"method":"_resolveFilename","native":false},{"column":27,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":785,"method":"_load","native":false},{"column":19,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":956,"method":"require","native":false},{"column":18,"file":"internal/modules/cjs/helpers.js","function":"require","line":74,"method":null,"native":false},{"column":17,"file":"/home/vinu/Projects/nodebb/node_modules/autoprefixer/lib/autoprefixer.js","function":null,"line":5,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1063,"method":"_compile","native":false}]}
2020-11-09T05:22:22.188Z [8872] - error: uncaughtException: Package exports for '/home/vinu/Projects/nodebb/node_modules/colorette' do not define a valid '.' target
Error: Package exports for '/home/vinu/Projects/nodebb/node_modules/colorette' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/vinu/Projects/nodebb/node_modules/autoprefixer/lib/autoprefixer.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {"error":{"code":"MODULE_NOT_FOUND"},"stack":"Error: Package exports for '/home/vinu/Projects/nodebb/node_modules/colorette' do not define a valid '.' target\n    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)\n    at applyExports (internal/modules/cjs/loader.js:459:14)\n    at resolveExports (internal/modules/cjs/loader.js:508:12)\n    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)\n    at Function.Module._load (internal/modules/cjs/loader.js:785:27)\n    at Module.require (internal/modules/cjs/loader.js:956:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/home/vinu/Projects/nodebb/node_modules/autoprefixer/lib/autoprefixer.js:5:17)\n    at Module._compile (internal/modules/cjs/loader.js:1063:30)","exception":true,"date":"Mon Nov 09 2020 10:52:22 GMT+0530 (India Standard Time)","process":{"pid":8872,"uid":1001,"gid":1001,"cwd":"/home/vinu/Projects/nodebb","execPath":"/home/vinu/.nvm/versions/node/v13.1.0/bin/node","version":"v13.1.0","argv":["/home/vinu/.nvm/versions/node/v13.1.0/bin/node","/home/vinu/Projects/nodebb/nodebb","setup"],"memoryUsage":{"rss":116781056,"heapTotal":77598720,"heapUsed":46246752,"external":21839905}},"os":{"loadavg":[1.68603515625,1.951171875,2.74951171875],"uptime":87688},"trace":[{"column":13,"file":"internal/modules/cjs/loader.js","function":"resolveExportsTarget","line":545,"method":null,"native":false},{"column":14,"file":"internal/modules/cjs/loader.js","function":"applyExports","line":459,"method":null,"native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"resolveExports","line":508,"method":null,"native":false},{"column":20,"file":"internal/modules/cjs/loader.js","function":"Module._findPath","line":577,"method":"_findPath","native":false},{"column":27,"file":"internal/modules/cjs/loader.js","function":"Module._resolveFilename","line":879,"method":"_resolveFilename","native":false},{"column":27,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":785,"method":"_load","native":false},{"column":19,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":956,"method":"require","native":false},{"column":18,"file":"internal/modules/cjs/helpers.js","function":"require","line":74,"method":null,"native":false},{"column":17,"file":"/home/vinu/Projects/nodebb/node_modules/autoprefixer/lib/autoprefixer.js","function":null,"line":5,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":1063,"method":"_compile","native":false}]}

```

Then I checked my node version I was using. It is v13.1.0

As per the documentation I stiched to node v14.15.0(using NVM) & executed the same command ```./nodebb setup```. Everything start works fine.

**Comment by barisusakli** [comment]
Supportee versions are even releases ie node 10, 12, 14
