### ISSUE TITLE
Issue on SSO Github2 plugin after migrating to 1.15

### ISSUE THREAD

**Issue by olivierlambert** [NodeBB/NodeBB#8871]
- **NodeBB version:** 1.15.1
- **NodeBB git hash:** 2790a3a3fe23e314844759744b5037d8cc66a2b4
- **Installed NodeBB Plugins:** 
```
Active plugins:
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-custom-pages (installed, disabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, enabled)
	* nodebb-plugin-github-embed (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-ns-awards (not installed, enabled)
	* nodebb-plugin-poll (installed, enabled)
	* nodebb-plugin-prometheus (installed, enabled)
	* nodebb-plugin-question-and-answer (installed, enabled)
	* nodebb-plugin-shortcuts (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, disabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-plugin-sso-facebook (installed, disabled)
	* nodebb-plugin-sso-github2 (installed, enabled)
	* nodebb-plugin-sso-twitter (installed, enabled)
	* nodebb-plugin-sso-wordpress (installed, disabled)
	* nodebb-plugin-tenor-gif (installed, enabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

```
- **Database type:** redis
- **Database version:** 3.2.12
- **Exact steps to cause this issue:**
1. Update to 1.15.1
2. Lost GitHub login
- **What you expected:**
Ability to login with Github account
- **What happened instead:**
No more login with Github, and error message in the logs:
```
2020-11-12T14:10:43.974Z [4567/108232] - warn: [plugins] Unable to load library for: nodebb-plugin-sso-github2
2020-11-12T14:10:43.974Z [4567/108232] - error: Error: Cannot find module './user'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at /usr/share/nginx/html/forum/node_modules/nodebb-plugin-sso-github2/library.js:4:27
    at Object.<anonymous> (/usr/share/nginx/html/forum/node_modules/nodebb-plugin-sso-github2/library.js:188:2)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by julianlam** [comment]
`github2` is not one of our plugins, please use `sso-github` instead, unless you needed the former for something else specifically.

**Comment by julianlam** [comment]
@revir Why not PR your changes into sso-github :wink:

**Comment by julianlam** [comment]
https://github.com/revir/nodebb-plugin-sso-github2/pull/1

**Comment by olivierlambert** [comment]
Thanks a lot for the fast answer. I indeed switched to the other plugin, and it works well :+1: 

Keep up the good work!

**Comment by revir** [comment]
Oh, I am so sorry. I will do it soon.

**Comment by revir** [comment]
PR sent, hope it'll work.
