### ISSUE TITLE
When I started running in cluster mode, an error occurred

### ISSUE THREAD

**Issue by haig233** [NodeBB/NodeBB#8910]
- **NodeBB version:** v1.15.2
- **NodeBB git hash:** ce5c0ee6e70db95934f18e4fcf26132afe3c88d3
- **NodeJS version:**14.15.1

- **Installed NodeBB Plugins:** 
```
Active plugins:
	* nodebb-plugin-composer-default (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, enabled)
	* nodebb-plugin-markdown (installed, enabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, disabled)
	* nodebb-plugin-spam-be-gone (installed, enabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-lavender (installed, disabled)
	* nodebb-theme-persona (installed, enabled)
	* nodebb-theme-slick (installed, disabled)
	* nodebb-theme-vanilla (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

```

- **Database type:** mongo
- **Database version:** 4.0.10

When I started running in cluster mode, the following error occurred:
```
2020-11-18T23:13:56.109Z [4567/25970] - error: {"eventName":"meta.rooms.enter","params":{"enter":"admin"}}
Error: [[error:invalid-session]]
    at validateSession (/www/wwwroot/bbs/src/socket.io/index.js:181:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async onMessage (/www/wwwroot/bbs/src/socket.io/index.js:129:3)
2020-11-18T23:13:56.528Z [4567/25970] - error: {"eventName":"meta.reconnected","params":null}
Error: [[error:invalid-session]]
    at validateSession (/www/wwwroot/bbs/src/socket.io/index.js:181:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async onMessage (/www/wwwroot/bbs/src/socket.io/index.js:129:3)
2020-11-18T23:13:56.528Z [4567/25970] - error: {"eventName":"admin.analytics.get","params":{"graph":"traffic","units":"hours"}}
Error: [[error:invalid-session]]
    at validateSession (/www/wwwroot/bbs/src/socket.io/index.js:181:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async onMessage (/www/wwwroot/bbs/src/socket.io/index.js:129:3)
^C

```

**Comment by barisusakli** [comment]
Those errors are normal after a server restart, they shouldn't happen after you refresh the page and get reconnected again.

If you are running in cluster mode setup sticky sessions on your load balancer.
