### ISSUE TITLE
nodebb upgrade error from v1.14.3 to v1.15.3

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#8990]
3. Checking installed plugins for updates...  OK
4. Updating NodeBB data store schema...
Parsing upgrade scripts...
2020-11-28T11:55:58.264Z [60001/17323] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-emailer-ssl-smtp`. Skipping.
2020-11-28T11:55:58.265Z [60001/17323] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-custom-pages`. Skipping.
OK | 4 script(s) found, 99 skipped
  → [2020/10/13] Create verified/unverified user groups...
    [##############] (94/94) 100% Error occurred
Error occurred during upgrade: Error: [[error:invalid-data]]
    at sortedSetAddBulk (/opt/testforum/src/database/mongo/sorted/add.js:34:10)
    at module.sortedSetAdd (/opt/testforum/src/database/mongo/sorted/add.js:12:17)
    at Object.wrapperCallback [as sortedSetAdd] (/opt/testforum/src/promisify.js:48:18)
    at batch.processSortedSet.batch (/opt/testforum/src/upgrades/1.15.0/verified_users_group.js:55:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.processSortedSet (/opt/testforum/src/database/mongo/sorted.js:527:5)
    at async exports.processSortedSet (/opt/testforum/src/batch.js:29:10)
    at async Object.method (/opt/testforum/src/upgrades/1.15.0/verified_users_group.js:42:3)
    at async Upgrade.process (/opt/testforum/src/upgrade.js:157:4)
    at async Upgrade.run (/opt/testforum/src/upgrade.js:107:2)
2020-11-28T11:55:58.337Z [60001/17323] - error: uncaughtException: [[error:invalid-data]]
...

**Comment by barisusakli** [comment]
@awunnenb thanks for reporting, let me know if the issue is resolved

**Comment by awunnenb** [comment]
the issue is resolved, thank you for great support!
best regards, Andreas

**Comment by awunnenb** [comment]
after rebuild and restart nodebb is down :

2020-12-01T08:46:34.366Z [60001/4622] - error: [plugin/iframely] Could not parse embed! Failed to lookup view "partials/iframely-widget-wrapper" in views directory "/opt/testforum
Dec 01 09:46:34 mail nodebb[4540]: (node:4622) UnhandledPromiseRejectionWarning: Error: Failed to lookup view "widgets/populartags" in views directory "/opt/testforum/build/public/templates"
Dec 01 09:46:34 mail nodebb[4540]:     at Function.render (/opt/testforum/node_modules/express/lib/application.js:580:17)
Dec 01 09:46:34 mail nodebb[4540]:     at Function.<anonymous> (/opt/testforum/src/webserver.js:11:63)
Dec 01 09:46:34 mail nodebb[4540]:     at internal/util.js:297:30
Dec 01 09:46:34 mail nodebb[4540]:     at new Promise (<anonymous>)
Dec 01 09:46:34 mail nodebb[4540]:     at Function.renderAsync (internal/util.js:296:12)
Dec 01 09:46:34 mail nodebb[4540]:     at Object.Widget.renderPopularTags [as method] (/opt/testforum/node_modules/nodebb-widget-essentials/library.js:230:26)
Dec 01 09:46:34 mail nodebb[4540]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Dec 01 09:46:34 mail nodebb[4540]: (node:4622) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by

**Comment by julianlam** [comment]
Run `./nodebb build`

**Comment by awunnenb** [comment]
thank you, it works. is ./nodebb build not the the same as  build/restart from admin panel?

How can i upgrade only to stable versions in future? The last month i always get beta versions 1.15.x.beta.
What is the correct way to only get stable versions?

my upgrade script looks like this:
...
git fetch
git reset --hard origin/master
./nodebb upgrade
...

is there a better rsolution?

**Comment by pitaj** [comment]
Don't use the master branch. Use versioned branches like `v1.15.x`

**Comment by awunnenb** [comment]
thank you, but how do i know, which exact nodebb version ist stable or beta?

**Comment by pitaj** [comment]
All versioned branches are stable.

**Comment by julianlam** [comment]
For a short while v1.13.x contained prerelease/beta versions, but that has been reset now.

**Comment by awunnenb** [comment]
ok, thank you all for your great support!
