### ISSUE TITLE
Upgrade from version 1.15.x to 1.16.x got error 

### ISSUE THREAD

**Issue by mysterydata** [NodeBB/NodeBB#9125]
hi got error after upgrading to 1.16.x branch please solve this asap.

```
NodeBB v1.16.0 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 2 process(es).

2020-12-18T06:49:34.972Z [4567/10432] - info: Initializing NodeBB v1.16.0 http://forum.domain.com
2020-12-18T06:49:35.071Z [4568/10438] - error: Error: [[error:redis-required-for-pubsub]]
    at get (/home/domain/web/forum.domain.com/nodebb/src/pubsub.js:51:9)
    at Object.on (/home/domain/web/forum.domain.com/nodebb/src/pubsub.js:63:3)
2020-12-18T06:49:35.073Z [4567/10432] - error: Error: [[error:redis-required-for-pubsub]]
    at module.exports (/home/domain/web/forum.domain.com/nodebb/src/cacheCreate.js:58:9)
    at get (/home/domain/web/forum.domain.com/nodebb/src/pubsub.js:51:9)
    at Object.module.exports.create (/home/domain/web/forum.domain.com/nodebb/src/database/cache.js:5:9)
    at Object.on (/home/domain/web/forum.domain.com/nodebb/src/pubsub.js:63:3)
    at module.exports (/home/domain/web/forum.domain.com/nodebb/src/database/mongo/hash.js:6:36)
    at module.exports (/home/domain/web/forum.domain.com/nodebb/src/cacheCreate.js:58:9)
    at Object.<anonymous> (/home/domain/web/forum.domain.com/nodebb/src/database/mongo.js:185:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.module.exports.create (/home/domain/web/forum.domain.com/nodebb/src/database/cache.js:5:9)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at module.exports (/home/domain/web/forum.domain.com/nodebb/src/database/mongo/hash.js:6:36)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Object.<anonymous> (/home/domain/web/forum.domain.com/nodebb/src/database/mongo.js:185:24)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[cluster] Child Process (10432) has exited (code: 0, signal: null)
[cluster] Child Process (10438) has exited (code: 0, signal: null)
```

**Comment by mysterydata** [comment]
```
2020-12-18T06:57:57.278Z [4567/11314] - info: Initializing NodeBB v1.16.0 http://forum.domain.com
2020-12-18T06:57:57.371Z [4567/11314] - error: Error: [[error:redis-required-for-pubsub]]
    at get (/home/domain/web/forum.domain.com/nodebb/src/pubsub.js:51:9)
    at Object.on (/home/domain/web/forum.domain.com/nodebb/src/pubsub.js:63:3)
    at module.exports (/home/domain/web/forum.domain.com/nodebb/src/cacheCreate.js:58:9)
    at Object.module.exports.create (/home/domain/web/forum.domain.com/nodebb/src/database/cache.js:5:9)
    at module.exports (/home/domain/web/forum.domain.com/nodebb/src/database/mongo/hash.js:6:36)
    at Object.<anonymous> (/home/domain/web/forum.domain.com/nodebb/src/database/mongo.js:185:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2020-12-18T06:57:57.374Z [4568/11320] - error: Error: [[error:redis-required-for-pubsub]]
    at get (/home/domain/web/forum.domain.com/nodebb/src/pubsub.js:51:9)
    at Object.on (/home/domain/web/forum.domain.com/nodebb/src/pubsub.js:63:3)
    at module.exports (/home/domain/web/forum.domain.com/nodebb/src/cacheCreate.js:58:9)
    at Object.module.exports.create (/home/domain/web/forum.domain.com/nodebb/src/database/cache.js:5:9)
    at module.exports (/home/domain/web/forum.domain.com/nodebb/src/database/mongo/hash.js:6:36)
    at Object.<anonymous> (/home/domain/web/forum.domain.com/nodebb/src/database/mongo.js:185:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[cluster] Child Process (11314) has exited (code: 0, signal: null)
[cluster] Child Process (11320) has exited (code: 0, signal: null)
```

**Comment by barisusakli** [comment]
`error: Error: [[error:redis-required-for-pubsub]]`

Setup redis if you are using clustering. See 1.16.0 breaking changes [here](https://community.nodebb.org/topic/15178/1-16-0-breaking-changes)

**Comment by mysterydata** [comment]
thanks, solved. This are totally major changes.
