### ISSUE TITLE
Mongodb issue while upgrading 1.15.x -> 1.16.x

### ISSUE THREAD

**Issue by fgallese** [NodeBB/NodeBB#9126]
While upgrading the forum, the db upgrade script failed due to a mongodb error `Index key too large to index`:

```
OK | 1 script(s) found, 103 skipped
  → [2020/12/11] Migrate existing topic thumbnails to new format...
Error occurred
    [#            ] (163/917) 17% 2020-12-18T12:06:14.382Z [4567/9] - warn: NodeBB Setup Aborted.
 MongoError: Index key too large to index, failing 12418 { : "topic:415:thumbs", : "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAPEhUQEBAWFRUVFRYWFhUVFRUYFRYVFRcXFxUWFRUYHiggGRslGxYVITEhJSkrLi4uFx8zODMtNyotLisBCgoKDg0..." }
    at Function.create (/usr/src/app/nodebb/node_modules/mongodb/lib/core/error.js:57:12)
    at toError (/usr/src/app/nodebb/node_modules/mongodb/lib/utils.js:123:22)
    at /usr/src/app/nodebb/node_modules/mongodb/lib/operations/common_functions.js:379:39
    at handler (/usr/src/app/nodebb/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
    at /usr/src/app/nodebb/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
    at handleOperationResult (/usr/src/app/nodebb/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/usr/src/app/nodebb/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (/usr/src/app/nodebb/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/usr/src/app/nodebb/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
```

So I disabled that in mongodb:

`db.adminCommand( { setParameter: 1, failIndexKeyTooLong: false } )`

And on the next try, I got a different error, but this time the migration was marked as done:

```
→ [2020/12/11] Migrate existing topic thumbnails to new format...
(node:9) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, stat '/usr/src/app/nodebb/public/uploads/files/data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAPEhUQEBAWFRUVFRYWFhUVFRUYFRYVFRcXFxUWFRUYHiggGRslGxYVITEhJSkrLi4uFx8zODMtNyotLisBCgoKDg0OGxAQGi0mHyAtLS0tKy0tLS0tLS0tKystLS0tLS0tLS4tLS0tLS0tLS0tLS0uLS0tLS0tLS0tLS0tLf/AABEIAOEA4QMBIgACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAAABgcBBQgEAwL/xABREAABAwICBQYHDAYIBQUAAAABAAIDBBEFIQYHEjFBEyJRYXGBFBcyVHOhsyMzNUJSYnKCkZKT0hVTsbLB0Qg0Q1WElKLTJGODo8IWJUR08P/EABsBAQADAQEBAQAAAAAAAAAAAAABAgQDBQYH/8QAMxEAAgIBAgMGBAQHAQAAAAAAAAECAxEEMRIhUQUTFDJBsRUicZEGM1JhNEJTcoGhwSP/2gAMAwEAAhEDEQA/ALqREVSoRLJZAEREICIiAIiIAiIgCIiAIiISEREAREQBERAEREAREQBERAEREAUO1j6Xy4SyB0ULJDK9zCHuc0DZbtXyBUxVV6+ve6L00ns1euKlJJkN4WTV+OSt8yg/Fk/KnjkrfMoPxZPyquQs2Xo+Fr6GbvZFi+OSt8yg/Fk/KnjkrfMoPxZPyqurJZPDV9B3sixfHJW+ZQfiyflTxyVvmUH4sn5VXVksnhq+hHeyLF8clb5lB+LJ+VPHJW+ZQfiyflVcr8PkDcyQO3JPDVbjvZFk+OSt8yg/Fk/KnjkrfMoPxZPyqCYbhVXVf1almlHBzIzsffdZvrUhpNWeMSZ+Dxx+lmaD3hgcuUoadF07H6G7brjrSbeBQfiyflXoGtms80g/Ek/ktbDqjxPIumpW57g6V3r2AvvJqsxQeTLSu7XzN9fJlYNVuu5PZ7O8Hwvxec55Yzsezxt1nmkH4kn5U8bdb5pB+JJ/JaSq1fYvGL+Csk9FMwnuD9laGvoqim/rNNND1vjds/fF2+tZHK9Hs1UdkWbS+7a9yc+Nus80g/Ek/knjbrPNIPxJP5KvmSB2bSD2G6/S5eIsN67F0TWUn9yf+Nus80g/Ek/KnjbrPNIPxJPyqAIniLB8D0f6X92T/wAbdZ5pB+JJ+VPG3WeaQfiSflUARPEWD4Ho/wBL+7J/4263zSD8ST+Sx42qzzSD8ST8qgKBPEWD4Ho/0v7l+aC4/JiVKKmSNsbuUkYWtJI5hte5UhUI1O/B3+In/fU3W9bHxV0VGyUV6NhERScwiIgAVXa+h7lR+nk9kVaIVW6+veqP08nsiulPnRWXlZUgRAi9gxBEKwgF1jauQ0AlzjZrWguc49DWjMrcaLaMVWKSFlO3ZY02kncDybOofLf80d9lcVDg2FaOQeESuAdudPJzpXutfZYALjcea1ZbdSo8ludoVN82QHRzVVW1Vn1bvBYz8UAPnI7PJj77nqU7i0cwLBWiWYRNdwlqXB8hPHY2t31QFoKHWVWV1S2Slpmw4fE/3eoqCGAs3E7Z5rSN4aLk2F7LV6ydH8Qdigro6JtdAY2NYx/OjbzbbJbtDjdw4HaWGdkpPmzSopbFh4lplCKGStw9orRG5reThJ2ruc0WIDSRYOBtbcq7brSxqrqPAqTD4o57E8nLtbbQBtG+2WgZG6zq70jnoMQZhlRhkVKajP3MODwbOLC4lztoZEdS/ekkRpdK6aZrXWmbEXEA/HY+nN/sCoSSXT/Tuowumpo2xNdW1DRzTmxjgGh5sPK57rAXUel06xrCJ4f0zFE6Cf40YG0zdtZt4tvctIz4FbDXVo5VSvpcRpIzK6ldzo2gl1muD2ODRmQCCDbpCjGlFfXaUy01LDQSwRxkukfIHbLS6wc7aIAAABsN5JQF9Ag2I3HMHqUNxzWThtFVuoapzmlrWlz9jajBeL7LrXINrHdbNS2WRkEZc42ZEy5J4NY3M/YFQmreKixSurq/EzCWuBLY5nNHvhJ2gCfiMaBcbrqECzqjRLBsWZ4RA2Pnf29K4MN/nbORPU4KCaQatq6lu+nPhUQzsAGztH0PJf3WPUvhqVqWQVeJSRvLaGJjnbTidkNbIeTcSeOwHda9mD6638tI6qpT4I6UtjljadqMZbLX8HHZ5xAseoqsq4y3Rp0+ruoea5Y9vsQljwbjcQbEEEOaRvDmnMHqK/SurFNH8Nx6EVML27ZFmVMNtsEfFkHxgOLXbupVJj+BVOHS8lVNFnH3OVt+TkA6CfJd80+tYraHHnHY+r0HbUL/AJLeUv8ATPAiIs57YQIgUkoubU78Hf4if99TdQnU78Hf4if99TZepHZH5pqPzZfV+4RECscQiyiAwFVuvn3qj9PJ7Iq0gqu19e9Ufp5PZFdKfOvqVl5WVGEQIvYMRgqSaC6Gy4tKcyymjdaWUb3HjHGfldJ4dq8Giuj0uJ1LaaMlrbbU0g/s4+r5x3D7eC6OwrDYaSFlPAwMjjADWj9p6Sd5Kxam/HyxO9Vf8zIppTpTRaP07KeGIGS1oKaPeb5Bzt5Avx3k9KiuF6Rv0jbVYRiNKKeYR8rGbOBY9pGztNdmCC5vaHHv8mtfRipoKsY7Qku2XB8odz+TcMtqx3xkZEfFvw4ajA9CnY7TSYlHiBdiDpCXtPMaxwyawkc4c0CzhluHBYTUROjljhc6kxY1D20ri2KjjNmulL3bQLvijO9wCSHZKz8P0Xrcdpga9j6BsLm+CCMnKIAWbJE43u3ZaQ8kOzPBbeqioMGDKuv2anETG1peGjbeWCwcGnJuVgZDmbBQLH9P62tLtshsfxYWlwZb/mWIMh7eb81dYUznsjnKyMSWYdSYLgUjqyorJKypHMMh2pXMJFtkbNw1xGXOdff1rz4jrwYCTTYdI/htSODMuxocbdSrmorZZQA+QkDc3cwdjBZo7gvPZaVo+rOTv6Imc2vetByooW9RMhP8F9KfXxV73UETh817x681BnQtJBIzG5fKWjY7O1uz+Sq9I/Rkq9eqLcoddlFMCyso5GNcC19tmWOxyIIyJHcvoNBtG8Ws+lcYnOaHBkTjG4tO48jIMhvzAsqcdh7DvvbovYepSHDtIpYQxkgE8LLWilzDQBYcm/yoyMrFpG5Q9JLHInv4k11laMy4dhgo8KpXmB7y+qkadqV2zbZDwMy0nMkZANA4lRjQWidJsRYbWRyslLBV0FY1o6BJIxm57Rvu0hwsFcNKyspmNlgc6rp3Na7kZXDwljXAH3KU5SfRfnv53Bayq0dpKsS4hhbY4q7YexsjmlvJyuFncpF8SW1xci42r2KyHbJG9I9L24VJDg+BQNfIJbyMF3DacbmIEm+0b5uJ5oA7rPxDDI62n5Crha5r2jbZe4DrXOy617g7nZKmdTvg9BXy02Ixvjr3u2Y3yZtIdva0/Kcc9r4wyB6b3QZOe9LtGJcLlDHkvhefcZun/lyW3PHr+1aZdH41hMNZC+nnZtMeLEcQeDmng4HMHqXP+PYNLh9Q+lmzLedHJwljO5/bwI6QsV9OPmR9b2N2n3n/AIWvn6Pr+x4ECIFlPo0XNqd+Dv8AET/vqbqEanfg7/ET/vqbr1I7I/NNR+bL6v3CIiscQsoiAwFVuvr3mj9PJ7Iq0gqu19e9Ufp5PZFdKfOisvKyolh5PAEkkAAbySbADrJsFlTPVHgXhddyzxeKkAf1GZ3vQ7gHO+6vUunwRbMkI8TwWnq70XGGUoY4Dl5LPncOLyMmg/JaMh39KlCIvHby8m0/MsTXgtcAWuBBBFwQciCFCqfDYMLcaHCYGipnJke913NgjubSSnfsi5DI/jHqu5bzTHSOLDKSSqlz2RZjOL5D5DR3+oFU3q51r8jPK3EQC2ok5R07RzmPNgA8bzGAAB8myYJP3ppoxVtqzGymklJaXcqC6R02ecj+DDc+SAAOC8NLoPWlplqGilhbm6Wc7IA42Z5Tj1cVe0+MsNm04E73NDmhjhsBrtz3vFw1p7yeAKrrWlXSRs5FzhJI8HlJLFscIsHCGEbtpwDr3u4jqNhsqvm8QRwnXFfMyrHgAkA3AJANrXAORtwWFgLK3mYIiwSpBkrfaG4D4ZMHSNcaeItdO5rS6zb7iBnY2ztuFzuXk0bwObEZvB4C0O2XPu42ADbdHWQO9XVq00Wkw2B4mtysr7vAN2hrbhgB7Lnv6lnvt4ItLc6VwyyWUzmOY0xkFmyNktts7NsrW4LTY5gsjn+F0bhHUtFjtX5Odg/spwN46H72ndcXB9EuHPhcZKSwubvgdlE8neW/q3npGR4jiPjXaV0lPC+eok5IR5PY/KRruDdje4nha4PAryzWj8YX4JXvZVPp2ippy6Mh4HKwPI5zCesG4O4h1xvW+XPL9brzibaxsIZT2ET2D3ySHaJDpCN723JA4XcOJXQNLUMlY2SNwcx7Q5rhuLXC4I7kJZ9VE9Y+jH6QpiYwOXhu+E9Py4z1OAt22KliKP2JhOUJKUd0cwRv2gD09O8HiD13X6Ck+snBPA65zmC0VSDK224SXAmb9pDvrFRhebZHglg/RdDqVqaI2L/P19S5tTnwd/iJ/wB9TdQjU2P/AG0f/Yn9oVN16S2R+e3/AJsvq/cIiKTkEREACq7X171R+nk9kVaKq7Xz71R+nk9kV0p86Ky8rKhcVfeqPCfBsNieRz6i9Q7ptJ72D2MDFQzKczOZCN8r2RD/AKjg3+K6pp4RGxrG5BrQ0DqaLD9i062XNI5ULk2fREXjxrEG0tPNUP8AJiifIfqNJt6lhO5z/r30mNVW+CMPuVKLEDcZnC7z3Cze4qsAV9auodK90rzdz3Oe49LnEkn7SvkArljpvUm9keDRPdZo2p3OcbAZSOzceyyqjSbHpa+Z0khs0E7DB5LW39ZPE8VMNHYZZNF2shttGVwIzu4GoPMb84nZHeq5c0tJBFiDYjoIyIW3SQXORlvlzwEX3oqKad2zDE+QgXIY0usOk23LwuqWBxYXc4XuOzeO3IrW5Jbs4pN7I+k0gaC47gre1ZaF0MsTK10ralzmghgsY4nEZtc3eXDdn9ioKtxB0mW5vR09q9+iulNXhkompZNm/lsOcbx0Pb/HeFhuvcuUdjTCnHNnWNBgtLTuL4II43OaGksaASBmBkveodoFrDpMXbstIjqALvgcc+sxn47fWOIUxWNnUKk/6SYFqI2zvPnxyEVv2q7FSX9JN39Sb6c+yRBFI7S6A/o/aTGaCTD5HXdBz4r8YnHNo+i71OC5+Us1X40aLE6aS9mueIn/AEJTsZ9hId9VWZY6wQIiqVIRrewzlqAzNHOpnCYfQ8mUfcJP1VTF10vXUrZo3wuF2yMcwjqcCD+1cywsLQGO8pl2O+kw7J9YWTVLZn1H4cu89T+q9n/wuvU58Gj09R7UqbWUJ1OfBrfT1HtHKbXWpbHzd35kvqwiIpOYREQBVdr3aTFR2z93f7JytFVpruHuVJ6d/snJxuHzL0O2nqVtsa3tJpfcrjQalL8TomkZcvtfhse/wAV0kqB1eNH6VpL8HTH/sSD+Kv6yd87lxy3O+v0kNJc6obIKEa6awxYRUWOb+Tj7nSNv6gVN1DNa2Dvr6SKjY8MM1TG3acCWizXuFwOsAd6IxI5XK32hejE+KVLaaEWBzkf8WOMeU49fADiVYXiEq/PYfuPVlartGYcOow1mcr3O5d53mRjixzB0NaWkAd/FTknJ6f/AEVTQ0opqUGIsaNhwe4Xe0hwdIBk47QvmCqZ09wgUVbLC1+0DaS5ABHKc4ggAC977l0ctTj2jdJXttUwtceD9z29jxmu1F3dy57HKcOJHOWI6VVDYP0bRtMEdrzvuOUmeQC4uePJj3WaOG/oUOil2DuHEX9WRVla3MCiwuqjZFHaCeIEc4kh7DsyAk9RYe8quqqnJeQxuWVug9d1MsP5ostHlyZ8Xhlrgm9/Jtw7V8Svc7CpegHvXmngcw2cLKsoSXNospJ7MUtQ+JzXxuLXNN2uaSHAjcQRuXQGqjWFW4i19NJAJZYmh3LlwY0tJt7rYE7X0RnY7lz0uif6PuDcjQyVRHOqJcjx5OK7W/6jIubJZPvAaiT36pLR8iAbAt0GQ3ce0bKj+nWgFPiFI6KJgZO3nxSEkuLwN0jySXNIyz6jwU0RVIycVVlK+F7opWFr2OLXNO9rgbEFfOJ5aQ5psQQQegg3BXQWtfV1+kKiKWjLGVEjXcqH3DHMjAtISAbOBc1u7O46FBJtSeLNBdenNgTlKeG/e0K2Sx0Vh1RysUcvy2Md95oP8V6FqdEiTQ0l9/g0Ps2rbKpUBc36TsbDXVkd91TK78Q8p/5rpBc36wxbFK30rPXDGrQpjc+CRo02ts0cnZBLOMcy2dTZvhot+vqPaFTdQbUt8Ft9NP7VynKq1h4OEpcT4uoREQgWWVhEACrXXd73Senf7JysoKtdd3vdJ6d/snKlnkZr0H8TX/cvcg2gsmzilEeHKvb96CVo9ZC6DJXNFBVchPBP+qnieT80PAf/AKSV0vdc9O8wN/b0HHVt9UgtHpfcRRSAe91dK8/RMzGPP3XlbxeLGqI1FPLCDYvjc1p+S63NcOw2Pcu54p7StZR+5VMsfCUCdnaLRygfZG7teV9sEr/CaeKe1i9gLm8Wv3PaesOBHcvhjnufJVH6mQbXopOZJfqF2v8AqISbRERCpW2vnB/CMO5cC7qaRr8t+w/mP7s2n6qoHBonF21fmi4+3o9S67xmgbVQS07/ACZY3xnseCL9179y5Yo8Nnga5skEjWtcRyhY7k3Z2Ba+1j1dK76bDmskWZUeR9bL5zQteLOFwvqEXqNZ5MxGgrqKzw2MEl1gGjM3JsB3ldc6M4WKKkgpR/ZRMYetwHOPe65XMrTskOGRFiCN4INxn2qaaH6dYhFPHE6R1QyRzI9h93EBzgCWHfcAnfdYrdK+bTNEbtky+UReevqhDE+U7mMc63TYXsO05d6wHc8eH+6TzzcG7MDPqc6Qj679k+jX70kq+QpKib5EMjrdJDDYDtNgvrg9KYYWMd5VrvPTI87Uh73OcVrNLvdBBSA51FRHteihPLS9xDA364Ukm1wqm5GCKL5EUbPutA/gvUhRCAua9O5dvE61w/Xlv3GMaf2LpNzgMzuGf2b1ytV1XLyyz/rZpZe6R7nD1FadIszOVz+UvHUt8Ft9PUe1KnKg2pb4Lb6ao9qVOVnluzqERFACIiABVrru96pPTv8AZOVlBVrru97o/Tv9k5Us8jNeg/ia/wC5e5VNRGHtLTxBH2roLQbFfDKCnnJu4xhsnpI+ZJ/qaVQBVh6mcY2JZqB5yf7vF9IWbM0dfkO+8s2llzcT6L8RafihG5enJ/52LaREWw+SNBhd6Wqlpj73OXVEHQCSBUR/fIk/6ruhbmuYx0b2y22C1wffdskWdfqtdeHSLC3VMQ5N+xNG4SQSWvsStva44tcCWuHEOKoLWnrBrauR9C6M00cZ2ZIr857wBtbbuLL7gMiLFESXHovp3h9QxsXhsRmZeN207Z2ywlu20usHB1toW+Upc2xFwbjpC4kBW7wXS2voj/w1XKwfJ2tpn3HXHqU4GDqrFHmd/gjCQLAzuBtsxndGD8p+YyzDbnI2XpxPC4qiB1M9o5N7NiwA5o4bPRbK3Yohqh0pZiNI7at4Sx5NRnm9z/Jl7CBa24bNtwCnijZkM55000Knwstc54kie4ta8ZEG1wHjgbA7ssiowr81tUvKYbKQLmN0cncHhrj91xVBL1dPY5wyzHZFRlhGVP8AUpSNfWySObfk4btPyXOcG5ddtpQnCaLwieKDa2eUkYzate204C9u9TzS2vptF9hlA4vqpR7oJTtNEViA5zRax2rEdjuCrqbEo8Pqy1UW5ZLovbMqL4rpJRS1EFA2qic98oc9geCdmIGQNyyuXtYLcRdc34/pziVfcVFU8tP9mw7EY6tltr991Ho3kEEEggggjIgjcQelebg1nbSjuDkVdVLWb44g6mgPTZ16mQdRe1jB6I9KrjVvp1iGJxOw0hxlDQPDBb3OE5Pc+++S2TTncnPcSrhoKOOCNkMTdlkbQ1rRwAFgoB90CIhBGtY+LeB4dUSA2c5nJR+kl5jfsvfuXObGBoAHAAfYrM1343yk8NCw5QjlpfpuBEQPY3aP1gq2K9DSQxFvqZ7nzwXrqW+C2+mqPalTlQbUt8Ft9NUe1KnKwS3ZoCIUUAyixdZQGFW2u1nuFK7oqCPvRP8A5KyVCdcFKX4c54FzDLFJ9XbDXH7Hn7FWSzFo0aSfBfCT9Gvcpgr6UlZJTSx1EPvkLg9o4G3lMPU5t296+aLzItxeUfod1MboOEtmjo/A8UjrII6mE3ZI0OHSL72kcCDcHsXuVI6s9KvAJjTTOtTzuyJOUUx49TX5A9Bt0lXaCvThJSWUfnmq009Pa65+hlV7rU1dtxRnL04DapjcjuErR8R56eg925WEl1YznFVbSSQPdFKwsew7LmuFi0jgQvgurtO9X1Ji7bvHJzAWbOwDa6mvHx2/rrnvS7QCvwskzRF0XCaO7oyOF+LT2q2Sx59BdJ5MLq2VLLlt9mVny4j5Q7eI6wuqaTHaSVjZWVMRa9oc272g2IuMrrkDCMPfVTR08flSyMjbxzeQLnqF79y7BwzCYKaKOFkbdmNjWDmi9mgDNQyGebF6qknglhfPEQ+N7SOUZndpHSuaAuq/Bo/1bfuhUnre0ebS1DaiGO0ct9rm8zlrlxzvvcL5dRWrSTw3HqZ7o8smt0NlpqJr8VqJGHwcODKc3Ejp3AcmW8CMznw7lWmOYtNWzvqZ37UkjruPAdAaOAAyA6l0jplhEWIYK8QBrtmBssRZnd0IDrNcczk1zc+lcwAE5Ab1ysm5yyztXFJGFudF9HanEp209Mzacc3OPksbxc88ApXoVqlrq/ZknBpoMjtPb7o4fMjPT0n1roHRnRulw2EQUsQaPjO3veflPdxK5tlsnl0I0TgwmnEEXOcbGWQjnSPtmeoDcBwCkSwiqQFrtI8ZioKeSqlPNjbe3Fzjk1g6ySB3rYk9KoPWfpb+kZ+QhdemgcbEbpZRkX/AEW5gdJuehXqg5ywiJS4VkiNZVyVEklRMbySvL39p+KOoCwHUF8l+rL8yOsCejNeukorCMTbbL41MsthUZ+VLUH/ALzx/BTdR7V3RGDDKSMix5FjnD50g2z63KQrxpbm4IiKAEREAXjxmgbVU81O7dLG9h+s0i/rXsRAcwMY5t2SCz2EseOh7DsuH2hfpTLWvgZpqvwlo9zqt/Q2dozH1mgHtDlDbrzLYcMj9D7P1K1GnjP1xh/Uw9gIIIuDvVl6tNObbNBWyZ5Ngmd8YbhFI75Y4Hjlx31qvzIwOFiLhTVa4P8AYp2j2fDV14fKS2Z1AsKoNCNYzqYNpsQcXR7mVJzcwcGzWzI+f9vSrC0rmqJaGY4dsyTPjIiIc0Czsi5rtxIbcjrsvQjJSWUfC36eyibhYsMpPWBrIq/0k+SgncyKm9yFs43kO57ntORBcLDqGW9WxUac0tJBSNxORjJqiJjnta0ljS5oJLhnstubZ/wKovSPAXYXQ0sc8ZFRUzPmkY7eIoeZHGbdJe9x7R0LzaTYdVz1MTagl9bVFrjFwia+whjI+KbZ2+K23Wr4OZfg0Hwuoeyuo7Qyi7o56YttcggnZILDvPBbMU2KxHm1FPO3olifG89r43Ef6VTWI0T6fGaDCaSZ7W07aeOTYe5u04uM87js8SHH1KX6ydNq2kxSloaKQDlGx7bXMa4F00pa3fmLAcOlRggnBrMUH/wqd3ZVOH7YlrsaocQr4nU89FSiN1szUSOcCNzhsxixHaq+g1uVcGKyU1W6PwVtTLCSGBrmNa8sa8u6rAnqutozS7Ep8YrMOjnAY2KfkLMYbPEQdEdq3OzPFSsrmGsknwLROtpoeQfiWxGAAGxRtuBnufLtWvluA3LEWjGE4FTyVjKZp5FheXv58htuDXO3EmwytvVRaIYVXaSyTtqcTka6JrTsu2nB20XA2YCA2xA4cQvdoeKt0ldo3Uyk8pHI2MuJcGTRWe0tvmGOABt1I228sYPbFjulGKRPxCkcI4GF2zFHsXcGbw0OBLyN3C9jZTnVLp47FonxzgCohtt7IsHsdezwOBuLEdirjQjWBNo+yXD6+lkOw9zmNFmua4+U3PIsJF7jpO9SfUfgNQJarE54jC2ouImEEXDnl7iAfijIA8c0BbyL51NQyJpkkeGtaLuc4gNAG8klUzp7rMdVB1Nh7iyE5Pn3PkG4ti4tb87eeHSphBzeEUbSWWevWlp9ym3h9E/LNtRM0/bDGRx+UeG7fe1YNaALDcsRsDRYCw6l+l6tVSrXIyzm5ML74Zhxq54aVu+aVrD1MJvIe5gcV8FZOpLADJLJiDxzYwYYb7i825Vw7AA2/W5VvnwwZNUcyLiYwNAaBYAAAdQyC/SIvKNYKIiAIsogMIiIDV6S4JFX076aXc8ZOHlMeM2vb1g2/YufcRoJqSZ9NUNtIzo3Pb8WRnS0+rcullHtMdE4MTjDX8yVlzFM0c5hPA/KaeLSuVtfGsep6PZ3aEtJZneL3RQaL249g1Th8nJVbNm5syQe9SfRdwPzTmvEvPlBxeGfc0aiq+PFW8hbXRvSWrw0/wDDvvHe7oJM4z0lvGM9Yy6lqkUxnKLyiuo01Wojw2LJb+F6Z4TiZjbVxMjnY4OY2oa0gPBuDFLuOfYepfTB9XkcOKSYs6d0xftOY14F2SPyLg4b2hnNGWSptzARYi46CMl78Jxyto/6tVSMb+rcduL7jt3dZa4alPzI+b1P4fnHnTLK6Pc3Ol9DW4TjhxYUjqiFzi8FoJsHR8m5pIB2HNztcWOS+Wh8VVjeOjEpKd0cMRD+cDstEbNmJgcQNp21YnvW8w7WxVMsKiljlHF0bjG77jrj1re0mtqgI90gqI/+m14+1hP7F3VsXszyLNBqa/NBla0mjLMRxrE6N1gXCpfG75MolY5juzMgjoJXw1SieLHY46ja5VoliftZkGOMtsT1BoCtmm1g4GHmRrtiQ32neDPa8333ds3Ky/WXgjTtiQl3ym08hdftDbq657GWcZQ5SWCsn0WKYTjVWcMpnSl5fs3Y50exMWyDPIc0kDM8FMtWugdbFVvxXFHDl3h2ywEEgvyc55bkMsg0dK91Xrjw9vvUFRIfoNYPte4KOYnriq33FNSRxfOlcZHfdbYesroqpvZHNzS9S4qimidzpGMOzntOa027zuUO0m1nUNHeOE+EyjLYitsNPz5Nw7BcqmsZ0hra7+tVUj2/qwdiL8Ntge+61rGgZAADqWiGkf8AMzjK5ehudJtKKzE3XqZLRg3bAzKJvRcb3u6z3ALTgLIS62RhGKwjhKTbywhWCVtNGtHarE5OTpWc0Gz5nA8lH03PxnfNHqSc1FZZMYt7Hz0ewSbEahtLBkTnI+2UUfF56+AHE966SwjDYqSGOnhbsxxtDWjjlxPSTvJ6StfojovBhkPIwi7jnJK7y5HdLj0dA4BbxeXda7JZNUIqKwERFyLhERAFlLogMIiIAgREIPhXUcU7DFNG2RjsnNe0OaR2FV7jGqWB52qOodBf4jm8rGPogkOb2XsrJRQ0msNHWu6dTzBtP9iphqgqP7xZ/lnf7qeKCo/vFn+Wd/uq2UCp3cOhp+I6r+o/uVMNUFR/eLP8s7/cTxQVH94s/wAsf9xWyid1DoPiOq/qP7lSO1Q1H94x/wCWd/uKDYrh09HKaepZsyNzFvJe3g+M8R+xdKLTaU6N0+Iw8lMLEZskb5cbuDmn9o3FVlRGSwkadJ2xfTZmcnJeqZz0Stfdb7H8FqMPlMFS3p5OUeRK0cW9Dulu8dma+OiejFRik3JQ81jSOVmIu2Mb7D5T7bh9q19nPuoT4uo/EF0NTOuVbysM82j+CVGIzCnpWXdve835OJvypD+wbypn4na/zqn+7KrY0a0fp8OhEFOyw3ucc3vdxc93EraLpPUzb5M8VVxSKU8TuIedU/3JVjxO4h53T/clV2IqeIs6k8EehSfidxDzun+7KseJ3EPO6f7kiu1E8RZ1HBHoVdo/qdiYQ+vnM9j71GDHF9Y32neoKy6KijgY2KGNrGNFg1gAaB1AL7IucpuW5ZJLYIlkVSQiIgCysIgMosWWUAWEKIAiIgCIiAIiIAiIgCIiA1mkWBQYhA6nqG3a7c4eUx3B7DwcF9sGwqCihZT07AxjBYAcTxc48XHeSV7bogCIigBERSAiIgCIiAIiIAiIgCIUQBZREBhZREBhERAFngiIDCIiAIiIAiyiAwiIgCIiAIiIAgWUQGCiIgCBZRAYKyERAYWURAYREQH/2Q=='
(node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  [##############] (917/917) 100%  OK
Schema update complete!
```

Now the forum seems to be working, but I'm wondering.. is the data fine ?

**Comment by julianlam** [comment]
Good question, I'll take a look

**Comment by fgallese** [comment]
Thanks @julianlam 
Just let me know if you need any test and/or further info from my side.

**Comment by barisusakli** [comment]
`db.adminCommand( { setParameter: 1, failIndexKeyTooLong: false } )` don't do this it could lead to slow queries if plugins are adding very large values.

I don't think thumbs are supposed to have base64 images in them.

**Comment by julianlam** [comment]
Yeah, that's correct, I don't actually know for what reason a base64 image is saved, will have to look into it.

**Comment by barisusakli** [comment]
I am guessing some topics on his forum had a base64 image string in the `thumb` field and during upgrade script those error. I am not sure if the previous thumb implementation even allowed base64.

**Comment by fgallese** [comment]
Actually, I have a theory of how that happened. See.. one or two days ago, I noticed in the admin panel that there was an update available for the composer plugin as well as the markdown and mentions plugins.

So I updated them.

Inmediately after updating those plugins, I started having an awful lot of errors, where for some reason, the forum was trying to access some js `topicThumbs.js`.

I had no idea what was going on, so I started looking into the recent changes of the forum, and I saw that was some kind of new feature or something related to version 1.16, so I guessed that you released a version of the plugin specific for the forum 1.16 and I broke something by using it with forum version 1.15.

So, I just pinned the version of those plugins to the release previous to all this `topicThumbs.js` stuff. And the forum started working again.

Could it be possible that this issue with the long key was introduced while all this stuff happened ?

If I look in the db for this cases and remove them, would I be causing any further issues ?

Thanks.

**Comment by julianlam** [comment]
@fgallese Unlikely, since we don't do anything specific with base64 encoding in the new thumbs implementation.

My guess is you already had them in the database, but they were document _values_, and never used as keys. They are used as keys now, since they're part of a sorted set. The original thumbs behaviour allowed uploading by URL, which would work if you pasted a base64 string in... **I guess**.

I'll research a fix...
