### ISSUE TITLE
Upgrading NodeBB causes error on startup

### ISSUE THREAD

**Issue by me-cooper** [NodeBB/NodeBB#9204]
Ref to: [error: Error: [[error:group-name-too-long]] on NodeBB Upgrade](https://community.nodebb.org/topic/15288/error-error-error-group-name-too-long-on-nodebb-upgrade)

After upgrading NodeBB 1.13.x to 1.16.1 I received following error:

```shell
 → [2020/10/13] Create verified/unverified user groups...Error occurred
2021-01-16T13:12:18.178Z [4567/28540] - error: Error: [[error:group-name-too-long]]
    at Object.Groups.validateGroupName (/home/makesmartnodebb/example.net/src/groups/create.js:84:10)
    at Groups.create (/home/makesmartnodebb/example.net/src/groups/create.js:19:10)
    at Object.wrapperCallback [as create] (/home/makesmartnodebb/example.net/src/promisify.js:48:18)
    at Object.method (/home/makesmartnodebb/example.net/src/upgrades/1.15.0/verified_users_group.js:31:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[cluster] Child Process (28540) has exited (code: 0, signal: null)
```

I changed the value via DB:

```
maximumGroupNameLength: 15
```

to 
```

maximumGroupNameLength: 30
```

I think new groups which were created within the upgrade caused this error.

Those were longer than `maximumGroupNameLength: 15`.

`registered-users` and `unverified-users`

**Comment by barisusakli** [comment]
@me-cooper thanks for reporting
