### ISSUE TITLE
error: TypeError: subClient.subscribe is not a function

### ISSUE THREAD

**Issue by mysterydata** [NodeBB/NodeBB#9231]
I'm using latest master getting this error when starting nodebb
```
2021-01-31T16:38:18.935Z [4568/23186] - error: TypeError: subClient.subscribe is not a function
    at new PubSub (/milkyway/nodebb/src/database/redis/pubsub.js:16:12)
    at Object.<anonymous> (/milkyway/nodebb/src/database/redis/pubsub.js:38:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at get (/milkyway/nodebb/src/pubsub.js:49:12)
    at Object.on (/milkyway/nodebb/src/pubsub.js:63:3)
[cluster] Child Process (23186) has exited (code: 0, signal: null)
2021-01-31T16:38:18.962Z [4567/23183] - error: TypeError: subClient.subscribe is not a function
    at new PubSub (/milkyway/nodebb/src/database/redis/pubsub.js:16:12)
    at Object.<anonymous> (/milkyway/nodebb/src/database/redis/pubsub.js:38:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at get (/milkyway/nodebb/src/pubsub.js:49:12)
    at Object.on (/milkyway/nodebb/src/pubsub.js:63:3)
[cluster] Child Process (23183) has exited (code: 0, signal: null)
```

**Comment by barisusakli** [comment]
@mysterydata thanks for reporting I am taking a look at this

**Comment by barisusakli** [comment]
@mysterydata, please let me know if you experience any issues after updating to latest master.

**Comment by mysterydata** [comment]
all good now thanks
