### ISSUE TITLE
Multiple ports cannot be started

### ISSUE THREAD

**Issue by v3u3i87** [NodeBB/NodeBB#9274]
#error version 1.16.2

##node -v 
v12.16.1

##error info

```text
2021-02-08T05:53:42.527Z [4567/886] - error: TypeError: subClient.subscribe is not a function
    at new PubSub (/usr/local/nodebb/src/database/redis/pubsub.js:16:12)
    at Object.<anonymous> (/usr/local/nodebb/src/database/redis/pubsub.js:38:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at get (/usr/local/nodebb/src/pubsub.js:49:12)
    at Object.on (/usr/local/nodebb/src/pubsub.js:63:3)
[cluster] Child Process (886) has exited (code: 0, signal: null)
2021-02-08T05:53:42.533Z [4568/888] - error: TypeError: subClient.subscribe is not a function
    at new PubSub (/usr/local/nodebb/src/database/redis/pubsub.js:16:12)
    at Object.<anonymous> (/usr/local/nodebb/src/database/redis/pubsub.js:38:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at get (/usr/local/nodebb/src/pubsub.js:49:12)
    at Object.on (/usr/local/nodebb/src/pubsub.js:63:3)
[cluster] Child Process (888) has exited (code: 0, signal: null)
2021-02-08T05:53:42.549Z [4569/894] - error: TypeError: subClient.subscribe is not a function
    at new PubSub (/usr/local/nodebb/src/database/redis/pubsub.js:16:12)
    at Object.<anonymous> (/usr/local/nodebb/src/database/redis/pubsub.js:38:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at get (/usr/local/nodebb/src/pubsub.js:49:12)
    at Object.on (/usr/local/nodebb/src/pubsub.js:63:3)
[cluster] Child Process (894) has exited (code: 0, signal: null)
```

How to start multiple ports correctly?

**Comment by pitaj** [comment]
#9231
