### ISSUE TITLE
using 1.16.2 unable to use api add topic thumbnail

### ISSUE THREAD

**Issue by cjie95731** [NodeBB/NodeBB#9327]
I use the postman tool and tried many times, but I can’t upload thumbnails

I am using 1.16.2. Since the update, I have been annoyed by this problem. The hook of the post cannot modify and return the thumbnails. I tried to modify it using the api, but I have not been able to post.

This problem has been troubled for nearly a week, I have no way, I take the liberty to ask if there is an error in the api

{
    "path": "&#x2F;api&#x2F;v3&#x2F;topics&#x2F;15227&#x2F;thumbs",
    "error": "[[error:invalid-files]]"
}
![image](https://user-images.githubusercontent.com/65453559/109110971-127c1c00-7773-11eb-94cc-f57183328f01.png)
![image](https://user-images.githubusercontent.com/65453559/109111012-20ca3800-7773-11eb-8460-34be0980165d.png)

I am extremely sorry about this question, but I still want to ask, it is very important to me

**Comment by julianlam** [comment]
When did you update to 1.16.2, can you share the results of `git rev-parse HEAD? Thank you

**Comment by cjie95731** [comment]
root@a:/home/bbs# git log
commit 023e4cfcee208a0bae121a6e343a8c53009fd090 (HEAD -> v1.16.x, tag: v1.16.2, origin/v1.16.x)
Author: Misty (Bot) <deploy@nodebb.org>
Date:   Thu Jan 21 00:43:53 2021 +0000

    chore: incrementing version number - v1.16.2

commit 4d6360d2755e29547e660f84d3de3ddace9e67dc
Merge: d7044a5e8 b5cb2f8b9
Author: Misty (Bot) <deploy@nodebb.org>
Date:   Thu Jan 21 00:43:52 2021 +0000

    Merge commit 'b5cb2f8b9c34ff2646ab60c22aa92b674daad64f' into v1.16.x


#git rev-parse HEAD
023e4cfcee208a0bae121a6e343a8c53009fd090

**Comment by barisusakli** [comment]
invalid-files error could be related to this https://github.com/NodeBB/NodeBB/issues/9333, make sure you have the correct dependencies installed `multiparty` needs to be  v4.2.2

**Comment by cjie95731** [comment]
`2021-03-14T05:46:59.153Z [4567/23000] - error: /api/v3/topics/4479/thumbs
Error: [[error:invalid-files]]
    at validateFiles (/home/bbs/src/middleware/index.js:106:15)
    at Layer.handle [as handle_request] (/home/bbs/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/bbs/node_modules/express/lib/router/route.js:137:13)
    at Form.<anonymous> (/home/bbs/node_modules/connect-multiparty/index.js:114:7)
    at Form.emit (events.js:327:22)
    at /home/bbs/node_modules/connect-multiparty/node_modules/multiparty/index.js:610:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)`

multiparty": "^4.2.1" and "^4.2.0" I've tried everything but 
both JPG and PNG files cannot be uploaded

{
"path": "/api/v3/topics/4479/thumbs",
"error": "[[ error:invalid-files ]]"
}

**Comment by barisusakli** [comment]
>multiparty": "^4.2.1" and "^4.2.0" I've tried everything but
multiparty dependency needs to be 4.2.2, try running `npm i multiparty@4.2.2 --save` and restart nodebb.

**Comment by cjie95731** [comment]
```
var request = require('request');
var fs = require('fs');
var options = {
  'method': 'POST',
  'url': 'https://xxxxxxxxxxxxxxxxx/api/v3/topics/2/thumbs',
  'headers': {
    'Authorization': 'Bearer fexxxxxxxx-2c75-4620-ac6f-2c8xxxxxx',
  },
  formData: {
    'files': {
      'value': fs.createReadStream('190eb937b96d38394019a8f4f6cff79f.jpg'),
      'options': {
        'filename': '190eb937b96d38394019a8f4f6cff79f.jpg',
        'contentType': null
      }
    }
  }
};
request(options, function (error, response) {
  console.log(response.body);
});

```

{
"path": "/api/v3/topics/4479/thumbs",
"error": "[[ error:invalid-files ]]"
}

I upgraded the version to 1.17.0 and still can’t succeed. I don’t know why. I post in this way and tried a lot. I really want to ask for help.

**_multiparty dependency needs to be 4.2.2, try running npm i multiparty@4.2.2 --save and restart nodebb._**

I tryed but It can't solve

**Comment by pitaj** [comment]
I think you need to have `contentType: 'multipart/form-data'`

What is the output of `npm ls multiparty` run in your nodebb directory?

**Comment by nodebb-misty** [comment]
Issue closed due to inactivity.

----

*This is an automated message. If you feel this action was in error, please comment on this issue so it can be looked at again*
