### ISSUE TITLE
Email not working

### ISSUE THREAD

**Issue by Moudoux** [NodeBB/NodeBB#9331]
- **NodeBB version:** v1.17.0-beta.0
- **NodeBB git hash:** 9bf94ad50ff9a408adf23357f51dcf403d4580b2
- **NodeJS version:** 14.16.0 LTS

- **Installed NodeBB Plugins:** Default

- **Database type:** mongo
- **Database version:** 4.4.4

- **Exact steps to cause this issue:**

1. Clone repo and run `docker-compose up -d`
2. Set up the forum 
3. Configure email to use a custom SMTP server 
4. Send a test email and check logs

- **What you expected:** It to send an email
- **What happened instead:** Email was not sent.

**Log output**

```
2021-02-26T18:45:49.828Z [4567/38] - error: admin.email.test
Error: Connection timeout
    at SMTPConnection._formatError (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
    at SMTPConnection._onError (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:760:20)
    at Timeout.<anonymous> (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

All the parameters are correct in my install, and works fine using in nodemailer. Looks like there is a formatting issue somewhere.

**Update** Also tried the latest stable release of NodeBB, same result, email does not work.

**Comment by pitaj** [comment]
Have you tried it without docker?

> All the parameters are correct in my install, and works fine using in nodemailer. Looks like there is a formatting issue somewhere.

What do you mean? Did you try nodemailer in a test script or something?

**Comment by pitaj** [comment]
I guess you got it working? If so, please share for the benefit of others.
