### ISSUE TITLE
1.16.2 Can't upload files  - error:invalid-files - Filetypes are allowed

### ISSUE THREAD

**Issue by me-cooper** [NodeBB/NodeBB#9333]
- **NodeBB version:** v1.16.2
- **Git-Hash:** 023e4cfcee208a0bae121a6e343a8c53009fd090
- **NodeJS version**: v14.15.4
- **Installed NodeBB Plugins:** 

- **Database type:** mongo
- **Database version:** db version v4.0.16
- **Exact steps to cause this issue:** Upload a Image

- **What you expected:**
Image will be uploaded and displayed

- **What happened instead in the console:**
```
2021-02-27T13:09:35.466Z [4567/5848] - error: /api/post/upload
Error: [[error:invalid-files]]
    at validateFiles (/home/nodebb/my.net/src/middleware/index.js:106:15)
    at Layer.handle [as handle_request] (/home/nodebb/my.net/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nodebb/my.net/node_modules/express/lib/router/route.js:137:13)
    at Form.<anonymous> (/home/nodebb/my.net/node_modules/connect-multiparty/index.js:114:7)
    at Form.emit (events.js:315:20)
    at emitCloseNT (internal/streams/destroy.js:87:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
^C
```

Filetypes are allowed: PNG JPG GIF
tested with JPG and PNG. No success.

Can't also upload via ACP ...

**Comment by barisusakli** [comment]
@me-cooper can you check the solution here https://community.nodebb.org/post/80174

**Comment by me-cooper** [comment]
> @me-cooper can you check the solution here https://community.nodebb.org/post/80174

Did work for me. Thanks a lot!

For everyone:

I manually updated `multiparty` to v4.2.2 it was v4.2.1. Now upload works again. 🥳
