### ISSUE TITLE
Latest release doesn't start

### ISSUE THREAD

**Issue by olivierlambert** [NodeBB/NodeBB#9500]
- **NodeBB version:** 1.17.0
- **NodeBB git hash:** git checkout done on 1.17.x few minutes go
- **NodeJS version:** `v12.22.1`
- **Installed NodeBB Plugins:** various plugins (more than 15)
- **Database type:** Redis
- **Database version:** Redis server v=3.2.12
- **Exact steps to cause this issue:** Upgraded from latest 1.16.x to 1.17.x

## Visible problem

Doing a `nodebb start` works, but when trying to access the forum, get the following log:

```
2021-04-22T07:26:34.800Z [4567/54574] - error: /forum/categories
TypeError: Cannot read property 'push' of undefined
    at Object.Twitter.appendUserHashWhitelist [as method] (node_modules/nodebb-plugin-sso-twitter/library.js:100:18)
    at src/plugins/hooks.js:131:29
    at new Promise (<anonymous>)
    at fireMethod (src/plugins/hooks.js:130:10)
    at Object.fireFilterHook [as filter] (/rc/plugins/hooks.js:149:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Hooks.fire (src/plugins/hooks.js:99:17)
    at async User.getUsersFields (src/user/data.js:59:19)
    at async User.bans.unbanIfExpired (src/user/bans.js:111:20)
    at async User.bans.canLoginIfBanned (src/user/bans.js:96:23)
(node:54574) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'push' of undefined
    at Object.Twitter.appendUserHashWhitelist [as method] (node_modules/nodebb-plugin-sso-twitter/library.js:100:18)
    at src/plugins/hooks.js:131:29
    at new Promise (<anonymous>)
    at fireMethod (src/plugins/hooks.js:130:10)
    at Object.fireFilterHook [as filter] (src/plugins/hooks.js:149:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Hooks.fire (src/plugins/hooks.js:99:17)
    at async User.getUsersFields (src/user/data.js:59:19)
    at async User.bans.unbanIfExpired (src/user/bans.js:111:20)
    at async User.bans.canLoginIfBanned (src/user/bans.js:96:23)
(node:54574) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
```

Getting back to `v1.16.x` and things are working again.

**Comment by barisusakli** [comment]
What's the version of `nodebb-plugin-sso-twitter` ?
Can you also post the output of `./nodebb plugins`

**Comment by olivierlambert** [comment]
It's `nodebb-plugin-sso-twitter@2.5.11`

Here you go about the plugin list:
```
$ ./nodebb plugins
Active plugins:
	* nodebb-plugin-composer-default@6.5.5 (installed, enabled)
	* nodebb-plugin-custom-pages@1.3.1 (installed, disabled)
	* nodebb-plugin-dbsearch@4.1.2 (installed, enabled)
	* nodebb-plugin-emoji@3.5.1 (installed, enabled)
	* nodebb-plugin-emoji-android@2.0.0 (installed, enabled)
	* nodebb-plugin-github-embed@0.7.5 (installed, enabled)
	* nodebb-plugin-markdown@8.12.4 (installed, enabled)
	* nodebb-plugin-mentions@2.13.6 (installed, enabled)
	* nodebb-plugin-ns-awards (not installed, enabled)
	* nodebb-plugin-poll@1.1.6 (installed, enabled)
	* nodebb-plugin-prometheus@0.4.0 (installed, enabled)
	* nodebb-plugin-question-and-answer@0.8.7 (installed, enabled)
	* nodebb-plugin-shortcuts@1.1.2 (installed, enabled)
	* nodebb-plugin-soundpack-default@1.0.0 (installed, disabled)
	* nodebb-plugin-spam-be-gone@0.7.7 (installed, enabled)
	* nodebb-plugin-sso-facebook@3.6.3 (installed, disabled)
	* nodebb-plugin-sso-github@2.3.0 (installed, enabled)
	* nodebb-plugin-sso-twitter@2.5.11 (installed, enabled)
	* nodebb-plugin-sso-wordpress@2.1.0 (installed, disabled)
	* nodebb-plugin-tenor-gif@1.2.5 (installed, enabled)
	* nodebb-rewards-essentials@0.1.4 (installed, enabled)
	* nodebb-theme-lavender@5.0.17 (installed, disabled)
	* nodebb-theme-persona@10.3.19 (installed, enabled)
	* nodebb-theme-slick@1.3.8 (installed, disabled)
	* nodebb-theme-vanilla@11.3.10 (installed, disabled)
	* nodebb-widget-essentials@5.0.2 (installed, enabled)
```

**Comment by barisusakli** [comment]
Which github-sso plugin is that?
Does it have this fix https://github.com/julianlam/nodebb-plugin-sso-github/commit/05652484f6e9cc5b6146b4bcae486abe6e12e93f?

**Comment by olivierlambert** [comment]
The fix you mentioned is bundled in `v2.2.4`. I'm using `nodebb-plugin-sso-github@2.3.0`.

But while checking the files, I still see the uncorrected version.

What should I do?

**Comment by olivierlambert** [comment]
![Capture d’écran de 2021-04-22 17-02-19](https://user-images.githubusercontent.com/1241401/115737634-9a099400-a38c-11eb-8029-a304bfefe151.png)

This is what I have in the plugin screen.

**Comment by olivierlambert** [comment]
Disabling the `nodebb-plugin-sso-github` is making nodebb work.

However, as soon as I re-enable it, same issue :thinking:

**Comment by olivierlambert** [comment]
So I removed the plugin and installed it via `npm` instead of the web UI.

Now it works, but NodeBB is reporting this:

![Capture d’écran de 2021-04-22 17-19-26](https://user-images.githubusercontent.com/1241401/115740234-e950c400-a38e-11eb-8a04-e6feccfd741a.png)

So why the web UI is wrong like this? What's going on?

**Comment by julianlam** [comment]
That's odd, there shouldn't be a v2.3.0... but I'll update and publish v2.3.1 and that should resolve...

**Comment by julianlam** [comment]
v2.3.1 of the Github SSO plugin is now published. Not sure what happened, v2.3.0 doesn't even show up on GitHub.

**Comment by julianlam** [comment]
```
$ npm show nodebb-plugin-sso-github@2.3.0

nodebb-plugin-sso-github@2.3.0 | BSD-2-Clause | deps: 1 | versions: 28
NodeBB GitHub SSO

keywords: nodebb, plugin, github, sso, single sign on, registration

dist
.tarball: https://registry.npmjs.org/nodebb-plugin-sso-github/-/nodebb-plugin-sso-github-2.3.0.tgz
.shasum: 2b8d6980eeb84d9e4efe2b7dab277a5f23454305
.integrity: sha512-VLNaqkfOBUnWpM9Cdhgp/+95OlwiGGidj3YFdoARrF0U33ELlS1Qr1jbDhhIM60q4vKxUPKnRry+W4IiFGLYJQ==
.unpackedSize: 14.5 kB

dependencies:
passport-github2: ^0.1.9 

maintainers:
- psychobunny <andrew@nodebb.org>
- julianlam <julian@nodebb.org>
- baris <barisusakli@gmail.com>
- qjmiao <qjmiao@gmail.com>

dist-tags:
latest: 2.3.1  

published 5 months ago by julianlam <julian@nodebb.org>
```

npm shows I published it 5 months ago. Seems to have been an accident. I've deprecated it on npm now.

**Comment by olivierlambert** [comment]
I can't test it for now because after restarting Node a lot of time to check plugins, I'm now rate limited by GitHub :D

```
2021-04-22T15:32:55.156Z [4567/3460] - error: [acp] Failed to fetch latest versionError: rate limit exceeded
```

**Comment by olivierlambert** [comment]
That explains the issue :) Thanks for the answer!
