### ISSUE TITLE
Redis cluster support

### ISSUE THREAD

**Issue by sandratatarevicova** [NodeBB/NodeBB#9508]
Since NodeBB 1.16.0 Redis is a requirement when running in clustered mode. I have set up a Redis cluster and configured it in NodeBB, but it does not work:

```
2021-04-26T13:38:52.091Z [4567/264] - error: /
ReplyError: MOVED 7728 10.102.14.23:6379
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)
```

It seems that it is because [`node-redis` does not support cluster](https://github.com/NodeRedis/node-redis/issues/574). Would it be possible to switch to `ioredis` or another module that supports Redis clusters, now when Redis is not optional but required?

**Comment by julianlam** [comment]
@sandratatarevicova Are you required to use redis _cluster_? NodeBB running in clustered mode is different from requiring redis to be run in clustered mode. A single redis instance should suffice and be more than enough to handle the few keys (mainly session keys) that we insert in.

**Comment by sandratatarevicova** [comment]
Yes, Redis cluster is highly preferred in our setup - it is a production forum with lots of users. We have 3 NodeBB instances (that can autoscale) and HA Mongo. Single Redis instance would be SPOF that we don't want to have 🙂

**Comment by pitaj** [comment]
Looks like it would be too hard to migrate to ioredis

https://github.com/luin/ioredis/wiki/Migrating-from-node_redis

**Comment by sandratatarevicova** [comment]
Thank you! 🙂  I am unfortunately still getting the same error:

```
2021-05-13T07:58:47.663Z [4567/269] - error: /service-worker.js
ReplyError: MOVED 3502 10.102.6.89:6379
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)
```

I am not sure if it is the cause, but it `socket.io-redis` 6.1.0 that is used on master uses `node-redis`. It seems that 7.0.0 supports `ioredis` - https://github.com/socketio/socket.io-redis-adapter#with-ioredis-client.

**Comment by barisusakli** [comment]
We are using 7.0.0 now just gotto add support for creating the clients.

Should we allow an array for the redis field to support cluster?
```
 "redis": {
        "host": "127.0.0.1",
        "port": "6379",
        "password": "",
        "database": "0"
    },
    ```
   vs
   ```
 "redis": [{
        "host": "127.0.0.1",
        "port": "6379",
        "password": "",
        "database": "0"
    }, {
            "host": "127.0.0.1",
        "port": "6380",
        "password": "",
        "database": "0"
    }]
    ```

**Comment by barisusakli** [comment]
I think it might be better to have a nester "cluster" block so we can still pass in options
```
"redis": {
   "options": {},
   "cluster": [
       {"host": "", "port": ""}, 
       {"host": "", "port": ""}
    ]
]
```

**Comment by sandratatarevicova** [comment]
I think all options should be OK for us, but the last one makes the most sense to me.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/94c12e37716a9ac36f6f653430202be8c8d3b5ba
Let me know if this works, the options are passed directly to ioredis so everything from https://github.com/luin/ioredis#cluster is available.

```
"redis": {
   "options": {
        "maxRedirections":  "16",
        "redisOptions": {
              "password": "<mypassword>"
        }
   },
   "cluster": [
       {"host": "", "port": ""}, 
       {"host": "", "port": ""}
    ]
]
```

**Comment by sandratatarevicova** [comment]
It seems that it works OK, thank you 🙂

**Comment by sandratatarevicova** [comment]
Will 1.17.1 be released soon? We would like to deploy it to production 🙂

**Comment by barisusakli** [comment]
It was supposed to be last week actually 😆 @julianlam
