### ISSUE TITLE
Can't start server after upgrade to 1.17.1

### ISSUE THREAD

**Issue by appagg** [NodeBB/NodeBB#9618]
After upgraded from 1.16.2 to 1.17.1, got the following error when trying to start the server:

2021-06-19T18:33:30.528Z [4567/29787] - error: uncaughtException: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at expandObjBy (/home/cfengying88/nodebb/src/settings.js:8:35)
    at expandObjBy (/home/cfengying88/nodebb/src/settings.js:15:8)
    at /home/cfengying88/nodebb/src/settings.js:97:14
    at /home/cfengying88/nodebb/src/promisify.js:43:50
    at cb (util.js:207:31)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {"error":{},"stack":"TypeError: Cannot convert undefined or null to object\n    at Function.entries (<anonymous>)\n    at expandObjBy (/home/cfengying88/nodebb/src/settings.js:8:35)\n    at expandObjBy (/home/cfengying88/nodebb/src/settings.js:15:8)\n    at /home/cfengying88/nodebb/src/settings.js:97:14\n    at /home/cfengying88/nodebb/src/promisify.js:43:50\n    at cb (util.js:207:31)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","exception":true,"date":"Sat Jun 19 2021 11:33:30 GMT-0700 (Pacific Daylight Time)","process":{"pid":29787,"uid":1001,"gid":1002,"cwd":"/home/cfengying88/nodebb","execPath":"/usr/bin/node","version":"v14.15.4","argv":["/usr/bin/node","/home/cfengying88/nodebb/app.js"],"memoryUsage":{"rss":129097728,"heapTotal":79790080,"heapUsed":71071184,"external":23488107,"arrayBuffers":19552177}},"os":{"loadavg":[1.17,0.9,0.58],"uptime":14410750},"trace":[{"column":null,"file":null,"function":"Function.entries","line":null,"method":"entries","native":false},{"column":35,"file":"/home/cfengying88/nodebb/src/settings.js","function":"expandObjBy","line":8,"method":null,"native":false},{"column":8,"file":"/home/cfengying88/nodebb/src/settings.js","function":"expandObjBy","line":15,"method":null,"native":false},{"column":14,"file":"/home/cfengying88/nodebb/src/settings.js","function":null,"line":97,"method":null,"native":false},{"column":50,"file":"/home/cfengying88/nodebb/src/promisify.js","function":null,"line":43,"method":null,"native":false},{"column":31,"file":"util.js","function":"cb","line":207,"method":null,"native":false},{"column":21,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":80,"method":null,"native":false}]}

**Comment by gasoved** [comment]
My guess here is that in b1257f6, a typeof check against "undefined" was added, but it seems that didn't account for "null"s, since typeof returns "object" for them. I don't know why it passes "null" in this instance though (if that's the case).

**Comment by pitaj** [comment]
What node version are you on?

**Comment by appagg** [comment]
@pitaj the node version is v14.15.4

**Comment by appagg** [comment]
@gasoved I'd guess it's from one of my plugin settings.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/blob/master/src/settings.js#L88 add a console.log(this.hash, settings) at that line to figure which plugin is crashing. It should show the name and data before the crash.
