### ISSUE TITLE
 ./nodebb setup error

### ISSUE THREAD

**Issue by acodercat** [NodeBB/NodeBB#9627]
- **NodeBB version:**  latest
- **NodeBB git hash:** 
- **NodeJS version:** 14.6
maohao-virtual-machine:~/Downloads/NodeBB-1.17.1$ ./nodebb setup
Dependencies outdated or not yet installed.
Installing them now...

Error: ENOENT: no such file or directory, access '/home/maohao/Downloads/NodeBB-1.17.1/node_modules/nconf/package.json'
    at Object.accessSync (fs.js:220:3)
    at Object.installAll (/home/maohao/Downloads/NodeBB-1.17.1/src/cli/package-install.js:50:6)
    at Object.<anonymous> (/home/maohao/Downloads/NodeBB-1.17.1/src/cli/index.js:62:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/maohao/Downloads/NodeBB-1.17.1/nodebb:5:1) {
  errno: -2,
  syscall: 'access',
  code: 'ENOENT',
  path: '/home/maohao/Downloads/NodeBB-1.17.1/node_modules/nconf/package.json'
}

**Comment by julianlam** [comment]
This doesn't impact the setup process, does it? I noticed it recently but the setup continued...

**Comment by julianlam** [comment]
Ah, it looks like this was a regression caused by this change here:

https://github.com/NodeBB/NodeBB/commit/ac86937c8879a20931db3e9a54d86a89ade566ec#diff-4a8d0a8692ac99ba6a42a8281286155e4982c0d1ed3002fd478d967e3598e332L69-R69

@pitaj @barisusakli correct me if I am wrong, but it looks like the flow of the code should be:

* if nconf installed, deps are present, so run install again with whatever package manager is defined in `config.json`
* else do nothing which triggers install via npm

**Comment by pitaj** [comment]
Yeah it shouldn't be logged there.
