### ISSUE TITLE
Sending email failed and the log said "Sender address rejected: not owned by user" and "ssl3_get_record:wrong version number"

### ISSUE THREAD

**Issue by fintechee** [NodeBB/NodeBB#9704]
Hi NodeBB Team,

Many thanks for developing this excellent forum package.
Really helpful.

But, sending email doesn't work.

- **NodeBB version:** 1.16.2
- **NodeJS version:** 14.17.2

- **Installed NodeBB Plugins:** default 

- **Database type:** mongo
- **Database version:** v4.0.26

- **Exact steps to cause this issue:**

1. Checked "Use an external email server to send emails" and setup "custom SMTP".
2. Sending test email failed(no matter whether "Enable pooled connection" is checked or not).
3. The log said:
```
2021-08-15T21:52:09.518Z [4567/843252] - [31merror[39m: admin.email.test
Error: Can't send mail - all recipients were rejected: 553 5.7.1 <no-reply@www.fintechee.org>: Sender address rejected: not owned by user noreply@fintechee.org
    at SMTPConnection._formatError (/var/www/nodebb/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionRCPT (/var/www/nodebb/node_modules/nodemailer/lib/smtp-connection/index.js:1626:28)
    at SMTPConnection.<anonymous> (/var/www/nodebb/node_modules/nodemailer/lib/smtp-connection/index.js:1579:30)
    at SMTPConnection._processResponse (/var/www/nodebb/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
    at SMTPConnection._onData (/var/www/nodebb/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (/var/www/nodebb/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at TLSSocket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
```
4. Why was the sender "no-reply@www.fintechee.org"? I didn't register it. And the setting for the sender is "noreply@fintechee.org". It's not registered as a NodeBB user as well.
5. So, I created a new account(no-reply@fintechee.org) in my SMTP server, modified config.json's url(removed www), rebuilt the package and restarted it. After all the steps, I tried to send a test email again, still failed.
6. But the log changed:
```
2021-08-15T23:26:44.395Z [4567/845503] - [31merror[39m: admin.email.test
Error: 140233218307968:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

- **What you expected:**

Sending test email is done successfully.
- **What happened instead:**

Sending test email failed.

- **Additionally**
Today, I installed the forum package entirely according to the guide on NodeBB's official website.
The only setting that I configured individually is the "301 redirect".
I added one more server section in the Nginx conf.
```
server {
    listen 80;
    listen 443;
    server_name fintechee.org;
    return 301 https://www.fintechee.org$request_uri;
}
```

Please teach me how to solve this problem. Many thanks.

**Comment by pitaj** [comment]
I think you're close. The ssl error is odd, have you tried different SMTP security settings since you got that far?

I found the following which may or may not help you: https://stackoverflow.com/questions/66317125/node-js-nodemailer-error-wrong-version-number-invalid-greeting

**Comment by fintechee** [comment]
@pitaj
Many thanks for your fast response!
I modified emailer.js and added 
tls: {
        ciphers:'SSLv3'
}, and rebuilt the forum.
But sending email didn't work yet.

I didn't try other SMTP providers, but I will give it a try.
Anyway, thank you for your help.

**Comment by julianlam** [comment]
Hi @fintechee -- I think at this point it is a problem with the SMTP settings and the remote MTA. As this is the issue tracker for NodeBB software itself, I don't think a bug exists here, so I will close the issue, but please do continue discussion here if needed.

**Comment by fintechee** [comment]
@fintechee
Many thanks, no problem.

**Comment by pitaj** [comment]
What is your SMTP security setting? STARTTLS? Have you tried the other options?
