### ISSUE TITLE
Cannot read property 'figure_out_scope' of null

### ISSUE THREAD

**Issue by awunnenb** [NodeBB/NodeBB#9951]
upgrade to latest nodebb at 10/29/2021:

Error: Error minifying undefined
TypeError: Cannot read property 'figure_out_scope' of null
    at Object.minify (eval at <anonymous> (/opt/nodebb/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:14862:38)
    at minifyAndSave (/opt/nodebb/src/meta/minifier.js:193:26)
    at /opt/nodebb/src/meta/minifier.js:161:9
    at minifyAndSave (/opt/nodebb/src/meta/minifier.js:203:9)
    at /opt/nodebb/src/meta/minifier.js:161:9
2021-10-29T20:45:25.157Z [60001/13974] - error: Error: Error minifying undefined
TypeError: Cannot read property 'figure_out_scope' of null
    at Object.minify (eval at <anonymous> (/opt/nodebb/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:14862:38)
    at minifyAndSave (/opt/nodebb/src/meta/minifier.js:193:26)
    at /opt/nodebb/src/meta/minifier.js:161:9
    at minifyAndSave (/opt/nodebb/src/meta/minifier.js:203:9)
    at /opt/nodebb/src/meta/minifier.js:161:9

**Comment by pitaj** [comment]
Please follow the issue template. What version of Nodejs?
